-- 一般性序號
CREATE SEQUENCE SEQ_EC INCREMENT BY 1 START WITH 100 NOMAXVALUE CACHE 3 NOORDER  NOCYCLE;
-- 特殊性序號
CREATE SEQUENCE SEQ_REWARD_LOG INCREMENT BY 1 START WITH 1 NOMAXVALUE CACHE 3 NOORDER  NOCYCLE;
CREATE SEQUENCE SEQ_ORDER INCREMENT BY 1 START WITH 1 NOMAXVALUE CACHE 3 NOORDER  NOCYCLE;

-- 首頁廣告, 廣告及證言, 促銷訊息, 紅利兌換活動, 金幣兌換活動
CREATE TABLE "EC_BANNER"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"CATEGORY" NUMBER(2,0) NOT NULL ENABLE,
"SUBJECT" VARCHAR2(255 CHAR),
"CONTENT_URL" VARCHAR2(255 BYTE) NOT NULL ENABLE,
"LINK" VARCHAR2(255 BYTE),
"DESCRIPTION" VARCHAR2(500 CHAR),
"ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
CONSTRAINT "EC_BANNER_PK" PRIMARY KEY ("ID") ENABLE
);
COMMENT ON COLUMN "EC_BANNER"."ID" IS 'PK';
COMMENT ON COLUMN "EC_BANNER"."CATEGORY" IS '1:首頁,2:廣告證言,3:紅利促銷,4:紅利兌換,5:金幣兌換,6:產品使用,7:台泥活動,8:伙伴活動';
COMMENT ON COLUMN "EC_BANNER"."SUBJECT" IS '主旨';
COMMENT ON COLUMN "EC_BANNER"."CONTENT_URL" IS '圖檔網址';
COMMENT ON COLUMN "EC_BANNER"."LINK" IS 'click link';
COMMENT ON COLUMN "EC_BANNER"."DESCRIPTION" IS '文字說明';
COMMENT ON COLUMN "EC_BANNER"."ACTIVE" IS '1:啟用, 0:停用';

-- 會員
CREATE TABLE "EC_MEMBER"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"LOGIN_ACCOUNT" VARCHAR2(50 BYTE) NOT NULL ENABLE,
"NAME" VARCHAR2(64 CHAR) NOT NULL ENABLE,
"EMAIL" VARCHAR2(64 BYTE) NOT NULL ENABLE,
"PHONE" VARCHAR2(50 BYTE),
"PASSWORD" VARCHAR2(64 BYTE) NOT NULL ENABLE,
"ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
"MODIFYTIME" DATE,
CONSTRAINT "EC_MEMBER_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_MEMBER_UK1" UNIQUE ("LOGIN_ACCOUNT") ENABLE
);
COMMENT ON COLUMN "EC_MEMBER"."ID" IS 'PK';
COMMENT ON COLUMN "EC_MEMBER"."LOGIN_ACCOUNT" IS '登入帳號';
COMMENT ON COLUMN "EC_MEMBER"."NAME" IS '姓名';
COMMENT ON COLUMN "EC_MEMBER"."EMAIL" IS '電子信箱';
COMMENT ON COLUMN "EC_MEMBER"."PHONE" IS '電話';
COMMENT ON COLUMN "EC_MEMBER"."PASSWORD" IS '密碼(SHA256)';
COMMENT ON COLUMN "EC_MEMBER"."ACTIVE" IS '1:啟用, 0:停用';
COMMENT ON COLUMN "EC_MEMBER"."MODIFYTIME" IS '異動時間';

-- 客戶
CREATE TABLE "EC_CUSTOMER"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE,
"NAME" VARCHAR2(64 CHAR) NOT NULL ENABLE,
"ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
CONSTRAINT "EC_CUSTOMER_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_CUSTOMER_UK1" UNIQUE ("CODE") ENABLE
);
COMMENT ON COLUMN "EC_CUSTOMER"."ID" IS 'PK';
COMMENT ON COLUMN "EC_CUSTOMER"."CODE" IS 'SAP代碼';
COMMENT ON COLUMN "EC_CUSTOMER"."NAME" IS '客戶名稱';
COMMENT ON COLUMN "EC_CUSTOMER"."ACTIVE" IS '1:啟用, 0:停用';

-- 商品
CREATE TABLE "EC_PRODUCT"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"CODE" VARCHAR2(18 CHAR) NOT NULL ENABLE,
"NAME" VARCHAR2(80 CHAR) NOT NULL ENABLE,
"DESCRIPTION" VARCHAR2(500 CHAR),
"ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
CONSTRAINT "EC_PRODUCT_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_PRODUCT_UK1" UNIQUE ("CODE") ENABLE
);
COMMENT ON COLUMN "EC_PRODUCT"."ID" IS 'PK';
COMMENT ON COLUMN "EC_PRODUCT"."CODE" IS 'SAP料號';
COMMENT ON COLUMN "EC_PRODUCT"."NAME" IS '商品名稱';
COMMENT ON COLUMN "EC_PRODUCT"."DESCRIPTION" IS '商品介紹';
COMMENT ON COLUMN "EC_PRODUCT"."ACTIVE" IS '1:啟用, 0:停用';

-- 公司
CREATE TABLE "EC_COMPANY" 
(
"ID" NUMBER(18,0) NOT NULL ENABLE, 
"CODE" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
"NAME" VARCHAR2(40 CHAR) NOT NULL ENABLE, 
"HIDE_CREDIT" NUMBER(1,0) NOT NULL ENABLE, 
CONSTRAINT "EC_COMPANY_PK" PRIMARY KEY ("ID") ENABLE, 
CONSTRAINT "EC_COMPANY_UK1" UNIQUE ("CODE") ENABLE
);
COMMENT ON COLUMN "EC_COMPANY"."ID" IS 'PK';
COMMENT ON COLUMN "EC_COMPANY"."CODE" IS 'SAP代碼';
COMMENT ON COLUMN "EC_COMPANY"."NAME" IS '公司名稱';
COMMENT ON COLUMN "EC_COMPANY"."HIDE_CREDIT" IS '隱藏客戶餘額(1:是, 0:否)';

-- 出貨廠
CREATE TABLE "EC_PLANT"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE,
"NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE,
"INCO_FLAG" NUMBER(3,0) DEFAULT 1 NOT NULL ENABLE,
"ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
"VKORG" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
"AUTO_ORDER" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
CONSTRAINT "EC_PLANT_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_PLANT_UK1" UNIQUE ("CODE") ENABLE
);
COMMENT ON COLUMN "EC_PLANT"."ID" IS 'PK';
COMMENT ON COLUMN "EC_PLANT"."CODE" IS 'SAP代碼';
COMMENT ON COLUMN "EC_PLANT"."NAME" IS '廠名稱';
COMMENT ON COLUMN "EC_PLANT"."INCO_FLAG" IS 'bit0:廠交自提(EXW), bit1:工地交自提(FCA)';
COMMENT ON COLUMN "EC_PLANT"."ACTIVE" IS '1:啟用, 0:停用';
COMMENT ON COLUMN "EC_PLANT"."VKORG" IS '銷售組織';
COMMENT ON COLUMN "EC_PLANT"."AUTO_ORDER" IS '1:自動核單, 0:人工核單';

-- 業務員
CREATE TABLE "EC_SALES"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"NAME" VARCHAR2(40 CHAR) NOT NULL ENABLE,
"CODE" VARCHAR2(40 BYTE) NOT NULL ENABLE,
"ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
CONSTRAINT "EC_SALES_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_SALES_UK1" UNIQUE ("CODE") ENABLE
)
;
COMMENT ON COLUMN "EC_SALES"."ID" IS 'PK';
COMMENT ON COLUMN "EC_SALES"."NAME" IS '姓名';
COMMENT ON COLUMN "EC_SALES"."CODE" IS '員工編號';
COMMENT ON COLUMN "EC_SALES"."ACTIVE" IS '1:啟用, 0:停用';

-- 銷售區
CREATE TABLE "EC_SALESAREA"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"CODE" VARCHAR2(10 BYTE) NOT NULL ENABLE,
"NAME" VARCHAR2(140 CHAR),
"ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
CONSTRAINT "EC_SALESAREA_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_SALESAREA_UK1" UNIQUE ("CODE") ENABLE
);
COMMENT ON COLUMN "EC_SALESAREA"."ID" IS 'PK';
COMMENT ON COLUMN "EC_SALESAREA"."CODE" IS '代碼';
COMMENT ON COLUMN "EC_SALESAREA"."NAME" IS '名稱';
COMMENT ON COLUMN "EC_SALESAREA"."ACTIVE" IS '1:啟用, 0:停用';

-- 送達地點
CREATE TABLE "EC_DELIVERY_PLACE" 
(
"ID" NUMBER(18,0) NOT NULL ENABLE, 
"CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
"NAME" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
"SALESAREA_ID" NUMBER(18,0) NOT NULL ENABLE, 
"PROVINCE" VARCHAR2(20 CHAR), 
"CITY" VARCHAR2(20 CHAR), 
"DISTRICT" VARCHAR2(20 CHAR), 
"TOWN" VARCHAR2(20 CHAR), 
"ACTIVE" NUMBER(1,0) NOT NULL ENABLE, 
CONSTRAINT "EC_DELIVERY_PLACE_PK" PRIMARY KEY ("ID") ENABLE, 
CONSTRAINT "EC_DELIVERY_PLACE_UK1" UNIQUE ("CODE") ENABLE, 
CONSTRAINT "EC_DELIVERY_PLACE_EC_SALE_FK1" FOREIGN KEY ("SALESAREA_ID") REFERENCES "EC_SALESAREA" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_DELIVERY_PLACE"."ID" IS 'PK';
COMMENT ON COLUMN "EC_DELIVERY_PLACE"."CODE" IS '代碼';
COMMENT ON COLUMN "EC_DELIVERY_PLACE"."NAME" IS '名稱';
COMMENT ON COLUMN "EC_DELIVERY_PLACE"."SALESAREA_ID" IS 'FK:SALESAREA.ID';
COMMENT ON COLUMN "EC_DELIVERY_PLACE"."PROVINCE" IS '省';
COMMENT ON COLUMN "EC_DELIVERY_PLACE"."CITY" IS '市';
COMMENT ON COLUMN "EC_DELIVERY_PLACE"."DISTRICT" IS '區';
COMMENT ON COLUMN "EC_DELIVERY_PLACE"."TOWN" IS '鎮';
COMMENT ON COLUMN "EC_DELIVERY_PLACE"."ACTIVE" IS '1:啟用, 0:停用';

-- 合約
CREATE TABLE "EC_CONTRACT"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"CODE" VARCHAR2(50 CHAR) NOT NULL ENABLE,
"NAME" VARCHAR2(50 CHAR) NOT NULL ENABLE,
"CUSTOMER_ID" NUMBER(18,0) NOT NULL ENABLE,
"ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
CONSTRAINT "EC_CONTRACT_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_CONTRACT_UK1" UNIQUE ("CODE") ENABLE,
CONSTRAINT "EC_CONTRACT_FK1" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "EC_CUSTOMER" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_CONTRACT"."ID" IS 'PK';
COMMENT ON COLUMN "EC_CONTRACT"."CODE" IS '合約號碼';
COMMENT ON COLUMN "EC_CONTRACT"."NAME" IS '合約名稱';
COMMENT ON COLUMN "EC_CONTRACT"."CUSTOMER_ID" IS 'FK:EC_CUSTOMER.ID';
COMMENT ON COLUMN "EC_CONTRACT"."ACTIVE" IS '1:啟用, 0:停用';

-- 台泥伙伴
CREATE TABLE "EC_PARTNER"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"NAME" VARCHAR2(100 CHAR) NOT NULL ENABLE,
"OWNER" NUMBER(18,0) NOT NULL ENABLE,
"DESCRIPTION" VARCHAR2(500 CHAR),
"ADDRESS" VARCHAR2(150 CHAR),
"CONTACT" VARCHAR2(20 CHAR),
"PHONE" VARCHAR2(50 BYTE),
"SOCIAL" VARCHAR2(64 BYTE),
"THEME" VARCHAR2(20 BYTE),
"PROVINCE" VARCHAR2(20 CHAR) NOT NULL,
"CITY" VARCHAR2(20 CHAR) NOT NULL,
"DISTRICT" VARCHAR2(20 CHAR),
"TOWN" VARCHAR2(20 CHAR),
"MEMBER" varchar2(500 BYTE),
"MESSAGE" varchar2(500 BYTE),
"STATUS" VARCHAR2(20 BYTE) NOT NULL ENABLE,
"CREATETIME" DATE NOT NULL ENABLE,
"RATE" NUMBER(2,1),
"ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
"APPROVER" NUMBER(18,0), 
"APPROVAL_TIME" DATE, 
CONSTRAINT "EC_PARTNER_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_PARTNER_UK1" UNIQUE ("NAME") ENABLE,
CONSTRAINT "EC_PARTNER_EC_MEMBER_FK1" FOREIGN KEY ("OWNER") REFERENCES "EC_MEMBER" ("ID") ENABLE,
CONSTRAINT "EC_PARTNER_TC_USER_FK1" FOREIGN KEY ("APPROVER") REFERENCES "TC_USER" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_PARTNER"."ID" IS 'PK';
COMMENT ON COLUMN "EC_PARTNER"."NAME" IS '伙伴名稱';
COMMENT ON COLUMN "EC_PARTNER"."OWNER" IS '建立人, FK:EC_MEMBER.ID';
COMMENT ON COLUMN "EC_PARTNER"."DESCRIPTION" IS '位置及介紹';
COMMENT ON COLUMN "EC_PARTNER"."ADDRESS" IS '地址';
COMMENT ON COLUMN "EC_PARTNER"."CONTACT" IS '連絡人';
COMMENT ON COLUMN "EC_PARTNER"."PHONE" IS '電話';
COMMENT ON COLUMN "EC_PARTNER"."SOCIAL" IS '社群聯絡方式';
COMMENT ON COLUMN "EC_PARTNER"."THEME" IS '版面';
COMMENT ON COLUMN "EC_PARTNER"."PROVINCE" IS '省';
COMMENT ON COLUMN "EC_PARTNER"."CITY" IS '市';
COMMENT ON COLUMN "EC_PARTNER"."DISTRICT" IS '區';
COMMENT ON COLUMN "EC_PARTNER"."TOWN" IS '鎮';
COMMENT ON COLUMN "EC_PARTNER"."MEMBER" IS 'MEMBER LIST';
COMMENT ON COLUMN "EC_PARTNER"."STATUS" IS '狀態 (APPLY: 申請中, APPROVE:申請通過, REJECT: 申請駁回)';
COMMENT ON COLUMN "EC_PARTNER"."MESSAGE" IS '駁回原因';
COMMENT ON COLUMN "EC_PARTNER"."CREATETIME" IS '建立時間';
COMMENT ON COLUMN "EC_PARTNER"."RATE" IS '評分(0~5)';
COMMENT ON COLUMN "EC_PARTNER"."ACTIVE" IS '1:啟用, 0:停用';
COMMENT ON COLUMN "EC_PARTNER"."APPROVER" IS '審核員(FK:TC_USER.ID)';
COMMENT ON COLUMN "EC_PARTNER"."APPROVAL_TIME" IS '審核時間';

-- 夥伴商品主檔
CREATE TABLE "EC_GOODS" 
(
"ID" NUMBER(18,0) NOT NULL ENABLE, 
"CODE" VARCHAR2(18 CHAR), 
"NAME" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
"DESCRIPTION" VARCHAR2(500 CHAR), 
"ACTIVE" NUMBER(1,0) NOT NULL ENABLE, 
CONSTRAINT "EC_GOODS_PK" PRIMARY KEY ("ID") ENABLE
);
COMMENT ON COLUMN "EC_GOODS"."ID" IS 'PK';
COMMENT ON COLUMN "EC_GOODS"."CODE" IS 'SAP料號';
COMMENT ON COLUMN "EC_GOODS"."NAME" IS '商品名稱';
COMMENT ON COLUMN "EC_GOODS"."DESCRIPTION" IS '商品介紹';
COMMENT ON COLUMN "EC_GOODS"."ACTIVE" IS '1:啟用, 0:停用';

-- 紅利/金幣
CREATE TABLE "EC_REWARD" 
(
"MEMBER_ID" NUMBER(18,0) NOT NULL ENABLE, 
"TYPE" NUMBER(1,0) NOT NULL ENABLE, 
"POINTS" NUMBER(8,0) NOT NULL ENABLE, 
"MODIFYTIME" DATE NOT NULL ENABLE, 
CONSTRAINT "EC_REWARD_PK" PRIMARY KEY ("MEMBER_ID", "TYPE") ENABLE, 
CONSTRAINT "EC_REWARD_EC_MEMBER_FK1" FOREIGN KEY ("MEMBER_ID") REFERENCES "EC_MEMBER" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_REWARD"."MEMBER_ID" IS 'FK:EC_MEMBER.ID';
COMMENT ON COLUMN "EC_REWARD"."TYPE" IS '1:紅利, 2:金幣';
COMMENT ON COLUMN "EC_REWARD"."POINTS" IS '累計點數';
COMMENT ON COLUMN "EC_REWARD"."MODIFYTIME" IS '最後修改時間';

-- 促銷活動
CREATE TABLE "EC_CAMPAIGN" 
(
"ID" NUMBER(18,0) NOT NULL ENABLE, 
"TYPE" NUMBER(1,0) NOT NULL ENABLE, 
"SUBJECT" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
"DESCRIPTION" VARCHAR2(500 CHAR), 
"START_DATE" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
"END_DATE" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
"CREATETIME" DATE DEFAULT sysdate NOT NULL ENABLE,
"ACTIVE" NUMBER(1,0) NOT NULL ENABLE, 
CONSTRAINT "EC_CAMPAIGN_PK" PRIMARY KEY ("ID") ENABLE
);
COMMENT ON COLUMN "EC_CAMPAIGN"."ID" IS 'PK';
COMMENT ON COLUMN "EC_CAMPAIGN"."TYPE" IS '1:台泥活動, 2:檔口活動';
COMMENT ON COLUMN "EC_CAMPAIGN"."SUBJECT" IS '主題';
COMMENT ON COLUMN "EC_CAMPAIGN"."DESCRIPTION" IS '描述';
COMMENT ON COLUMN "EC_CAMPAIGN"."START_DATE" IS '開始日期(yyyy/MM/dd)';
COMMENT ON COLUMN "EC_CAMPAIGN"."END_DATE" IS '結束日期(yyyy/MM/dd)';
COMMENT ON COLUMN "EC_CAMPAIGN"."CREATETIME" IS '建立時間';
COMMENT ON COLUMN "EC_CAMPAIGN"."ACTIVE" IS '1:啟用, 0:停用';

-- 中國行政區 (省,市)
CREATE TABLE "EC_DIVISIONS_CN" 
(
"ID" NUMBER(18,0) NOT NULL ENABLE, 
"NAME" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
"PARENT" NUMBER(18,0), 
"LAYER" NUMBER(1,0), 
"SALES_CONTACT" VARCHAR2(500 BYTE), 
CONSTRAINT "EC_DIVISIONS_CN_PK" PRIMARY KEY ("ID") ENABLE
);
COMMENT ON COLUMN "EC_DIVISIONS_CN"."ID" IS '代碼';
COMMENT ON COLUMN "EC_DIVISIONS_CN"."NAME" IS '名稱';
COMMENT ON COLUMN "EC_DIVISIONS_CN"."PARENT" IS '上層代碼';
COMMENT ON COLUMN "EC_DIVISIONS_CN"."LAYER" IS '0:省,1:市,2:區';
COMMENT ON COLUMN "EC_DIVISIONS_CN"."SALES_CONTACT" IS '業務窗口(email)';

-----------------------------------------
--  會員-客戶(ManyToMany)
CREATE TABLE "EC_MEMBER_CUSTOMER"
(
"MEMBER_ID" NUMBER(18,0) NOT NULL ENABLE,
"CUSTOMER_ID" NUMBER(18,0) NOT NULL ENABLE,
"DUMMY" VARCHAR2(20),
CONSTRAINT "EC_MEMBER_CUSTOMER_PK" PRIMARY KEY ("MEMBER_ID", "CUSTOMER_ID") ENABLE,
CONSTRAINT "EC_MEMBER_CUSTOMER_FK1" FOREIGN KEY ("MEMBER_ID") REFERENCES "EC_MEMBER" ("ID") ENABLE,
CONSTRAINT "EC_MEMBER_CUSTOMER_FK2" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "EC_CUSTOMER" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_MEMBER_CUSTOMER"."MEMBER_ID" IS 'FK:EC_MEMBER_ID';
COMMENT ON COLUMN "EC_MEMBER_CUSTOMER"."CUSTOMER_ID" IS 'FK:EC_CUSTOMER_ID';

--  會員-台泥伙伴(ManyToMany)
CREATE TABLE "EC_MEMBER_PARTNER" 
(
"MEMBER_ID" NUMBER(18,0) NOT NULL ENABLE, 
"PARTNER_ID" NUMBER(18,0) NOT NULL ENABLE, 
"DUMMY" VARCHAR2(20 BYTE), 
CONSTRAINT "EC_MEMBER_PARTNER_PK" PRIMARY KEY ("MEMBER_ID", "PARTNER_ID") ENABLE, 
CONSTRAINT "EC_MEMBER_PARTNER_EC_MEMB_FK1" FOREIGN KEY ("MEMBER_ID") REFERENCES "EC_MEMBER" ("ID") ENABLE, 
CONSTRAINT "EC_MEMBER_PARTNER_EC_PART_FK1" FOREIGN KEY ("PARTNER_ID") REFERENCES "EC_PARTNER" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_MEMBER_PARTNER"."MEMBER_ID" IS 'FK:EC_MEMBER.ID';
COMMENT ON COLUMN "EC_MEMBER_PARTNER"."PARTNER_ID" IS 'FK:EC_PARTNE.ID';

-- 出貨廠-商品(ManyToMany)
CREATE TABLE "EC_PLANT_PRODUCT"
(
"PLANT_ID" NUMBER(18,0) NOT NULL ENABLE,
"PRODUCT_ID" NUMBER(18,0) NOT NULL ENABLE,
"ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
CONSTRAINT "EC_PLANT_PRODUCT_PK" PRIMARY KEY ("PLANT_ID", "PRODUCT_ID") ENABLE,
CONSTRAINT "EC_PLANT_PRODUCT_FK1" FOREIGN KEY ("PLANT_ID") REFERENCES "EC_PLANT" ("ID") ENABLE,
CONSTRAINT "EC_PLANT_PRODUCT_FK2" FOREIGN KEY ("PRODUCT_ID") REFERENCES "EC_PRODUCT" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_PLANT_PRODUCT"."PLANT_ID" IS 'FK:EC_PLANT.ID';
COMMENT ON COLUMN "EC_PLANT_PRODUCT"."PRODUCT_ID" IS 'FK:EC_PRODUCT.ID';
COMMENT ON COLUMN "EC_PLANT_PRODUCT"."ACTIVE" IS '1:啟用, 0:停用';

-- 出貨廠-銷售區
CREATE TABLE "EC_PLANT_SALESAREA"
(
"PLANT_ID" NUMBER(18,0) NOT NULL ENABLE,
"SALESAREA_ID" NUMBER(18,0) NOT NULL ENABLE,
"DUMMY" VARCHAR2(20),
CONSTRAINT "EC_PLANT_SALESAREA_PK" PRIMARY KEY ("PLANT_ID", "SALESAREA_ID") ENABLE,
CONSTRAINT "EC_PLANT_SALESAREA_FK1" FOREIGN KEY ("PLANT_ID") REFERENCES "EC_PLANT" ("ID") ENABLE,
CONSTRAINT "EC_PLANT_SALESAREA_FK2" FOREIGN KEY ("SALESAREA_ID") REFERENCES "EC_SALESAREA" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_PLANT_SALESAREA"."PLANT_ID" IS 'FK:EC_PLANT.ID';
COMMENT ON COLUMN "EC_PLANT_SALESAREA"."SALESAREA_ID" IS 'FK:EC_SALESAREA.ID';

-- 合約商品
CREATE TABLE "EC_CONTRACT_PRODUCT"
(
"CONTRACT_ID" NUMBER(18,0) NOT NULL ENABLE,
"PRODUCT_ID" NUMBER(18,0) NOT NULL ENABLE,
"PLANT_ID" NUMBER(18,0) NOT NULL ENABLE,
"SALESAREA_ID" NUMBER(18,0) NOT NULL ENABLE,
"UNIT_PRICE" NUMBER(15,2),
"METHOD" VARCHAR2(3 BYTE) NOT NULL ENABLE,
"POSNR" NUMBER(3,0) DEFAULT 10 NOT NULL ENABLE,
CONSTRAINT "EC_CONTRACT_PRODUCT_PK" PRIMARY KEY ("CONTRACT_ID","POSNR") ENABLE,
CONSTRAINT "EC_CONTRACT_PRODUCT_FK1" FOREIGN KEY ("CONTRACT_ID") REFERENCES "EC_CONTRACT" ("ID") ENABLE,
CONSTRAINT "EC_CONTRACT_PRODUCT_FK2" FOREIGN KEY ("PRODUCT_ID") REFERENCES "EC_PRODUCT" ("ID") ENABLE,
CONSTRAINT "EC_CONTRACT_PRODUCT_FK3" FOREIGN KEY ("PLANT_ID") REFERENCES "EC_PLANT" ("ID") ENABLE,
CONSTRAINT "EC_CONTRACT_PRODUCT_FK4" FOREIGN KEY ("SALESAREA_ID") REFERENCES "EC_SALESAREA" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_CONTRACT_PRODUCT"."CONTRACT_ID" IS 'FK:EC_CONTRACT.ID';
COMMENT ON COLUMN "EC_CONTRACT_PRODUCT"."PRODUCT_ID" IS 'FK:EC_PRODUCT.ID';
COMMENT ON COLUMN "EC_CONTRACT_PRODUCT"."PLANT_ID" IS 'FK:EC_PLANT.ID';
COMMENT ON COLUMN "EC_CONTRACT_PRODUCT"."SALESAREA_ID" IS 'FK:EC_SALESAREA.ID';
COMMENT ON COLUMN "EC_CONTRACT_PRODUCT"."UNIT_PRICE" IS '單價';
COMMENT ON COLUMN "EC_CONTRACT_PRODUCT"."METHOD" IS '廠交自提/工地交自提';
COMMENT ON COLUMN "EC_CONTRACT_PRODUCT"."POSNR" IS '合約項次';

-- 客戶-業務員
CREATE TABLE "EC_CUSTOMER_SALES"
(
"CUSTOMER_ID" NUMBER(18,0) NOT NULL ENABLE,
"SALES_ID" NUMBER(18,0) NOT NULL ENABLE,
"DUMMY" VARCHAR2(20),
CONSTRAINT "EC_CUSTOMER_SALES_PK1" PRIMARY KEY ("CUSTOMER_ID", "SALES_ID") ENABLE,
CONSTRAINT "EC_CUSTOMER_SALES_FK1" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "EC_CUSTOMER" ("ID") ENABLE,
CONSTRAINT "EC_CUSTOMER_SALES_FK2" FOREIGN KEY ("SALES_ID") REFERENCES "EC_SALES" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_CUSTOMER_SALES"."CUSTOMER_ID" IS 'FK:EC_CUSTOMER.ID';
COMMENT ON COLUMN "EC_CUSTOMER_SALES"."SALES_ID" IS 'FK:EC_SALES.ID';

-- 常用送達地點
CREATE TABLE "EC_DELIVERY_PREFERENCE" 
(
"MEMBER_ID" NUMBER(18,0) NOT NULL ENABLE, 
"DELIVERY_ID" NUMBER(18,0) NOT NULL ENABLE, 
"DUMMY" VARCHAR2(20 BYTE), 
"PLANT_ID" NUMBER(18,0) NOT NULL ENABLE, 
CONSTRAINT "EC_DELIVERY_PREFERENCE_PK" PRIMARY KEY ("MEMBER_ID", "DELIVERY_ID", "PLANT_ID") ENABLE, 
CONSTRAINT "EC_DELIVERY_PREFERENCE_FK1" FOREIGN KEY ("MEMBER_ID") REFERENCES "EC_MEMBER" ("ID") ENABLE, 
CONSTRAINT "EC_DELIVERY_PREFERENCE_FK2" FOREIGN KEY ("DELIVERY_ID") REFERENCES "EC_DELIVERY_PLACE" ("ID") ENABLE, 
CONSTRAINT "EC_DELIVERY_PREFERENCE_FK3" FOREIGN KEY ("PLANT_ID") REFERENCES "EC_PLANT" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_DELIVERY_PREFERENCE"."MEMBER_ID" IS 'FK:EC_MEMBER.ID';
COMMENT ON COLUMN "EC_DELIVERY_PREFERENCE"."DELIVERY_ID" IS 'FK:EC_DELIVERY_PLACE.ID';
COMMENT ON COLUMN "EC_DELIVERY_PREFERENCE"."PLANT_ID" IS 'FK:EC_PLANT.ID';

-- 訂單
CREATE TABLE "EC_ORDER"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"MEMBER_ID" NUMBER(18,0) NOT NULL ENABLE,
"CUSTOMER_ID" NUMBER(18,0) NOT NULL ENABLE,
"PRODUCT_ID" NUMBER(18,0) NOT NULL ENABLE,
"PRODUCT_CODE" VARCHAR2(18 CHAR) NOT NULL ENABLE,
"PRODUCT_NAME" VARCHAR2(80 CHAR) NOT NULL ENABLE,
"UNIT_PRICE" NUMBER(15,2),
"QUANTITY" NUMBER(12,3) NOT NULL ENABLE,
"AMOUNT" NUMBER(15,2),
"VEHICLE" VARCHAR2(40 CHAR) NOT NULL ENABLE,
"DELIVERY_DATE" VARCHAR2(8 BYTE) NOT NULL ENABLE,
"METHOD" VARCHAR2(3 BYTE) NOT NULL ENABLE,
"CONTRACT_ID" NUMBER(18,0),
"CONTRACT_CODE" VARCHAR2(50 CHAR),
"CONTRACT_NAME" VARCHAR2(50 CHAR),
"PLANT_ID" NUMBER(18,0) NOT NULL ENABLE,
"PLANT_CODE" VARCHAR2(10 CHAR) NOT NULL ENABLE,
"PLANT_NAME" VARCHAR2(70 CHAR) NOT NULL ENABLE,
"SALESAREA_ID" NUMBER(18,0) NOT NULL ENABLE,
"SALESAREA_CODE" VARCHAR2(6 CHAR) NOT NULL ENABLE,
"SALESAREA_NAME" VARCHAR2(40 CHAR) NOT NULL ENABLE,
"DELIVERY_ID" NUMBER(18,0),
"DELIVERY_CODE" VARCHAR2(20 BYTE),
"DELIVERY_NAME" VARCHAR2(140 CHAR),
"SALES_ID" NUMBER(18,0) NOT NULL ENABLE,
"SALES_CODE" VARCHAR2(8 CHAR) NOT NULL ENABLE,
"SALES_NAME" VARCHAR2(40 CHAR) NOT NULL ENABLE,
"BONUS"	NUMBER(5,0) DEFAULT 0 NOT NULL ENABLE,
"STATUS" VARCHAR2(20 BYTE) NOT NULL ENABLE,
"SAP_ORDERNUM" VARCHAR2(40 CHAR),
"MESSAGE" VARCHAR2(255 CHAR),
"CREATETIME" DATE NOT NULL ENABLE,
"SITE_LOC" VARCHAR2(60 BYTE), 
"APPROVER" NUMBER(18,0), 
"APPROVAL_TIME" DATE, 
"POSNR" NUMBER(3,0), 
CONSTRAINT "EC_ORDER_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_ORDER_EC_CONTRACT_FK1" FOREIGN KEY ("CONTRACT_ID") REFERENCES "EC_CONTRACT" ("ID") ENABLE,
CONSTRAINT "EC_ORDER_EC_CUSTOMER_FK1" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "EC_CUSTOMER" ("ID") ENABLE,
CONSTRAINT "EC_ORDER_EC_DELIVERY_FK1" FOREIGN KEY ("DELIVERY_ID") REFERENCES "EC_DELIVERY_PLACE" ("ID") ENABLE,
CONSTRAINT "EC_ORDER_EC_MEMBER_FK1" FOREIGN KEY ("MEMBER_ID") REFERENCES "EC_MEMBER" ("ID") ENABLE,
CONSTRAINT "EC_ORDER_EC_PLANT_FK1" FOREIGN KEY ("PLANT_ID") REFERENCES "EC_PLANT" ("ID") ENABLE,
CONSTRAINT "EC_ORDER_EC_PRODUCT_FK1" FOREIGN KEY ("PRODUCT_ID") REFERENCES "EC_PRODUCT" ("ID") ENABLE,
CONSTRAINT "EC_ORDER_EC_SALESAREA_FK1" FOREIGN KEY ("SALESAREA_ID") REFERENCES "EC_SALESAREA" ("ID") ENABLE,
CONSTRAINT "EC_ORDER_EC_SALES_FK1" FOREIGN KEY ("SALES_ID") REFERENCES "EC_SALES" ("ID") ENABLE,
CONSTRAINT "EC_ORDER_TC_USER_FK1" FOREIGN KEY ("APPROVER") REFERENCES "TC_USER" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_ORDER"."ID" IS 'PK';
COMMENT ON COLUMN "EC_ORDER"."MEMBER_ID" IS 'FK:EC_MEMBER.ID';
COMMENT ON COLUMN "EC_ORDER"."CUSTOMER_ID" IS 'FK:EC_CUSTOMER.ID';
COMMENT ON COLUMN "EC_ORDER"."PRODUCT_ID" IS 'FK:EC_PRODUCT.ID';
COMMENT ON COLUMN "EC_ORDER"."PRODUCT_CODE" IS '料號';
COMMENT ON COLUMN "EC_ORDER"."PRODUCT_NAME" IS '品名';
COMMENT ON COLUMN "EC_ORDER"."UNIT_PRICE" IS '單價(RMB)';
COMMENT ON COLUMN "EC_ORDER"."QUANTITY" IS '數量';
COMMENT ON COLUMN "EC_ORDER"."AMOUNT" IS '總額';
COMMENT ON COLUMN "EC_ORDER"."VEHICLE" IS '車號';
COMMENT ON COLUMN "EC_ORDER"."DELIVERY_DATE" IS '提貨日';
COMMENT ON COLUMN "EC_ORDER"."METHOD" IS '廠交自提/工地交自提';
COMMENT ON COLUMN "EC_ORDER"."CONTRACT_ID" IS 'FK:EC_CONTRACT.ID';
COMMENT ON COLUMN "EC_ORDER"."CONTRACT_CODE" IS '合約號碼';
COMMENT ON COLUMN "EC_ORDER"."CONTRACT_NAME" IS '合約名稱';
COMMENT ON COLUMN "EC_ORDER"."PLANT_ID" IS 'FK:EC_PLANT.ID';
COMMENT ON COLUMN "EC_ORDER"."PLANT_CODE" IS '廠代碼';
COMMENT ON COLUMN "EC_ORDER"."PLANT_NAME" IS '廠名稱';
COMMENT ON COLUMN "EC_ORDER"."SALESAREA_ID" IS 'FK:EC_SALESAREA.ID';
COMMENT ON COLUMN "EC_ORDER"."SALESAREA_CODE" IS '銷售區代碼';
COMMENT ON COLUMN "EC_ORDER"."SALESAREA_NAME" IS '銷售區名稱';
COMMENT ON COLUMN "EC_ORDER"."DELIVERY_ID" IS 'FK:EC_DELIVERY_PLACE.ID';
COMMENT ON COLUMN "EC_ORDER"."DELIVERY_CODE" IS '送達地點代碼';
COMMENT ON COLUMN "EC_ORDER"."DELIVERY_NAME" IS '送達地點名稱';
COMMENT ON COLUMN "EC_ORDER"."SALES_ID" IS 'FK:EC_SALES.ID';
COMMENT ON COLUMN "EC_ORDER"."SALES_CODE" IS '業務員工號';
COMMENT ON COLUMN "EC_ORDER"."SALES_NAME" IS '業務員名稱';
COMMENT ON COLUMN "EC_ORDER"."BONUS" IS '紅利';
COMMENT ON COLUMN "EC_ORDER"."SAP_ORDERNUM" IS 'SAP訂單號碼';
COMMENT ON COLUMN "EC_ORDER"."MESSAGE" IS '訊息';
COMMENT ON COLUMN "EC_ORDER"."STATUS" IS '狀態 (OPEN:未出貨, CANCEL: 取消, CLOSE:已出貨)';
COMMENT ON COLUMN "EC_ORDER"."CREATETIME" IS '建立時間';
COMMENT ON COLUMN "EC_ORDER"."SITE_LOC" IS '袋裝噴碼';
COMMENT ON COLUMN "EC_ORDER"."APPROVER" IS '審核員(FK:TC_USER.ID)';
COMMENT ON COLUMN "EC_ORDER"."APPROVAL_TIME" IS '審核時間';
COMMENT ON COLUMN "EC_ORDER"."POSNR" IS '合約項次';

-- 紅利/金幣記錄
CREATE TABLE "EC_REWARD_LOG" 
(
"ID" NUMBER(18,0) NOT NULL ENABLE, 
"MEMBER_ID" NUMBER(18,0) NOT NULL ENABLE, 
"TYPE" NUMBER(1,0) NOT NULL ENABLE, 
"POINTS" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
"POINT_BALANCE" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
"EVENT_TYPE" VARCHAR2(40 CHAR) NOT NULL ENABLE, 
"EVENT_DETAIL" VARCHAR2(300 CHAR), 
"EVENT_TIME" DATE NOT NULL ENABLE, 
"CREATOR" NUMBER(18,0), 
"ORDER_ID" NUMBER(18,0), 
CONSTRAINT "EC_REWARD_LOG_PK" PRIMARY KEY ("ID") ENABLE, 
CONSTRAINT "EC_REWARD_LOG_EC_MEMBER_FK1" FOREIGN KEY ("MEMBER_ID") REFERENCES "EC_MEMBER" ("ID") ENABLE, 
CONSTRAINT "EC_REWARD_LOG_EC_MEMBER_FK2" FOREIGN KEY ("CREATOR") REFERENCES "TC_USER" ("ID") ENABLE, 
CONSTRAINT "EC_REWARD_LOG_EC_ORDER_FK1" FOREIGN KEY ("ORDER_ID") REFERENCES "EC_ORDER" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_REWARD_LOG"."ID" IS 'PK';
COMMENT ON COLUMN "EC_REWARD_LOG"."MEMBER_ID" IS 'FK:EC_MEMBER.ID';
COMMENT ON COLUMN "EC_REWARD_LOG"."TYPE" IS '1:紅利, 2:金幣';
COMMENT ON COLUMN "EC_REWARD_LOG"."POINTS" IS '贈點';
COMMENT ON COLUMN "EC_REWARD_LOG"."POINT_BALANCE" IS '累計點數(含贈點)';
COMMENT ON COLUMN "EC_REWARD_LOG"."EVENT_TYPE" IS 'LOGIN, ORDER_CREATE, ...';
COMMENT ON COLUMN "EC_REWARD_LOG"."EVENT_TIME" IS '贈點時間';
COMMENT ON COLUMN "EC_REWARD_LOG"."CREATOR" IS '建立者(FK:TC_USER.ID)';
COMMENT ON COLUMN "EC_REWARD_LOG"."ORDER_ID" IS 'FK:EC_ORDER.ID';

-- 伙伴評語
CREATE TABLE "EC_PARTNER_COMMENT"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"PARTNER_ID" NUMBER(18,0) NOT NULL ENABLE,
"MEMBER_ID" NUMBER(18,0) NOT NULL ENABLE,
"RATE" NUMBER(2,1) NOT NULL ENABLE,
"MESSAGE" VARCHAR2(500 CHAR),
"STATUS" VARCHAR2(20),
"ACTIVE" number(1) not null,
"CREATETIME" DATE NOT NULL ENABLE,
"APPROVER" NUMBER(18,0), 
"APPROVAL_TIME" DATE, 
CONSTRAINT "EC_PARTNER_COMMENT_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_PARTNER_COMMENT_FK1" FOREIGN KEY ("PARTNER_ID") REFERENCES "EC_PARTNER" ("ID") ENABLE,
CONSTRAINT "EC_PARTNER_COMMENT_FK2" FOREIGN KEY ("MEMBER_ID") REFERENCES "EC_MEMBER" ("ID") ENABLE,
CONSTRAINT "EC_PARTNER_COMMENT_FK3" FOREIGN KEY ("APPROVER") REFERENCES "TC_USER" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_PARTNER_COMMENT"."ID" IS 'PK';
COMMENT ON COLUMN "EC_PARTNER_COMMENT"."PARTNER_ID" IS 'FK:EC_PARTNER.ID';
COMMENT ON COLUMN "EC_PARTNER_COMMENT"."MEMBER_ID" IS 'FK:EC_MEMBER.ID';
COMMENT ON COLUMN "EC_PARTNER_COMMENT"."RATE" IS '評分(0~5)';
COMMENT ON COLUMN "EC_PARTNER_COMMENT"."MESSAGE" IS '評語';
COMMENT ON COLUMN "EC_PARTNER_COMMENT"."STATUS" IS 'APPLY, APPROVE, REJECT';
COMMENT ON COLUMN "EC_PARTNER_COMMENT"."ACTIVE" IS '0:失效, 1:生效';
COMMENT ON COLUMN "EC_PARTNER_COMMENT"."CREATETIME" IS '建立時間';
COMMENT ON COLUMN "EC_PARTNER_COMMENT"."APPROVER" IS '審核員(FK:TC_USER.ID)';
COMMENT ON COLUMN "EC_PARTNER_COMMENT"."APPROVAL_TIME" IS '審核時間';

-- 伙伴商品
CREATE TABLE "EC_BANNER_PRODUCT"
(
"BANNER_ID" NUMBER(18,0) NOT NULL ENABLE,
"PRODUCT_ID" NUMBER(18,0) NOT NULL ENABLE,
"DUMMY" VARCHAR2(20),
CONSTRAINT "EC_BANNER_PRODUCT_PK" PRIMARY KEY ("BANNER_ID", "PRODUCT_ID") ENABLE,
CONSTRAINT "EC_BANNER_PRODUCT_FK1" FOREIGN KEY ("BANNER_ID") REFERENCES "EC_BANNER" ("ID") ENABLE,
CONSTRAINT "EC_BANNER_PRODUCT_FK2" FOREIGN KEY ("PRODUCT_ID") REFERENCES "EC_PRODUCT" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_BANNER_PRODUCT"."BANNER_ID" IS 'FK:EC_BANNER.ID';
COMMENT ON COLUMN "EC_BANNER_PRODUCT"."PRODUCT_ID" IS 'FK:EC_PRODUCT.ID';

-- 伙伴商品
/*
CREATE TABLE "EC_PARTNER_PRODUCT"
(
"PARTNER_ID" NUMBER(18,0) NOT NULL ENABLE,
"PRODUCT_ID" NUMBER(18,0) NOT NULL ENABLE,
"UNIT_PRICE" NUMBER(15,2),
CONSTRAINT "EC_PARTNER_PRODUCT_PK" PRIMARY KEY ("PARTNER_ID", "PRODUCT_ID") ENABLE,
CONSTRAINT "EC_PARTNER_PRODUCT_FK1" FOREIGN KEY ("PARTNER_ID") REFERENCES "EC_PARTNER" ("ID") ENABLE,
CONSTRAINT "EC_PARTNER_PRODUCT_FK2" FOREIGN KEY ("PRODUCT_ID") REFERENCES "EC_PRODUCT" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_PARTNER_PRODUCT"."PARTNER_ID" IS 'FK:EC_PARTNER.ID';
COMMENT ON COLUMN "EC_PARTNER_PRODUCT"."PRODUCT_ID" IS 'FK:EC_PRODUCT.ID';
COMMENT ON COLUMN "EC_PARTNER_PRODUCT"."UNIT_PRICE" IS '單價(RMB)';
*/

CREATE TABLE "EC_PARTNER_GOODS" 
(
"PARTNER_ID" NUMBER(18,0) NOT NULL ENABLE, 
"GOODS_ID" NUMBER(18,0) NOT NULL ENABLE, 
"DUMMY" VARCHAR2(20 BYTE), 
CONSTRAINT "EC_PARTNER_GOODS_PK" PRIMARY KEY ("PARTNER_ID", "GOODS_ID") ENABLE, 
CONSTRAINT "EC_PARTNER_GOODS_FK1" FOREIGN KEY ("PARTNER_ID") REFERENCES "EC_PARTNER" ("ID") ENABLE, 
CONSTRAINT "EC_PARTNER_GOODS_FK2" FOREIGN KEY ("GOODS_ID") REFERENCES "EC_GOODS" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_PARTNER_GOODS"."PARTNER_ID" IS 'FK:EC_PARTNER.ID';
COMMENT ON COLUMN "EC_PARTNER_GOODS"."GOODS_ID" IS 'FK:EC_GOODS.ID';

-- 申請會員,簽約客戶
CREATE TABLE "EC_FORM" 
(
"ID" NUMBER(18,0) NOT NULL ENABLE, 
"TYPE" NUMBER(1,0) NOT NULL ENABLE, 
"NAME" VARCHAR2(64 CHAR) NOT NULL ENABLE, 
"EMAIL" VARCHAR2(64 BYTE) NOT NULL ENABLE, 
"PHONE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
"CREATETIME" DATE NOT NULL ENABLE, 
"STATUS" NUMBER(1,0) NOT NULL ENABLE, 
"NOTES" VARCHAR2(100 BYTE), 
"MEMBER_ID" NUMBER(18,0), 
"PROVINCE" VARCHAR2(20 CHAR), 
CONSTRAINT "EC_FORM_PK" PRIMARY KEY ("ID") ENABLE, 
CONSTRAINT "EC_FORM_EC_MEMBER_FK1" FOREIGN KEY ("MEMBER_ID") REFERENCES "EC_MEMBER" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_FORM"."ID" IS 'PK';
COMMENT ON COLUMN "EC_FORM"."TYPE" IS '1:申請註冊, 2:申請簽約客戶';
COMMENT ON COLUMN "EC_FORM"."NAME" IS '名稱';
COMMENT ON COLUMN "EC_FORM"."EMAIL" IS '信箱';
COMMENT ON COLUMN "EC_FORM"."PHONE" IS '電話';
COMMENT ON COLUMN "EC_FORM"."CREATETIME" IS '建立時間';
COMMENT ON COLUMN "EC_FORM"."STATUS" IS '1:申請, 2:已同意, 3:已拒絕';
COMMENT ON COLUMN "EC_FORM"."NOTES" IS '備註';
COMMENT ON COLUMN "EC_FORM"."MEMBER_ID" IS '會員ID(申請簽約客戶用)';
COMMENT ON COLUMN "EC_FORM"."PROVINCE" IS '省';

-- 散客商品購買
/*
CREATE TABLE "EC_PRODUCT_BUY" 
(
"ID" NUMBER(18,0) NOT NULL ENABLE, 
"PRODUCT_ID" NUMBER(18,0) NOT NULL ENABLE, 
"MEMBER_ID" NUMBER(18,0) NOT NULL ENABLE, 
"QUANTITY" NUMBER(9,0) NOT NULL ENABLE, 
"UOM" VARCHAR2(3 CHAR),
"CREATETIME" DATE NOT NULL ENABLE, 
CONSTRAINT "EC_PRODUCT_BUY_PK" PRIMARY KEY ("ID") ENABLE, 
CONSTRAINT "EC_PRODUCT_BUY_FK1" FOREIGN KEY ("PRODUCT_ID") REFERENCES "EC_PRODUCT" ("ID") ENABLE,
CONSTRAINT "EC_PRODUCT_BUY_FK2" FOREIGN KEY ("MEMBER_ID") REFERENCES "EC_MEMBER" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_PRODUCT_BUY"."ID" IS 'PK';
COMMENT ON COLUMN "EC_PRODUCT_BUY"."PRODUCT_ID" IS 'FK:EC_PRODUCT.ID';
COMMENT ON COLUMN "EC_PRODUCT_BUY"."MEMBER_ID" IS 'FK:EC_MEMBER.ID';
COMMENT ON COLUMN "EC_PRODUCT_BUY"."QUANTITY" IS '購買數量';
COMMENT ON COLUMN "EC_PRODUCT_BUY"."UOM" IS '單位(噸,包)';
COMMENT ON COLUMN "EC_PRODUCT_BUY"."CREATETIME" IS '建立時間';
*/

CREATE TABLE "EC_GOODS_BUY" 
(
"ID" NUMBER(18,0) NOT NULL ENABLE, 
"GOODS_ID" NUMBER(18,0) NOT NULL ENABLE, 
"MEMBER_ID" NUMBER(18,0) NOT NULL ENABLE, 
"QUANTITY" NUMBER(9,0) NOT NULL ENABLE, 
"UOM" VARCHAR2(3 CHAR), 
"CREATETIME" DATE NOT NULL ENABLE, 
CONSTRAINT "EC_GOODS_BUY_PK" PRIMARY KEY ("ID") ENABLE, 
CONSTRAINT "EC_GOODS_BUY_FK1" FOREIGN KEY ("GOODS_ID") REFERENCES "EC_GOODS" ("ID") ENABLE, 
CONSTRAINT "EC_GOODS_BUY_FK2" FOREIGN KEY ("MEMBER_ID") REFERENCES "EC_MEMBER" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_GOODS_BUY"."ID" IS 'PK';
COMMENT ON COLUMN "EC_GOODS_BUY"."GOODS_ID" IS 'FK:EC_GOODS.ID';
COMMENT ON COLUMN "EC_GOODS_BUY"."MEMBER_ID" IS 'FK:EC_MEMBER.ID';
COMMENT ON COLUMN "EC_GOODS_BUY"."QUANTITY" IS '購買數量';
COMMENT ON COLUMN "EC_GOODS_BUY"."UOM" IS '單位(噸,包)';
COMMENT ON COLUMN "EC_GOODS_BUY"."CREATETIME" IS '建立時間';

-- click log
CREATE TABLE "EC_CLICK_LOG" 
(
"ID" NUMBER(18,0) NOT NULL ENABLE, 
"CLIENT_KEY" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
"MEMBER_ID" NUMBER(18,0), 
"OBJ_TYPE" VARCHAR2(64 BYTE) NOT NULL ENABLE, 
"OBJ_ID" NUMBER(18,0) NOT NULL ENABLE, 
"CREATETIME" DATE NOT NULL ENABLE, 
CONSTRAINT "EC_CLICK_LOG_PK" PRIMARY KEY ("ID") ENABLE, 
CONSTRAINT "EC_CLICK_LOG_EC_MEMBER_FK1" FOREIGN KEY ("MEMBER_ID") REFERENCES "EC_MEMBER" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_CLICK_LOG"."ID" IS 'PK';
COMMENT ON COLUMN "EC_CLICK_LOG"."CLIENT_KEY" IS 'client ID';
COMMENT ON COLUMN "EC_CLICK_LOG"."MEMBER_ID" IS 'FK:EC_MEMBER.ID';
COMMENT ON COLUMN "EC_CLICK_LOG"."OBJ_TYPE" IS 'entity type';
COMMENT ON COLUMN "EC_CLICK_LOG"."OBJ_ID" IS 'entity id';
COMMENT ON COLUMN "EC_CLICK_LOG"."CREATETIME" IS '建立時間';

-- 通知
CREATE TABLE "EC_NOTIFY" 
(
"ID" NUMBER(18,0) NOT NULL ENABLE, 
"TYPE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
"SUBJECT" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
"READ_COUNT" NUMBER(3,0) DEFAULT 0, 
"NOTIFY_CLASSNAME" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
"NOTIFY_CLASSID" NUMBER(18,0) NOT NULL ENABLE, 
"MEMBER_ID" NUMBER(18,0) NOT NULL ENABLE, 
"CREATETIME" DATE, 
CONSTRAINT "EC_NOTIFY_PK" PRIMARY KEY ("ID") ENABLE, 
CONSTRAINT "EC_NOTIFY_FK01" FOREIGN KEY ("MEMBER_ID") REFERENCES "EC_MEMBER" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_NOTIFY"."ID" IS 'PK';
COMMENT ON COLUMN "EC_NOTIFY"."TYPE" IS '類別';
COMMENT ON COLUMN "EC_NOTIFY"."SUBJECT" IS '標題';
COMMENT ON COLUMN "EC_NOTIFY"."READ_COUNT" IS '閱讀次數';
COMMENT ON COLUMN "EC_NOTIFY"."NOTIFY_CLASSNAME" IS 'Notify class name';
COMMENT ON COLUMN "EC_NOTIFY"."NOTIFY_CLASSID" IS 'Notify class id';
COMMENT ON COLUMN "EC_NOTIFY"."MEMBER_ID" IS 'FK:EC_MEMBER.ID';
COMMENT ON COLUMN "EC_NOTIFY"."CREATETIME" IS '通知時間';


-- 訂單 log
CREATE TABLE "EC_ORDER_LOG" 
(
"ID" NUMBER(18,0) NOT NULL ENABLE, 
"ORDER_ID" NUMBER(18,0) NOT NULL ENABLE, 
"EVENT_TYPE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
"CREATETIME" DATE NOT NULL ENABLE, 
"MEMBER_ID" NUMBER(18,0), 
"USER_ID" NUMBER(18,0), 
"MESSAGE" VARCHAR2(100 CHAR), 
CONSTRAINT "EC_ORDER_LOG_PK" PRIMARY KEY ("ID") ENABLE, 
CONSTRAINT "EC_ORDER_LOG_FK1" FOREIGN KEY ("ORDER_ID") REFERENCES "EC_ORDER" ("ID") ENABLE, 
CONSTRAINT "EC_ORDER_LOG_FK2" FOREIGN KEY ("MEMBER_ID") REFERENCES "EC_MEMBER" ("ID") ENABLE, 
CONSTRAINT "EC_ORDER_LOG_FK3" FOREIGN KEY ("USER_ID") REFERENCES "TC_USER" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_ORDER_LOG"."ID" IS 'PK';
COMMENT ON COLUMN "EC_ORDER_LOG"."ORDER_ID" IS 'FK:EC_ORDER.ID';
COMMENT ON COLUMN "EC_ORDER_LOG"."EVENT_TYPE" IS 'OPEN,APPROVE,FAIL,CANCEL,CLOSE';
COMMENT ON COLUMN "EC_ORDER_LOG"."CREATETIME" IS '建立時間';
COMMENT ON COLUMN "EC_ORDER_LOG"."MEMBER_ID" IS 'FK:EC_MEMBER.ID(前台user)';
COMMENT ON COLUMN "EC_ORDER_LOG"."USER_ID" IS 'FK:TC_USER.ID(後台user)';
COMMENT ON COLUMN "EC_ORDER_LOG"."MESSAGE" IS '訊息';

-- 登入 log
CREATE TABLE "EC_LOGIN_LOG" 
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"MEMBER_ID" NUMBER(18,0) NOT NULL ENABLE,
"LOGIN_TIME" DATE NOT NULL ENABLE,
CONSTRAINT "EC_LOGIN_LOG_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_LOGIN_LOG_EC_MEMBER_FK1" FOREIGN KEY ("MEMBER_ID") REFERENCES "EC_MEMBER" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_LOGIN_LOG"."ID" IS 'PK';
COMMENT ON COLUMN "EC_LOGIN_LOG"."LOGIN_TIME" IS '登入時間';
COMMENT ON COLUMN "EC_LOGIN_LOG"."MEMBER_ID" IS 'FK:EC_MEMBER.ID';

-- 常用車輛
CREATE TABLE "EC_VEHICLE_PREFERENCE" 
(
"MEMBER_ID" NUMBER(18,0) NOT NULL ENABLE, 
"VEHICLE" VARCHAR2(40 CHAR) NOT NULL ENABLE, 
"DUMMY" VARCHAR2(20 BYTE), 
CONSTRAINT "EC_VEHICLE_PREFERENCE_PK" PRIMARY KEY ("MEMBER_ID", "VEHICLE") ENABLE
);
COMMENT ON COLUMN "EC_VEHICLE_PREFERENCE"."MEMBER_ID" IS 'FK:EC_MEMBER.ID';
COMMENT ON COLUMN "EC_VEHICLE_PREFERENCE"."VEHICLE" IS '車號';

-- 送達地點銷售組織
CREATE TABLE "EC_DELIVERY_VKORG" 
(
"DELIVERY_ID" NUMBER(18,0) NOT NULL ENABLE, 
"VKORG" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
"SALESAREA_ID" NUMBER(18,0) NOT NULL ENABLE, 
CONSTRAINT "EC_DELIVERY_VKORG_PK" PRIMARY KEY ("DELIVERY_ID", "VKORG") ENABLE, 
CONSTRAINT "EC_DELIVERY_VKORG_FK1" FOREIGN KEY ("DELIVERY_ID") REFERENCES "EC_DELIVERY_PLACE" ("ID") ENABLE, 
CONSTRAINT "EC_DELIVERY_VKORG_FK2" FOREIGN KEY ("SALESAREA_ID") REFERENCES "EC_SALESAREA" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_DELIVERY_VKORG"."DELIVERY_ID" IS 'FK:EC_DELIVERY_PLACE.ID';
COMMENT ON COLUMN "EC_DELIVERY_VKORG"."VKORG" IS '銷售組織';
COMMENT ON COLUMN "EC_DELIVERY_VKORG"."SALESAREA_ID" IS 'FK:EC_SALESAREA.ID';

-- 排程
CREATE TABLE "TC_SCHEDULE" 
(
"NAME" VARCHAR2(50) NOT NULL ENABLE,
"EXEC_TIME" DATE,
"ACTIVE" NUMBER(1,0) DEFAULT 1,
CONSTRAINT "TC_SCHEDULE_PK" PRIMARY KEY ("NAME") ENABLE
);
COMMENT ON COLUMN "TC_SCHEDULE"."ACTIVE" IS '啟用 (1:是, 0:否)';
COMMENT ON COLUMN "TC_SCHEDULE"."EXEC_TIME" IS '前次執行時間';
COMMENT ON COLUMN "TC_SCHEDULE"."NAME" IS 'PK:排程名稱';

-- 文章
CREATE TABLE "EC_ARTICLE" 
(
"ID" NUMBER(18,0) NOT NULL ENABLE, 
"TITLE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
"PUBDATE" DATE, 
"LINK" VARCHAR2(255 BYTE), 
"ACTIVE" NUMBER(1,0) NOT NULL ENABLE, 
"CREATOR" NUMBER(18,0) NOT NULL ENABLE, 
"CREATETIME" DATE NOT NULL ENABLE, 
CONSTRAINT "EC_ARTICLE_PK" PRIMARY KEY ("ID") ENABLE, 
CONSTRAINT "EC_ARTICLE_FK1" FOREIGN KEY ("CREATOR") REFERENCES "TC_USER" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_ARTICLE"."ID" IS 'PK';
COMMENT ON COLUMN "EC_ARTICLE"."TITLE" IS '主旨';
COMMENT ON COLUMN "EC_ARTICLE"."PUBDATE" IS '發佈時間';
COMMENT ON COLUMN "EC_ARTICLE"."LINK" IS '內容網址';
COMMENT ON COLUMN "EC_ARTICLE"."ACTIVE" IS '1:有效, 0:無效';
COMMENT ON COLUMN "EC_ARTICLE"."CREATOR" IS '建立者(FK:TC_USER.ID)';
COMMENT ON COLUMN "EC_ARTICLE"."CREATETIME" IS '建立時間';

-- 公告
CREATE TABLE "EC_BULLETIN" 
(
"ID" NUMBER(18,0) NOT NULL ENABLE, 
"TITLE" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
"START_TIME" DATE NOT NULL ENABLE, 
"END_TIME" DATE NOT NULL ENABLE, 
"ACTIVE" NUMBER(1,0) NOT NULL ENABLE, 
"CREATOR" NUMBER(18,0) NOT NULL ENABLE, 
"CREATETIME" DATE NOT NULL ENABLE, 
CONSTRAINT "EC_BULLETIN_PK" PRIMARY KEY ("ID") ENABLE
);
COMMENT ON COLUMN "EC_BULLETIN"."ID" IS 'PK';
COMMENT ON COLUMN "EC_BULLETIN"."TITLE" IS '主旨';
COMMENT ON COLUMN "EC_BULLETIN"."START_TIME" IS '開始時間';
COMMENT ON COLUMN "EC_BULLETIN"."END_TIME" IS '結束時間';
COMMENT ON COLUMN "EC_BULLETIN"."ACTIVE" IS '1:啟用, 0:停用';
COMMENT ON COLUMN "EC_BULLETIN"."CREATOR" IS '建立者(FK:TC_USER.ID)';
COMMENT ON COLUMN "EC_BULLETIN"."CREATETIME" IS '建立時間';
