-- 群組
UPDATE TC_GROUP SET NAME='系統管理員' WHERE ID=1;
-- INSERT INTO TC_GROUP (ID,CODE,NAME,CREATOR,CREATETIMESTAMP) values (2, 'switch-user','切換使用者', 1, sysdate);

-- restful user
-- INSERT INTO TC_GROUP (ID,CODE,NAME,CREATOR,CREATETIMESTAMP) values (3, 'REST_USER','RESTful執行者', 1, sysdate);
-- INSERT INTO TC_USER (ID,LOGIN_ACCOUNT,CNAME,DISABLED,CREATOR,CREATETIMESTAMP) VALUES (14,'web.restful','',0,1,sysdate);
-- INSERT INTO TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (14,14,3,1,sysdate);

-- 自訂群組

-- 檔案上傳路徑
-- 測試機: D:\FileVault\<yourapp>\
-- QA機:   /opt/FileUpload/<yourapp>/
-- 正式機: /opt/FileUpload/<yourapp>/
-- UPDATE TC_FVVAULT SET LOCATION='D:\FileVault\MyGUI\';

-- 排程控管
-- INSERT INTO TC_SCHEDULE (NAME) VALUES ('CommonReportNotify');

CREATE TABLE "ET_USER"."KB_LINK" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"PRIMARYTYPE" VARCHAR2(3 CHAR), 
	"PRIMARYID" NUMBER(38,0), 
	"URL" VARCHAR2(200 BYTE),
	"OPENMETHOD" VARCHAR2(3 CHAR), 
	"CREATOR" NUMBER(38,0), 
	"CREATETIMESTAMP" DATE, 
	"MODIFIER" NUMBER(38,0), 
	"MODIFYTIMESTAMP" DATE, 
	CONSTRAINT KB_LINK_PK PRIMARY KEY (ID),
	CONSTRAINT KB_LINK_FK1 FOREIGN KEY (CREATOR) REFERENCES TC_USER(ID),
	CONSTRAINT KB_LINK_FK2 FOREIGN KEY (MODIFIER) REFERENCES TC_USER(ID)
   );
CREATE TABLE "ET_USER"."KB_PHOTO_GALLERY" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"CODE" VARCHAR2(10 CHAR), 
	"PRIMARYTYPE" VARCHAR2(3 CHAR), 
	"PRIMARYID" NUMBER(38,0), 
	"CNAME" VARCHAR2(120 CHAR), 
	"ENAME" VARCHAR2(120 CHAR), 
	"SUBJECT" VARCHAR2(300 CHAR), 
	"DESCRIPTION" NVARCHAR2(2000),
	"DATADATE" DATE, 
	"PARENT" NUMBER(38,0), 
	"LANG" VARCHAR2(3 CHAR), 
	"WIDTH" NUMBER(10,0), 
	"HEIGHT" NUMBER(10,0), 
	"COMPRESSED" NUMBER(10,0), 
	"STATUS" VARCHAR2(3 CHAR), 
	"IDENTIFY_IMG" NUMBER(10,0), 
	"CREATOR" NUMBER(38,0), 
	"CREATETIMESTAMP" DATE, 
	"MODIFIER" NUMBER(38,0), 
	"MODIFYTIMESTAMP" DATE, 
	CONSTRAINT KB_PHOTO_GALLERY_PK PRIMARY KEY (ID),
	CONSTRAINT KB_PHOTO_GALLERY_FK1 FOREIGN KEY (CREATOR) REFERENCES TC_USER(ID),
	CONSTRAINT KB_PHOTO_GALLERY_FK2 FOREIGN KEY (MODIFIER) REFERENCES TC_USER(ID)
   );   

CREATE TABLE "ET_USER"."KB_PUBLICATION" 
   (	"ID" NUMBER(18,0) NOT NULL ENABLE, 
	"TYPE" VARCHAR2(3 CHAR), 
	"DATATYPE" VARCHAR2(3 CHAR), 
	"DATADATE" DATE, 
	"CODE" VARCHAR2(40 CHAR), 
	"TITLE" VARCHAR2(600 CHAR), 
	"SUMMARY" NVARCHAR2(2000),
	"STATUS" VARCHAR2(3 CHAR), 
	"PARENT" NUMBER(38,0), 
	"NEWS" NUMBER(10,0), 
	"LANG" VARCHAR2(3 CHAR), 
	"CREATOR" NUMBER(18,0), 
	"CREATETIMESTAMP" DATE, 
	"MODIFIER" NUMBER(18,0), 
	"MODIFYTIMESTAMP" DATE,
	CONSTRAINT KB_PUBLICATION_PK PRIMARY KEY (ID),
	CONSTRAINT KB_PUBLICATION_FK1 FOREIGN KEY (CREATOR) REFERENCES TC_USER(ID),
	CONSTRAINT KB_PUBLICATION_FK2 FOREIGN KEY (MODIFIER) REFERENCES TC_USER(ID)
   );

 CREATE TABLE "ET_USER"."KB_RICH_CONTENT" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"PRIMARYTYPE" VARCHAR2(3 CHAR), 
	"PRIMARYID" NUMBER(38,0), 
	"SAVETYPE" VARCHAR2(3 CHAR), 
	"CONTENTS" NVARCHAR2(2000),
	"CREATOR" NUMBER(38,0), 
	"CREATETIMESTAMP" DATE, 
	"MODIFIER" NUMBER(38,0), 
	"MODIFYTIMESTAMP" DATE, 
	CONSTRAINT KB_RICH_CONTENT_PK PRIMARY KEY (ID),
	CONSTRAINT KB_RICH_CONTENT_FK1 FOREIGN KEY (CREATOR) REFERENCES TC_USER(ID),
	CONSTRAINT KB_RICH_CONTENT_FK2 FOREIGN KEY (MODIFIER) REFERENCES TC_USER(ID)
   );  
   
CREATE TABLE "ET_USER"."KB_SYS_PROPS" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"CODE" VARCHAR2(10 CHAR), 
	"NAME" VARCHAR2(180 CHAR), 
	"VALUE" VARCHAR2(180 CHAR), 
	"CREATOR" NUMBER(38,0), 
	"CREATETIMESTAMP" DATE, 
	"MODIFIER" NUMBER(38,0), 
	"MODIFYTIMESTAMP" DATE,
	CONSTRAINT KB_SYS_PROPS_PK PRIMARY KEY (ID),
	CONSTRAINT KB_SYS_PROPS_FK1 FOREIGN KEY (CREATOR) REFERENCES TC_USER(ID),
	CONSTRAINT KB_SYS_PROPS_FK2 FOREIGN KEY (MODIFIER) REFERENCES TC_USER(ID)
   );
   
 CREATE TABLE "ET_USER"."KB_VIDEO" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"PRIMARYTYPE" VARCHAR2(3 CHAR), 
	"PRIMARYID" NUMBER(38,0), 
	"CNAME" VARCHAR2(120 CHAR), 
	"ENAME" VARCHAR2(120 CHAR), 
	"TITLE" VARCHAR2(300 CHAR), 
	"ETITLE" VARCHAR2(300 CHAR), 
	"DESCRIPTION" CLOB, 
	"EDESCRIPTION" CLOB, 
	"CHANNEL" VARCHAR2(120 CHAR), 
	"RELEASEDATE" DATE, 
	"PARENT" NUMBER(38,0), 
	"LANG" VARCHAR2(3 CHAR), 
	"WIDTH" NUMBER(10,0), 
	"HEIGHT" NUMBER(10,0), 
	"STATUS" VARCHAR2(3 CHAR), 
	"CREATOR" NUMBER(38,0), 
	"CREATETIMESTAMP" DATE, 
	"MODIFIER" NUMBER(38,0), 
	"MODIFYTIMESTAMP" DATE,
	CONSTRAINT KB_VIDEO_PK PRIMARY KEY (ID),
	CONSTRAINT KB_VIDEO_FK1 FOREIGN KEY (CREATOR) REFERENCES TC_USER(ID),
	CONSTRAINT KB_VIDEO_FK2 FOREIGN KEY (MODIFIER) REFERENCES TC_USER(ID)
   );  
   
 -- 會員
CREATE TABLE "EC_MEMBER"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"LOGIN_ACCOUNT" VARCHAR2(50 BYTE) NOT NULL ENABLE,
"NAME" VARCHAR2(64 CHAR) NOT NULL ENABLE,
"EMAIL" VARCHAR2(64 BYTE),
"PHONE" VARCHAR2(50 BYTE),
"PASSWORD" VARCHAR2(128 BYTE),
"ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
"APPLY_VENDER_CODE" VARCHAR2(20 CHAR),
"APPLY_VENDER_NAME" VARCHAR2(70 CHAR),	
"CREATOR" NUMBER(18,0), 
"CREATETIME" DATE,
"MODIFIER" NUMBER(18,0), 
"MODIFYTIME" DATE,
"TYPE" VARCHAR2(30 BYTE),
"DISABLED" NUMBER(1,0) DEFAULT 0,
"APPROVETIME" DATE,
"APPLYTIME" DATE,
"ENAME" VARCHAR2(128 BYTE),
CONSTRAINT "EC_MEMBER_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_MEMBER_UK1" UNIQUE ("LOGIN_ACCOUNT") ENABLE
);
COMMENT ON COLUMN "EC_MEMBER"."ID" IS 'PK';
COMMENT ON COLUMN "EC_MEMBER"."LOGIN_ACCOUNT" IS '登入帳號';
COMMENT ON COLUMN "EC_MEMBER"."NAME" IS '姓名';
COMMENT ON COLUMN "EC_MEMBER"."EMAIL" IS '電子信箱';
COMMENT ON COLUMN "EC_MEMBER"."PHONE" IS '電話';
COMMENT ON COLUMN "EC_MEMBER"."PASSWORD" IS '密碼(SHA256)';
COMMENT ON COLUMN "EC_MEMBER"."APPLY_VENDER_CODE" IS '申請供應商代碼';
COMMENT ON COLUMN "EC_MEMBER"."APPLY_VENDER_NAME" IS '申請供應商名稱';
COMMENT ON COLUMN "EC_MEMBER"."ACTIVE" IS '1:啟用, 0:停用';
COMMENT ON COLUMN "EC_MEMBER"."CREATOR" IS '建立人';
COMMENT ON COLUMN "EC_MEMBER"."CREATETIME" IS '建立時間';
COMMENT ON COLUMN "EC_MEMBER"."MODIFIER" IS '最近修改人';
COMMENT ON COLUMN "EC_MEMBER"."MODIFYTIME" IS '最近修改時間';
COMMENT ON COLUMN "EC_MEMBER"."TYPE" IS '帳號類型(P:個人;C:公司)MemberTypeEnum';    
COMMENT ON COLUMN "EC_MEMBER"."DISABLED" IS '無效';  
COMMENT ON COLUMN "EC_MEMBER"."APPROVETIME" IS '核准時間'; 
COMMENT ON COLUMN "EC_MEMBER"."APPLYTIME" IS '申請時間';   
COMMENT ON COLUMN "EC_MEMBER"."ENAME" IS '英文姓名'; 

CREATE SEQUENCE SEQ_MEMBER INCREMENT BY 1 START WITH 1 NOMAXVALUE CACHE 3 NOORDER  NOCYCLE;

--公司
--drop table EC_COMPANY;
--drop SEQUENCE SEQ_COMPANY;
CREATE TABLE "EC_COMPANY" 
(	"ID" NUMBER(18,0) NOT NULL ENABLE, 
	"TYPE" NVARCHAR2(100), --供貨商類別
	"MAIN_ID" NUMBER(18,0), 
	"CODE" NVARCHAR2(20),
	"CNAME" NVARCHAR2(300), 
	"ENAME" VARCHAR2(300 BYTE), 
	"ID_TYPE" VARCHAR2(2 BYTE), 
	"ID_CODE" VARCHAR2(50 BYTE), --公司統編 / 稅籍編號
	"ID_CODE2" VARCHAR2(50 BYTE),
	"ID_CODE3" VARCHAR2(50 BYTE),
	"ID_CODE4" VARCHAR2(50 BYTE),
	"ID_CODE5" VARCHAR2(50 BYTE),
	"NICKNAME" NVARCHAR2(100), 
	"BRIEF" NVARCHAR2(1200), 
	"BRIEF2" NVARCHAR2(1200),--主要產品
	"BRIEF3" NVARCHAR2(1200),--代理品牌	
	"TEL1" VARCHAR2(30 BYTE), --電話1(公司登記電話)
	"TEL2" VARCHAR2(30 BYTE), --電話2(聯絡人電話)
	"TEL3" VARCHAR2(30 BYTE), --電話3(聯絡人手機)
	"TEL4" VARCHAR2(30 BYTE), --電話4(聯絡傳真)
	"OWNER1" VARCHAR2(100 BYTE), --負責人1
	"OWNER2" VARCHAR2(100 BYTE), --負責人2(聯絡人)
	"OWNER1_TITLE" VARCHAR2(100 BYTE), --負責人1職稱
	"OWNER2_TITLE" VARCHAR2(100 BYTE), --負責人2職稱(聯絡人職稱)
	"COUNTRY" NUMBER(18,0), --國別
	"COUNTRY_CODE" VARCHAR2(10 BYTE), --國別代碼
	"CURRENCY" NUMBER(18,0),--訂單幣別
	"CURRENCY_CODE" VARCHAR2(10 BYTE),--幣別代碼
	"STATE" NUMBER(18,0), 
	"ZIP1" VARCHAR2(20 BYTE),--邮政编码
	"ZIP2" VARCHAR2(20 BYTE),
	"ADDR1" NVARCHAR2(500), --地址1(公司登記地址)
	"ADDR2" NVARCHAR2(500),--地址2(聯絡地址)
	URL1 VARCHAR2(1024 BYTE),--公司網站 
	URL2 VARCHAR2(1024 BYTE),--聯絡人電子信箱
	"START_AT" DATE, --公司創立日期
	"CATEGORY" NUMBER(18,0), 
	INDUSTRY NVARCHAR2(200),--供應商行業別
	"CAPITAL" NUMBER(18,0),--資本額
	"YEAR_REVENUE" NUMBER(18,0),--年營業額
	"EMPLOYEE" NUMBER(18,0),--員工人數
	
	"BANK1" NVARCHAR2(100),--銀行名稱 / 分行
	"BANK2" NVARCHAR2(100),
	"BANK1_BENEFICIARY" NVARCHAR2(100),--受款人
	"BANK2_BENEFICIARY" NVARCHAR2(100),
	"BANK1_CODE" VARCHAR2(100 BYTE),--銀行代號 (金資代碼)
	"BANK2_CODE" VARCHAR2(100 BYTE),
	"BANK1_ACCOUNT" VARCHAR2(100 BYTE),--銀行帳號
	"BANK2_ACCOUNT" VARCHAR2(100 BYTE),
	"BANK1_ADDR" NVARCHAR2(100),--銀行地址
	"BANK2_ADDR" NVARCHAR2(100),
	"CREATOR" NUMBER(18,0), 
	"CREATETIME" DATE, 
	"MODIFIER" NUMBER(18,0), 
	"MODIFYTIME" DATE, 

	 CONSTRAINT "EC_COMPANY_PK" PRIMARY KEY ("ID")
);
COMMENT ON COLUMN "EC_COMPANY"."ID" IS 'PK';
COMMENT ON COLUMN "EC_COMPANY"."TYPE" IS '類型';
COMMENT ON COLUMN "EC_COMPANY"."MAIN_ID" IS '來源主檔ID (by類型)';
COMMENT ON COLUMN "EC_COMPANY"."CODE" IS '公司編號';
COMMENT ON COLUMN "EC_COMPANY"."CNAME" IS '公司中文名稱';
COMMENT ON COLUMN "EC_COMPANY"."ENAME" IS '公司英文名稱';
COMMENT ON COLUMN "EC_COMPANY"."ID_TYPE" IS 'ID_CODE類別';
COMMENT ON COLUMN "EC_COMPANY"."ID_CODE" IS '公司統編 / 稅籍編號';--营业执照编码
COMMENT ON COLUMN "EC_COMPANY"."ID_CODE2" IS '統編、營業登記號';--税务登记证号
COMMENT ON COLUMN "EC_COMPANY"."ID_CODE3" IS '統編、營業登記號';--经营许可证号
COMMENT ON COLUMN "EC_COMPANY"."ID_CODE4" IS '統編、營業登記號';--组织机构代码
COMMENT ON COLUMN "EC_COMPANY"."ID_CODE5" IS '統編、營業登記號';
COMMENT ON COLUMN "EC_COMPANY"."NICKNAME" IS '簡稱';
COMMENT ON COLUMN "EC_COMPANY"."BRIEF" IS '簡介';--经营范围
COMMENT ON COLUMN "EC_COMPANY"."BRIEF2" IS '簡介2(主要產品)';--经营业绩
COMMENT ON COLUMN "EC_COMPANY"."BRIEF3" IS '簡介3(代理品牌	)';--企业介绍
COMMENT ON COLUMN EC_COMPANY.TEL1 IS '電話1(公司登記電話)';--固定电话
COMMENT ON COLUMN EC_COMPANY.TEL2 IS '電話2(聯絡人電話)';
COMMENT ON COLUMN EC_COMPANY.TEL3 IS '電話3(聯絡人手機)';
COMMENT ON COLUMN EC_COMPANY.TEL4 IS '電話4(聯絡傳真)';
COMMENT ON COLUMN EC_COMPANY.OWNER1 IS '負責人1';--法人代表
COMMENT ON COLUMN EC_COMPANY.OWNER2 IS '負責人2(聯絡人)';
COMMENT ON COLUMN EC_COMPANY.OWNER1_TITLE IS '負責人1職稱';
COMMENT ON COLUMN EC_COMPANY.OWNER2_TITLE IS '負責人2職稱(聯絡人職稱)';
COMMENT ON COLUMN EC_COMPANY.COUNTRY IS '國別';
COMMENT ON COLUMN EC_COMPANY.STATE IS '州、省(所在區域)';
COMMENT ON COLUMN "EC_COMPANY"."ZIP1" IS '郵遞區號';--邮政编码
COMMENT ON COLUMN "EC_COMPANY"."ZIP2" IS '郵遞區號';--邮政编码
COMMENT ON COLUMN "EC_COMPANY"."ADDR1" IS '地址1(公司登記地址)';--公司注册地
COMMENT ON COLUMN "EC_COMPANY"."ADDR2" IS '地址2(聯絡地址)';--办公地址
COMMENT ON COLUMN EC_COMPANY.URL1 IS '公司網站';
COMMENT ON COLUMN EC_COMPANY.URL2 IS '聯絡人電子信箱';
COMMENT ON COLUMN EC_COMPANY.START_AT IS '公司創立日期';
COMMENT ON COLUMN EC_COMPANY.CATEGORY IS '分類';--分類
COMMENT ON COLUMN EC_COMPANY.INDUSTRY IS '供應商行業別';
COMMENT ON COLUMN EC_COMPANY.CAPITAL IS '資本額';--注册资金
COMMENT ON COLUMN EC_COMPANY.YEAR_REVENUE IS '年營業額';
COMMENT ON COLUMN EC_COMPANY.EMPLOYEE IS '員工人數';
COMMENT ON COLUMN EC_COMPANY.CURRENCY IS '訂單幣別';
COMMENT ON COLUMN "EC_COMPANY"."BANK1" IS '銀行名稱 / 分行';--开户行
COMMENT ON COLUMN "EC_COMPANY"."BANK2" IS '銀行2';--
COMMENT ON COLUMN "EC_COMPANY"."BANK1_BENEFICIARY" IS '受款人1';
COMMENT ON COLUMN "EC_COMPANY"."BANK2_BENEFICIARY" IS '受款人2';
COMMENT ON COLUMN "EC_COMPANY"."BANK1_CODE" IS '銀行代號 (金資代碼)1';
COMMENT ON COLUMN "EC_COMPANY"."BANK2_CODE" IS '銀行代號 (金資代碼)2';
COMMENT ON COLUMN "EC_COMPANY"."BANK1_ACCOUNT" IS '銀行帳號1';
COMMENT ON COLUMN "EC_COMPANY"."BANK2_ACCOUNT" IS '銀行帳號2';
COMMENT ON COLUMN "EC_COMPANY"."BANK1_ADDR" IS '銀行地址1';
COMMENT ON COLUMN "EC_COMPANY"."BANK2_ADDR" IS '銀行地址2';
COMMENT ON COLUMN EC_COMPANY.CREATOR IS '建立者';
COMMENT ON COLUMN EC_COMPANY.CREATETIME IS '建立時間';
COMMENT ON COLUMN EC_COMPANY.MODIFIER IS '最近修改人';
COMMENT ON COLUMN EC_COMPANY.MODIFYTIME IS '最近修改時間';

CREATE SEQUENCE SEQ_COMPANY INCREMENT BY 1 START WITH 1 NOMAXVALUE CACHE 3 NOORDER  NOCYCLE;

--簡單選項主檔
CREATE TABLE "EC_OPTION" 
   (	
   "ID" NUMBER(18,0) NOT NULL ENABLE, 
	"TYPE" VARCHAR2(30 BYTE), 
	"CNAME" NVARCHAR2(200), 
	"ENAME" VARCHAR2(200 BYTE), 
	"CODE" VARCHAR2(100 BYTE), 
	"PARENT" NUMBER(18,0), 
	"MEMO" VARCHAR2(300 BYTE), 
	"LEVELNUM" NUMBER(10,0), 
	"SORTNUM" NUMBER(10,0), 
	"DISABLED" NUMBER(1,0) DEFAULT 0, 
	"READONLY" NUMBER(1,0) DEFAULT 0, 
	"CREATOR" NUMBER(18,0), 
	"CREATETIME" DATE, 
	"MODIFIER" NUMBER(18,0), 
	"MODIFYTIME" DATE, 
	"STORE_ID" NUMBER(18,0), 
	 CONSTRAINT "EC_OPTION_PK" PRIMARY KEY ("ID")
   )
COMMENT ON COLUMN "EC_OPTION"."ID" IS 'PK ID';
   COMMENT ON COLUMN "EC_OPTION"."TYPE" IS '類別';
   COMMENT ON COLUMN "EC_OPTION"."CNAME" IS '中文名稱';
   COMMENT ON COLUMN "EC_OPTION"."ENAME" IS '英文名稱';
   COMMENT ON COLUMN "EC_OPTION"."CODE" IS '代碼';
   COMMENT ON COLUMN "EC_OPTION"."PARENT" IS '上層ID';
   COMMENT ON COLUMN "EC_OPTION"."MEMO" IS '備註';
   COMMENT ON COLUMN "EC_OPTION"."LEVELNUM" IS '階層';
   COMMENT ON COLUMN "EC_OPTION"."SORTNUM" IS '排序';
   COMMENT ON COLUMN "EC_OPTION"."DISABLED" IS '無效';
   COMMENT ON COLUMN "EC_OPTION"."READONLY" IS '唯讀';
   COMMENT ON COLUMN "EC_OPTION"."CREATOR" IS '建立者';
   COMMENT ON COLUMN "EC_OPTION"."CREATETIME" IS '建立時間';
   COMMENT ON COLUMN "EC_OPTION"."MODIFIER" IS '最近修改人';
   COMMENT ON COLUMN "EC_OPTION"."MODIFYTIME" IS '最近修改時間';
   COMMENT ON COLUMN "EC_OPTION"."STORE_ID" IS '商店ID';
   COMMENT ON TABLE "EC_OPTION"  IS '簡單選項主檔';
CREATE SEQUENCE SEQ_OPTION INCREMENT BY 1 START WITH 1 NOMAXVALUE CACHE 3 NOORDER  NOCYCLE;
   
   

  CREATE TABLE "EC_FILE" 
   (	
   "ID" NUMBER(18,0) NOT NULL ENABLE, 
	"PRIMARY_TYPE" VARCHAR2(50 BYTE), 
	"PRIMARY_ID" NUMBER(18,0), 
	"NAME" NVARCHAR2(600), 
	"DESCRIPTION" NVARCHAR2(600), 
	"FILENAME" NVARCHAR2(600), 
	"SAVENAME" VARCHAR2(50 BYTE), 
	"SAVEDIR" VARCHAR2(100 BYTE), 
	"CREATOR" NUMBER(18,0), 
	"CREATETIME" DATE, 
	"MODIFIER" NUMBER(18,0), 
	"MODIFYTIME" DATE, 
	"CONTENT_TYPE" VARCHAR2(100 BYTE), 
	"FILESIZE" NUMBER(12,0), 
	 CONSTRAINT "EC_PRD_FILE_PK" PRIMARY KEY ("ID")
   ) ;

   COMMENT ON COLUMN "EC_FILE"."ID" IS 'PK ID';
   COMMENT ON COLUMN "EC_FILE"."PRIMARY_TYPE" IS '對應主關聯類別(Class Name or FileEnum)';
   COMMENT ON COLUMN "EC_FILE"."PRIMARY_ID" IS '對應主關聯檔ID';
   COMMENT ON COLUMN "EC_FILE"."NAME" IS '顯示名稱';
   COMMENT ON COLUMN "EC_FILE"."DESCRIPTION" IS '說明';
   COMMENT ON COLUMN "EC_FILE"."FILENAME" IS '原檔名';
   COMMENT ON COLUMN "EC_FILE"."SAVENAME" IS '儲存檔名';
   COMMENT ON COLUMN "EC_FILE"."SAVEDIR" IS '儲存路徑';
   COMMENT ON COLUMN "EC_FILE"."CREATOR" IS '建立者';
   COMMENT ON COLUMN "EC_FILE"."CREATETIME" IS '建立時間';
   COMMENT ON COLUMN "EC_FILE"."MODIFIER" IS '最近修改人';
   COMMENT ON COLUMN "EC_FILE"."MODIFYTIME" IS '最近修改時間';
   COMMENT ON COLUMN "EC_FILE"."CONTENT_TYPE" IS '檔案類型';
   COMMENT ON COLUMN "EC_FILE"."FILESIZE" IS '檔案大小bytes';
   COMMENT ON TABLE "EC_FILE"  IS '上傳檔案主檔';
CREATE SEQUENCE SEQ_FILE INCREMENT BY 1 START WITH 1 NOMAXVALUE CACHE 3 NOORDER  NOCYCLE;


CREATE TABLE "EC_USE_LOG" 
   (	
   "ID" NUMBER(18,0) NOT NULL ENABLE, 
	"TYPE" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"CATEGORY" VARCHAR2(50 BYTE), 
	"MEMBER_ID" NUMBER(18,0), 
	"PERIOD" NUMBER(12,0), 
	"SRC" VARCHAR2(20 BYTE), 
	"CLIENT_IP" VARCHAR2(30 BYTE), 
	"CLIENT_INFO" VARCHAR2(500 BYTE), 
	"MEMO" NVARCHAR2(600), 
	"CREATOR" NUMBER(18,0), 
	"CREATETIME" DATE, 
	"MODIFIER" NUMBER(18,0), 
	"MODIFYTIME" DATE, 
	"PATROL_LATITUDE" NUMBER, 
	"PATROL_LONGITUDE" NUMBER, 
	 CONSTRAINT "USE_LOG_PK" PRIMARY KEY ("ID")
   );
 
   COMMENT ON COLUMN "EC_USE_LOG"."ID" IS 'PK ID';
   COMMENT ON COLUMN "EC_USE_LOG"."TYPE" IS 'LOG分類 (LogTypeEnum)';
   COMMENT ON COLUMN "EC_USE_LOG"."CATEGORY" IS '細部分類代碼 (LogCateforyEnum)';
   COMMENT ON COLUMN "EC_USE_LOG"."MEMBER_ID" IS '操作人EC_MEMBER.ID';
   COMMENT ON COLUMN "EC_USE_LOG"."PERIOD" IS '期間(秒)';
   COMMENT ON COLUMN "EC_USE_LOG"."SRC" IS '來源 (WEB、APP)';
   COMMENT ON COLUMN "EC_USE_LOG"."CLIENT_IP" IS 'Client IP';
   COMMENT ON COLUMN "EC_USE_LOG"."CLIENT_INFO" IS '其他用戶端資訊(JSON格式)';
   COMMENT ON COLUMN "EC_USE_LOG"."MEMO" IS '備註';
   COMMENT ON COLUMN "EC_USE_LOG"."CREATOR" IS '建立人';
   COMMENT ON COLUMN "EC_USE_LOG"."CREATETIME" IS '建立時間';
   COMMENT ON COLUMN "EC_USE_LOG"."MODIFIER" IS '最近修改人';
   COMMENT ON COLUMN "EC_USE_LOG"."MODIFYTIME" IS '最近修改時間';
   COMMENT ON COLUMN "EC_USE_LOG"."PATROL_LATITUDE" IS '緯度';
   COMMENT ON COLUMN "EC_USE_LOG"."PATROL_LONGITUDE" IS '經度';
   COMMENT ON TABLE "EC_USE_LOG"  IS '使用記錄';
CREATE SEQUENCE SEQ_USE_LOG INCREMENT BY 1 START WITH 1 NOMAXVALUE CACHE 3 NOORDER  NOCYCLE;

--供應商主檔
--同步或直接查warehouse
CREATE TABLE "TC_ZTAB_EXP_LFA1" 
   (	"MANDT" VARCHAR2(6 CHAR), 
	"LIFNR" VARCHAR2(20 CHAR), 
	"NAME1" VARCHAR2(70 CHAR), 
	"SPERM" VARCHAR2(2 CHAR), 
	"EKORG" VARCHAR2(8 CHAR), 
	"EKOTX" VARCHAR2(40 CHAR), 
	"VERKF" VARCHAR2(60 CHAR), 
	"TELF1" VARCHAR2(32 CHAR), 
	"TELBX" VARCHAR2(512 CHAR), 
	"WAERS" VARCHAR2(10 CHAR), 
	"ZTERM" VARCHAR2(8 CHAR), 
	"ORT01" VARCHAR2(70 CHAR), 
	"STR_SUPPL1" VARCHAR2(80 CHAR), 
	"LAND1" VARCHAR2(6 CHAR), 
	"SORTL" VARCHAR2(50 CHAR), 
	"LOEVM" VARCHAR2(2 CHAR), 
	"LIFNR_UI" VARCHAR2(20 CHAR), 
	"SYNC_TIME_STAMP" DATE, 
	"NAME2" VARCHAR2(70 CHAR), 
	"NAME3" VARCHAR2(70 CHAR), 
	"NAME4" VARCHAR2(70 CHAR), 
	"TELFX" VARCHAR2(62 CHAR), 
	"RISK" VARCHAR2(1 CHAR), 
	"CSPERM" VARCHAR2(1 CHAR), 
	"SPERQ" VARCHAR2(2 CHAR), 
	"Z_CANNOT_BLOCK" VARCHAR2(1 CHAR), 
	"Z_NBLOCK_SDATE" DATE, 
	"Z_NBLOCK_EDATE" DATE, 
	"ZARTI_PERSON1" VARCHAR2(60 CHAR), 
	"ZARTI_PERSON2" VARCHAR2(60 CHAR), 
	"ZARTI_PERSON3" VARCHAR2(60 CHAR), 
	"ZSTOCKHOLDER1" VARCHAR2(60 CHAR), 
	"ZSTOCKHOLDER2" VARCHAR2(60 CHAR), 
	"ZSTOCKHOLDER3" VARCHAR2(60 CHAR), 
	"ZSTOCKHOLDER4" VARCHAR2(60 CHAR), 
	"ZSTOCKHOLDER5" VARCHAR2(60 CHAR), 
	"ZVENDOR_TYPE" VARCHAR2(2 CHAR), 
	"PSTLZ" VARCHAR2(20 CHAR), 
	"SORT2" VARCHAR2(40 CHAR), 
	"STREET" VARCHAR2(120 CHAR), 
	"STR_SUPPL2" VARCHAR2(80 CHAR), 
	"STR_SUPPL3" VARCHAR2(80 CHAR), 
	"SPRAS" VARCHAR2(2 CHAR), 
	"TEL_NUMBER" VARCHAR2(60 CHAR), 
	"TEL_EXTENS" VARCHAR2(20 CHAR), 
	"TELF2" VARCHAR2(32 CHAR), 
	"ADRNR" VARCHAR2(20 CHAR), 
	"KONZS" VARCHAR2(20 CHAR), 
	"KTOKK" VARCHAR2(8 CHAR), 
	"STCEG" VARCHAR2(40 CHAR), 
	"LNRZA" VARCHAR2(20 CHAR), 
	"BANKS" VARCHAR2(6 CHAR), 
	"BANKL" VARCHAR2(30 CHAR), 
	"BANKA" VARCHAR2(120 CHAR), 
	"BRNCH" VARCHAR2(80 CHAR), 
	"BANKN" VARCHAR2(36 CHAR), 
	"BVTYP" VARCHAR2(8 CHAR), 
	"BKREF" VARCHAR2(40 CHAR), 
	"KOINH" VARCHAR2(120 CHAR), 
	"LOEVM_X" VARCHAR2(2 CHAR), 
	"SPERR" VARCHAR2(2 CHAR), 
	"CONFS" VARCHAR2(2 CHAR), 
	"ZZREMARK" VARCHAR2(120 CHAR), 
	"BUKRS" VARCHAR2(8 CHAR), 
	"BUTXT" VARCHAR2(50 CHAR), 
	"LOEVM_B" VARCHAR2(2 CHAR), 
	"ZUAWA" VARCHAR2(6 CHAR), 
	"AKONT" VARCHAR2(20 CHAR), 
	"BEGRU" VARCHAR2(8 CHAR), 
	"ZWELS" VARCHAR2(20 CHAR), 
	"ZAHLS" VARCHAR2(2 CHAR), 
	"ZTERM_B" VARCHAR2(8 CHAR), 
	"FDGRV" VARCHAR2(20 CHAR), 
	"LNRZB" VARCHAR2(20 CHAR), 
	"REPRF" VARCHAR2(2 CHAR), 
	"MINDK" VARCHAR2(6 CHAR), 
	"UZAWE" VARCHAR2(4 CHAR), 
	"WEBRE" VARCHAR2(2 CHAR), 
	"MOB_NUMBER" VARCHAR2(60 CHAR)
   );
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."MANDT" IS '用戶端';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."LIFNR" IS '供應商或貸方的帳號';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."NAME1" IS '名稱 1';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."SPERM" IS '採購組織層次的採購凍結';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."EKORG" IS '採購組織';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."EKOTX" IS '採購組織說明';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."VERKF" IS '供應商辦公室裡的負責銷售員';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."TELF1" IS '供應商電話號碼';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."TELBX" IS '電子信箱號碼';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."WAERS" IS '採購單幣別';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."ZTERM" IS '付款條件碼';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."ORT01" IS '城市';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."STR_SUPPL1" IS '街道 2';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."LAND1" IS '國家代碼';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."SORTL" IS '搜尋條件 1';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."LOEVM" IS '供應商在採購層次的刪除旗標';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."LIFNR_UI" IS 'AP用供應商代碼，去掉Prefix 3個0';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."SYNC_TIME_STAMP" IS 'SAP資料同步時間';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."NAME2" IS '名稱 2';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."NAME3" IS '名稱 3';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."NAME4" IS '名稱 4';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."TELFX" IS '傳真號碼';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."RISK" IS '高風險';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."CSPERM" IS '中央採購凍結';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."SPERQ" IS '將被凍結的功能';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."Z_CANNOT_BLOCK" IS '永久不可凍結';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."Z_NBLOCK_SDATE" IS '不可凍結開始日期';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."Z_NBLOCK_EDATE" IS '不可凍結結束日期';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."ZARTI_PERSON1" IS '法人１ ';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."ZARTI_PERSON2" IS '高風險';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."ZARTI_PERSON3" IS '法人3';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."ZSTOCKHOLDER1" IS '股東１';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."ZSTOCKHOLDER2" IS '股東２';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."ZSTOCKHOLDER3" IS '股東３';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."ZSTOCKHOLDER4" IS '股東４';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."ZSTOCKHOLDER5" IS '股東５';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."ZVENDOR_TYPE" IS '供應商A1/A2/A3/B/C分類';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."PSTLZ" IS '郵遞區號';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."SORT2" IS '搜尋條件 2';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."STREET" IS '街道';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."STR_SUPPL2" IS '街道 3';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."STR_SUPPL3" IS '街道 4';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."SPRAS" IS '語言代碼';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."TEL_NUMBER" IS '第一個電話號碼：撥號代碼 + 號碼';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."TEL_EXTENS" IS '第一個電話號碼：分機';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."TELF2" IS '第二個電話號碼';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."ADRNR" IS '地址';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."KONZS" IS '群組碼';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."KTOKK" IS '供應商科目群組';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."STCEG" IS '加值稅登記號碼';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."LNRZA" IS '代理收款人帳號';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."BANKS" IS '銀行國碼';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."BANKL" IS '凍結原因';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."BANKA" IS '銀行名稱';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."BRNCH" IS '銀行分行';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."BANKN" IS '銀行帳號';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."BVTYP" IS '夥伴銀行類型';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."BKREF" IS '銀行明細的參考規範';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."KOINH" IS '帳戶所有人名稱';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."LOEVM_X" IS '主檔記錄的中央刪除旗標';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."SPERR" IS '中央過帳凍結';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."CONFS" IS '更改權限狀態（中央） ';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."ZZREMARK" IS '備註/說明';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."BUKRS" IS '公司代碼';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."BUTXT" IS '公司代碼或公司名稱';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."LOEVM_B" IS '主檔記錄的刪除旗標（公司代碼層次） ';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."ZUAWA" IS '根據指派號碼的排序碼';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."AKONT" IS '總帳科目中的統制科目';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."BEGRU" IS '權限群組';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."ZWELS" IS '待考慮之付款方式清單';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."ZAHLS" IS '付款的凍結碼';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."ZTERM_B" IS '付款條件碼';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."FDGRV" IS '規劃群組';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."LNRZB" IS '替代受款人帳號';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."REPRF" IS '雙重發票或貸項通知單的核查旗標';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."MINDK" IS '少數指示碼';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."UZAWE" IS '付款方法補充';
   COMMENT ON COLUMN "TC_ZTAB_EXP_LFA1"."WEBRE" IS '指示碼：以 GR 為基礎的發票驗證';
   COMMENT ON TABLE "TC_ZTAB_EXP_LFA1"  IS '帶出供應商主檔';
   
   CREATE INDEX "TC_ZTAB_EXP_LFA1_INDEX1" ON "WAREHOUSE"."TC_ZTAB_EXP_LFA1" ("MANDT", "LIFNR") ;
   CREATE INDEX "TC_ZTAB_EXP_LFA1_INDEX2" ON "WAREHOUSE"."TC_ZTAB_EXP_LFA1" ("MANDT", "LIFNR_UI") ;
   CREATE INDEX "TC_ZTAB_EXP_LFA1_INDEX3" ON "WAREHOUSE"."TC_ZTAB_EXP_LFA1" ("EKORG", "LIFNR_UI") ;
   ALTER TABLE "TC_ZTAB_EXP_LFA1" MODIFY ("LIFNR" NOT NULL ENABLE);
  ALTER TABLE "TC_ZTAB_EXP_LFA1" MODIFY ("MANDT" NOT NULL ENABLE);
  
select * from TC_ZTAB_EXP_LFA1 l;



--key:MANDT LIFNR_UI,  ZKORG ?!!!! 
--供應商 會員 關聯table
CREATE TABLE "ET_VENDER" 
   (	
   "ID" NUMBER(18,0) NOT NULL ENABLE, 
	"MAIN_ID" NUMBER(18,0) NOT NULL ENABLE, 
	"MANDT" VARCHAR2(6 CHAR), 
	"LIFNR_UI" VARCHAR2(20 CHAR), 
	"CNAME" NVARCHAR2(200), 
	"ENAME" VARCHAR2(200 BYTE),
	"NICKNAME" NVARCHAR2(100), 
	"CREATOR" NUMBER(18,0), 
	"CREATETIME" DATE, 
	"MODIFIER" NUMBER(18,0), 
	"MODIFYTIME" DATE, 
	 CONSTRAINT "LFA1_MEMBER_PK" PRIMARY KEY ("ID")
   );
COMMENT ON COLUMN "ET_VENDER"."ID" IS 'PK ID';
   COMMENT ON COLUMN "ET_VENDER"."MAIN_ID" IS 'EC_MEMBER_ID';
   COMMENT ON COLUMN "ET_VENDER"."MANDT" IS '用戶端';
   COMMENT ON COLUMN "ET_VENDER"."LIFNR_UI" IS 'AP用供應商代碼，去掉Prefix 3個0';
   COMMENT ON COLUMN "ET_VENDER"."CNAME" IS '公司中文名稱';
   COMMENT ON COLUMN "ET_VENDER"."ENAME" IS '公司英文名稱';
   COMMENT ON COLUMN "ET_VENDER"."NICKNAME" IS '暱稱';
   COMMENT ON COLUMN "ET_VENDER"."CREATOR" IS '建立人';
   COMMENT ON COLUMN "ET_VENDER"."CREATETIME" IS '建立時間';
   COMMENT ON COLUMN "ET_VENDER"."MODIFIER" IS '最近修改人';
   COMMENT ON COLUMN "ET_VENDER"."MODIFYTIME" IS '最近修改時間';
CREATE SEQUENCE SEQ_VENDER INCREMENT BY 1 START WITH 1 NOMAXVALUE CACHE 3 NOORDER  NOCYCLE;

--供應商 類別 關聯table

  --drop table ET_LFA1_CATEGORY;
CREATE TABLE "ET_VENDER_CATEGORY" 
   (	
   "ID" NUMBER(18,0) NOT NULL ENABLE, 
   --"CATEGORY" VARCHAR2(50 BYTE), 
	"CATEGORY" NUMBER(18,0), 
	"MANDT" VARCHAR2(6 CHAR), 
	"LIFNR_UI" VARCHAR2(20 CHAR), 
	"CREATOR" NUMBER(18,0), 
	"CREATETIME" DATE, 
	"MODIFIER" NUMBER(18,0), 
	"MODIFYTIME" DATE, 
	 CONSTRAINT "VENDER_CATEGORY_PK" PRIMARY KEY ("ID")
   );
COMMENT ON COLUMN "ET_VENDER_CATEGORY"."ID" IS 'PK ID';
   COMMENT ON COLUMN "ET_VENDER_CATEGORY"."CATEGORY" IS '細部分類代碼 (VenderCateforyEnum)';
   COMMENT ON COLUMN "ET_VENDER_CATEGORY"."MANDT" IS '用戶端';
   COMMENT ON COLUMN "ET_VENDER_CATEGORY"."LIFNR_UI" IS 'AP用供應商代碼，去掉Prefix 3個0';
   COMMENT ON COLUMN "ET_VENDER_CATEGORY"."CREATOR" IS '建立人';
   COMMENT ON COLUMN "ET_VENDER_CATEGORY"."CREATETIME" IS '建立時間';
   COMMENT ON COLUMN "ET_VENDER_CATEGORY"."MODIFIER" IS '最近修改人';
   COMMENT ON COLUMN "ET_VENDER_CATEGORY"."MODIFYTIME" IS '最近修改時間';
CREATE SEQUENCE SEQ_VENDER_CATEGORY INCREMENT BY 1 START WITH 1 NOMAXVALUE CACHE 3 NOORDER  NOCYCLE;   
--標案 類別 關聯table ?!




--標案
CREATE TABLE "ET_TENDER" 
   (	
   "ID" NUMBER(18,0) NOT NULL ENABLE, 
   "TYPE" VARCHAR2(20 BYTE),
   "CODE" VARCHAR2(40 CHAR), 
   "TITLE" VARCHAR2(600 CHAR), 
   "SUMMARY" NVARCHAR2(2000),
   "DATADATE" DATE, --發佈日期
   "S_SALE_DATE" DATE,
   "E_SALE_DATE" DATE,
   "S_TENDER_DATE" DATE,
   "E_TENDER_DATE" DATE,
   "VERIFY_DATE" DATE,
   "CLOSE_DATE" DATE,
   "FACTORY_CODE" VARCHAR2(10 CHAR), 
   "FACTORY_ID" NUMBER(18,0),
   "AREA_ID" NUMBER(18,0), 
   "CATEGORY_ID" NUMBER(18,0),
   "AMOUNT" NUMBER(10,3),--標書費用
   "INSURANCE_AMOUNT" NUMBER(10,3),--投保金金額
	"STATUS" VARCHAR2(3 CHAR), 
	"LANG" VARCHAR2(3 CHAR), 
	"CREATOR" NUMBER(18,0), 
	"CREATETIME" DATE, 
	"MODIFIER" NUMBER(18,0), 
	"MODIFYTIME" DATE,
	CONSTRAINT ET_TENDER_PK PRIMARY KEY (ID),
	CONSTRAINT ET_TENDER_FK1 FOREIGN KEY (CREATOR) REFERENCES TC_USER(ID),
	CONSTRAINT ET_TENDER_FK2 FOREIGN KEY (MODIFIER) REFERENCES TC_USER(ID)
   );
CREATE SEQUENCE SEQ_TENDER INCREMENT BY 1 START WITH 1 NOMAXVALUE CACHE 3 NOORDER  NOCYCLE;

COMMENT ON COLUMN "ET_TENDER"."ID" IS 'PK ID';
COMMENT ON COLUMN "ET_TENDER"."TYPE" IS '案件分類';
COMMENT ON COLUMN "ET_TENDER"."CODE" IS '案件編號';
COMMENT ON COLUMN "ET_TENDER"."TITLE" IS '標題';
COMMENT ON COLUMN "ET_TENDER"."SUMMARY" IS '摘要';
COMMENT ON COLUMN "ET_TENDER"."DATADATE" IS '發佈日期';
COMMENT ON COLUMN "ET_TENDER"."S_SALE_DATE" IS '標書發售日期(起)';
COMMENT ON COLUMN "ET_TENDER"."E_SALE_DATE" IS '標書發售日期(迄)';
COMMENT ON COLUMN "ET_TENDER"."S_TENDER_DATE" IS '招標日期(起)';
COMMENT ON COLUMN "ET_TENDER"."E_TENDER_DATE" IS '招標日期(迄)';
COMMENT ON COLUMN "ET_TENDER"."VERIFY_DATE" IS '評標日期';
COMMENT ON COLUMN "ET_TENDER"."CLOSE_DATE" IS '決標日期';
COMMENT ON COLUMN "ET_TENDER"."AREA_ID" IS '地區';
COMMENT ON COLUMN "ET_TENDER"."CATEGORY_ID" IS '案件物料類型';
COMMENT ON COLUMN "ET_TENDER"."STATUS" IS '狀態';


--廠別權限 相關
CM_COMPANY
CM_FACTORY
CM_FACTORY_GROUP_R
CM_FACTORYCATEGORY
CM_FACTORYGROUP
CM_USER_FACTORYGROUP_R
CM_USERCOMPANY
CM_USERFACTORY

CREATE TABLE "CM_COMPANY" 
   (	
   "ID" NUMBER(18,0) NOT NULL ENABLE, 
	"COMPANY_NAME" VARCHAR2(60 CHAR), 
	"SAP_CLIENT_CODE" VARCHAR2(10 BYTE), 
	"LANGUAGE" VARCHAR2(1 BYTE), 
	"SAP_CLIENT" VARCHAR2(5 BYTE), 
	"SORT_NUM" NUMBER(10,0), 
	 CONSTRAINT "SAPCLIENT_PK" PRIMARY KEY ("ID")
	 );

   COMMENT ON COLUMN "CM_COMPANY"."ID" IS 'PK ID';
Insert into CM_COMPANY (ID,COMPANY_NAME,SAP_CLIENT_CODE,LANGUAGE,SAP_CLIENT,SORT_NUM) values (1,N'台泥台灣','tcc','M','168',1);
Insert into CM_COMPANY (ID,COMPANY_NAME,SAP_CLIENT_CODE,LANGUAGE,SAP_CLIENT,SORT_NUM) values (2,N'台泥大陸','tcc_cn','1','268',2);

  CREATE TABLE "CM_FACTORYCATEGORY" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"SORT_NUM" NUMBER(10,0), 
	 CONSTRAINT "FACTORYCATEGORY_PK" PRIMARY KEY ("ID")
  ) ;
   COMMENT ON COLUMN "CM_FACTORYCATEGORY"."ID" IS 'PK ID';
   COMMENT ON COLUMN "CM_FACTORYCATEGORY"."CODE" IS '類別代碼';
   COMMENT ON COLUMN "CM_FACTORYCATEGORY"."NAME" IS '類別名稱';
   COMMENT ON COLUMN "CM_FACTORYCATEGORY"."SORT_NUM" IS '顯示順序';
   COMMENT ON TABLE "CM_FACTORYCATEGORY"  IS '月度計劃表類別主檔';
Insert into CM_FACTORYCATEGORY (ID,CODE,NAME,SORT_NUM) values (1,'1','水泥廠',1);
Insert into CM_FACTORYCATEGORY (ID,CODE,NAME,SORT_NUM) values (2,'2','全能廠',2);
Insert into CM_FACTORYCATEGORY (ID,CODE,NAME,SORT_NUM) values (3,'3','預拌廠、發貨站',3);
Insert into CM_FACTORYCATEGORY (ID,CODE,NAME,SORT_NUM) values (4,'4','碼頭廠',4);
Insert into CM_FACTORYCATEGORY (ID,CODE,NAME,SORT_NUM) values (5,'5','礦業廠',5);
Insert into CM_FACTORYCATEGORY (ID,CODE,NAME,SORT_NUM) values (6,'6','[關企]中橡廠',9);
Insert into CM_FACTORYCATEGORY (ID,CODE,NAME,SORT_NUM) values (8,'8','中轉站',6);
Insert into CM_FACTORYCATEGORY (ID,CODE,NAME,SORT_NUM) values (9,'9','台灣其他',7);
Insert into CM_FACTORYCATEGORY (ID,CODE,NAME,SORT_NUM) values (10,'10','大陸其他',8);
 
CREATE TABLE "CM_FACTORYGROUP" 
   (	"ID" NUMBER(18,0), 
	"GROUPNAME" VARCHAR2(64 BYTE), 
	"DESCRIPTION" VARCHAR2(256 BYTE), 
	"CREATOR" NUMBER(18,0), 
	"CREATETIMESTAMP" DATE, 
	"MODIFIER" NUMBER(18,0), 
	"MODIFYTIMESTAMP" DATE, 
	"GROUPTYPE" CHAR(1 BYTE), 
	"CODE" VARCHAR2(64 BYTE), 
	"SORTNUM" NUMBER(10,0), 
	"DISABLED" NUMBER(1,0) DEFAULT 0,
	CONSTRAINT "FACTORYGROUP_PK" PRIMARY KEY ("ID")
   );
 COMMENT ON COLUMN "CM_FACTORYGROUP"."ID" IS 'PK ID';
   COMMENT ON COLUMN "CM_FACTORYGROUP"."GROUPNAME" IS '群組名稱';
   COMMENT ON COLUMN "CM_FACTORYGROUP"."DESCRIPTION" IS '敘述';
   COMMENT ON COLUMN "CM_FACTORYGROUP"."CREATOR" IS '建立者';
   COMMENT ON COLUMN "CM_FACTORYGROUP"."CREATETIMESTAMP" IS '建立時間';
   COMMENT ON COLUMN "CM_FACTORYGROUP"."MODIFIER" IS '異動者';
   COMMENT ON COLUMN "CM_FACTORYGROUP"."MODIFYTIMESTAMP" IS '異動時間';
   COMMENT ON COLUMN "CM_FACTORYGROUP"."GROUPTYPE" IS '群組類別(0: PO履歷特殊跨廠)';
   COMMENT ON COLUMN "CM_FACTORYGROUP"."CODE" IS '代碼';
   COMMENT ON COLUMN "CM_FACTORYGROUP"."SORTNUM" IS '排序';
   COMMENT ON COLUMN "CM_FACTORYGROUP"."DISABLED" IS '無效';
   COMMENT ON TABLE "CM_FACTORYGROUP"  IS '自訂工廠群組主檔';
Insert into CM_FACTORYGROUP (ID,GROUPNAME,DESCRIPTION,CREATOR,CREATETIMESTAMP,MODIFIER,MODIFYTIMESTAMP,GROUPTYPE,CODE,SORTNUM,DISABLED) values (1,'台泥所有廠<物料>','台泥所有廠<物料>',1,to_date('2015-11-13 14:25:02','yyyy-mm-dd HH24:MI:SS'),1,to_date('2016-08-03 13:10:02','yyyy-mm-dd HH24:MI:SS'),'1','ALL_MM',1,0);
Insert into CM_FACTORYGROUP (ID,GROUPNAME,DESCRIPTION,CREATOR,CREATETIMESTAMP,MODIFIER,MODIFYTIMESTAMP,GROUPTYPE,CODE,SORTNUM,DISABLED) values (6,'台泥台灣廠(不含預拌廠)','台泥台灣廠(不含預拌廠)',1,to_date('2015-11-18 12:29:29','yyyy-mm-dd HH24:MI:SS'),1,to_date('2015-11-18 13:23:06','yyyy-mm-dd HH24:MI:SS'),'1','TCCM',6,0);
Insert into CM_FACTORYGROUP (ID,GROUPNAME,DESCRIPTION,CREATOR,CREATETIMESTAMP,MODIFIER,MODIFYTIMESTAMP,GROUPTYPE,CODE,SORTNUM,DISABLED) values (5,'台泥大陸直管各廠','台泥大陸直管各廠',1,to_date('2015-01-13 15:12:05','yyyy-mm-dd HH24:MI:SS'),1,to_date('2015-11-18 13:22:48','yyyy-mm-dd HH24:MI:SS'),'1','TCDCN',5,0);
Insert into CM_FACTORYGROUP (ID,GROUPNAME,DESCRIPTION,CREATOR,CREATETIMESTAMP,MODIFIER,MODIFYTIMESTAMP,GROUPTYPE,CODE,SORTNUM,DISABLED) values (4,'新台泥各廠','杭州本部下轄廠',1,to_date('2014-08-21 17:54:39','yyyy-mm-dd HH24:MI:SS'),1,to_date('2016-08-03 13:10:23','yyyy-mm-dd HH24:MI:SS'),'1','HZCN',4,0);
Insert into CM_FACTORYGROUP (ID,GROUPNAME,DESCRIPTION,CREATOR,CREATETIMESTAMP,MODIFIER,MODIFYTIMESTAMP,GROUPTYPE,CODE,SORTNUM,DISABLED) values (3,'台泥台灣各廠','台泥台灣',1,to_date('2014-07-02 16:24:39','yyyy-mm-dd HH24:MI:SS'),1,to_date('2015-11-18 13:23:20','yyyy-mm-dd HH24:MI:SS'),'1','TCC',3,0);
Insert into CM_FACTORYGROUP (ID,GROUPNAME,DESCRIPTION,CREATOR,CREATETIMESTAMP,MODIFIER,MODIFYTIMESTAMP,GROUPTYPE,CODE,SORTNUM,DISABLED) values (2,'台泥大陸各廠','台泥大陸',1,to_date('2014-07-02 16:24:42','yyyy-mm-dd HH24:MI:SS'),1,to_date('2016-08-03 13:10:12','yyyy-mm-dd HH24:MI:SS'),'1','TCCCN',2,0);
Insert into CM_FACTORYGROUP (ID,GROUPNAME,DESCRIPTION,CREATOR,CREATETIMESTAMP,MODIFIER,MODIFYTIMESTAMP,GROUPTYPE,CODE,SORTNUM,DISABLED) values (12,'總處','總處，含處辦案件',1,to_date('2014-11-18 18:03:52','yyyy-mm-dd HH24:MI:SS'),1,to_date('2015-11-18 13:25:09','yyyy-mm-dd HH24:MI:SS'),'1','1010',21,0);
Insert into CM_FACTORYGROUP (ID,GROUPNAME,DESCRIPTION,CREATOR,CREATETIMESTAMP,MODIFIER,MODIFYTIMESTAMP,GROUPTYPE,CODE,SORTNUM,DISABLED) values (13,'杭州本部',' 杭州本部，含本部辦案件',1,to_date('2014-11-18 18:04:49','yyyy-mm-dd HH24:MI:SS'),1,to_date('2015-11-18 13:25:16','yyyy-mm-dd HH24:MI:SS'),'1','3010',22,0);
Insert into CM_FACTORYGROUP (ID,GROUPNAME,DESCRIPTION,CREATOR,CREATETIMESTAMP,MODIFIER,MODIFYTIMESTAMP,GROUPTYPE,CODE,SORTNUM,DISABLED) values (7,'台灣水泥製品各廠','台灣水泥製品各廠',1,to_date('2015-01-13 15:12:05','yyyy-mm-dd HH24:MI:SS'),1,to_date('2015-11-18 13:23:55','yyyy-mm-dd HH24:MI:SS'),'1','TCCF',7,0);


CREATE TABLE "CM_FACTORY" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"SAP_CLIENT_CODE" VARCHAR2(10 BYTE), 
	"CATEGORY_ID" NUMBER, 
	"CURRENCY" VARCHAR2(3 BYTE), 
	"COMPANY_ID" NUMBER, 
	 CONSTRAINT "CM_FACTORY_PK" PRIMARY KEY ("ID")
   ) ;
 
   COMMENT ON COLUMN "CM_FACTORY"."ID" IS 'PK ID';
   COMMENT ON COLUMN "CM_FACTORY"."CODE" IS '廠別代碼';
   COMMENT ON COLUMN "CM_FACTORY"."NAME" IS '廠別名稱';
   COMMENT ON COLUMN "CM_FACTORY"."SAP_CLIENT_CODE" IS 'SAP_CLIENT_CODE';
   COMMENT ON COLUMN "CM_FACTORY"."CATEGORY_ID" IS '類別ID';
   COMMENT ON COLUMN "CM_FACTORY"."CURRENCY" IS '預設幣別';
   COMMENT ON COLUMN "CM_FACTORY"."COMPANY_ID" IS '公司ID (CM_COMPANY.ID)';
   COMMENT ON TABLE "CM_FACTORY"  IS 'SAP廠別主檔';
   
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (55,'4111',N'华蓥厂','tcc_cn',2,'RMB',2);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (101,'3211',N'广安厂','tcc_cn',2,'RMB',2);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (102,'3511',N'凯里厂','tcc_cn',2,'RMB',2);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (53,'4211',N'纳溪厂','tcc_cn',2,'RMB',2);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (54,'4311',N'叙永厂','tcc_cn',2,'RMB',2);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (103,'3010',N'杭州本部','tcc_cn',10,'RMB',2);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (39,'3311',N'重慶廠','tcc_cn',2,'RMB',2);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (42,'3111',N'港安厂','tcc_cn',2,'RMB',2);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (43,'3411',N'安順厂','tcc_cn',2,'RMB',2);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (7,'2711',N'句容廠','tcc_cn',2,'RMB',2);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (8,'6011',N'英德台泥矿业','tcc_cn',5,'RMB',2);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (9,'6511',N'贵港台泥矿业','tcc_cn',5,'RMB',2);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (1,'1021',N'蘇澳廠','tcc',1,'TWD',1);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (2,'1022',N'花蓮廠','tcc',1,'TWD',1);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (3,'1023',N'和平廠','tcc',1,'TWD',1);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (4,'2011',N'英德廠','tcc_cn',2,'RMB',2);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (5,'2211',N'福州廠','tcc_cn',2,'RMB',2);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (6,'2511',N'貴港廠','tcc_cn',2,'RMB',2);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (10,'1040',N'台北廠','tcc',3,'TWD',1);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (11,'1041',N'桃園分廠','tcc',3,'TWD',1);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (12,'1042',N'中壢分廠','tcc',3,'TWD',1);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (13,'1043',N'土城分廠','tcc',3,'TWD',1);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (14,'1044',N'八德分廠','tcc',3,'TWD',1);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (15,'1046',N'龜山分廠','tcc',3,'TWD',1);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (16,'1047',N'東大分廠','tcc',3,'TWD',1);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (17,'1048',N'新竹分廠','tcc',3,'TWD',1);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (18,'1049',N'宜蘭分廠','tcc',3,'TWD',1);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (20,'1050',N'台中廠','tcc',3,'TWD',1);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (21,'1051',N'大肚分廠','tcc',3,'TWD',1);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (37,'1052',N'大里分廠','tcc',3,'TWD',1);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (34,'1053',N'太平分廠','tcc',3,'TWD',1);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (22,'1054',N'草屯分廠','tcc',3,'TWD',1);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (24,'1060',N'鼓山廠','tcc',3,'TWD',1);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (25,'1061',N'嘉義分廠','tcc',3,'TWD',1);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (26,'1062',N'台南分廠','tcc',3,'TWD',1);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (27,'1063',N'仁武分廠','tcc',3,'TWD',1);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (28,'1064',N'小港分廠','tcc',3,'TWD',1);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (29,'1065',N'安平分廠','tcc',3,'TWD',1);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (30,'1067',N'善化分廠','tcc',3,'TWD',1);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (31,'1068',N'路竹分廠','tcc',3,'TWD',1);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (23,'1071',N'花蓮預拌','tcc',3,'TWD',1);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (36,'6711',N'江苏台泥矿业工程有限公司','tcc_cn',5,'RMB',2);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (38,'3611',N'遼寧廠','tcc_cn',2,'RMB',2);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (40,'6821',N'蘇澳礦場','tcc',5,'TWD',1);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (41,'6823',N'和平礦場','tcc',5,'TWD',1);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (44,'2911',N'東莞廠','tcc_cn',2,'RMB',2);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (11010,'1010',N'總處','tcc',9,'TWD',1);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (33,'2311',N'洋屿码头','tcc_cn',4,'RMB',null);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (56,'6311',N'靖州厂','tcc_cn',2,'RMB',2);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (57,'6111',N'怀化厂','tcc_cn',2,'RMB',2);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (59,'1055',N'神岡分廠','tcc',3,'TWD',1);

Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (60,'104A',N'桃園二廠','tcc',3,'TWD',1);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (61,'104B',N'中壢二廠','tcc',3,'TWD',1);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (32,'1069',N'新市分廠','tcc',3,'TWD',1);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (110,'1621',N'信昌林園廠','tpcc',7,'TWD',4);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (58,'2611',N'韶关厂','tcc_cn',2,'RMB',2);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (39,'3311',N'重慶廠','tcc_cn',2,'RMB',2);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (45,'8010',N'中橡總處','csrc',6,'TWD',3);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (47,'8020',N'中橡林園廠','csrc',6,'TWD',3);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (48,'8100',N'马炭厂','csrc',6,'TWD',3);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (49,'8200',N'鞍炭厂','csrc',6,'TWD',3);
Insert into CM_FACTORY (ID,CODE,NAME,SAP_CLIENT_CODE,CATEGORY_ID,CURRENCY,COMPANY_ID) values (50,'8600',N'重庆厂','csrc',6,'TWD',3);



CREATE TABLE "CM_FACTORY_GROUP_R" 
   (	"ID" NUMBER(18,0) NOT NULL ENABLE, 
	"FACTORY_ID" NUMBER(18,0) NOT NULL ENABLE, 
	"FACTORYGROUP_ID" NUMBER(18,0) NOT NULL ENABLE, 
	"CREATOR" NUMBER(18,0), 
	"CREATETIMESTAMP" DATE, 
	"MODIFIER" NUMBER(18,0), 
	"MODIFYTIMESTAMP" DATE, 
	 CONSTRAINT "FACTORY_GROUP_R_PK" PRIMARY KEY ("ID")
  );
   COMMENT ON COLUMN "CM_FACTORY_GROUP_R"."ID" IS 'PK ID';
   COMMENT ON COLUMN "CM_FACTORY_GROUP_R"."FACTORY_ID" IS '廠別ID';
   COMMENT ON COLUMN "CM_FACTORY_GROUP_R"."FACTORYGROUP_ID" IS '群組ID';
   COMMENT ON COLUMN "CM_FACTORY_GROUP_R"."CREATOR" IS '建立者';
   COMMENT ON COLUMN "CM_FACTORY_GROUP_R"."CREATETIMESTAMP" IS '建立時間';
   COMMENT ON COLUMN "CM_FACTORY_GROUP_R"."MODIFIER" IS '異動者';
   COMMENT ON COLUMN "CM_FACTORY_GROUP_R"."MODIFYTIMESTAMP" IS '異動時間';
   COMMENT ON TABLE "CM_FACTORY_GROUP_R"  IS '工廠與自訂群組關聯檔';

CREATE TABLE "CM_USERCOMPANY" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	"SAP_CLIENT_CODE" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"CREATOR" NUMBER, 
	"CREATETIMESTAMP" DATE, 
	 CONSTRAINT "PP_USERCOMPANY_PK" PRIMARY KEY ("ID")
  );

   COMMENT ON COLUMN "CM_USERCOMPANY"."ID" IS 'PK ID';
   COMMENT ON COLUMN "CM_USERCOMPANY"."USER_ID" IS '使用者TC_USER ID';
   COMMENT ON COLUMN "CM_USERCOMPANY"."SAP_CLIENT_CODE" IS 'jndi/sapclient.config中定義的sapclient設定值Prefix';
   COMMENT ON COLUMN "CM_USERCOMPANY"."CREATOR" IS '建立者TC_USER ID';
   COMMENT ON COLUMN "CM_USERCOMPANY"."CREATETIMESTAMP" IS '建立時間';
   COMMENT ON TABLE "CM_USERCOMPANY"  IS '使用者公司權限關聯';   
   
CREATE TABLE "CM_USERFACTORY" 
   (	"ID" NUMBER(18,0) NOT NULL ENABLE, 
	"USER_ID" NUMBER(18,0) NOT NULL ENABLE, 
	"FACTORY_ID" NUMBER(18,0) NOT NULL ENABLE, 
	"CREATOR" NUMBER(18,0) DEFAULT 1, 
	"CREATETIMESTAMP" DATE DEFAULT sysdate, 
	 CONSTRAINT "USERFACTORY_PK" PRIMARY KEY ("ID")
  );
COMMENT ON TABLE "CM_USERFACTORY"  IS '使用者工廠關聯';

CREATE TABLE "CM_USER_FACTORYGROUP_R" 
   (	"ID" NUMBER(18,0) NOT NULL ENABLE, 
	"USER_ID" NUMBER(18,0), 
	"FACTORYGROUP_ID" NUMBER(18,0), 
	"CREATOR" NUMBER(18,0), 
	"CREATETIMESTAMP" DATE, 
	"MODIFIER" NUMBER(18,0), 
	"MODIFYTIMESTAMP" DATE, 
	"USERGROUP_ID" NUMBER(18,0) DEFAULT 0, 
	 CONSTRAINT "USER_FACTORYGROUP_PK" PRIMARY KEY ("ID"), 
	 CONSTRAINT "USER_FACTORYGROUP_FK1" FOREIGN KEY ("USER_ID")
	) ;

   COMMENT ON COLUMN "CM_USER_FACTORYGROUP_R"."ID" IS 'PK ID';
   COMMENT ON COLUMN "CM_USER_FACTORYGROUP_R"."USER_ID" IS '使用者 ID';
   COMMENT ON COLUMN "CM_USER_FACTORYGROUP_R"."FACTORYGROUP_ID" IS '工廠群組 ID';
   COMMENT ON COLUMN "CM_USER_FACTORYGROUP_R"."CREATOR" IS '建立者';
   COMMENT ON COLUMN "CM_USER_FACTORYGROUP_R"."CREATETIMESTAMP" IS '建立時間';
   COMMENT ON COLUMN "CM_USER_FACTORYGROUP_R"."MODIFIER" IS '異動者';
   COMMENT ON COLUMN "CM_USER_FACTORYGROUP_R"."MODIFYTIMESTAMP" IS '異動時間';
   COMMENT ON COLUMN "CM_USER_FACTORYGROUP_R"."USERGROUP_ID" IS 'for 特定角色的設定(回饋機制) TC_GROUP.ID';
   COMMENT ON TABLE "CM_USER_FACTORYGROUP_R"  IS '使用者與工廠群組關聯檔';

   
   
--供應商類別設定 申請
CREATE TABLE "ET_VC_FORM" 
   (	
   "ID" NUMBER(18,0) NOT NULL ENABLE, 
   "FACTORY_ID" NUMBER(18,0),
   "MANDT" VARCHAR2(6 CHAR), 
	"LIFNR_UI" VARCHAR2(20 CHAR),
    "CIDS" VARCHAR2(50 BYTE), 
    "CNAMES" VARCHAR2(50 BYTE), 
	"STATUS" VARCHAR2(20 BYTE),
	"PROCESS" NUMBER(18,0),
	"CREATOR" NUMBER(18,0), 
	"CREATETIME" DATE, 
	"MODIFIER" NUMBER(18,0), 
	"MODIFYTIME" DATE, 
	 CONSTRAINT "ET_VC_FORM_PK" PRIMARY KEY ("ID")
   );
COMMENT ON COLUMN "ET_VC_FORM"."ID" IS 'PK ID';
   COMMENT ON COLUMN "ET_VC_FORM"."MANDT" IS '用戶端';
   COMMENT ON COLUMN "ET_VC_FORM"."LIFNR_UI" IS 'AP用供應商代碼，去掉Prefix 3個0';
   COMMENT ON COLUMN "ET_VC_FORM"."CIDS" IS '分類ID合併顯示';
   COMMENT ON COLUMN "ET_VC_FORM"."CNAMES" IS '分類名稱合併顯示';
   COMMENT ON COLUMN "ET_VC_FORM"."FACTORY_ID" IS '申請廠別';--判斷簽核關卡
   COMMENT ON COLUMN "ET_VC_FORM"."STATUS" IS '狀態';
   COMMENT ON COLUMN "ET_VC_FORM"."PROCESS" IS '流程';
   COMMENT ON COLUMN "ET_VC_FORM"."CREATOR" IS '建立人';
   COMMENT ON COLUMN "ET_VC_FORM"."CREATETIME" IS '建立時間';
   COMMENT ON COLUMN "ET_VC_FORM"."MODIFIER" IS '最近修改人';
   COMMENT ON COLUMN "ET_VC_FORM"."MODIFYTIME" IS '最近修改時間';
CREATE SEQUENCE SEQ_VC_FORM INCREMENT BY 1 START WITH 1 NOMAXVALUE CACHE 3 NOORDER  NOCYCLE;

  

--會員申請
CREATE TABLE "ET_MEMBER_FORM" 
   (	
   "ID" NUMBER(18,0) NOT NULL ENABLE, 
   "MEMBER_ID" NUMBER(18,0),
   "FACTORY_ID" NUMBER(18,0),
   "TYPE" VARCHAR2(6 CHAR), 	
   "MANDT" VARCHAR2(6 CHAR), 
   "LIFNR_UI" VARCHAR2(20 CHAR),
   "APPLY_VENDER_CODE" VARCHAR2(20 CHAR),
   "APPLY_VENDER_NAME" VARCHAR2(70 CHAR),	
    "CIDS" VARCHAR2(50 BYTE), 
    "CNAMES" VARCHAR2(50 BYTE), 
	"STATUS" VARCHAR2(20 BYTE),
	"PROCESS" NUMBER(18,0),
	"CREATOR" NUMBER(18,0), 
	"CREATETIME" DATE, 
	"MODIFIER" NUMBER(18,0), 
	"MODIFYTIME" DATE, 
	--M_NV
	
	
	
	
	
	
	 CONSTRAINT "MEMBER_FORM_PK" PRIMARY KEY ("ID")
   );
COMMENT ON COLUMN "ET_MEMBER_FORM"."ID" IS 'PK ID';
COMMENT ON COLUMN "ET_MEMBER_FORM"."TYPE" IS '會員申請類別';
COMMENT ON COLUMN "ET_MEMBER_FORM"."FACTORY_ID" IS '申請人廠別';--判斷簽核關卡
   COMMENT ON COLUMN "ET_MEMBER_FORM"."MANDT" IS '用戶端';
   COMMENT ON COLUMN "ET_MEMBER_FORM"."LIFNR_UI" IS 'AP用供應商代碼，去掉Prefix 3個0';
   COMMENT ON COLUMN "ET_MEMBER_FORM"."CIDS" IS '分類ID合併顯示';
   COMMENT ON COLUMN "ET_MEMBER_FORM"."CNAMES" IS '分類名稱合併顯示';
   COMMENT ON COLUMN "ET_MEMBER_FORM"."STATUS" IS '狀態';
   COMMENT ON COLUMN "ET_MEMBER_FORM"."PROCESS" IS '流程';
   COMMENT ON COLUMN "ET_MEMBER_FORM"."CREATOR" IS '建立人';
   COMMENT ON COLUMN "ET_MEMBER_FORM"."CREATETIME" IS '建立時間';
   COMMENT ON COLUMN "ET_MEMBER_FORM"."MODIFIER" IS '最近修改人';
   COMMENT ON COLUMN "ET_MEMBER_FORM"."MODIFYTIME" IS '最近修改時間';
CREATE SEQUENCE SEQ_MEMBER_FORM INCREMENT BY 1 START WITH 1 NOMAXVALUE CACHE 3 NOORDER  NOCYCLE;


--投標確認
CREATE TABLE "ET_TENDER_CONFORM" 
   (	
   "ID" NUMBER(18,0) NOT NULL ENABLE, 
   "MEMBER_ID" NUMBER(18,0),
   "TENDER_ID" NUMBER(18,0), 	
   "MANDT" VARCHAR2(6 CHAR), 
   "LIFNR_UI" VARCHAR2(20 CHAR),
   "VENDER_NAME" VARCHAR2(70 CHAR),	
   "CREATOR" NUMBER(18,0), 
	"CREATETIME" DATE, 
	"MODIFIER" NUMBER(18,0), 
	"MODIFYTIME" DATE, 
	 CONSTRAINT "TENDER_CONFORM_PK" PRIMARY KEY ("ID")
   );  
COMMENT ON COLUMN "ET_TENDER_CONFORM"."ID" IS 'PK ID';
COMMENT ON COLUMN "ET_TENDER_CONFORM"."MEMBER_ID" IS '會員ID';
COMMENT ON COLUMN "ET_TENDER_CONFORM"."TENDER_ID" IS '案件ID';
COMMENT ON COLUMN "ET_TENDER_CONFORM"."MANDT" IS '用戶端';
COMMENT ON COLUMN "ET_TENDER_CONFORM"."LIFNR_UI" IS 'AP用供應商代碼，去掉Prefix 3個0';
COMMENT ON COLUMN "ET_TENDER_CONFORM"."VENDER_NAME" IS '供應商名稱';
COMMENT ON COLUMN "ET_TENDER_CONFORM"."CREATOR" IS '建立人';
COMMENT ON COLUMN "ET_TENDER_CONFORM"."CREATETIME" IS '建立時間';
COMMENT ON COLUMN "ET_TENDER_CONFORM"."MODIFIER" IS '最近修改人';
COMMENT ON COLUMN "ET_TENDER_CONFORM"."MODIFYTIME" IS '最近修改時間';
CREATE SEQUENCE SEQ_TENDER_CONFORM INCREMENT BY 1 START WITH 1 NOMAXVALUE CACHE 3 NOORDER  NOCYCLE;
   
 --drop table KB_PUBLICATION;

 
--CREATE SEQUENCE  "ET_USER"."CM_ACTIVITY_LOG_ID_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--CREATE SEQUENCE  "ET_USER"."KB_LINK_ID_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--CREATE SEQUENCE  "ET_USER"."KB_PHOTO_GALLERY_ID_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--CREATE SEQUENCE  "ET_USER"."KB_PUBLICATION_ID_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--CREATE SEQUENCE  "ET_USER"."KB_RICH_CONTENT_ID_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--CREATE SEQUENCE  "ET_USER"."KB_VIDEO_ID_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;



COMMIT;


--供應商筆數 27902   (prod 20542)
--指同步tcc_cn


select count(1) from TC_ZTAB_EXP_LFA1
--select * from TC_ZTAB_EXP_LFA1
where 1=1
--排除一次性供應商
and LIFNR_UI != '0000001'
--排除 "黑名單凍結廠商"(中央採購凍結 CSPERM='X' AND SPERQ='99')
and CSPERM is null 
and (SPERQ!='99' or SPERQ is null )
--必須要有採購組織
and EKORG is not null
;



--案件筆數
select count(1) from ET_TENDER
where 1=1
and STATUS not in ('')
;


--供應商分類
select --* 
distinct S.MANDT, S.LIFNR_UI venderCode, S.NAME1 CNAME
, vc.C_IDS
, vc.C_NAMES
from TC_ZTAB_EXP_LFA1 S
LEFT OUTER JOIN (
 SELECT A.MANDT, A.LIFNR_UI
, LISTAGG(A.CATEGORY, ',') WITHIN GROUP (ORDER BY A.CATEGORY) C_IDS
, LISTAGG(to_char(o.CNAME), ',') WITHIN GROUP (ORDER BY o.SORTNUM) C_NAMES
FROM ET_VENDER_CATEGORY A
join EC_OPTION o on o.id = A.CATEGORY AND o.TYPE = 'tenderCategory'
GROUP BY A.MANDT, A.LIFNR_UI
) vc on vc.MANDT = S.MANDT and vc.LIFNR_UI=S.LIFNR_UI
WHERE 1=1
--AND vc.C_IDS LIKE '%1%'
order by vc.C_IDS, S.LIFNR_UI, S.MANDT
;

--userFactory
SELECT  U.ID, U.LOGIN_ACCOUNT, U.EMP_ID, U.CNAME , U.EMAIL, U.CREATETIMESTAMP, 
 T.FACTORY AS FACTORYS, 
 P.COMPANY AS COMPANIES, 
 G.FGROUP AS FACTORYGROUPS, 
 CREATUSER.LOGIN_ACCOUNT AS CREATOR 
 FROM TC_USER U 
 LEFT OUTER JOIN TC_USER CREATUSER ON U.CREATOR = CREATUSER.ID 
 LEFT OUTER JOIN ( 
   SELECT UF.USER_ID, 
   LISTAGG(F.CODE||'('||F.NAME||')', ',') WITHIN GROUP (ORDER BY F.CODE) FACTORY, 
   LISTAGG('~'||F.ID||'~', ',') WITHIN GROUP (ORDER BY F.CODE) FACTORYCODE 
   FROM CM_USERFACTORY UF 
   JOIN CM_FACTORY F ON UF.FACTORY_ID=F.ID 
   GROUP BY UF.USER_ID 
 ) T ON U.ID = T.USER_ID 
 LEFT OUTER JOIN ( 
   SELECT A.USER_ID, 
   LISTAGG(B.SAP_CLIENT_CODE, ',') WITHIN GROUP (ORDER BY B.SAP_CLIENT_CODE) COMPANY, 
   LISTAGG('~'||B.SAP_CLIENT_CODE||'~', ',') WITHIN GROUP (ORDER BY B.SAP_CLIENT_CODE) COMPANYCODE 
   FROM CM_USERCOMPANY A 
   JOIN CM_COMPANY B ON B.SAP_CLIENT_CODE=A.SAP_CLIENT_CODE 
   GROUP BY A.USER_ID 
 ) P ON U.ID = P.USER_ID 
 LEFT OUTER JOIN ( 
   SELECT USER_ID,  
   LISTAGG(GROUPNAME, ',') WITHIN GROUP (ORDER BY GROUPNAME) FGROUP, 
   LISTAGG('~'||TO_CHAR(ID)||'~', ',') WITHIN GROUP (ORDER BY ID) FGROUPID 
   FROM ( 
     SELECT USER_ID, GROUPNAME, ID 
     FROM ( 
       SELECT FG.USER_ID, F.GROUPNAME, F.ID 
       FROM CM_USER_FACTORYGROUP_R FG  
       JOIN CM_FACTORYGROUP F ON F.disabled=0 and FG.FACTORYGROUP_ID=F.ID  
     ) A 
     GROUP BY USER_ID, GROUPNAME, ID 
   ) B 
   GROUP BY USER_ID 
 ) G ON U.ID = G.USER_ID 
 WHERE U.DISABLED = 0 
 ORDER BY U.LOGIN_ACCOUNT 
;



