CREATE TABLE "SK_SP_USER"."SK_FI_COST"
  (
    "ID"        NUMBER(18,0) NOT NULL ENABLE,
    "MATNR"     VARCHAR2(12 BYTE),
    "UNIT_COST" NUMBER(13,3),
    "YEAR"      VARCHAR2(4 BYTE),
    CONSTRAINT "SK_FI_COST_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "USERS" ENABLE
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "USERS" ;
  /////////////////////////////////////////////////
  
  CREATE TABLE "SK_SP_USER"."SK_SALES_BUGET"
  (
    "ID"         NUMBER(18,0) NOT NULL ENABLE,
    "YEAR_MONTH"   VARCHAR2(6 BYTE),
    "SAP_ID"      VARCHAR2(4 BYTE),
    "CUST_CODE"  VARCHAR2(6 BYTE),
	"PRD_TYPE"  VARCHAR2(2 BYTE),
	"MATNR"  VARCHAR2(12 BYTE),
    "AMOUNT"  NUMBER(13,3),
	"UNITS"  NUMBER(13,3),
    CONSTRAINT "SK_SALES_BUGET_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "USERS" ENABLE
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "USERS" ;
  
  ///////////////////////////////////////////
