CREATE TABLE TC_USER 
(	
    ID NUMBER(18) NOT NULL ENABLE, 
	LOGIN_ACCOUNT VARCHAR2(60 BYTE) NOT NULL ENABLE, 
	EMAIL VARCHAR2(60 BYTE), 	
	EMP_ID VARCHAR2(20 BYTE),
	CNAME VARCHAR2(20 CHAR),
    disabled   NUMBER(1) default 0, 	
	CREATOR NUMBER(18) ,
    CREATETIMESTAMP DATE NOT NULL,	
	CONSTRAINT TC_USER_PK PRIMARY KEY (ID),
	CONSTRAINT TC_USER_UK UNIQUE (LOGIN_ACCOUNT,CREATETIMESTAMP),
	CONSTRAINT TC_USER_FK FOREIGN KEY (CREATOR) REFERENCES TC_USER(ID)
)
/
COMMENT ON COLUMN TC_USER.LOGIN_ACCOUNT IS '登入帳號';
/ 
CREATE TABLE TC_GROUP 
(	
    ID NUMBER(18) NOT NULL ENABLE, 
    CODE VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	NAME VARCHAR2(90 CHAR) NOT NULL ENABLE, 
	CREATOR NUMBER(18) , 
	CREATETIMESTAMP DATE,
	CONSTRAINT TC_GROUP_PK PRIMARY KEY (ID),
	CONSTRAINT TC_GROUP_UK UNIQUE (CODE),
	CONSTRAINT TC_GROUP_FK FOREIGN KEY (CREATOR) REFERENCES TC_USER(ID)
)
/
COMMENT ON COLUMN TC_GROUP.ID IS 'TC_GROUP.ID';
/
COMMENT ON COLUMN TC_GROUP.CODE IS '群組代號';
/
COMMENT ON COLUMN TC_GROUP.NAME IS '群組名稱';
/
COMMENT ON COLUMN TC_GROUP.CREATOR IS 'ref. TC_USER.ID';
/
CREATE TABLE TC_USERGROUP 
(	
	 ID NUMBER(18) NOT NULL ENABLE, 
	 USER_ID NUMBER(18) NOT NULL ENABLE, 
	 GROUP_ID NUMBER(18) DEFAULT 1 NOT NULL ENABLE, 
	 CREATOR NUMBER(18) , 
	 CREATETIMESTAMP DATE,
 	 CONSTRAINT TC_USERGROUP_PK PRIMARY KEY (ID),
	 CONSTRAINT TC_USERGROUP_UK1 UNIQUE (USER_ID, GROUP_ID) ENABLE,
	 CONSTRAINT TC_USERGROUP_FK1 FOREIGN KEY (GROUP_ID) REFERENCES TC_GROUP (ID),
	 CONSTRAINT TC_USERGROUP_FK2 FOREIGN KEY (USER_ID) REFERENCES TC_USER (ID),
	 CONSTRAINT TC_USERGROUP_FK3 FOREIGN KEY (CREATOR) REFERENCES TC_USER (ID)
)
/
COMMENT ON COLUMN TC_USERGROUP.ID IS 'PK';
COMMENT ON COLUMN TC_USERGROUP.USER_ID IS 'Group member (FK:TC_USER.ID)';
COMMENT ON COLUMN TC_USERGROUP.GROUP_ID IS 'group (FK:TC_GROUP.ID)';
COMMENT ON COLUMN TC_USERGROUP.CREATOR IS '建立者';
COMMENT ON COLUMN TC_USERGROUP.CREATETIMESTAMP IS '建立時間';

CREATE TABLE TC_APPLICATIONDATA 
(	
   ID NUMBER(18) NOT NULL ENABLE, 
	CONTAINERCLASSNAME VARCHAR2(255) DEFAULT NULL, 
	CONTAINERID NUMBER(18) DEFAULT NULL, 
	CONTENTROLE VARCHAR2(1) DEFAULT 'P', 
	CREATOR NUMBER(18) DEFAULT NULL NOT NULL ENABLE, 
	CREATETIMESTAMP DATE DEFAULT sysdate NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(1000 char), 
	FVITEM NUMBER(18) DEFAULT NULL NOT NULL ENABLE, 
	CONSTRAINT TC_APPLICATIONDATA_PK PRIMARY KEY (ID),
	CONSTRAINT TC_APPLICATIONDATA_FK1 FOREIGN KEY (CREATOR) REFERENCES TC_USER (ID) 
)
/
COMMENT ON COLUMN TC_APPLICATIONDATA.ID IS 'APPLICATIONDATA.ID';
/
COMMENT ON COLUMN TC_APPLICATIONDATA.CONTAINERCLASSNAME IS 'entity name(ex. com.tcci.hep.entity.LEAVE)';
/
COMMENT ON COLUMN TC_APPLICATIONDATA.CONTAINERID IS 'entity ID(ex. LEAVE.ID)';
/
COMMENT ON COLUMN TC_APPLICATIONDATA.CONTENTROLE IS 'Primary:P,Secondary:S';
/
COMMENT ON COLUMN TC_APPLICATIONDATA.CREATOR IS 'ref TC_USER';
/
COMMENT ON COLUMN TC_APPLICATIONDATA.CREATETIMESTAMP 
IS '建立時間';
/
COMMENT ON COLUMN TC_APPLICATIONDATA.DESCRIPTION 
IS '說明';
/
COMMENT ON COLUMN TC_APPLICATIONDATA.FVITEM IS 'FVITEM.ID';
/
CREATE TABLE TC_DOMAIN 
(	ID NUMBER(18) NOT NULL ENABLE, 
	NAME VARCHAR2(600 char) NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(100 char) DEFAULT NULL, 
	CONSTRAINT TC_DOMAIN_PK PRIMARY KEY (ID)
)
/
COMMENT ON COLUMN TC_DOMAIN.ID IS 'DOMAIN.ID';
/
COMMENT ON COLUMN TC_DOMAIN.NAME IS 'Domain name';
/
COMMENT ON COLUMN TC_DOMAIN.DESCRIPTION IS '說明';
/
CREATE TABLE TC_FVITEM 
(	ID NUMBER(18) NOT NULL ENABLE, 
	NAME VARCHAR2(255 char) NOT NULL ENABLE, 
	FILENAME VARCHAR2(255 char) NOT NULL ENABLE, 
	FILESIZE NUMBER(18) NOT NULL ENABLE, 
	CONTENTTYPE VARCHAR2(255 char) DEFAULT NULL, 
	DOMAIN NUMBER(18) NOT NULL ENABLE, 
	CREATOR NUMBER(18) DEFAULT NULL NOT NULL ENABLE, 
	CREATETIMESTAMP DATE DEFAULT sysdate NOT NULL ENABLE, 
    CONSTRAINT FUL_FVITEM_PK PRIMARY KEY (ID),
  	CONSTRAINT TC_FVITEM_FK1 FOREIGN KEY (DOMAIN) REFERENCES TC_DOMAIN (ID),
	CONSTRAINT TC_FVITEM_FK2 FOREIGN KEY (CREATOR) REFERENCES TC_USER (ID) 
)
/
COMMENT ON COLUMN TC_FVITEM.ID IS 'FVITEM.ID';
/
COMMENT ON COLUMN TC_FVITEM.NAME IS '實體附件顯示名稱';
/
COMMENT ON COLUMN TC_FVITEM.FILENAME IS '檔名';
/
COMMENT ON COLUMN TC_FVITEM.FILESIZE IS '檔案大小';
/
COMMENT ON COLUMN TC_FVITEM.CONTENTTYPE IS 'mime type';
/
COMMENT ON COLUMN TC_FVITEM.DOMAIN IS 'ref. DOMAIN.ID';
/
COMMENT ON COLUMN TC_FVITEM.CREATOR IS '建立者(ref. TC_USER)';
/
COMMENT ON COLUMN TC_FVITEM.CREATETIMESTAMP IS '建立時間';
/
CREATE TABLE TC_FVVAULT 
(	ID NUMBER(18) NOT NULL ENABLE, 
	NAME NVARCHAR2(255) DEFAULT NULL, 
	HOSTNAME NVARCHAR2(255) NOT NULL ENABLE, 
	DOMAIN NUMBER(18) NOT NULL ENABLE, 
	LOCATION NVARCHAR2(600) NOT NULL ENABLE, 
	READONLY NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	ENABLED NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	URL VARCHAR2(600), 
	 CONSTRAINT FUL_FVVAULT_PK PRIMARY KEY (ID),
	 CONSTRAINT TC_FVVAULT_FK1 FOREIGN KEY (DOMAIN) REFERENCES TC_DOMAIN (ID)
)
/
COMMENT ON COLUMN TC_FVVAULT.ID IS 'FVVAULT.ID';
/
COMMENT ON COLUMN TC_FVVAULT.NAME IS '實體備份目錄';
/
COMMENT ON COLUMN TC_FVVAULT.HOSTNAME IS '主機名稱';
/
COMMENT ON COLUMN TC_FVVAULT.DOMAIN IS 'DOMAIN.ID';
/
COMMENT ON COLUMN TC_FVVAULT.LOCATION IS '實體目錄';
/
COMMENT ON COLUMN TC_FVVAULT.READONLY IS '是否唯讀[0:false,1:true]';
/
COMMENT ON COLUMN TC_FVVAULT.ENABLED IS '是否開放[0:false,1,true]';
/
COMMENT ON COLUMN TC_FVVAULT.URL IS 'http url';
/ 
CREATE SEQUENCE SEQ_FVITEM INCREMENT BY 1 START WITH 2 NOMAXVALUE CACHE 3 NOORDER  NOCYCLE;
/
CREATE SEQUENCE SEQ_TCC INCREMENT BY 1 START WITH 100 NOMAXVALUE CACHE 3 NOORDER  NOCYCLE;
/ 

CREATE TABLE TC_SITE (
  ID NUMBER(18) NOT NULL,
  NAME VARCHAR2(255) NOT NULL,
  HOSTNAME VARCHAR2(255) NOT NULL,
  CONSTRAINT TC_SITE_PK PRIMARY KEY (ID)
);

COMMENT ON COLUMN TC_SITE.ID IS 'PK';
COMMENT ON COLUMN TC_SITE.NAME IS '名稱';
COMMENT ON COLUMN TC_SITE.HOSTNAME IS '主機名稱';


REM INSERTING into TC_DOMAIN
INSERT INTO TC_DOMAIN (ID,NAME,DESCRIPTION) VALUES (1,'Default','Default');
INSERT INTO TC_DOMAIN (ID,NAME,DESCRIPTION) VALUES (2,'DocImages','Doc Images');
INSERT INTO TC_DOMAIN (ID,NAME,DESCRIPTION) VALUES (3,'CustomImages','Custom Images');
--Insert into TC_DOMAIN (ID,NAME,DESCRIPTION) values (2,'TrashCan','TrashCan');

REM INSERTING into TC_FVVAULT
INSERT INTO TC_FVVAULT (ID,NAME,HOSTNAME,DOMAIN,LOCATION,READONLY,ENABLED,URL) VALUES (1,'Default','localhost',1,'/opt/FileUpload/et-admin/',0,1,NULL);
INSERT INTO TC_FVVAULT (ID,NAME,HOSTNAME,DOMAIN,LOCATION,READONLY,ENABLED,URL) VALUES (2,'DocImages','localhost',1,'/opt/FileUpload/et-admin/DocImages/',0,1,NULL);
INSERT INTO TC_FVVAULT (ID,NAME,HOSTNAME,DOMAIN,LOCATION,READONLY,ENABLED,URL) VALUES (3,'CustomImages','localhost',1,'/opt/FileUpload/et-admin/CustomImages/',0,1,NULL);
--Insert into TC_FVVAULT (ID,NAME,HOSTNAME,DOMAIN,LOCATION,READONLY,ENABLED,URL) values (2,'TrashCan','localhost',2,'D:\FileVault\APP\TrashCan\',0,1,null);

--Default	localhost	1	/opt/FileUpload/et-admin/
--Default	localhost	1	D:\FileUpload\et-admin\
/

REM INSERTING into TC_USER
INSERT INTO TC_USER (ID,LOGIN_ACCOUNT,CNAME,DISABLED,CREATOR,CREATETIMESTAMP) VALUES (1,'administrator','',0,1,SYSDATE);
INSERT INTO TC_USER (ID,LOGIN_ACCOUNT,CNAME,DISABLED,CREATOR,CREATETIMESTAMP) VALUES (2,'jackson.lee','李毓霖',0,1,SYSDATE);
INSERT INTO TC_USER (ID,LOGIN_ACCOUNT,CNAME,DISABLED,CREATOR,CREATETIMESTAMP) VALUES (3,'yen-chi.sun','孫延麒',0,1,SYSDATE);
INSERT INTO TC_USER (ID,LOGIN_ACCOUNT,CNAME,DISABLED,CREATOR,CREATETIMESTAMP) VALUES (4,'kyle.cheng','鄭傑鳴',0,1,SYSDATE);



REM INSERTING into TC_GROUP
Insert into TC_GROUP (ID,CODE,NAME,CREATOR,CREATETIMESTAMP) values (1,'ADMINISTRATORS',N'系統管理員',1,sysdate);
Insert into TC_GROUP (ID,CODE,NAME,CREATOR,CREATETIMESTAMP) values (2,'RESTFUL_USER',N'RESTFUL USER',1,sysdate);
Insert into TC_GROUP (ID,CODE,NAME,CREATOR,CREATETIMESTAMP) values (3,'APUSER',N'系統使用者',1,sysdate);
Insert into TC_GROUP (ID,CODE,NAME,CREATOR,CREATETIMESTAMP) values (4,'HQ_MM',N'總處物料人員',1,sysdate);
Insert into TC_GROUP (ID,CODE,NAME,CREATOR,CREATETIMESTAMP) values (5,'HZ_MM',N'杭州本部物料人員',1,sysdate);



REM INSERTING into TC_USERGROUP
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (1,1,1,1,sysdate);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (2,2,1,1,sysdate);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (3,3,1,1,sysdate);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (4,4,1,1,sysdate);
commit;
/



  CREATE TABLE "TC_SCHEDULE" 
   (	
   "NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"EXEC_TIME" DATE, 
	"ACTIVE" NUMBER(1,0) DEFAULT 1, 
	 CONSTRAINT "TC_SCHEDULE_PK" PRIMARY KEY ("NAME")
   ) ;
   COMMENT ON COLUMN "TC_SCHEDULE"."NAME" IS 'PK:排程名稱';
   COMMENT ON COLUMN "TC_SCHEDULE"."EXEC_TIME" IS '前次執行時間';
Insert into TC_SCHEDULE (NAME,EXEC_TIME,ACTIVE) values ('updateTenderStatus',sysdate,1);--更新標案狀態


