--公司主檔 增加欄位
ALTER TABLE FC_COMPANY ADD SORT int;
ALTER TABLE FC_COMPANY ADD CURRENCY bigint;
ALTER TABLE FC_COMPANY ADD PARENT nvarchar(6);

--建立公司報表上傳者關聯表
CREATE TABLE FC_UPLOADER_R (
	ID bigint NOT NULL IDENTITY,
	COMPANY_ID bigint,
	USER_ID bigint,
	CREATETIMESTAMP datetime NOT NULL
	CONSTRAINT FC_UPLOADER_R_PK PRIMARY KEY (ID),
	CONSTRAINT FC_UPLOADER_R_FK1 FOREIGN KEY (COMPANY_ID) REFERENCES FC_COMPANY (ID),
	CONSTRAINT FC_UPLOADER_R_FK2 FOREIGN KEY (USER_ID) REFERENCES TC_USER (ID)
)

--將原上傳者 寫入公司報表上傳者關聯表
INSERT INTO FC_UPLOADER_R (COMPANY_ID,USER_ID,CREATETIMESTAMP) 
select id, uploader, GETDATE() from FC_COMPANY
where 1=1 and ACTIVE = 'true' and UPLOADER is not null

--建立幣別主檔
CREATE TABLE FC_CURRENCY (
	ID bigint NOT NULL IDENTITY,
	CODE nvarchar(6) NOT NULL,
	NAME nvarchar(50) NOT NULL
	CONSTRAINT FC_CURRENCY_PK PRIMARY KEY (ID),
	CONSTRAINT FC_CURRENCY_UK1 UNIQUE (CODE),
	--CONSTRAINT FC_CURRENCY_UK2 UNIQUE (NAME)
)
--寫入幣別
INSERT INTO FC_CURRENCY (CODE,NAME) VALUES ('NTD',N'新台幣');
INSERT INTO FC_CURRENCY (CODE,NAME) VALUES ('USD',N'美金');
INSERT INTO FC_CURRENCY (CODE,NAME) VALUES ('HKD',N'港幣');
INSERT INTO FC_CURRENCY (CODE,NAME) VALUES ('PHP',N'菲國比索');
INSERT INTO FC_CURRENCY (CODE,NAME) VALUES ('CNY',N'人民幣');
INSERT INTO FC_CURRENCY (CODE,NAME) VALUES ('CAD',N'加拿大幣');
INSERT INTO FC_CURRENCY (CODE,NAME) VALUES ('INR',N'印度盧比');

--月結匯率檔
CREATE TABLE FC_MONTHLY_EXCHANGE_RATE (
	ID bigint NOT NULL IDENTITY,
	CURRENCY bigint NOT NULL,
	YEARMONTH char(6) NOT NULL,
	RATE decimal(18,6),
	MODIFIER bigint,
	MODIFYTIMESTAMP datetime NOT NULL
	CONSTRAINT FC_MONTHLY_EXCHANGE_RATE_PK PRIMARY KEY (ID),
	CONSTRAINT FC_MONTHLY_EXCHANGE_RATE_UK1 UNIQUE (CURRENCY, YEARMONTH),
	CONSTRAINT FC_MONTHLY_EXCHANGE_RATE_FK1 FOREIGN KEY (CURRENCY) REFERENCES FC_CURRENCY (ID),
	CONSTRAINT FC_MONTHLY_EXCHANGE_RATE_FK2 FOREIGN KEY (MODIFIER) REFERENCES TC_USER (ID)
)

--報表匯入資料檔 增加XLS原始金額欄位
ALTER TABLE FC_REPORT_VALUE ADD AMOUNT_XLS decimal(18,3);

--20151014以後修改
--會計科目 對應檔
CREATE TABLE FC_ACCOUNTS (
	ID bigint NOT NULL IDENTITY,
	COMP_GROUP nvarchar(6) NOT NULL,
	CODE nvarchar(6) NOT NULL,
	NAME nvarchar(50) NOT NULL,
	ENAME nvarchar(50),
	CATEGORY nvarchar(6),
	ACTIVE bit NOT NULL
	CONSTRAINT FC_ACCOUNTS_PK PRIMARY KEY (ID),
	CONSTRAINT FC_ACCOUNTS_UK1 UNIQUE (COMP_GROUP, CODE, NAME)
);
--D0206
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE) VALUES ('TCC','4111',N'銷貨收入 - 水泥及熟料',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE) VALUES ('TCC','4114',N'銷貨收入 - 電力',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE) VALUES ('TCC','4115',N'銷貨收入 - 化工',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE) VALUES ('TCC','4116',N'銷貨收入 - 礦源',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE) VALUES ('TCC','4117',N'銷貨收入 - 電子陶瓷',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE) VALUES ('TCC','4119',N'銷貨收入 - 其他',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE) VALUES ('TCC','4300',N'租賃收入 - 租賃及建設業',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE) VALUES ('TCC','4500',N'營建工程收入 - 營建業',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE) VALUES ('TCC','4600',N'勞務收入 - 運輸、港務及環保等服務業',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE) VALUES ('TCC','4800',N'其他營業收入',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE) VALUES ('TCC','7110',N'利息收入',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE) VALUES ('TCC','7210',N'租金收入',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE) VALUES ('TCC','7480',N'什項收入',0);
--損益表
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE) VALUES ('TCC','4000',N'營業收入',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE) VALUES ('TCC','4110',N'銷貨收入 - 買賣及製造業',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE) VALUES ('TCC','4190',N'減：銷貨退回及折讓',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE) VALUES ('TCC','4100',N'銷貨收入淨額',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE) VALUES ('TCC','4200',N'投資收入 - 投資業',0);

--config 增加編輯鎖定
INSERT INTO FC_CONFIG (CONFIG_KEY,CONFIG_VALUE) VALUES ('EDITLOCK',0);

--報表模板 增加版本號碼
ALTER TABLE FC_REPORT_TEMPLATE ADD VERSION nvarchar(20);

--公司主檔 增加欄位
ALTER TABLE FC_COMPANY ADD COMBINE_INCOME bit;
update FC_COMPANY set COMBINE_INCOME = 'true' where 1=1;
sp_RENAME 'FC_COMPANY.PARENT' , 'COMP_GROUP', 'COLUMN'; 
sp_RENAME 'FC_ACCOUNTS.PARENT' , 'COMP_GROUP', 'COLUMN'; 

--FC_REPORT_TEMPLATE 模板增加企業團欄位
ALTER TABLE FC_REPORT_TEMPLATE ADD COMP_GROUP nvarchar(6);
update FC_REPORT_TEMPLATE set COMP_GROUP = 'TCC' where 1=1;

--增加 平均匯率 原匯率欄位表示期末匯率
ALTER TABLE FC_MONTHLY_EXCHANGE_RATE ADD AVG_RATE decimal(18,6);


--正式環境 人工insert FC_REPORT_UPLOAD
--20151015
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201401',27,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201403',6,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201401',1,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201401',17,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201401',6,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201401',7,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201401',8,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201401',21,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201401',10,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201401',22,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201401',18,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201401',11,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201401',23,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201401',20,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201401',4,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201401',26,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201401',16,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201401',2,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201401',3,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201401',25,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201401',15,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201401',5,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201401',12,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201401',14,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201401',9,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201401',13,1,GETDATE());

--20151016
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201504',1,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201504',17,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201504',6,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201504',7,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201504',8,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201504',21,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201504',10,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201504',22,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201504',18,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201504',11,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201504',23,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201504',20,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201504',4,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201504',26,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201504',27,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201504',16,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201504',2,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201504',3,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201504',25,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201504',15,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201504',5,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201504',12,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201504',14,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201504',9,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201504',13,1,GETDATE());
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201504',24,1,GETDATE());

--歷史資料會科調整
update FC_REPORT_A0102 set CODE = '4110' where code = '4111';
update FC_REPORT_A0102 set CODE = '4200' where code = '4210';
update FC_REPORT_A0102 set CODE = '4300' where code = '4310';
update FC_REPORT_A0102 set CODE = '4500' where code = '4511';
update FC_REPORT_A0102 set CODE = '4600' where code = '4611';
update FC_REPORT_A0102 set CODE = '4800' where code = '4881';

update FC_CONFIG set CONFIG_VALUE = '201406' where id = 3;
commit;

--20151020 企業團獨立開關帳
ALTER TABLE FC_CONFIG ADD COMP_GROUP nvarchar(6);
update FC_CONFIG set COMP_GROUP = 'TCC' where 1=1;
--修改原本的unique key
ALTER TABLE FC_CONFIG DROP CONSTRAINT FC_CONFIG_UK;
ALTER TABLE FC_CONFIG ADD CONSTRAINT FC_CONFIG_UK UNIQUE(CONFIG_KEY,COMP_GROUP);
--新增中橡開關帳設定
INSERT INTO FC_CONFIG (CONFIG_KEY,CONFIG_VALUE,COMP_GROUP) VALUES ('STOPUPLOAD',0,'CSRC');
INSERT INTO FC_CONFIG (CONFIG_KEY,CONFIG_VALUE,COMP_GROUP) VALUES ('EDITLOCK',0,'CSRC');


--公司幣別設定
--先人工設定外幣
--其他null ==> 設為台幣
update FC_COMPANY set CURRENCY = 1 where CURRENCY is null
--增加公司簡稱欄位
ALTER TABLE FC_COMPANY ADD ABBREVIATION nvarchar(20);

--增加欄位 對應SAP的幣別代碼
ALTER TABLE FC_CURRENCY ADD SAP_CODE nvarchar(6);
update FC_CURRENCY set SAP_CODE = 'TWD' where CODE ='NTD';
update FC_CURRENCY set SAP_CODE = 'RMB' where CODE ='CNY';
--幣別代碼改統一以SAP代碼為主
ALTER TABLE FC_CURRENCY DROP COLUMN SAP_CODE;
update FC_CURRENCY set CODE = 'TWD' where CODE ='NTD';
update FC_CURRENCY set CODE = 'RMB' where CODE ='CNY';

--20151112修改
--修改FC_REPORT_TEMPLATE 原本的unique key
ALTER TABLE FC_REPORT_TEMPLATE DROP CONSTRAINT FC_REPORT_TEMPLATE_UK;
ALTER TABLE FC_REPORT_TEMPLATE ADD CONSTRAINT FC_REPORT_TEMPLATE_UK UNIQUE(YEARMONTH,COMP_GROUP);

--增加 公司 英文名稱
ALTER TABLE FC_COMPANY ADD ENAME nvarchar(50);
--修改COMP_GROUP 資料長度
ALTER TABLE FC_COMPANY ALTER Column COMP_GROUP nvarchar(8);
ALTER TABLE FC_ACCOUNTS ALTER Column COMP_GROUP nvarchar(8);
ALTER TABLE FC_CONFIG ALTER Column COMP_GROUP nvarchar(8);
ALTER TABLE FC_REPORT_TEMPLATE ALTER Column COMP_GROUP nvarchar(8);

--20151112 正式環境insert但 ACTIVE==false
--加入中橡公司
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE,COMP_GROUP,COMBINE_INCOME,ABBREVIATION,ENAME) VALUES ('8000',N'中國合成橡膠股份有限公司',1,'CSRC',1,N'中橡','China Synthetic Rubber Corporation');
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE,COMP_GROUP,COMBINE_INCOME,ABBREVIATION,ENAME) VALUES ('8C00','CCC USA Corp.',1,'CSRC',1,'CCC USA','CCC USA Corp.');
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE,COMP_GROUP,COMBINE_INCOME,ABBREVIATION,ENAME) VALUES ('8A00','CSRC (BVI) Ltd.',1,'CSRC',1,'CSRC (BVI)','CSRC (BVI) Ltd.');
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE,COMP_GROUP,COMBINE_INCOME,ABBREVIATION,ENAME) VALUES ('8700',N'協原化學股份有限公司',1,'CSRC',1,N'協原','Consolidated Resource Company');
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE,COMP_GROUP,COMBINE_INCOME,ABBREVIATION,ENAME) VALUES ('8H00','Synpac (North Carolina) Inc.',1,'CSRC',1,'NC Groups','Synpac (North Carolina) Inc.');
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE,COMP_GROUP,COMBINE_INCOME,ABBREVIATION,ENAME) VALUES ('9600',N'景德製藥股份有限公司',1,'CSRC',1,N'景德','Synpac-Kingdom Pharmaceutical Co., Ltd.');
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE,COMP_GROUP,COMBINE_INCOME,ABBREVIATION,ENAME) VALUES ('9100',N'能元科技公司',1,'CSRC',1,N'能元','E-One Energy Technology Corp.');
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE,COMP_GROUP,COMBINE_INCOME,ABBREVIATION,ENAME) VALUES ('8900',N'首能科技股份有限公司',1,'CSRC',1,N'首能','Sole Energy Tech Corp.');
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE,COMP_GROUP,COMBINE_INCOME,ABBREVIATION,ENAME) VALUES ('8E00',N'中成開發投資股份有限公司',1,'CSRC',1,N'中成','CS Development & Investment Co.');
--& 特殊字元 要輸入'& Investment'
--update FC_COMPANY set ENAME = 'CS Development & Investment Co.' where CODE = '8E00';
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE,COMP_GROUP,COMBINE_INCOME,ABBREVIATION,ENAME) VALUES ('8G00','Synpac Ltd',1,'CSRC',1,'Synpac','Synpac Ltd');
--加入中橡BVI公司 
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE,COMP_GROUP,COMBINE_INCOME,ABBREVIATION,ENAME) VALUES ('8100',N'中橡(馬鞍山)化學工業有限公司',1,'CSRC_BVI',1,N'馬鞍山','CSRC China Corporation');
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE,COMP_GROUP,COMBINE_INCOME,ABBREVIATION,ENAME) VALUES ('8200',N'中橡(鞍山)化學工業有限公司',1,'CSRC_BVI',1,N'鞍山','CSRC China (Anshan) Corporation');
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE,COMP_GROUP,COMBINE_INCOME,ABBREVIATION,ENAME) VALUES ('8600',N'中橡(重慶)炭黑有限公司',1,'CSRC_BVI',1,N'重慶','CSRC China (Chongqing) Corporation');
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE,COMP_GROUP,COMBINE_INCOME,ABBREVIATION,ENAME) VALUES ('8300','Continental Carbon India Ltd.',1,'CSRC_BVI',1,'CCIL','Continental Carbon India Ltd.');

--正式環境 人工insert FC_REPORT_UPLOAD
--20151112  CSRC, CSRC_BVI 201410~201509

--CSRC, CSRC_BVI 開關帳
update FC_CONFIG set COMP_GROUP = 'TCC' where id = 3;
INSERT INTO FC_CONFIG (CONFIG_KEY,CONFIG_VALUE,COMP_GROUP) VALUES ('YEARMONTH','201510','CSRC');
INSERT INTO FC_CONFIG (CONFIG_KEY,CONFIG_VALUE,COMP_GROUP) VALUES ('YEARMONTH',null,'CSRC_BVI');
INSERT INTO FC_CONFIG (CONFIG_KEY,CONFIG_VALUE,COMP_GROUP) VALUES ('STOPUPLOAD',0,'CSRC_BVI');
INSERT INTO FC_CONFIG (CONFIG_KEY,CONFIG_VALUE,COMP_GROUP) VALUES ('EDITLOCK',0,'CSRC_BVI');

--20151112  CSRC, CSRC_BVI 共用會科
--A0102
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ENAME,ACTIVE) VALUES ('CSRC','4000',N'營業收入','Operating Revenue',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ENAME,ACTIVE) VALUES ('CSRC','4110',N'銷貨收入 - 買賣及製造業','Sales revenue ',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ENAME,ACTIVE) VALUES ('CSRC','4190',N'減：銷貨退回及折讓','Sales return discounts and allowances',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ENAME,ACTIVE) VALUES ('CSRC','4100',N'銷貨收入淨額','Net sales',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ENAME,ACTIVE) VALUES ('CSRC','4200',N'投資收入 - 投資業','Investment revenue - Investment',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ENAME,ACTIVE) VALUES ('CSRC','4800',N'其他營業收入','Other operating revenue',0);
--D0206
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ENAME,ACTIVE) VALUES ('CSRC','4111',N'銷貨收入 - 碳煙','Sales - Carbon Black',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ENAME,ACTIVE) VALUES ('CSRC','4112',N'銷貨收入 - 生技','Sales - Biotechnology',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ENAME,ACTIVE) VALUES ('CSRC','4113',N'銷貨收入 - 電子','Sales - Electronic Product',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ENAME,ACTIVE) VALUES ('CSRC','4114',N'銷貨收入 - 其他','Sales - Other',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ENAME,ACTIVE) VALUES ('CSRC','7110',N'利息收入','Interest income',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ENAME,ACTIVE) VALUES ('CSRC','7210',N'租金收入','Rental income',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ENAME,ACTIVE) VALUES ('CSRC','7480',N'什項收入','Others',0);


--新增tcUser 公司群組權限
--有可能一對多 設關聯表
CREATE TABLE FC_USER_COMPGROUP_R (
	ID bigint NOT NULL IDENTITY,
	COMP_GROUP nvarchar(8),
	USER_ID bigint,
	CREATETIMESTAMP datetime NOT NULL
	CONSTRAINT FC_USER_COMPGROUP_R_PK PRIMARY KEY (ID),
	CONSTRAINT FC_USER_COMPGROUP_R_FK1 FOREIGN KEY (USER_ID) REFERENCES TC_USER (ID)
)
--insert script
--INSERT INTO FC_USER_COMPGROUP_R (COMP_GROUP,USER_ID,CREATETIMESTAMP) VALUES ('CSRC',23,GETDATE());
--將原tc user(無特殊群組權限) 都設公司群組權限為台泥
INSERT INTO FC_USER_COMPGROUP_R (COMP_GROUP,USER_ID,CREATETIMESTAMP) 
select 'TCC', a.tuid, GETDATE()
from (
select tu.id as tuid, ug.id from TC_USER tu
left outer join TC_USERGROUP ug on ug.USER_ID = tu.id
where 1=1 and tu.DISABLED = 'false'
and ug.id is null
) a

--report config setting
--CATEGORY enum(VALUE_ITEM, VALIDATOR_ITEM, ACCOUNT_ITEM)
--VALUE_ITEM (SHEET, START_ROW)
--VALIDATOR_ITEM (SHEET, CELL_RANGE)
--ACCOUNT_ITEM (SHEET,COL_CODE, ACC_CODE, ACC_DESC)
CREATE TABLE FC_RPT_CONFIG (
	ID bigint NOT NULL IDENTITY,
	COMP_GROUP nvarchar(8), 
	CATEGORY nvarchar(20),
	SHEET nvarchar(10),
	CELL_RANGE nvarchar(10),
	COL_CODE nvarchar(10),
	ACC_CODE nvarchar(10),
	ACC_DESC nvarchar(50),
	START_ROW int,
	CREATETIMESTAMP datetime NOT NULL
	CONSTRAINT FC_RPT_CONFIG_PK PRIMARY KEY (ID)
)

--insert script
--TCC VALUE_ITEM
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,START_ROW,CREATETIMESTAMP) VALUES ('TCC','VALUE_ITEM','D0206',11,GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,START_ROW,CREATETIMESTAMP) VALUES ('TCC','VALUE_ITEM','D0208',13,GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,START_ROW,CREATETIMESTAMP) VALUES ('TCC','VALUE_ITEM','A0102',8,GETDATE());
--CSRC VALUE_ITEM
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,START_ROW,CREATETIMESTAMP) VALUES ('CSRC','VALUE_ITEM','D0206',11,GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,START_ROW,CREATETIMESTAMP) VALUES ('CSRC','VALUE_ITEM','D0208',13,GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,START_ROW,CREATETIMESTAMP) VALUES ('CSRC','VALUE_ITEM','A0102',8,GETDATE());
--TCC VALIDATOR_ITEM
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,CELL_RANGE,CREATETIMESTAMP) VALUES ('TCC','VALIDATOR_ITEM','A0102','D9:D10',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,CELL_RANGE,CREATETIMESTAMP) VALUES ('TCC','VALIDATOR_ITEM','A0102','D12:D16',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,CELL_RANGE,CREATETIMESTAMP) VALUES ('TCC','VALIDATOR_ITEM','D0206','C11:V37',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,CELL_RANGE,CREATETIMESTAMP) VALUES ('TCC','VALIDATOR_ITEM','D0208','C13:H39',GETDATE());
--CSRC VALIDATOR_ITEM
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,CELL_RANGE,CREATETIMESTAMP) VALUES ('CSRC','VALIDATOR_ITEM','A0102','D9:D10',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,CELL_RANGE,CREATETIMESTAMP) VALUES ('CSRC','VALIDATOR_ITEM','A0102','D12:D13',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,CELL_RANGE,CREATETIMESTAMP) VALUES ('CSRC','VALIDATOR_ITEM','D0206','C11:O20',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,CELL_RANGE,CREATETIMESTAMP) VALUES ('CSRC','VALIDATOR_ITEM','D0208','C13:H22',GETDATE());
--CSRC_BVI VALIDATOR_ITEM
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,CELL_RANGE,CREATETIMESTAMP) VALUES ('CSRC_BVI','VALIDATOR_ITEM','A0102','D9:D10',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,CELL_RANGE,CREATETIMESTAMP) VALUES ('CSRC_BVI','VALIDATOR_ITEM','A0102','D12:D13',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,CELL_RANGE,CREATETIMESTAMP) VALUES ('CSRC_BVI','VALIDATOR_ITEM','D0206','C11:O14',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,CELL_RANGE,CREATETIMESTAMP) VALUES ('CSRC_BVI','VALIDATOR_ITEM','D0208','C13:H16',GETDATE());
--TCC ACCOUNT_ITEM
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('TCC','ACCOUNT_ITEM','D0206','C','4111','銷貨(水泥熟料)',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('TCC','ACCOUNT_ITEM','D0206','E','4114','銷貨(電力)',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('TCC','ACCOUNT_ITEM','D0206','G','4115','銷貨(化工)',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('TCC','ACCOUNT_ITEM','D0206','I','4116','銷貨(礦源)',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('TCC','ACCOUNT_ITEM','D0206','K','4117','銷貨(電子陶瓷)',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('TCC','ACCOUNT_ITEM','D0206','M','4119','銷貨(其他)',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('TCC','ACCOUNT_ITEM','D0206','O','4300','租賃建設業',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('TCC','ACCOUNT_ITEM','D0206','P','4500','營建業',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('TCC','ACCOUNT_ITEM','D0206','Q','4600','勞務收入',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('TCC','ACCOUNT_ITEM','D0206','R','4800','其他營業',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('TCC','ACCOUNT_ITEM','D0206','T','7110','利息收入',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('TCC','ACCOUNT_ITEM','D0206','U','7210','租金收入',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('TCC','ACCOUNT_ITEM','D0206','V','7480','什項收入',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('TCC','ACCOUNT_ITEM','D0208','C','0001','進貨運輸成本運什費',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('TCC','ACCOUNT_ITEM','D0208','D','0002','其他營業成本',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('TCC','ACCOUNT_ITEM','D0208','E','0003','營業費用_租金支出',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('TCC','ACCOUNT_ITEM','D0208','F','0004','營業費用_其他',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('TCC','ACCOUNT_ITEM','D0208','G','7510','利息費用',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('TCC','ACCOUNT_ITEM','D0208','H','7880','什項支出',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('TCC','ACCOUNT_ITEM','A0102','D','','金額',GETDATE());
--CSRC ACCOUNT_ITEM
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('CSRC','ACCOUNT_ITEM','D0206','C','4111','銷貨(碳煙)',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('CSRC','ACCOUNT_ITEM','D0206','E','4112','銷貨(生技)',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('CSRC','ACCOUNT_ITEM','D0206','G','4113','銷貨(電子)',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('CSRC','ACCOUNT_ITEM','D0206','I','4114','銷貨(其他)',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('CSRC','ACCOUNT_ITEM','D0206','K','4800','其他營業',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('CSRC','ACCOUNT_ITEM','D0206','M','7110','利息收入',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('CSRC','ACCOUNT_ITEM','D0206','N','7210','租金收入',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('CSRC','ACCOUNT_ITEM','D0206','O','7480','什項收入',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('CSRC','ACCOUNT_ITEM','D0208','C','0001','進貨運輸成本運什費',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('CSRC','ACCOUNT_ITEM','D0208','D','0002','其他營業成本',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('CSRC','ACCOUNT_ITEM','D0208','E','0003','營業費用_租金支出',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('CSRC','ACCOUNT_ITEM','D0208','F','0004','營業費用_其他',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('CSRC','ACCOUNT_ITEM','D0208','G','7510','利息費用',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('CSRC','ACCOUNT_ITEM','D0208','H','7880','什項支出',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('CSRC','ACCOUNT_ITEM','A0102','D','','金額',GETDATE());


--非合併營收的公司
update FC_COMPANY set COMBINE_INCOME = 'false' where code='7A00';
update FC_COMPANY set COMBINE_INCOME = 'false' where code='7B00';


--20151125
--公司群組建立主檔
CREATE TABLE FC_COMP_GROUP (
	ID bigint NOT NULL IDENTITY,
	CODE nvarchar(8), 
	NAME nvarchar(20),
	CURRENCY bigint
	CONSTRAINT FC_COMP_GROUP_PK PRIMARY KEY (ID),
	CONSTRAINT FC_COMP_GROUP_FK1 FOREIGN KEY (CURRENCY) REFERENCES FC_CURRENCY (ID)
)
INSERT INTO FC_COMP_GROUP (CODE,NAME,CURRENCY) VALUES ('TCC',N'台泥',1);
INSERT INTO FC_COMP_GROUP (CODE,NAME,CURRENCY) VALUES ('CSRC',N'中橡',1);
INSERT INTO FC_COMP_GROUP (CODE,NAME,CURRENCY) VALUES ('CSRC_BVI','CSRC (BVI)',2);
update FC_COMP_GROUP set NAME = N'台泥' where id =1;
update FC_COMP_GROUP set NAME = N'中橡' where id =2;

--增加 轉換目標幣別
ALTER TABLE FC_MONTHLY_EXCHANGE_RATE ADD TO_CURRENCY bigint;

update FC_MONTHLY_EXCHANGE_RATE set TO_CURRENCY = 1 where 1=1;
--ALTER TABLE FC_MONTHLY_EXCHANGE_RATE ADD TO_CURRENCY bigint NOT NULL,;
--刪掉舊的UK
ALTER TABLE FC_MONTHLY_EXCHANGE_RATE DROP CONSTRAINT FC_MONTHLY_EXCHANGE_RATE_UK1;
--加的FK
ALTER TABLE FC_MONTHLY_EXCHANGE_RATE ADD FOREIGN KEY (TO_CURRENCY) REFERENCES FC_CURRENCY(ID);



--TCC ACCOUNT_ITEM 增加英文敘述 中文亂碼 修正
ALTER TABLE FC_RPT_CONFIG ADD ACC_EDESC nvarchar(50);
--update FC_RPT_CONFIG set ACC_CODE = '4111' where CATEGORY='ACCOUNT_ITEM' AND COMP_GROUP='TCC' AND SHEET='D0206' AND COL_CODE='C';

--TCC
--D0206
update FC_RPT_CONFIG set ACC_DESC = N'銷貨(水泥熟料)' where CATEGORY='ACCOUNT_ITEM' AND COMP_GROUP='TCC' AND SHEET='D0206' AND ACC_CODE='4111';
update FC_RPT_CONFIG set ACC_DESC = N'銷貨(電力)' where CATEGORY='ACCOUNT_ITEM' AND COMP_GROUP='TCC' AND SHEET='D0206' AND ACC_CODE='4114';
update FC_RPT_CONFIG set ACC_DESC = N'銷貨(化工)' where CATEGORY='ACCOUNT_ITEM' AND COMP_GROUP='TCC' AND SHEET='D0206' AND ACC_CODE='4115';
update FC_RPT_CONFIG set ACC_DESC = N'銷貨(礦源)' where CATEGORY='ACCOUNT_ITEM' AND COMP_GROUP='TCC' AND SHEET='D0206' AND ACC_CODE='4116';
update FC_RPT_CONFIG set ACC_DESC = N'銷貨(電子陶瓷)' where CATEGORY='ACCOUNT_ITEM' AND COMP_GROUP='TCC' AND SHEET='D0206' AND ACC_CODE='4117';
update FC_RPT_CONFIG set ACC_DESC = N'銷貨(其他)' where CATEGORY='ACCOUNT_ITEM' AND COMP_GROUP='TCC' AND SHEET='D0206' AND ACC_CODE='4119';
update FC_RPT_CONFIG set ACC_DESC = N'租賃建設業' where CATEGORY='ACCOUNT_ITEM' AND COMP_GROUP='TCC' AND SHEET='D0206' AND ACC_CODE='4300';
update FC_RPT_CONFIG set ACC_DESC = N'營建業' where CATEGORY='ACCOUNT_ITEM' AND COMP_GROUP='TCC' AND SHEET='D0206' AND ACC_CODE='4500';
update FC_RPT_CONFIG set ACC_DESC = N'勞務收入' where CATEGORY='ACCOUNT_ITEM' AND COMP_GROUP='TCC' AND SHEET='D0206' AND ACC_CODE='4600';
update FC_RPT_CONFIG set ACC_DESC = N'其他營業' where CATEGORY='ACCOUNT_ITEM' AND COMP_GROUP='TCC' AND SHEET='D0206' AND ACC_CODE='4800';
update FC_RPT_CONFIG set ACC_DESC = N'利息收入' where CATEGORY='ACCOUNT_ITEM' AND COMP_GROUP='TCC' AND SHEET='D0206' AND ACC_CODE='7110';
update FC_RPT_CONFIG set ACC_DESC = N'租金收入' where CATEGORY='ACCOUNT_ITEM' AND COMP_GROUP='TCC' AND SHEET='D0206' AND ACC_CODE='7210';
update FC_RPT_CONFIG set ACC_DESC = N'什項收入' where CATEGORY='ACCOUNT_ITEM' AND COMP_GROUP='TCC' AND SHEET='D0206' AND ACC_CODE='7480';
--D0208
update FC_RPT_CONFIG set ACC_DESC = N'進貨運輸成本運什費' where CATEGORY='ACCOUNT_ITEM' AND COMP_GROUP='TCC' AND SHEET='D0208' AND ACC_CODE='0001';
update FC_RPT_CONFIG set ACC_DESC = N'其他營業成本' where CATEGORY='ACCOUNT_ITEM' AND COMP_GROUP='TCC' AND SHEET='D0208' AND ACC_CODE='0002';
update FC_RPT_CONFIG set ACC_DESC = N'營業費用_租金支出' where CATEGORY='ACCOUNT_ITEM' AND COMP_GROUP='TCC' AND SHEET='D0208' AND ACC_CODE='0003';
update FC_RPT_CONFIG set ACC_DESC = N'營業費用_其他' where CATEGORY='ACCOUNT_ITEM' AND COMP_GROUP='TCC' AND SHEET='D0208' AND ACC_CODE='0004';
update FC_RPT_CONFIG set ACC_DESC = N'利息費用' where CATEGORY='ACCOUNT_ITEM' AND COMP_GROUP='TCC' AND SHEET='D0208' AND ACC_CODE='7510';
update FC_RPT_CONFIG set ACC_DESC = N'什項支出' where CATEGORY='ACCOUNT_ITEM' AND COMP_GROUP='TCC' AND SHEET='D0208' AND ACC_CODE='7880';
--A0102
update FC_RPT_CONFIG set ACC_DESC = N'金額' where CATEGORY='ACCOUNT_ITEM' AND COMP_GROUP='TCC' AND SHEET='A0102' AND COL_CODE='D';
--CSRC
--D0206
update FC_RPT_CONFIG set ACC_DESC = N'銷貨(碳煙)',ACC_EDESC='Sales - Carbon Black' where CATEGORY='ACCOUNT_ITEM' AND COMP_GROUP='CSRC' AND SHEET='D0206' AND ACC_CODE='4111';
update FC_RPT_CONFIG set ACC_DESC = N'銷貨(生技)',ACC_EDESC='Sales - Biotechnology' where CATEGORY='ACCOUNT_ITEM' AND COMP_GROUP='CSRC' AND SHEET='D0206' AND ACC_CODE='4112';
update FC_RPT_CONFIG set ACC_DESC = N'銷貨(電子)',ACC_EDESC='Sales - Electronic Product' where CATEGORY='ACCOUNT_ITEM' AND COMP_GROUP='CSRC' AND SHEET='D0206' AND ACC_CODE='4113';
update FC_RPT_CONFIG set ACC_DESC = N'銷貨(其他)',ACC_EDESC='Sales - Other' where CATEGORY='ACCOUNT_ITEM' AND COMP_GROUP='CSRC' AND SHEET='D0206' AND ACC_CODE='4114';
update FC_RPT_CONFIG set ACC_DESC = N'其他營業',ACC_EDESC='Other operating revenue' where CATEGORY='ACCOUNT_ITEM' AND COMP_GROUP='CSRC' AND SHEET='D0206' AND ACC_CODE='4800';
update FC_RPT_CONFIG set ACC_DESC = N'利息收入',ACC_EDESC='Interest income' where CATEGORY='ACCOUNT_ITEM' AND COMP_GROUP='CSRC' AND SHEET='D0206' AND ACC_CODE='7110';
update FC_RPT_CONFIG set ACC_DESC = N'租金收入',ACC_EDESC='Rental income' where CATEGORY='ACCOUNT_ITEM' AND COMP_GROUP='CSRC' AND SHEET='D0206' AND ACC_CODE='7210';
update FC_RPT_CONFIG set ACC_DESC = N'什項收入',ACC_EDESC='Others' where CATEGORY='ACCOUNT_ITEM' AND COMP_GROUP='CSRC' AND SHEET='D0206' AND ACC_CODE='7480';
--D0208
update FC_RPT_CONFIG set ACC_DESC = N'進貨運輸成本運什費',ACC_EDESC='freightIn、freightIn-freight、other Operating costs' where CATEGORY='ACCOUNT_ITEM' AND COMP_GROUP='CSRC' AND SHEET='D0208' AND ACC_CODE='0001';
update FC_RPT_CONFIG set ACC_DESC = N'其他營業成本',ACC_EDESC='Other Operating costs' where CATEGORY='ACCOUNT_ITEM' AND COMP_GROUP='CSRC' AND SHEET='D0208' AND ACC_CODE='0002';
update FC_RPT_CONFIG set ACC_DESC = N'營業費用_租金支出',ACC_EDESC='Operating expenses-Rent expense' where CATEGORY='ACCOUNT_ITEM' AND COMP_GROUP='CSRC' AND SHEET='D0208' AND ACC_CODE='0003';
update FC_RPT_CONFIG set ACC_DESC = N'營業費用_其他',ACC_EDESC='Operating expenses-other(Note)' where CATEGORY='ACCOUNT_ITEM' AND COMP_GROUP='CSRC' AND SHEET='D0208' AND ACC_CODE='0004';
update FC_RPT_CONFIG set ACC_DESC = N'利息費用',ACC_EDESC='Interest expense' where CATEGORY='ACCOUNT_ITEM' AND COMP_GROUP='CSRC' AND SHEET='D0208' AND ACC_CODE='7510';
update FC_RPT_CONFIG set ACC_DESC = N'什項支出',ACC_EDESC='Other expenses' where CATEGORY='ACCOUNT_ITEM' AND COMP_GROUP='CSRC' AND SHEET='D0208' AND ACC_CODE='7880';
--A0102
update FC_RPT_CONFIG set ACC_DESC = N'金額' where CATEGORY='ACCOUNT_ITEM' AND COMP_GROUP='CSRC' AND SHEET='A0102' AND COL_CODE='D';



--中橡增加會科  沖銷股東權益
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ENAME,ACTIVE) VALUES ('CSRC','3220',N'資本公積-庫藏股票交易','Capital surplus, treasury share transactions',0);
--INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('CSRC','ACCOUNT_ITEM','D0208','I','3220',N'資本公積-庫藏股票交易',GETDATE());
--update FC_RPT_CONFIG set ACC_EDESC = 'Capital surplus, treasury share transactions' where CATEGORY='VALIDATOR_ITEM' AND COMP_GROUP='CSRC' AND SHEET='D0208' AND COL_CODE = 'I';
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,ACC_EDESC,CREATETIMESTAMP) VALUES ('CSRC','ACCOUNT_ITEM','D0208','I','3220',N'資本公積-庫藏股票交易','Capital surplus, treasury share transactions',GETDATE());
update FC_RPT_CONFIG set CELL_RANGE = 'C13:I22' where CATEGORY='VALIDATOR_ITEM' AND COMP_GROUP='CSRC' AND SHEET='D0208';
update FC_RPT_CONFIG set CELL_RANGE = 'C13:I16' where CATEGORY='VALIDATOR_ITEM' AND COMP_GROUP='CSRC_BVI' AND SHEET='D0208';

--調整中橡 A0102損益表 檢查欄位
update FC_RPT_CONFIG set CELL_RANGE = 'D9:D13' 
where COMP_GROUP in ('CSRC', 'CSRC_BVI') and CATEGORY = 'VALIDATOR_ITEM' 
and SHEET = 'A0102' and CELL_RANGE = 'D9:D10';
update FC_RPT_CONFIG set CELL_RANGE = 'D15:D16' 
where COMP_GROUP in ('CSRC', 'CSRC_BVI') and CATEGORY = 'VALIDATOR_ITEM' 
and SHEET = 'A0102' and CELL_RANGE = 'D12:D13';

--------------------------------------------------------------------------
--CSRC_BVI歷史資料(201409~201509) 台幣轉美金
--201509 31.444
--201508 31.298
--201507 31.175
--201506 31.179 
--201505 31.235 
--201504 31.396 
--201503 31.523 
--201502 31.558
--201501 31.63
--201412 30.306
--201411 30.206
--201410 30.155
--201409 30.128
--D0206 D0208
--update FC_REPORT_VALUE set amount = amount/31.444, amount_xls = amount_xls*32
--update FC_REPORT_VALUE set amount = amount/31.444
select amount, amount_xls, amount/31.444, amount_xls from FC_REPORT_VALUE
where id in (
select v.id from FC_REPORT_VALUE v
join FC_REPORT_UPLOAD u on u.id = v.REPORT_ID
join FC_COMPANY c on c.id = u.COMPANY
where 1=1
and c.COMP_GROUP = 'CSRC_BVI'
and u.YEARMONTH = '201509'
);
--A0102
--update FC_REPORT_A0102 set amount = amount/31.444
select amount, amount_xls, amount/31.444, amount_xls*32 from FC_REPORT_A0102
where id in (
select a.id from FC_REPORT_A0102 a
join FC_REPORT_UPLOAD u on u.id = a.REPORT_ID
join FC_COMPANY c on c.id = u.COMPANY
where 1=1
and c.COMP_GROUP = 'CSRC_BVI'
and u.YEARMONTH = '201509'
);

--update FC_REPORT_VALUE set amount = amount/30.128
select amount, amount_xls from FC_REPORT_VALUE
where id in (
select v.id from FC_REPORT_VALUE v
join FC_REPORT_UPLOAD u on u.id = v.REPORT_ID
join FC_COMPANY c on c.id = u.COMPANY
where 1=1
and c.COMP_GROUP = 'CSRC_BVI'
and u.YEARMONTH = '201409'
);

--update FC_REPORT_A0102 set amount = amount/30.128
select amount, amount_xls from FC_REPORT_A0102
where id in (
select a.id from FC_REPORT_A0102 a
join FC_REPORT_UPLOAD u on u.id = a.REPORT_ID
join FC_COMPANY c on c.id = u.COMPANY
where 1=1
and c.COMP_GROUP = 'CSRC_BVI'
and u.YEARMONTH = '201409'
);
-----------------------------------------------------------

--update FC_RPT_CONFIG CSRC_BVI A0102
--DELETE FC_RPT_CONFIG where CATEGORY='VALIDATOR_ITEM' AND COMP_GROUP='CSRC_BVI' AND SHEET='A0102' AND ID= 16;
--調整回來 中橡BVI A0102損益表 檢查欄位
update FC_RPT_CONFIG set CELL_RANGE = 'D9:D10' 
where COMP_GROUP = 'CSRC' and CATEGORY = 'VALIDATOR_ITEM' 
and SHEET = 'A0102' and CELL_RANGE = 'D9:D13';
update FC_RPT_CONFIG set CELL_RANGE = 'D12:D13' 
where COMP_GROUP = 'CSRC' and CATEGORY = 'VALIDATOR_ITEM' 
and SHEET = 'A0102' and CELL_RANGE = 'D15:D16';

SET IDENTITY_INSERT FC_RPT_CONFIG ON;
SET IDENTITY_INSERT FC_RPT_CONFIG OFF;
INSERT INTO FC_RPT_CONFIG (ID,COMP_GROUP,CATEGORY,SHEET,CELL_RANGE,CREATETIMESTAMP) VALUES (16'CSRC_BVI','VALIDATOR_ITEM','A0102','D12:D13',GETDATE());

--20160115
--原BVI下四家 14家併為一層
--update FC_RPT_CONFIG
update FC_RPT_CONFIG set CELL_RANGE = 'C11:O23' 
where COMP_GROUP = 'CSRC' and CATEGORY = 'VALIDATOR_ITEM' 
and SHEET = 'D0206' and CELL_RANGE = 'C11:O20';
update FC_RPT_CONFIG set CELL_RANGE = 'C13:I25' 
where COMP_GROUP = 'CSRC' and CATEGORY = 'VALIDATOR_ITEM' 
and SHEET = 'D0208' and CELL_RANGE = 'C13:I22';

--歷史資料改回台幣值 (201411~201511)
--update FC_REPORT_VALUE set AMOUNT = AMOUNT_XLS 
select * from FC_REPORT_VALUE
where id in (select v.id from FC_REPORT_VALUE v
join FC_REPORT_UPLOAD u on v.REPORT_ID= u.id
join FC_COMPANY c on c.id = u.COMPANY
where 1=1
and u.YEARMONTH = '201501'
--and u.YEARMONTH in ('201411','201412','201501','201502','201503','201504','201505','201506'
-- ,'201507','201508','201509')
and c.code in ('8100','8200','8300','8600')
);
--update FC_REPORT_A0102 set AMOUNT = AMOUNT_XLS 
select * from FC_REPORT_A0102
where id in (select v.id from FC_REPORT_A0102 v
join FC_REPORT_UPLOAD u on v.REPORT_ID= u.id
join FC_COMPANY c on c.id = u.COMPANY
where 1=1
and u.YEARMONTH = '201511'
--and u.YEARMONTH in ('201411','201412','201501','201502','201503','201504','201505','201506'
-- ,'201507','201508','201509')
and c.code in ('8100','8200','8300','8600')
);

--刪除201510 細項
select * from FC_REPORT_A0102 v
join FC_REPORT_UPLOAD u on v.REPORT_ID= u.id
join FC_COMPANY c on c.id = u.COMPANY
where 1=1
and u.YEARMONTH = '201510'
and c.code in ('8100','8200','8300','8600')
;
--4111
update Fc_Report_VALUE set AMOUNT = 94069071,AMOUNT_XLS = 94069071 where id = 3964;--8100
update Fc_Report_VALUE set AMOUNT = 1453501,AMOUNT_XLS = 1453501 where id = 3966;--8200
update Fc_Report_VALUE set AMOUNT = 147665567,AMOUNT_XLS = 147665567 where id = 3968;--8600
delete Fc_Report_VALUE where id in (3963,3965,3967);
--4100
update FC_REPORT_A0102 set AMOUNT = 1243844319 where id = 3371;--8100
update FC_REPORT_A0102 set AMOUNT = 647919149 where id = 3372;--8200
update FC_REPORT_A0102 set AMOUNT = 1609165022 where id = 3374;--8300
update FC_REPORT_A0102 set AMOUNT = 256542413 where id = 3373;--8600

--寫入201511
select * from FC_REPORT_UPLOAD u
join FC_COMPANY c on c.id = u.COMPANY
where 1=1
and c.code in ('8100','8200','8300','8600')
and u.YEARMONTH = '201511'
;
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201511',40,1,GETDATE());--8100
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201511',41,1,GETDATE());--8200
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201511',42,1,GETDATE());--8600
INSERT INTO FC_REPORT_UPLOAD (YEARMONTH,COMPANY,UPLOADER,MODIFYTIMESTAMP) VALUES ('201511',43,1,GETDATE());--8300
1010
1011
1012
1013
Insert into FC_REPORT_VALUE (REPORT_ID,SHEET,COID2,CODE,AMOUNT,AMOUNT_ORIG,MODIFIER,MODIFYTIMESTAMP,AMOUNT_XLS) 
values (1010,'D0206',43,'4111',113974448.000,113974448.000,19,CONVERT(datetime,'2016-01-15 13:44:43.153'),null);
Insert into FC_REPORT_VALUE (REPORT_ID,SHEET,COID2,CODE,AMOUNT,AMOUNT_ORIG,MODIFIER,MODIFYTIMESTAMP,AMOUNT_XLS) 
values (1011,'D0206',43,'4111',2409880.000,2409880.000,19,CONVERT(datetime,'2016-01-15 13:44:43.153'),null);
Insert into FC_REPORT_VALUE (REPORT_ID,SHEET,COID2,CODE,AMOUNT,AMOUNT_ORIG,MODIFIER,MODIFYTIMESTAMP,AMOUNT_XLS) 
values (1012,'D0206',43,'4111',149406295.000,149406295.000,19,CONVERT(datetime,'2016-01-15 13:44:43.153'),null);

Insert into FC_REPORT_A0102 (REPORT_ID,CODE,AMOUNT,AMOUNT_XLS,MODIFIER,MODIFYTIMESTAMP) 
values (1010,4110,1352350019,1352350019,1,GETDATE());
Insert into FC_REPORT_A0102 (REPORT_ID,CODE,AMOUNT,AMOUNT_XLS,MODIFIER,MODIFYTIMESTAMP) 
values (1011,4110,707366454,707366454,1,GETDATE());
Insert into FC_REPORT_A0102 (REPORT_ID,CODE,AMOUNT,AMOUNT_XLS,MODIFIER,MODIFYTIMESTAMP) 
values (1012,4110,273033264,273033264,1,GETDATE());
Insert into FC_REPORT_A0102 (REPORT_ID,CODE,AMOUNT,AMOUNT_XLS,MODIFIER,MODIFYTIMESTAMP) 
values (1013,4110,1716644864,1716644864,1,GETDATE());

--201510損益金額更正
update FC_REPORT_A0102 set AMOUNT = 1243844319 where REPORT_ID = 924;--8100
update FC_REPORT_A0102 set AMOUNT = 647919149 where REPORT_ID = 925;--8200
update FC_REPORT_A0102 set AMOUNT = 1609165022 where REPORT_ID = 926;--8300
update FC_REPORT_A0102 set AMOUNT = 256542413 where REPORT_ID = 927;--8600


--增加公司群組其他 OTHER
INSERT INTO FC_COMP_GROUP (CODE,NAME,CURRENCY) VALUES ('OTHER',N'其他',1);


--再次調整 中橡 A0102損益表 檢查欄位
update FC_RPT_CONFIG set CELL_RANGE = 'D9:D14' 
where COMP_GROUP = 'CSRC' and CATEGORY = 'VALIDATOR_ITEM' 
and SHEET = 'A0102' and CELL_RANGE = 'D9:D10';
update FC_RPT_CONFIG set CELL_RANGE = 'D16:D17' 
where COMP_GROUP = 'CSRC' and CATEGORY = 'VALIDATOR_ITEM' 
and SHEET = 'A0102' and CELL_RANGE = 'D12:D13';

--調整 201512金額
select * from FC_REPORT_UPLOAD u
join FC_COMPANY c on c.id = u.COMPANY
where 1=1
and c.code in ('8100','8200','8300','8600')
and u.YEARMONTH = '201512'
;--1015 1016 1018 1017

--歷史資料改回報表值 (201512)
--8100馬鞍山 D0206 4111 三個對象公司沖銷
update FC_REPORT_VALUE set AMOUNT = 124891984 where id = 4344;
update FC_REPORT_VALUE set AMOUNT = 0 where id = 4347;
update FC_REPORT_VALUE set AMOUNT = 0 where id = 4350;
--A0102
update FC_REPORT_A0102 set AMOUNT = 1447347340
--select * from FC_REPORT_A0102
where id in (select v.id from FC_REPORT_A0102 v
join FC_REPORT_UPLOAD u on v.REPORT_ID= u.id
join FC_COMPANY c on c.id = u.COMPANY
where 1=1
and u.id = 1015
);
--8200鞍山 D0206 4111 三個對象公司沖銷
update FC_REPORT_VALUE set AMOUNT = 21134812 where id = 4353;
update FC_REPORT_VALUE set AMOUNT = 0 where id = 4354;
update FC_REPORT_VALUE set AMOUNT = 0 where id = 4356;
--A0102
update FC_REPORT_A0102 set AMOUNT = 776192036
--select * from FC_REPORT_A0102
where id in (select v.id from FC_REPORT_A0102 v
join FC_REPORT_UPLOAD u on v.REPORT_ID= u.id
join FC_COMPANY c on c.id = u.COMPANY
where 1=1
and u.id = 1016
);
--8600重慶 D0206 4111 1個對象公司沖銷
update FC_REPORT_VALUE set AMOUNT = 154995397 where id = 4359;
--A0102
update FC_REPORT_A0102 set AMOUNT = 296815149
--select * from FC_REPORT_A0102
where id in (select v.id from FC_REPORT_A0102 v
join FC_REPORT_UPLOAD u on v.REPORT_ID= u.id
join FC_COMPANY c on c.id = u.COMPANY
where 1=1
and u.id = 1018
);
--8300CCIL D0206 4111 0個對象公司沖銷
--A0102
update FC_REPORT_A0102 set AMOUNT = 1820992767
--select * from FC_REPORT_A0102
where id in (select v.id from FC_REPORT_A0102 v
join FC_REPORT_UPLOAD u on v.REPORT_ID= u.id
join FC_COMPANY c on c.id = u.COMPANY
where 1=1
and u.id = 1017
);
