-- 使用者
INSERT INTO TC_USER (LOGIN_ACCOUNT,CNAME,DISABLED,CREATOR,CREATETIMESTAMP) VALUES ('chii',N'宮起',0,1,GETDATE());

-- 群組
UPDATE TC_GROUP SET NAME='系統管理員' WHERE ID=1;
INSERT INTO TC_GROUP (CODE,NAME,CREATOR,CREATETIMESTAMP) values ('switch-user','切換使用者', 1, GETDATE());
INSERT INTO TC_GROUP (CODE,NAME,CREATOR,CREATETIMESTAMP) values ('FINANCIAL_HQ','總處財務', 1, GETDATE());

-- 檔案上傳路徑
-- 測試機: D:\FileVault\fcs\
-- QA機:   /opt/FileUpload/fcs/
-- 正式機: /opt/FileUpload/fcs/
UPDATE TC_FVVAULT SET LOCATION='D:\FileVault\fcs\'; 
-- '

-- 公司
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE) VALUES ('1000','台灣水泥股份有限公司', 1);
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE) VALUES ('1100','達和大豐環保(股)公司', 1);
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE) VALUES ('1200','鳳勝實業股份有限公司', 1);
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE) VALUES ('1300','光和耐火工業股份有限公司', 1);
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE) VALUES ('1400','光和建設開發(股)公司', 1);
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE) VALUES ('1500','台泥化學工業股份有限公司', 1);
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE) VALUES ('1600','信昌化學工業股份有限公司', 1);
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE) VALUES ('1700','和平電力股份有限公司', 1);
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE) VALUES ('1800','萬青水泥股份有限公司', 1);
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE) VALUES ('1900','和平工業區專用港實業股份有限公司', 1);
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE) VALUES ('1A00','信昌投資股份有限公司', 1);
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE) VALUES ('1C00','英屬維京群島商和平企業經營管理顧問股份有限公司', 1);
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE) VALUES ('1D00','金昌石礦股份有限公司', 1);
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE) VALUES ('1E00','東成石礦股份有限公司', 1);
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE) VALUES ('1F00','Trans Philipines Mineral Corp.', 1);
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE) VALUES ('1H00','和順建材股份有限公司', 1);
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE) VALUES ('2B00','TCC International Ltd', 1);
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE) VALUES ('2W00','Hong Kong Cement Mfg. Company Ltd', 1);
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE) VALUES ('5100','達和彰北環保(股)公司', 1);
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE) VALUES ('5200','台灣通運倉儲股份有限公司', 1);
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE) VALUES ('5300','達和航運股份有限公司', 1);
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE) VALUES ('5400','台灣士敏工程企業(股)公司', 1);
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE) VALUES ('5500','台泥資訊(股)公司', 1);
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE) VALUES ('5E00','達榮環保股份有限公司', 1);
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE) VALUES ('5F00','TAICORN MINERALS CORP.', 1);
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE) VALUES ('7700','東宇興業股份有限公司', 1);
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE) VALUES ('7800','合盛礦業股份有限公司', 1);
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE) VALUES ('7A00','合一生技公司', 0);
INSERT INTO FC_COMPANY (CODE,NAME,ACTIVE) VALUES ('7B00','合裕管顧公司', 0);
