-- TABLE: MY_SERVICE
CREATE TABLE MY_SERVICE 
(
	ID NUMBER(18,0) NOT NULL ENABLE, 
	SERVICE VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	SERVICE_URL VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(500 CHAR), 
	ACTIVE NUMBER(1,0) NOT NULL ENABLE, 
	CONSTRAINT MY_SERVICE_PK PRIMARY KEY (ID) ENABLE,
	CONSTRAINT MY_SERVICE_UK1 UNIQUE (SERVICE) ENABLE
);
COMMENT ON COLUMN MY_SERVICE.ID IS 'PK';
COMMENT ON COLUMN MY_SERVICE.SERVICE IS '服務, ex: /dashboard/service/swlsService/';
COMMENT ON COLUMN MY_SERVICE.SERVICE_URL IS '服務網址, ex: http://192.168.203.81/dashboard/service/swlsService/';
COMMENT ON COLUMN MY_SERVICE.DESCRIPTION IS '服務說明';
COMMENT ON COLUMN MY_SERVICE.ACTIVE IS '1:啟用, 0:停用';

-- TABLE: MY_MOBILE_APP
CREATE TABLE MY_MOBILE_APP 
(
	ID NUMBER(18,0) NOT NULL ENABLE, 
	PLATFORM VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	APP_VERSION VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	CONSTRAINT MY_MOBILE_APP_PK PRIMARY KEY (ID) ENABLE, 
	CONSTRAINT MY_MOBILE_APP_UK1 UNIQUE (PLATFORM) ENABLE
);
COMMENT ON COLUMN MY_MOBILE_APP.ID IS 'PK';
COMMENT ON COLUMN MY_MOBILE_APP.PLATFORM IS 'android/ios/windows phone';
COMMENT ON COLUMN MY_MOBILE_APP.APP_VERSION IS 'APP版本';
