--合併報表 IS本表不填 A0102_IS 相關資訊
--會計科目主檔 增加借貸方科目flag FC_ACCOUNTS
ALTER TABLE FC_ACCOUNTS ADD DC_FLAG nvarchar(1);
update FC_ACCOUNTS set DC_FLAG = 'C' where COMP_GROUP = 'TCC' 
AND CODE in ('4111', '4112', '4113', '4114', '4115', '4116', '4117', '4119'
, '4130', '4190', '4200', '4300', '4500', '4600', '4800');
update FC_ACCOUNTS set DC_FLAG = 'C' where COMP_GROUP = 'TCC' 
AND CODE in ('7110', '7210');
--會計科目主檔寫入 IS本表不填(季) 會計科目(5000~8620)
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','5000',N'營業成本',0,null);
--4XXX
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','4112',N'銷貨收入 - 水泥製品',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','4113',N'銷貨收入 - 紙張及紙袋',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','4130',N'分期付款銷貨收入',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','4130',N'分期付款銷貨收入',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','4520',N'工程收入 - 營建業',0,'C');--爭議
--5XXX
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','5100',N'銷貨成本 - 買賣及製造業',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','5111',N'銷貨成本 - 水泥及熟料',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','5112',N'銷貨成本 - 水泥製品',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','5113',N'銷貨成本 - 紙張及紙袋',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','5114',N'銷貨成本 - 電力',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','5115',N'銷貨成本 - 化工',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','5116',N'銷貨成本 - 礦源',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','5117',N'銷貨成本 - 電子陶瓷',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','5119',N'銷貨成本 - 其他',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','5200',N'投資支出 - 投資業',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','5300',N'租賃成本 - 租賃及建設業',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','5500',N'工程成本 - 營建業',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','5600',N'勞務成本 - 運輸、港務及環保等服務業',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','5800',N'其他營業成本',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','5900',N'營業毛利(毛損)',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','5910',N'與關聯企業之未實現利益',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','5920',N'與關聯企業之已實現利益',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','5950',N'已實現營業毛利(毛損)',0,null);
--6XXX
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','6000',N'營業費用',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','6100',N'推銷費用',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','6200',N'管理費用',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','6300',N'研究發展費用',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','6500',N'其他收益及費損淨額',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','6510',N'其他收益',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','6520',N'其他費損',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','6900',N'營業淨利(淨損)',0,null);
--7XXX
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','7000',N'營業外收入及利益',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','7100',N'利息收入',0,'C');
--INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','7110',N'租金收入',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','7130',N'股利收入',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','7140',N'廉價購買利益',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','7160',N'違約金收入',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','7175',N'壞帳轉回利益',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','7180',N'沖銷逾期應付款利益',0,'C');
--INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','7210',N'處分不動產、廠房及設備利益',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','7215',N'處分投資性不動產利益',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','7225',N'處分投資利益',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','7230',N'外幣兌換利益',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','7235',N'透過損益按公允價值衡量之金融資產(負債)利益',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','7270',N'減損迴轉利益',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','7370',N'採用權益法之關聯企業及合資損益之份額',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','7375',N'採用權益法之子公司損益之份額',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','7010',N'其他收入',0,'C');
--7000 爭議 7500?!
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','7510',N'利息費用',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','7520',N'負債性特別股股息',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','7630',N'外幣兌換損失',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','7050',N'財務成本',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','7540',N'停工損失',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','7610',N'處分不動產、廠房及設備損失',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','7615',N'處分投資性不動產損失',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','7620',N'處分無形資產損失',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','7625',N'處分投資損失',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','7670',N'減損損失',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','7635',N'透過損益按公允價值衡量之金融資產(負債)損失',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','7770',N'採用權益法認列之關聯企業及合資損失之份額',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','7775',N'採用權益法認列之子公司損失之份額',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','7590',N'什項支出',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','7990',N'稅前淨利(淨損)',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','7950',N'所得稅費用(利益)',0,'D');
--8XXX
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','8000',N'繼續營業部門淨利(淨損)',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','8100',N'停業部門(損)益',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','8200',N'本期淨利(淨損)',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','8620',N'非控制權益淨利',0,'D');

--會計科目主檔寫入 BS本表不填(季) 會計科目()
--11XX
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','11XX',N'流動資產',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1100',N'現金及約當現金',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1101',N'庫存現金',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1102',N'零用金／週轉金',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1103',N'銀行存款',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1105',N'在途現金',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','110701',N'商業本票',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','110702',N'銀行承兌匯票',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','110703',N'原始到期日在三個月以內之銀行定期存款',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','110704',N'附買回債券',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1108',N'分類為約當現金之銀行透支',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1110',N'透過損益按公允價值衡量之金融資產-流動',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1125',N'備供出售金融資產-流動',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','112601',N'國內上市(櫃)股票',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','112602',N'國內興櫃股票',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','112603',N'基金受益憑證',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','112604',N'債券投資-政府公債',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','112605',N'債券投資-公司債',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','112606',N'國外上市(櫃)股票',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1127',N'備供出售金融資產評價',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1129',N'累計減損-備供出售金融資產',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1130',N'持有至到期日金融資產-流動',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1135',N'避險之衍生性金融資產-流動',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1144',N'以成本衡量之金融資產-流動',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1147',N'無活絡市場之債券投資-流動',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1150',N'應收票據淨額',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1151',N'應收票據',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1152',N'其他應收票據',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1153',N'應收票據貼現',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1159',N'減：備抵呆帳-應收票據',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1160',N'應收票據-關係人淨額',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1161',N'應收票據-關係人',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1162',N'其他應收票據-關係人',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1163',N'應收票據貼現-關係人',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1169',N'減：備抵呆帳-應收關係人票據',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1170',N'應收帳款淨額',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1171',N'應收銷售及管理費(證券投資信託業適用)',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1172',N'應收帳款',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1173',N'應收分期帳款',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1174',N'未實現利息收入-應收分期帳款',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1175',N'應收租賃款',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1176',N'融資租賃之未賺得融資收益',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1177',N'減：備抵銷售退回及折讓',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1179',N'減：備抵呆帳-應收帳款',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1180',N'應收帳款-關係人淨額',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1181',N'應收帳款-關係人',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1182',N'應收分期帳款-關係人',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1183',N'未實現利息收入-應收關係人分期帳款',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1184',N'應收租賃款-關係人',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1185',N'融資租賃之未賺得融資收益-關係人',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1186',N'減：備抵呆帳-應收關係人帳款、分期帳款及租賃款',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1200',N'其他應收款項淨額',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1201',N'應收退稅款',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1202',N'未收代墊款(海陸運輸業適用)',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1203',N'應收工程保留款',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1204',N'應收歸墊款',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1205',N'應收收益',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1206',N'其他應收款-其他',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1209',N'減：備抵呆帳-其他應收款項',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1210',N'其他應收款-關係人',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1211',N'應收收益-關係人',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1212',N'其他應收款-關係人-其他',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1219',N'減：備抵呆帳-其他應收關係人款項',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1476',N'其他金融資產-流動',0,'D');
--13XX
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','13XX',N'存貨',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','130X',N'存貨 – 買賣業',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1301',N'商品存貨',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1302',N'寄銷品',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1308',N'在途商品',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1309',N'備抵存貨跌價及呆滯損失',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','131X',N'存貨 – 製造業',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1311',N'製成品',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1312',N'副產品',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1313',N'半成品',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1314',N'在製品',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1315',N'原  料',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1316',N'物  料',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1318',N'在途原物料',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1318',N'在途原物料',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1319',N'備抵存貨跌價及呆滯損失',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','132X',N'存貨 – 建設業',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1321',N'待售房地',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1322',N'待售車位',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1323',N'營建用地',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1324',N'在建房地',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1325',N'預付土地款',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1326',N'材料 – 庫存',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1328',N'在途材料',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1329',N'備抵存貨跌價損失',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','133X',N'存貨 – 其他行業',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1331',N'油料',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1332',N'物料',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1338',N'其他存貨',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1339',N'備抵存貨跌價及呆滯損失',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','135X',N'在建工程 – 營造業',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1351',N'在建材料',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1352',N'在建工料',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1353',N'在建人工',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1354',N'在建費用',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1355',N'待分攤在建費用',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1356',N'在建工程 – 利息資本化',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1357',N'在建工程 – 工程損益',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1359',N'備抵存貨跌價及呆滯損失',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','140X',N'預付款項',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1411',N'預付薪資',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1412',N'預付租金',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1413',N'船長週轉金(海陸運輸業適用)',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1414',N'預付保險費',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1415',N'用品盤存',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1416',N'預付退休金-流動',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1419',N'其他預付費用',0,'D');
--1412重複
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1460',N'待出售非流動資產',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1477',N'受限制資產',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1479',N'其他流動資產',0,'D');
--15XX
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','15XX',N'非流動資產',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1510',N'透過損益按公允價值衡量之金融資產-非流動',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1523',N'備供出售金融資產-非流動',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','152401',N'國內上市(櫃)股票',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','152402',N'國內興櫃股票',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','152403',N'基金受益憑證',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','152404',N'債券投資-政府公債',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','152405',N'債券投資-公司債',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','152406',N'國外上市(櫃)股票',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1525',N'備供出售金融資產評價',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1526',N'累計減損-備供出售金融資產',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1527',N'持有至到期日金融資產-非流動',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1530',N'避險之衍生性金融資產-非流動',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1543',N'以成本衡量之金融資產-非流動',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1546',N'無活絡市場之債券投資-非流動',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1550',N'採權益法之長期投資',0,'D');
--16XX
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','16XX',N'不動產、廠房及設備',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1602',N'成本-土地',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1611',N'成本-房屋及建築',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1616',N'成本-機器設備',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1671',N'成本-運輸設備',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1691',N'成本-辦公設備',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1716',N'成本-租賃資產(營業用)',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1736',N'成本-其他設備',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1603',N'重估增值-土地',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1607',N'重估增值-土地改良物',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1612',N'重估增值-房屋及建築',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1617',N'重估增值-機器設備',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1672',N'重估增值-運輸設備',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1692',N'重估增值-辦公設備',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1737',N'重估增值-其他設備',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1613',N'累計折舊 – 房屋及建築',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1618',N'累計折舊 – 機器設備',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1673',N'累計折舊 – 運輸設備',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1693',N'累計折舊 – 辦公設備',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1718',N'累計折舊 – 租賃資產(營業用)',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1738',N'累計折舊 – 其他設備',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1604',N'累計減損 –土地',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1614',N'累計減損 –房屋及建築',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1619',N'累計減損 –機器設備',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1674',N'累計減損 –運輸設備',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1694',N'累計減損 –辦公設備',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1719',N'累計減損 –租賃資產(營業用)',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1739',N'累計減損 –其他設備',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1740',N'未完工程',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1760',N'投資性不動產',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1761',N'成本-土地',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1765',N'成本-房屋及建築',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1768',N'累計減損 –其他設備',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1764',N'累計減損 –土地',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1769',N'累計減損 –房屋及建築',0,'C');
--17XX
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','17XX',N'無形資產',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1782',N'成本-商標權',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1786',N'成本-專利權',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1792',N'成本-特許權',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1805',N'成本-商    譽',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1751',N'成本-採礦權',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1825',N'電腦軟件',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1822',N'成本-其他無形資產',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1783',N'累計攤銷-商標權',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1787',N'累計攤銷-專利權',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1793',N'累計攤銷-特許權',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1753',N'累計攤銷-採礦權',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1826',N'電腦軟件',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1823',N'累計攤銷-其他無形資產',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1784',N'累計減損 –商標權',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1788',N'累計減損 –專利權',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1794',N'累計減損 –特許權',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1805-1',N'累計減損 –商    譽',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1754',N'累計減損 –採礦權',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1827',N'累計減損 –電腦軟件',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1824',N'累計減損 –其他無形資產',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1840',N'遞延所得稅資產 - 非流動',0,'D');
--19XX
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','19XX',N'其他非流動資產',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1915',N'預付設備款',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1920',N'存出保證金(品)',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1930',N'長期應收票據及款項',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1935',N'長期應收租賃款',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1940',N'長期應收票據及款項 – 關係人',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1950',N'基　金',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1960',N'預付投資款',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1970',N'其他長期投資',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1975',N'預付退休金 - 非流動',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1985',N'長期預付租賃款(LUR)',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1980',N'其他金融資產－非流動',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1990',N'其他非流動資產',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1991',N'遞延借項-聯屬公司間損失',0,'D');
--21XX
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','21XX',N'流動負債',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2100',N'短期借款',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2110',N'應付短期票券',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2120',N'透過損益按公允價值衡量之金融負債－流動',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2125',N'避險之衍生性金融負債-流動',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2150',N'應付票據',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2160',N'應付票據-關係人',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2170',N'應付帳款',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2180',N'應付帳款-關係人',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2200',N'其他應付款',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2220',N'其他應付款項-關係人',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2230',N'當期所得稅負債',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2251',N'員工福利負債準備-流動',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2256',N'除役、復原及修復成本之短期負債準備',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2259',N'其他短期負債準備',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2260',N'待出售非流動資產直接相關之負債',0,'C');
--23XX
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','23XX',N'其他流動負債',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2305',N'其他金融負債-流動',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2310',N'預收款項',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2321',N'一年或一營業週期內到期或執行賣回權公司債',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2322',N'一年或一營業週期內到期長期借款',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2323',N'一年或一營業週期內到期長期應付票據及款項-非關係人',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2324',N'一年或一營業週期內到期長期應付票據及款項-關係人',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2325',N'特別股負債-流動',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2355',N'應付租賃款－流動',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2399',N'其他流動負債-其他',0,'C');
--25XX
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','25XX',N'非流動負債',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2500',N'透過損益按公允價值衡量之金融負債-非流動',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2510',N'避險之衍生性金融負債-非流動',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2525',N'以成本衡量之金融負債-非流動',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2530',N'應付公司債 - 已減除一年內到期部份',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2540',N'長期借款 - 已減除一年內到期部份',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2551',N'員工福利負債準備-非流動',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2556',N'除役、復原及修復成本之長期負債準備',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2559',N'其他長期負債準備',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2570',N'遞延所得稅負債 - 非流動',0,'C');
--26XX
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','26XX',N'其他非流動負債',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2610',N'長期應付票據及款項',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2620',N'長期應付票據及款項-關係人',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2630',N'長期遞延收入',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2635',N'特別股負債-非流動',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2640',N'應計退休金負債',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2645',N'存入保證金',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2650',N'採權益法長期股權投資貸餘',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2660',N'遞延貸項-聯屬公司間利益',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','2670',N'其他非流動負債-其他',0,'C');
--31XX
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','31XX',N'股本',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','3110',N'普通股股本',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','3120',N'特別股股本',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','3140',N'預收股本',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','3150',N'待分配股票股利',0,'C');
--32XX
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','32XX',N'資本公積',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','3210',N'資本公積 - 發行溢價',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','3220',N'資本公積 - 庫藏股',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','3240',N'資本公積 - 處分資產增益',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','3250',N'資本公積 - 受贈資產',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','3260',N'資本公積 - 採權益法認列關聯企業及合資企業股權淨值之變動數',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','3265',N'資本公積 - 採權益法認列子公司股權淨值之變動數',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','3270',N'資本公積 - 合併溢額',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','3271',N'資本公積 - 員工認股權',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','3280',N'資本公積 - 其他',0,'C');
--33XX
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','33XX',N'保留盈餘',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','3310',N'法定盈餘公積',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','3320',N'特別盈餘公積',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','3350',N'未分配盈餘(或待彌補虧損)',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','3400',N'其他權益',0,null);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','3410',N'國外營運機構財務報表換算之兌換差額',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','3425',N'備供出售金融資產未實現損益',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','3430',N'現金流量避險中屬有效避險部分之避險工具利益(損失)',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','3470',N'與待出售非流動資產直接相關之權益',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','3480',N'採用權益法之關聯企業及合資之其他權益份額',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','3480-1',N'採用權益法之子公司之其他權益份額',0,'C');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','3490',N'其他權益-其他',0,'C');
--35XX
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','35XX',N'非控制權益',0,'C');


--IS 合併損益表 試算表
--BS 資產負債表
CREATE TABLE RPT_ISBS (
	ID bigint NOT NULL IDENTITY,
	COMP_GROUP nvarchar(6) NOT NULL,
	YEARMONTH char(6) NOT NULL,
	SHEET nvarchar(20) NOT NULL,
	CODE nvarchar(20) NOT NULL,
	--AMOUNT_ORIG decimal(18,3),--期初金額
	--AMOUNT_DEBIT decimal(18,3),--借方金額
	--AMOUNT_CREDIT decimal(18,3),--貸方金額
	AMOUNT decimal(18,3),--期末金額
	MODIFIER bigint NOT NULL,
	MODIFYTIMESTAMP datetime NOT NULL,
	CONSTRAINT FC_RPT_ISBS_PK PRIMARY KEY (ID),
	CONSTRAINT FC_RPT_ISBS_FK1 FOREIGN KEY (MODIFIER) REFERENCES TC_USER (ID)
)
--sp_RENAME 'FC_RPT_ISBS' , 'RPT_ISBS'; 
--ALTER TABLE RPT_ISBS DROP COLUMN AMOUNT_ORIG;
--ALTER TABLE RPT_ISBS DROP COLUMN AMOUNT_DEBIT;
--ALTER TABLE RPT_ISBS DROP COLUMN AMOUNT_CREDIT;

--合併報表上傳檔
CREATE TABLE RPT_ISBS_UPLOAD (
	ID bigint NOT NULL IDENTITY,
    COMP_GROUP nvarchar(6) NOT NULL,	
	YEARMONTH char(6) NOT NULL,
	MODIFIER bigint NOT NULL,
	MODIFYTIMESTAMP datetime NOT NULL,
	CONSTRAINT RPT_ISBS_UPLOAD_PK PRIMARY KEY (ID),
	CONSTRAINT RPT_ISBS_UPLOAD_UK UNIQUE (COMP_GROUP, YEARMONTH),
	CONSTRAINT RPT_ISBS_UPLOAD_FK1 FOREIGN KEY (MODIFIER) REFERENCES TC_USER (ID)
)


--調整轉帳傳票
--傳票編號 = 作帳年月 + 序號
CREATE TABLE RPT_ACCOUNTING_DOC_M (
	ID bigint NOT NULL IDENTITY,
	COMP_GROUP nvarchar(6) NOT NULL,
	YEARMONTH char(6) NOT NULL,--作帳年月
	SNO int(4) NOT NULL,--序號
	NOTE nvarchar(500) NULL,--摘要
	STATUS int(1) NOT NULL,--傳票狀態(1:輸入;3:過帳;9:作廢)
	MODIFIER bigint NOT NULL, --作帳人員
	MODIFYTIMESTAMP datetime NOT NULL,
	CREATETIMESTAMP datetime NOT NULL,--建立日期
	POSTINTTIMESTAMP datetime NULL,--過帳日期
	DISABLETIMESTAMP datetime NULL,--作廢日期
	CONSTRAINT RPT_ACCOUNTING_DOC_M_PK PRIMARY KEY (ID),
	CONSTRAINT RPT_ACCOUNTING_DOC_M_FK1 FOREIGN KEY (MODIFIER) REFERENCES TC_USER (ID)
	CONSTRAINT RPT_ACCOUNTING_DOC_M_UK1 UNIQUE (COMP_GROUP, YEARMONTH, SNO)
)
--附號 = 借貸碼 + 序號
CREATE TABLE RPT_ACCOUNTING_DOC_D (
	ID bigint NOT NULL IDENTITY,
	MASTER bigint NOT NULL,
	DC_FLAG nvarchar(1);--借貸碼
	SNO int(4) NOT NULL,--序號
	CODE nvarchar(20) NOT NULL,
	COMPANY bigint  NOT NULL,
	AMOUNT decimal(18,3),
	NOTE nvarchar(500) NULL,--摘要
	CONSTRAINT RPT_ACCOUNTING_DOC_D_PK PRIMARY KEY (ID),
	CONSTRAINT RPT_ACCOUNTING_DOC_D_FK1 FOREIGN KEY (MASTER) REFERENCES RPT_ACCOUNTING_DOC_M (ID),
	CONSTRAINT RPT_ACCOUNTING_DOC_D_FK2 FOREIGN KEY (COMPANY) REFERENCES FC_COMPANY (ID),
	CONSTRAINT RPT_ACCOUNTING_DOC_D_UK1 UNIQUE (MASTER, DC_FLAG, SNO)
)

--20151222
--試算表上傳檔Spreadsheet
CREATE TABLE RPT_SHEET_UPLOAD (
	ID bigint NOT NULL IDENTITY,
    COMPANY bigint  NOT NULL,	
	YEARMONTH char(6) NOT NULL,
	MODIFIER bigint NOT NULL,
	MODIFYTIMESTAMP datetime NOT NULL,
	CONSTRAINT RPT_SHEET_UPLOAD_PK PRIMARY KEY (ID),
	CONSTRAINT RPT_SHEET_UPLOAD_UK UNIQUE (COMPANY, YEARMONTH),
    CONSTRAINT RPT_SHEET_UPLOAD_FK1 FOREIGN KEY (COMPANY) REFERENCES FC_COMPANY (ID),
	CONSTRAINT RPT_SHEET_UPLOAD_FK2 FOREIGN KEY (MODIFIER) REFERENCES TC_USER (ID)
)

--會計科目主檔寫入 20160114
--11XX
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1XXX','',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','11XX',N'流動資產',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1100',N'現金及約當現金',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1101',N'庫存現金',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1102',N'零用金／週轉金',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1103',N'銀行存款',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1105',N'在途現金',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','110701',N'商業本票',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','110702',N'銀行承兌匯票',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','110703',N'原始到期日在三個月以內之銀行定期存款',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','110704',N'附買回債券',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1108',N'分類為約當現金之銀行透支',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1110',N'透過損益按公允價值衡量之金融資產-流動',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1125',N'備供出售金融資產-流動',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','112601',N'國內上市(櫃)股票',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','112602',N'國內興櫃股票',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','112603',N'基金受益憑證',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','112604',N'債券投資-政府公債',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','112605',N'債券投資-公司債',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','112606',N'國外上市(櫃)股票',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1127',N'備供出售金融資產評價',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1129',N'累計減損-備供出售金融資產',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1130',N'持有至到期日金融資產-流動',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1135',N'避險之衍生性金融資產-流動',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1144',N'以成本衡量之金融資產-流動',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1147',N'無活絡市場之債券投資-流動',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1150',N'應收票據淨額',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1151',N'應收票據',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1152',N'其他應收票據',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1153',N'應收票據貼現',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1159',N'減：備抵呆帳-應收票據',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1160',N'應收票據-關係人淨額',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1161',N'應收票據-關係人',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1162',N'其他應收票據-關係人',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1163',N'應收票據貼現-關係人',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1169',N'減：備抵呆帳-應收關係人票據',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1170',N'應收帳款淨額',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1171',N'應收銷售及管理費(證券投資信託業適用)',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1172',N'應收帳款',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1173',N'應收分期帳款',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1174',N'未實現利息收入-應收分期帳款',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1175',N'應收租賃款',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1176',N'融資租賃之未賺得融資收益',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1177',N'減：備抵銷售退回及折讓',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1179',N'減：備抵呆帳-應收帳款',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1180',N'應收帳款-關係人淨額',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1181',N'應收帳款-關係人',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1182',N'應收分期帳款-關係人',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1183',N'未實現利息收入-應收關係人分期帳款',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1184',N'應收租賃款-關係人',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1185',N'融資租賃之未賺得融資收益-關係人',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1186',N'減：備抵呆帳-應收關係人帳款、分期帳款及租賃款',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1200',N'其他應收款項淨額',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1201',N'應收退稅款',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1202',N'未收代墊款(海陸運輸業適用)',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1203',N'應收工程保留款',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1204',N'應收歸墊款',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1205',N'應收收益',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1206',N'其他應收款-其他',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1209',N'減：備抵呆帳-其他應收款項',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1210',N'其他應收款-關係人',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1211',N'應收收益-關係人',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1212',N'其他應收款-關係人-其他',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1219',N'減：備抵呆帳-其他應收關係人款項',0,'D');
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE,DC_FLAG) VALUES ('TCC','1476',N'其他金融資產-流動',0,'D');



--20160125 合併報表 試算表資料上傳紀錄檔
CREATE TABLE RPT_DATA_UPLOAD_RECORD(
ID bigint NOT NULL IDENTITY,
COMPANY_CODE NVARCHAR(4) NOT NULL,
YEARMONTH NVARCHAR(6) NOT NULL,
MODIFIER bigint NULL,
MODIFYTIMESTAMP datetime NOT NULL,
CONSTRAINT RPT_DATA_UPLOAD_RECORD_UK UNIQUE (COMPANY_CODE, YEARMONTH),
CONSTRAINT RPT_DATA_UPLOAD_RECORD_FK1 FOREIGN KEY (MODIFIER) REFERENCES TC_USER (ID)
);
GRANT DELETE,INSERT,SELECT,UPDATE ON RPT_DATA_UPLOAD_RECORD TO erp_user;
--20160126 合併會科主檔_ACCT MASTER
--"A-台泥, B-中橡 從合併層次碼第1碼, 決定ZGROUP"
CREATE TABLE ZTFI_AFCS_ACMA(
ID bigint NOT NULL IDENTITY,
ZGROUP NVARCHAR(1) NOT NULL,
ZAADET NVARCHAR(6) NOT NULL,
ZAADET_NM NVARCHAR(60) NULL,
ZABNOT NVARCHAR(4) NULL,
ZABNOT_NM NVARCHAR(60) NULL,
ZACLIN NVARCHAR(4) NULL,
ZACLIN_NM NVARCHAR(60) NULL,
ZADSUB NVARCHAR(4) NULL,
ZADSUB_NM NVARCHAR(60) NULL,
ZAECLS NVARCHAR(4) NULL,
ZAECLS_NM NVARCHAR(60) NULL,
MODIFIER bigint NULL,
MODIFYTIMESTAMP datetime NULL,
CONSTRAINT ZTFI_AFCS_ACMA_UK UNIQUE (ZGROUP, ZAADET),
CONSTRAINT ZTFI_AFCS_ACMA_FK1 FOREIGN KEY (MODIFIER) REFERENCES TC_USER (ID)
);
GRANT DELETE,INSERT,SELECT,UPDATE ON ZTFI_AFCS_ACMA TO erp_user;


--20160201 比照合併營收 寫入D大類沖銷資料 (D0202, D0204)
--暫不考慮跟FC_REPORT_VALUE並用
CREATE TABLE RPT_D_VALUE (
	ID bigint NOT NULL IDENTITY, 
	UPLOAD_ID bigint NOT NULL,
	SHEET nvarchar(20) NOT NULL,
	COID2 bigint NOT NULL,
	CODE nvarchar(20) NOT NULL,
	AMOUNT decimal(18,3),
	--AMOUNT_ORIG decimal(18,3), --不做對帳用
	AMOUNT_XLS decimal(18,3),
	MODIFIER bigint NOT NULL,
	MODIFYTIMESTAMP datetime NOT NULL,
	CONSTRAINT RPT_D_VALUE_PK PRIMARY KEY (ID),
	CONSTRAINT RPT_D_VALUE_FK1 FOREIGN KEY (UPLOAD_ID) REFERENCES RPT_SHEET_UPLOAD (ID),
	CONSTRAINT RPT_D_VALUE_FK2 FOREIGN KEY (COID2) REFERENCES FC_COMPANY (ID),
	CONSTRAINT RPT_D_VALUE_FK3 FOREIGN KEY (MODIFIER) REFERENCES TC_USER (ID)
);

-------------20160202 更新版 start
--D0202
--INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE) VALUES ('TCC','1161',N'應收票據-關係人',0);
--INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE) VALUES ('TCC','1181',N'應收帳款-關係人',0);
--INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE) VALUES ('TCC','1212',N'其他應收款-關係人',0);
update FC_ACCOUNTS set NAME = N'其他應收款-關係人' where CODE = '1212';
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE) VALUES ('TCC','1419',N'其他預付費用',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE) VALUES ('TCC','1421',N'預付貨款',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE) VALUES ('TCC','1429',N'其他預付款',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE) VALUES ('TCC','1479',N'其他流動資產',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE) VALUES ('TCC','1920',N'存出保證金',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE) VALUES ('TCC','1940',N'長期應收票據及款項 – 關係人',0);
--D0204
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE) VALUES ('TCC','2100',N'短期借款',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE) VALUES ('TCC','2161',N'應付票據-關係人',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE) VALUES ('TCC','2181',N'應付帳款-關係人',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE) VALUES ('TCC','2220',N'其他應付款-關係人',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE) VALUES ('TCC','2310',N'預收款項',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE) VALUES ('TCC','2645',N'存入保證金(品)',0);
INSERT INTO FC_ACCOUNTS (COMP_GROUP,CODE,NAME,ACTIVE) VALUES ('TCC','2399',N'其他負債-其他',0);

--insert script
--TCC VALUE_ITEM
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,START_ROW,CREATETIMESTAMP) VALUES ('TCC','VALUE_ITEM','D0202',10,GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,START_ROW,CREATETIMESTAMP) VALUES ('TCC','VALUE_ITEM','D0204',10,GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,START_ROW,CREATETIMESTAMP) VALUES ('TCC','VALUE_ITEM','TB',2,GETDATE());
--TCC VALIDATOR_ITEM
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,CELL_RANGE,CREATETIMESTAMP) VALUES ('TCC','VALIDATOR_ITEM','D0202','C10:K36',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,CELL_RANGE,CREATETIMESTAMP) VALUES ('TCC','VALIDATOR_ITEM','D0204','C10:I36',GETDATE());
--TCC ACCOUNT_ITEM
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('TCC','ACCOUNT_ITEM','D0202','C','1161',N'應收票據-關係人',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('TCC','ACCOUNT_ITEM','D0202','D','1181',N'應收帳款-關係人',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('TCC','ACCOUNT_ITEM','D0202','E','1212',N'其他應收款-關係人',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('TCC','ACCOUNT_ITEM','D0202','F','1421',N'預付貨款',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('TCC','ACCOUNT_ITEM','D0202','G','1429',N'其他預付款',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('TCC','ACCOUNT_ITEM','D0202','H','1479',N'其他流動資產',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('TCC','ACCOUNT_ITEM','D0202','I','1920',N'存出保證金',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('TCC','ACCOUNT_ITEM','D0202','J','1419',N'其他預付費用',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('TCC','ACCOUNT_ITEM','D0202','K','1940',N'長期應收票據及款項 – 關係人',GETDATE());

INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('TCC','ACCOUNT_ITEM','D0204','C','2100',N'短期借款',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('TCC','ACCOUNT_ITEM','D0204','D','2161',N'應付票據-關係人',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('TCC','ACCOUNT_ITEM','D0204','E','2181',N'應付帳款-關係人',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('TCC','ACCOUNT_ITEM','D0204','F','2220',N'其他應付款-關係人',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('TCC','ACCOUNT_ITEM','D0204','G','2310',N'預收款項',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('TCC','ACCOUNT_ITEM','D0204','H','2645',N'存入保證金(品)',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('TCC','ACCOUNT_ITEM','D0204','I','2399',N'其他負債-其他',GETDATE());
INSERT INTO FC_RPT_CONFIG (COMP_GROUP,CATEGORY,SHEET,COL_CODE,ACC_CODE,ACC_DESC,CREATETIMESTAMP) VALUES ('TCC','ACCOUNT_ITEM','TB','C','',N'金額',GETDATE());
-------------20160202 更新版 end
--update FC_RPT_CONFIG set ACC_DESC = N'金額'
select * from  FC_RPT_CONFIG
where 1=1 and CATEGORY = 'ACCOUNT_ITEM' and SHEET = 'TB';
RPT_OPEN_YM
RPT_STOPUPLOAD

--20160203
--合併報表開帳年月 限制調整分錄的傳票年月 RPT_OPEN_YM
INSERT INTO FC_CONFIG (CONFIG_KEY,CONFIG_VALUE,COMP_GROUP) VALUES ('RPT_OPEN_YM','201601','TCC');
INSERT INTO FC_CONFIG (CONFIG_KEY,CONFIG_VALUE,COMP_GROUP) VALUES ('RPT_STOPUPLOAD',0,'TCC');
--INSERT INTO FC_CONFIG (CONFIG_KEY,CONFIG_VALUE,COMP_GROUP) VALUES ('RPT_OPEN_YM',null,'CSRC');
--INSERT INTO FC_CONFIG (CONFIG_KEY,CONFIG_VALUE,COMP_GROUP) VALUES ('RPT_STOPUPLOAD',0,'CSRC');

--20160203 TB WEB上傳資料
CREATE TABLE RPT_TB_VALUE (
	ID bigint NOT NULL IDENTITY, 
	UPLOAD_ID bigint NOT NULL,
	CODE nvarchar(20) NOT NULL,
	AMOUNT decimal(18,3),
	--AMOUNT_XLS decimal(18,3),--不做幣別轉換
	MODIFIER bigint NOT NULL,
	MODIFYTIMESTAMP datetime NOT NULL,
	CONSTRAINT RPT_TB_VALUE_PK PRIMARY KEY (ID),
	CONSTRAINT RPT_TB_VALUE_FK1 FOREIGN KEY (UPLOAD_ID) REFERENCES RPT_SHEET_UPLOAD (ID),
	CONSTRAINT RPT_TB_VALUE_FK2 FOREIGN KEY (MODIFIER) REFERENCES TC_USER (ID)
);

--公司群組增加 SAP辨識碼 "A-台泥, B-中橡
ALTER TABLE FC_COMP_GROUP ADD SAP_GROUP_CODE nvarchar(1) NULL;
update FC_COMP_GROUP set SAP_GROUP_CODE = 'A' where code in ('TCC', 'OTHER');
update FC_COMP_GROUP set SAP_GROUP_CODE = 'B' where code = 'CSRC';

--20160204 合併報表餘額檔
CREATE TABLE ZTFI_AFCS_CSBA(
ID bigint NOT NULL IDENTITY,
ZGJAHR SMALLINT(5) NOT NULL,
ZMONAT SMALLINT(5) NOT NULL,
ZBUKTO NVARCHAR(6) NOT NULL,
ZBUKFM NVARCHAR(6) NOT NULL,
ZAADET NVARCHAR(6) NOT NULL,
WAERS NVARCHAR(5),
DMBTR DECIMAL(13, 2),

ZCSWAE NVARCHAR(5),
ZCSBTR DECIMAL(13, 2),
ZCSBTR_CLR DECIMAL(13, 2),
ZTWBTR DECIMAL(13, 0),
ZTWBTR_CLR DECIMAL(13, 0)
, CONSTRAINT ZTFI_AFCS_CSBA_UK UNIQUE (ZGJAHR, ZMONAT, ZBUKTO, ZBUKFM, ZAADET)
);
GRANT DELETE,INSERT,SELECT,UPDATE ON ZTFI_AFCS_CSBA TO erp_user;
--合併報表 合併報表公司設定主檔
CREATE TABLE ZTFI_AFCS_CSBU(
ID bigint NOT NULL IDENTITY,
MANDT NVARCHAR(3) NOT NULL,
ZCSLVL NVARCHAR(12) NOT NULL,
ZBUKFM NVARCHAR(6) NOT NULL,
ZBUKFM_NM NVARCHAR(40) NOT NULL,
ZCSTYP NVARCHAR(1),
ZCSDTB NVARCHAR(3),
ZBUKTO NVARCHAR(6),
WAERS NVARCHAR(5)
--, CONSTRAINT ZTFI_AFCS_CSBA_UK UNIQUE (MANDT, ZCSLVL, ZBUKFM, ZBUKFM_NM, ZCSTYP)
);
GRANT DELETE,INSERT,SELECT,UPDATE ON ZTFI_AFCS_CSBU TO erp_user;


--台訊BVI 上傳 
--增加台訊group 還是 公司清單增加台訊BVI
--INSERT INTO FC_COMP_GROUP (CODE,NAME,CURRENCY) VALUES ('TCC',N'台泥',1);
--20160204 公司主檔 增加欄位 合併報表上傳
ALTER TABLE FC_COMPANY ADD CONSOLIDATION_RPT bit;
update FC_COMPANY SET CONSOLIDATION_RPT = COMBINE_INCOME where 1=1 and COMP_GROUP = 'TCC';
--20160316 定義 合併報表 web上傳的公司 ??? 用之前的CONSOLIDATION_RPT就可以
--20160317感覺還是要加
ALTER TABLE FC_COMPANY ADD CONSOLIDATION_RPT_UPLOAD bit;
--ALTER TABLE FC_COMPANY drop CONSOLIDATION_RPT_UPLOAD;
--update FC_COMPANY SET CONSOLIDATION_RPT_UPLOAD = 'false' where 1=1;
update FC_COMPANY SET CONSOLIDATION_RPT_UPLOAD = CONSOLIDATION_RPT where 1=1;


--20160321公司代碼欄位六碼
ALTER TABLE RPT_DATA_UPLOAD_RECORD ALTER Column COMPANY_CODE nvarchar(6);

--20160323 合併報表公司組織階層關係
CREATE TABLE RPT_COMPANY_ORG (
	ID bigint NOT NULL IDENTITY,
	COMP_GROUP nvarchar(6) NOT NULL,
  CODE nvarchar(6) NOT NULL,	
	PARENT_ID bigint,
	CONSTRAINT RPT_COMPANY_ORG_PK PRIMARY KEY (ID),
	--CONSTRAINT RPT_COMPANY_ORG_FK1 FOREIGN KEY (CODE) REFERENCES FC_COMPANY (CODE),
	CONSTRAINT RPT_COMPANY_ORG_FK1 FOREIGN KEY (PARENT_ID) REFERENCES RPT_COMPANY_ORG (ID)
);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID) VALUES ('TCC',N'1000XX',null);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID) VALUES ('TCC',N'1000',1);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID) VALUES ('TCC',N'1100',1);

INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID) VALUES ('TCC',N'1200',1);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID) VALUES ('TCC',N'1300',1);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID) VALUES ('TCC',N'1400',1);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID) VALUES ('TCC',N'1500',1);

INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID) VALUES ('TCC',N'1600',1);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID) VALUES ('TCC',N'1700',1);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID) VALUES ('TCC',N'1800',1);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID) VALUES ('TCC',N'1900',1);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID) VALUES ('TCC',N'1A00XX',1);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID) VALUES ('TCC',N'1C00',1);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID) VALUES ('TCC',N'1D00',1);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID) VALUES ('TCC',N'1E00',1);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID) VALUES ('TCC',N'2W00XX',1);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID) VALUES ('TCC',N'2B00XX',1);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID) VALUES ('TCC',N'5200XX',1);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID) VALUES ('TCC',N'5300XX',1);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID) VALUES ('TCC',N'5400XX',1);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID) VALUES ('TCC',N'5500XX',1);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID) VALUES ('TCC',N'5E00',1);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID) VALUES ('TCC',N'6800',1);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID) VALUES ('TCC',N'7700',1);



--開發參考pmis OrgController.java OrganizationVO

--20160328補SAP上傳log
INSERT INTO RPT_DATA_UPLOAD_RECORD (COMPANY_CODE,YEARMONTH,UPLOAD_DATE,UPLOAD_TIME) VALUES ('5300XX','201512','20160328','000000');



--20160328 SAP資料上傳紀錄檔  FUNC(A:關係人對帳; B:合併報表)
--drop table FC_SAP_UPLOAD_RECORD;
CREATE TABLE FC_SAP_UPLOAD_RECORD(
ID bigint NOT NULL IDENTITY,
FUNC NVARCHAR(1) NOT NULL,
COMPANY_CODE NVARCHAR(6) NOT NULL,
YEARMONTH NVARCHAR(6) NOT NULL,
UPLOAD_DATE NVARCHAR(8),
UPLOAD_TIME NVARCHAR(6),
CONSTRAINT FC_SAP_UPLOAD_RECORD_PK PRIMARY KEY (ID)
);

GRANT DELETE,INSERT,SELECT,UPDATE ON FC_SAP_UPLOAD_RECORD TO erp_user;

INSERT INTO FC_SAP_UPLOAD_RECORD (FUNC,COMPANY_CODE,YEARMONTH,UPLOAD_DATE,UPLOAD_TIME) 
VALUES ('B','5300XX','201512','20160328','155820');

--20160329刪除原遷就SAP 提供組合成上傳時間的string欄位(IRS,RPT)
--刪除前 補已上傳的資料 只能捕日期
--update IRS_TRAN_UPLOAD_RECORD 
--update RPT_DATA_UPLOAD_RECORD 
--set MODIFYTIMESTAMP=convert(datetime, UPLOAD_DATE)
--set MODIFYTIMESTAMP=convert(datetime, UPLOAD_DATE + ' ' + substring(UPLOAD_TIME,1,2) + ':' + substring(UPLOAD_TIME,3,2)+ ':' + substring(UPLOAD_TIME,5,2))
select MODIFYTIMESTAMP, UPLOAD_DATE, UPLOAD_TIME,
convert(datetime, UPLOAD_DATE) d1,
convert(datetime, UPLOAD_DATE + ' ' + substring(UPLOAD_TIME,1,2) + ':' + substring(UPLOAD_TIME,3,2)+ ':' + substring(UPLOAD_TIME,5,2)) d2
from IRS_TRAN_UPLOAD_RECORD
--from RPT_DATA_UPLOAD_RECORD
where 1=1 
--and MODIFYTIMESTAMP is null;
and UPLOAD_DATE is not null and UPLOAD_TIME is not null;

update IRS_TRAN_UPLOAD_RECORD
set MODIFYTIMESTAMP=convert(datetime, UPLOAD_DATE + ' ' + substring(UPLOAD_TIME,1,2) + ':' + substring(UPLOAD_TIME,3,2)+ ':' + substring(UPLOAD_TIME,5,2))
where 1=1 
and UPLOAD_DATE is not null and UPLOAD_TIME is not null;

ALTER TABLE IRS_TRAN_UPLOAD_RECORD DROP COLUMN UPLOAD_DATE;
ALTER TABLE IRS_TRAN_UPLOAD_RECORD DROP COLUMN UPLOAD_TIME;
ALTER TABLE RPT_DATA_UPLOAD_RECORD DROP COLUMN UPLOAD_DATE;
ALTER TABLE RPT_DATA_UPLOAD_RECORD DROP COLUMN UPLOAD_TIME;
--加index FC_SAP_UPLOAD_RECORD
CREATE INDEX IDX_SAP_UPLOAD_RECORD ON FC_SAP_UPLOAD_RECORD (FUNC, COMPANY_CODE, YEARMONTH);

--20160511合併報表開關帳設定 提供SAP查詢 統一控管
GRANT SELECT ON FC_CONFIG TO erp_user;
--檢查上傳報表年月是否為開帳年月(YYYYMM)
SELECT CONFIG_VALUE FROM FC_CONFIG WHERE CONFIG_KEY = 'RPT_OPEN_YM' AND COMP_GROUP = 'TCC';
--檢查 是否停止上傳(關帳) (0:開1:關)
SELECT CONFIG_VALUE FROM FC_CONFIG WHERE CONFIG_KEY = 'RPT_STOPUPLOAD' AND COMP_GROUP = 'TCC';

--20160511 新增權限group, role 合併報表總處負責人
--glassfish-web.xml,web.xml
INSERT INTO TC_GROUP (CODE,NAME,CREATOR,CREATETIMESTAMP) values ('CONSOLIDATION_RPT_HQ',N'合併報表總處負責人', 1, GETDATE());
update TC_GROUP set NAME = N'合併報表總處負責人' where CODE = 'CONSOLIDATION_RPT_HQ';

--20160517RPT_COMPANY_ORG組織 階層HLEVEL hierarchy
ALTER TABLE RPT_COMPANY_ORG ADD HLEVEL SMALLINT;
update RPT_COMPANY_ORG set HLEVEL = 1 where 1=1 and COMP_GROUP = 'TCC';
update RPT_COMPANY_ORG set HLEVEL = 0 where 1=1 and code = '1000XX';

--20160523 SAP資料上傳紀錄檔 增加SAP上傳人中文名稱
ALTER TABLE FC_SAP_UPLOAD_RECORD ADD USER_NAME NVARCHAR(10);
--A:關係人對帳; B:合併報表
ALTER TABLE IRS_TRAN_UPLOAD_RECORD ADD SAP_USER_NAME NVARCHAR(10);
ALTER TABLE RPT_DATA_UPLOAD_RECORD ADD SAP_USER_NAME NVARCHAR(10);
--for test
INSERT INTO FC_SAP_UPLOAD_RECORD (FUNC,COMPANY_CODE,YEARMONTH,UPLOAD_DATE,UPLOAD_TIME,USER_NAME) 
VALUES ('A','1000','201604','20160523','151314',N'for test');
INSERT INTO FC_SAP_UPLOAD_RECORD (FUNC,COMPANY_CODE,YEARMONTH,UPLOAD_DATE,UPLOAD_TIME,USER_NAME) 
VALUES ('B','5200XX','201512','20160523','151314',N'for test B');

--20160525 先準備中橡的組織圖 新增根 在新增編輯下層
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID,HLEVEL) VALUES ('CSRC',N'8000XX',null,0);

--20160531 TCCI 2B00XX下設定 ==> TCCIH 2C00下 HLEVEL:3 25筆
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID,HLEVEL) VALUES ('TCC',N'2000',48,3);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID,HLEVEL) VALUES ('TCC',N'2200',48,3);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID,HLEVEL) VALUES ('TCC',N'2400',48,3);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID,HLEVEL) VALUES ('TCC',N'2500',48,3);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID,HLEVEL) VALUES ('TCC',N'2600',48,3);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID,HLEVEL) VALUES ('TCC',N'2700',48,3);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID,HLEVEL) VALUES ('TCC',N'2900',48,3);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID,HLEVEL) VALUES ('TCC',N'3000',48,3);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID,HLEVEL) VALUES ('TCC',N'3100',48,3);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID,HLEVEL) VALUES ('TCC',N'3200',48,3);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID,HLEVEL) VALUES ('TCC',N'3300',48,3);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID,HLEVEL) VALUES ('TCC',N'3400',48,3);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID,HLEVEL) VALUES ('TCC',N'3500',48,3);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID,HLEVEL) VALUES ('TCC',N'3600',48,3);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID,HLEVEL) VALUES ('TCC',N'4100',48,3);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID,HLEVEL) VALUES ('TCC',N'4200',48,3);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID,HLEVEL) VALUES ('TCC',N'4300',48,3);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID,HLEVEL) VALUES ('TCC',N'4400',48,3);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID,HLEVEL) VALUES ('TCC',N'6000',48,3);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID,HLEVEL) VALUES ('TCC',N'6100',48,3);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID,HLEVEL) VALUES ('TCC',N'6200',48,3);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID,HLEVEL) VALUES ('TCC',N'6300',48,3);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID,HLEVEL) VALUES ('TCC',N'6500',48,3);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID,HLEVEL) VALUES ('TCC',N'6700',48,3);
INSERT INTO RPT_COMPANY_ORG (COMP_GROUP,CODE,PARENT_ID,HLEVEL) VALUES ('TCC',N'3F00',48,3);

--20160601 勘誤表功能 部分公司停用
ALTER TABLE RPT_COMPANY_ORG ALTER column CODE NVARCHAR(10);
--停用
update RPT_COMPANY_ORG set CODE = Convert(nvarchar(4),CODE) + N'(停用)'
where PARENT_ID = 48;
update RPT_COMPANY_ORG set CODE = Convert(nvarchar(4),CODE) + N'(停用)'
where CODE in ('5600','5900','1G00','1P00');
--啟用 ready
--update RPT_COMPANY_ORG set CODE = subString(CODE,1,4)
--where PARENT_ID = 48;
--where CODE in ('5600','5900','1G00','1P00');


--20160623 SAP資料上傳紀錄檔 SAP上傳人中文名稱 欄位長度增加為20碼
ALTER TABLE FC_SAP_UPLOAD_RECORD ALTER column USER_NAME NVARCHAR(20);
--20160704 IRS & RPT 資料上傳紀錄檔 SAP上傳人中文名稱 欄位長度增加為20碼  遺漏
ALTER TABLE IRS_TRAN_UPLOAD_RECORD ALTER column SAP_USER_NAME NVARCHAR(20);
ALTER TABLE RPT_DATA_UPLOAD_RECORD ALTER column SAP_USER_NAME NVARCHAR(20);

--20160704 config 增加 排程更新資料上傳紀錄檔時的執行完成時間
INSERT INTO FC_CONFIG (CONFIG_KEY,CONFIG_VALUE) VALUES ('UPLOAD_RECORD_BATCH',null);