/*
	適用 2015/12/11 以前的 tcc-fc-model.jar, 之後的已直接加入 install_fc.sql 中.
*/
CREATE INDEX [TC_APPLICATIONDATA_IDX1] ON [TC_APPLICATIONDATA] ([CONTAINERCLASSNAME],[CONTAINERID]);

CREATE INDEX [TC_URLDTA_IDX1] ON [TC_URLDATA]([CONTAINERCLASSNAME],[CONTAINERID]);

ALTER TABLE [TC_USERGROUP] ADD CONSTRAINT [TC_USERGROUP_UK1] UNIQUE ([USER_ID],[GROUP_ID]);