CREATE TABLE TC_USER 
(	
    ID numeric(18) NOT NULL IDENTITY, 
    LOGIN_ACCOUNT NVARCHAR(60) NOT NULL, 
    EMAIL NVARCHAR(60), 	
    EMP_ID NVARCHAR(20),
    CNAME NVARCHAR(20),
    DISABLED BIT, 	
    CREATOR numeric(18) ,
    CREATETIMESTAMP DATETIME,	
    CONSTRAINT TC_USER_PK PRIMARY KEY (ID),
    CONSTRAINT TC_USER_UK UNIQUE (LOGIN_ACCOUNT,CREATETIMESTAMP),
    CONSTRAINT TC_USER_FK FOREIGN KEY (CREATOR) REFERENCES TC_USER(ID)
);

CREATE TABLE TC_GROUP 
(	
    ID numeric(18) NOT NULL IDENTITY, 
    CODE NVARCHAR(30) NOT NULL, 
    NAME NVARCHAR(90) NOT NULL, 
    CREATOR numeric(18), 
    CREATETIMESTAMP DATETIME,
    CONSTRAINT TC_GROUP_PK PRIMARY KEY (ID),
    CONSTRAINT TC_GROUP_UK UNIQUE (CODE),
    CONSTRAINT TC_GROUP_FK FOREIGN KEY (CREATOR) REFERENCES TC_USER(ID)
);

CREATE TABLE TC_USERGROUP 
(	
    ID numeric(18) NOT NULL IDENTITY, 
    USER_ID numeric(18) NOT NULL, 
    GROUP_ID numeric(18) DEFAULT 1 NOT NULL, 
    CREATOR numeric(18) , 
    CREATETIMESTAMP DATETIME,
    CONSTRAINT TC_USERGROUP_PK PRIMARY KEY (ID),
	CONSTRAINT TC_USERGROUP_UK1 UNIQUE (USER_ID,GROUP_ID),
    CONSTRAINT TC_USERGROUP_FK1 FOREIGN KEY (GROUP_ID) REFERENCES TC_GROUP (ID), 
    CONSTRAINT TC_USERGROUP_FK2 FOREIGN KEY (USER_ID) REFERENCES TC_USER (ID),
    CONSTRAINT TC_USERGROUP_FK3 FOREIGN KEY (CREATOR) REFERENCES TC_USER (ID),
);

CREATE INDEX [TC_USERGROUP_IDX1] ON [TC_USERGROUP]([USER_ID],[GROUP_ID]);

CREATE TABLE TC_APPLICATIONDATA 
(	
   ID numeric(18) NOT NULL IDENTITY, 
	CONTAINERCLASSNAME NVARCHAR(255) DEFAULT NULL, 
	CONTAINERID numeric(18) DEFAULT NULL, 
	CONTENTROLE NVARCHAR(1) DEFAULT 'P', 
	CREATOR numeric(18) NOT NULL, 
	CREATETIMESTAMP DATETIME DEFAULT GETDATE() NOT NULL, 
	DESCRIPTION NVARCHAR(1000), 
	FVITEM numeric(18) NOT NULL, 
	CONSTRAINT TC_APPLICATIONDATA_PK PRIMARY KEY (ID),
	CONSTRAINT TC_APPLICATIONDATA_FK1 FOREIGN KEY (CREATOR) REFERENCES TC_USER (ID) 
);

CREATE INDEX [TC_APPLICATIONDATA_IDX1] ON [TC_APPLICATIONDATA] ([CONTAINERCLASSNAME],[CONTAINERID]);

CREATE TABLE  TC_URLDATA (
  ID NUMERIC(18)  NOT NULL ,
  CONTAINERCLASSNAME NVARCHAR(255) DEFAULT NULL,
  CONTAINERID NUMERIC(18)  DEFAULT NULL,
  CREATETIMESTAMP DATETIME DEFAULT NULL,
  CONTENTROLE NVARCHAR(255) DEFAULT NULL,
  CREATOR NUMERIC(18)  DEFAULT NULL,
  URL NVARCHAR(1000) DEFAULT NULL,
  DESCRIPTION NVARCHAR(1000) DEFAULT NULL,
  CONSTRAINT TC_URLDATA_PK PRIMARY KEY  (ID),
  CONSTRAINT TC_URLDATA_FK01 FOREIGN KEY (CREATOR) REFERENCES TC_USER (ID)
) ;

CREATE INDEX [TC_URLDTA_IDX1] ON [TC_URLDATA]([CONTAINERCLASSNAME],[CONTAINERID]);

CREATE TABLE TC_DOMAIN 
(	
  ID numeric(18) NOT NULL IDENTITY, 
	NAME NVARCHAR(600) NOT NULL, 
	DESCRIPTION NVARCHAR(100) DEFAULT NULL, 
	CONSTRAINT TC_DOMAIN_PK PRIMARY KEY (ID)
);

CREATE TABLE TC_FVITEM 
(	
  ID numeric(18) NOT NULL IDENTITY, 
	NAME NVARCHAR(255) NOT NULL, 
	FILENAME NVARCHAR(255) NOT NULL, 
	FILESIZE numeric(18) NOT NULL, 
	CONTENTTYPE NVARCHAR(255) DEFAULT NULL, 
	DOMAIN numeric(18) NOT NULL, 
	CREATOR numeric(18) NOT NULL, 
	CREATETIMESTAMP DATETIME DEFAULT GETDATE() NOT NULL, 
    CONSTRAINT FUL_FVITEM_PK PRIMARY KEY (ID),
  	CONSTRAINT TC_FVITEM_FK1 FOREIGN KEY (DOMAIN) REFERENCES TC_DOMAIN (ID),
	CONSTRAINT TC_FVITEM_FK2 FOREIGN KEY (CREATOR) REFERENCES TC_USER (ID) 
);

CREATE TABLE TC_FVVAULT 
(	
  ID numeric(18) NOT NULL IDENTITY, 
	NAME NVARCHAR(255) DEFAULT NULL, 
	HOSTNAME NVARCHAR(255) NOT NULL, 
	DOMAIN numeric(18) NOT NULL, 
	LOCATION NVARCHAR(600) NOT NULL, 
	READONLY BIT DEFAULT 0 NOT NULL, 
	ENABLED BIT DEFAULT 1 NOT NULL, 
	URL NVARCHAR(600), 
	 CONSTRAINT FUL_FVVAULT_PK PRIMARY KEY (ID),
	 CONSTRAINT TC_FVVAULT_FK1 FOREIGN KEY (DOMAIN) REFERENCES TC_DOMAIN (ID)
);

INSERT INTO TC_DOMAIN (NAME,DESCRIPTION) VALUES ('Default','Default');
INSERT INTO TC_DOMAIN (NAME,DESCRIPTION) VALUES ('TrashCan','TrashCan');

INSERT INTO TC_FVVAULT (NAME,HOSTNAME,DOMAIN,LOCATION,READONLY,ENABLED,URL) values ('Default','localhost',1,'D:\FileVault\APP\Default\',0,1,null);
INSERT INTO TC_FVVAULT (NAME,HOSTNAME,DOMAIN,LOCATION,READONLY,ENABLED,URL) VALUES ('Trash Can','localhost',2,'D:\FileVault\APP\TrashCan\',0,1,NULL);

INSERT INTO TC_USER (LOGIN_ACCOUNT,CNAME,DISABLED,CREATOR,CREATETIMESTAMP) VALUES ('administrator','',0,1,GETDATE());
INSERT INTO TC_USER (LOGIN_ACCOUNT,CNAME,DISABLED,CREATOR,CREATETIMESTAMP) VALUES ('jimmy.lee',N'李振銘',0,1,GETDATE());
INSERT INTO TC_USER (LOGIN_ACCOUNT,CNAME,DISABLED,CREATOR,CREATETIMESTAMP) VALUES ('gilbert.lin',N'林振雄',0,1,GETDATE());
INSERT INTO TC_USER (LOGIN_ACCOUNT,CNAME,DISABLED,CREATOR,CREATETIMESTAMP) VALUES ('jackson.lee',N'李毓霖',0,1,GETDATE());
INSERT INTO TC_USER (LOGIN_ACCOUNT,CNAME,DISABLED,CREATOR,CREATETIMESTAMP) VALUES ('jason.chang',N'張裕豐',0,1,GETDATE());
INSERT INTO TC_USER (LOGIN_ACCOUNT,CNAME,DISABLED,CREATOR,CREATETIMESTAMP) VALUES ('neo.fu',N'傅柏貴',0,1,GETDATE());
INSERT INTO TC_USER (LOGIN_ACCOUNT,CNAME,DISABLED,CREATOR,CREATETIMESTAMP) VALUES ('wayne.hu',N'胡憲維',0,1,GETDATE());
INSERT INTO TC_USER (LOGIN_ACCOUNT,CNAME,DISABLED,CREATOR,CREATETIMESTAMP) VALUES ('edwin.ho',N'何炎運',0,1,GETDATE());
INSERT INTO TC_USER (LOGIN_ACCOUNT,CNAME,DISABLED,CREATOR,CREATETIMESTAMP) VALUES ('sam.lin',N'林坤憲',0,1,GETDATE());
INSERT INTO TC_USER (LOGIN_ACCOUNT,CNAME,DISABLED,CREATOR,CREATETIMESTAMP) VALUES ('yen-chi.sun',N'孫延麒',0,1,GETDATE());
INSERT INTO TC_USER (LOGIN_ACCOUNT,CNAME,DISABLED,CREATOR,CREATETIMESTAMP) VALUES ('david.jen',N'任大為',0,1,GETDATE());
INSERT INTO TC_USER (LOGIN_ACCOUNT,CNAME,DISABLED,CREATOR,CREATETIMESTAMP) VALUES ('kyle.cheng',N'鄭傑鳴',0,1,GETDATE());
INSERT INTO TC_USER (LOGIN_ACCOUNT,CNAME,DISABLED,CREATOR,CREATETIMESTAMP) VALUES ('peter.pan',N'潘倫政',0,1,GETDATE());
INSERT INTO TC_GROUP (CODE,NAME,CREATOR,CREATETIMESTAMP) values ('ADMINISTRATORS','Administrators Group',1,GETDATE());

INSERT INTO TC_USERGROUP (USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (1,1,1,GETDATE());
INSERT INTO TC_USERGROUP (USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (2,1,1,GETDATE());
INSERT INTO TC_USERGROUP (USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (3,1,1,GETDATE());
INSERT INTO TC_USERGROUP (USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (4,1,1,GETDATE());
INSERT INTO TC_USERGROUP (USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (5,1,1,GETDATE());
INSERT INTO TC_USERGROUP (USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (6,1,1,GETDATE());
INSERT INTO TC_USERGROUP (USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (7,1,1,GETDATE());
INSERT INTO TC_USERGROUP (USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (8,1,1,GETDATE());
INSERT INTO TC_USERGROUP (USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (9,1,1,GETDATE());
INSERT INTO TC_USERGROUP (USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (10,1,1,GETDATE());
INSERT INTO TC_USERGROUP (USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (11,1,1,GETDATE());
INSERT INTO TC_USERGROUP (USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (12,1,1,GETDATE());
INSERT INTO TC_USERGROUP (USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (13,1,1,GETDATE());
