 CREATE TABLE TC_USER 
(	
    ID BIGSERIAL PRIMARY KEY, 
    LOGIN_ACCOUNT VARCHAR(60) NOT NULL, 
    EMAIL VARCHAR(60), 	
    EMP_ID VARCHAR(20),
    CNAME VARCHAR(20),
    DISABLED numeric(1) DEFAULT 0, 	
    CREATOR BIGINT REFERENCES TC_USER (ID),
    CREATETIMESTAMP TIMESTAMP,
    CONSTRAINT TC_USER_UK1 UNIQUE (LOGIN_ACCOUNT,CREATETIMESTAMP)
);

CREATE TABLE TC_GROUP 
(	
    ID BIGSERIAL PRIMARY KEY, 
    CODE VARCHAR(30) NOT NULL UNIQUE, 
    NAME VARCHAR(90) NOT NULL, 
    CREATOR BIGINT REFERENCES TC_USER(ID), 
    CREATETIMESTAMP TIMESTAMP
);

CREATE TABLE TC_USERGROUP 
(	
    ID BIGSERIAL PRIMARY KEY, 
    USER_ID BIGINT NOT NULL REFERENCES TC_USER (ID), 
    GROUP_ID BIGINT DEFAULT 1 NOT NULL REFERENCES TC_GROUP (ID), 
    CREATOR BIGINT REFERENCES TC_USER (ID), 
    CREATETIMESTAMP TIMESTAMP,
	  CONSTRAINT TC_USERGROUP_UK1 UNIQUE(USER_ID,GROUP_ID)
);

CREATE TABLE TC_APPLICATIONDATA 
(	
   ID BIGSERIAL PRIMARY KEY, 
	CONTAINERCLASSNAME VARCHAR(255) DEFAULT NULL, 
	CONTAINERID numeric(18) DEFAULT NULL, 
	CONTENTROLE VARCHAR(1) DEFAULT 'P', 
	CREATOR BIGINT NOT NULL REFERENCES TC_USER (ID), 
	CREATETIMESTAMP TIMESTAMP DEFAULT NOW() NOT NULL, 
	DESCRIPTION VARCHAR(1000), 
	FVITEM BIGINT NOT NULL
);

CREATE INDEX TC_APPLICATIONDATA_IDX1 ON TC_APPLICATIONDATA (CONTAINERCLASSNAME,CONTAINERID);

CREATE TABLE  TC_URLDATA (
  ID BIGINT PRIMARY KEY,
  CONTAINERCLASSNAME VARCHAR(255) DEFAULT NULL,
  CONTAINERID BIGINT  DEFAULT NULL,
  CREATETIMESTAMP TIMESTAMP DEFAULT NULL,
  CONTENTROLE VARCHAR(255) DEFAULT NULL,
  CREATOR BIGINT  DEFAULT NULL REFERENCES TC_USER (ID),
  URL VARCHAR(1000) DEFAULT NULL,
  DESCRIPTION VARCHAR(1000) DEFAULT NULL
) ;

CREATE INDEX TC_URLDATA_IDX1 ON TC_URLDATA (CONTAINERCLASSNAME,CONTAINERID);

CREATE TABLE TC_DOMAIN 
(	
  ID BIGSERIAL PRIMARY KEY, 
	NAME VARCHAR(600) NOT NULL, 
	DESCRIPTION VARCHAR(100) DEFAULT NULL
);

CREATE TABLE TC_FVITEM 
(	
  ID BIGSERIAL PRIMARY KEY, 
	NAME VARCHAR(255) NOT NULL, 
	FILENAME VARCHAR(255) NOT NULL, 
	FILESIZE numeric(18) NOT NULL, 
	CONTENTTYPE VARCHAR(255) DEFAULT NULL, 
    RECYCLED NUMERIC(1) DEFAULT 0 NOT NULL,
	DOMAIN BIGINT NOT NULL REFERENCES TC_DOMAIN (ID), 
	CREATOR BIGINT NOT NULL REFERENCES TC_USER (ID), 
	CREATETIMESTAMP TIMESTAMP DEFAULT NOW() NOT NULL 
);

CREATE TABLE TC_FVVAULT 
(	
  ID BIGSERIAL PRIMARY KEY, 
	NAME VARCHAR(255) DEFAULT NULL, 
	HOSTNAME VARCHAR(255) NOT NULL, 
	DOMAIN BIGINT NOT NULL REFERENCES TC_DOMAIN (ID), 
	LOCATION VARCHAR(600) NOT NULL, 
	READONLY NUMERIC(1) DEFAULT 0 NOT NULL, 
	ENABLED NUMERIC(1) DEFAULT 1 NOT NULL, 
	URL VARCHAR(600)
);

INSERT INTO TC_DOMAIN (NAME,DESCRIPTION) VALUES ('Default','Default');
INSERT INTO TC_DOMAIN (NAME,DESCRIPTION) VALUES ('TrashCan','TrashCan');

INSERT INTO TC_FVVAULT (NAME,HOSTNAME,DOMAIN,LOCATION,READONLY,ENABLED,URL) values ('Default','localhost',1,'D:\FileVault\APP\Default\',0,1,null);
INSERT INTO TC_FVVAULT (NAME,HOSTNAME,DOMAIN,LOCATION,READONLY,ENABLED,URL) VALUES ('Trash Can','localhost',2,'E:\FileVault\APP\TrashCan\',0,1,NULL);

INSERT INTO TC_USER (LOGIN_ACCOUNT,CNAME,DISABLED,CREATOR,CREATETIMESTAMP) VALUES ('administrator','',0,1,NOW());
INSERT INTO TC_USER (LOGIN_ACCOUNT,CNAME,DISABLED,CREATOR,CREATETIMESTAMP) VALUES ('jimmy.lee',N'李振銘',0,1,NOW());
INSERT INTO TC_USER (LOGIN_ACCOUNT,CNAME,DISABLED,CREATOR,CREATETIMESTAMP) VALUES ('gilbert.lin',N'林振雄',0,1,NOW());
INSERT INTO TC_USER (LOGIN_ACCOUNT,CNAME,DISABLED,CREATOR,CREATETIMESTAMP) VALUES ('jackson.lee',N'李毓霖',0,1,NOW());
INSERT INTO TC_USER (LOGIN_ACCOUNT,CNAME,DISABLED,CREATOR,CREATETIMESTAMP) VALUES ('jason.chang',N'張裕豐',0,1,NOW());
INSERT INTO TC_USER (LOGIN_ACCOUNT,CNAME,DISABLED,CREATOR,CREATETIMESTAMP) VALUES ('neo.fu',N'傅柏貴',0,1,NOW());
INSERT INTO TC_USER (LOGIN_ACCOUNT,CNAME,DISABLED,CREATOR,CREATETIMESTAMP) VALUES ('wayne.hu',N'胡憲維',0,1,NOW());
INSERT INTO TC_USER (LOGIN_ACCOUNT,CNAME,DISABLED,CREATOR,CREATETIMESTAMP) VALUES ('edwin.ho',N'何炎運',0,1,NOW());
INSERT INTO TC_USER (LOGIN_ACCOUNT,CNAME,DISABLED,CREATOR,CREATETIMESTAMP) VALUES ('sam.lin',N'林坤憲',0,1,NOW());
INSERT INTO TC_USER (LOGIN_ACCOUNT,CNAME,DISABLED,CREATOR,CREATETIMESTAMP) VALUES ('yen-chi.sun',N'孫延麒',0,1,NOW());
INSERT INTO TC_USER (LOGIN_ACCOUNT,CNAME,DISABLED,CREATOR,CREATETIMESTAMP) VALUES ('david.jen',N'任大為',0,1,NOW());
INSERT INTO TC_USER (LOGIN_ACCOUNT,CNAME,DISABLED,CREATOR,CREATETIMESTAMP) VALUES ('kyle.cheng',N'鄭傑鳴',0,1,NOW());
INSERT INTO TC_USER (LOGIN_ACCOUNT,CNAME,DISABLED,CREATOR,CREATETIMESTAMP) VALUES ('peter.pan',N'潘倫政',0,1,NOW());
INSERT INTO TC_USER (LOGIN_ACCOUNT,CNAME,DISABLED,CREATOR,CREATETIMESTAMP) VALUES ('ted.shih',N'施谷澤',0,1,NOW());
INSERT INTO TC_GROUP (CODE,NAME,CREATOR,CREATETIMESTAMP) values ('ADMINISTRATORS','系統管理員',1,NOW());
INSERT INTO TC_GROUP (CODE,NAME,CREATOR,CREATETIMESTAMP) values ('switch-user','切換使用者', 1, NOW());

INSERT INTO TC_USERGROUP (USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (1,1,1,NOW());
INSERT INTO TC_USERGROUP (USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (2,1,1,NOW());
INSERT INTO TC_USERGROUP (USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (3,1,1,NOW());
INSERT INTO TC_USERGROUP (USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (4,1,1,NOW());
INSERT INTO TC_USERGROUP (USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (5,1,1,NOW());
INSERT INTO TC_USERGROUP (USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (6,1,1,NOW());
INSERT INTO TC_USERGROUP (USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (7,1,1,NOW());
INSERT INTO TC_USERGROUP (USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (8,1,1,NOW());
INSERT INTO TC_USERGROUP (USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (9,1,1,NOW());
INSERT INTO TC_USERGROUP (USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (10,1,1,NOW());
INSERT INTO TC_USERGROUP (USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (11,1,1,NOW());
INSERT INTO TC_USERGROUP (USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (12,1,1,NOW());
INSERT INTO TC_USERGROUP (USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (13,1,1,NOW());
INSERT INTO TC_USERGROUP (USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (14,1,1,NOW());