
  CREATE TABLE "TC_USER" 
   (	"ID" NUMBER(18,0) NOT NULL ENABLE, 
	"LOGIN_ACCOUNT" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"LOGIN_NAME" VARCHAR2(15 CHAR) DEFAULT NULL NOT NULL ENABLE, 
	"EMP_ID" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"ROLE_ID" NUMBER(18,0) DEFAULT 1 NOT NULL ENABLE, 
	"IS_VALID" VARCHAR2(1 CHAR) DEFAULT 'Y' NOT NULL ENABLE, 
	"UPDATE_USER" NUMBER(18,0) NOT NULL ENABLE, 
	 CONSTRAINT "TC_USER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "TC_USER"."ID" IS 'seqence';
 
   COMMENT ON COLUMN "TC_USER"."LOGIN_ACCOUNT" IS '登入帳號';
 
   COMMENT ON COLUMN "TC_USER"."LOGIN_NAME" IS '登入者姓名';
 
   COMMENT ON COLUMN "TC_USER"."EMP_ID" IS '工號';
 
   COMMENT ON COLUMN "TC_USER"."ROLE_ID" IS '1:GeneralRole';
 
   COMMENT ON COLUMN "TC_USER"."IS_VALID" IS '是否有效';
 
   COMMENT ON COLUMN "TC_USER"."UPDATE_USER" IS 'ref. TC_USER.ID';
 

  CREATE TABLE "TC_GROUP" 
   (	"ID" NUMBER(18,0) NOT NULL ENABLE, 
	"GROUP_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"GROUP_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"UPDATE_USER" NUMBER(18,0) NOT NULL ENABLE, 
	 CONSTRAINT "TC_GROUP_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "TC_GROUP"."ID" IS 'TC_GROUP.ID';
 
   COMMENT ON COLUMN "TC_GROUP"."GROUP_ID" IS '群組代號';
 
   COMMENT ON COLUMN "TC_GROUP"."GROUP_NAME" IS '群組名稱';
 
   COMMENT ON COLUMN "TC_GROUP"."UPDATE_USER" IS 'ref. TC_USER.ID';
 

  CREATE TABLE "TC_USERGROUP" 
   (	"ID" NUMBER(18,0) NOT NULL ENABLE, 
	"USER_ID" NUMBER(18,0) NOT NULL ENABLE, 
	"GROUP_ID" NUMBER(18,0) DEFAULT 1 NOT NULL ENABLE, 
	"UPDATE_USER" NUMBER(18,0) DEFAULT 1 NOT NULL ENABLE, 
	 CONSTRAINT "TC_USERGROUP_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "TC_USERGROUP_TC_GROUP_FK1" FOREIGN KEY ("GROUP_ID")
	  REFERENCES "TC_GROUP" ("ID") ENABLE, 
	 CONSTRAINT "TC_USERGROUP_TC_USER_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "TC_USER" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "TC_USERGROUP"."ID" IS '使用者群組對照ID';
 
   COMMENT ON COLUMN "TC_USERGROUP"."USER_ID" IS 'TC_USER.ID';
 
   COMMENT ON COLUMN "TC_USERGROUP"."GROUP_ID" IS 'TC_GROUP.ID';
 
   COMMENT ON COLUMN "TC_USERGROUP"."UPDATE_USER" IS 'TC_USER.ID';
 

  CREATE TABLE "TC_APPLICATIONDATA" 
   (	"ID" NUMBER(18,0) NOT NULL ENABLE, 
	"CONTAINERCLASSNAME" NVARCHAR2(255) DEFAULT NULL, 
	"CONTAINERID" NUMBER(18,0) DEFAULT NULL, 
	"CONTENTROLE" NVARCHAR2(1) DEFAULT 'P', 
	"CREATOR" NUMBER(18,0) DEFAULT NULL NOT NULL ENABLE, 
	"CREATETIMESTAMP" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"DESCRIPTION" NVARCHAR2(1000) NOT NULL ENABLE, 
	"FVITEM" NUMBER(18,0) DEFAULT NULL NOT NULL ENABLE, 
	 CONSTRAINT "FUL_APPLICATIONDATA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "TC_APPLICATIONDATA_TC_FVI_FK1" FOREIGN KEY ("FVITEM")
	  REFERENCES "TC_FVITEM" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "TC_APPLICATIONDATA"."ID" IS 'APPLICATIONDATA.ID';
 
   COMMENT ON COLUMN "TC_APPLICATIONDATA"."CONTAINERCLASSNAME" IS 'entity name(ex. com.tcci.hep.entity.LEAVE)';
 
   COMMENT ON COLUMN "TC_APPLICATIONDATA"."CONTAINERID" IS 'entity ID(ex. LEAVE.ID)';
 
   COMMENT ON COLUMN "TC_APPLICATIONDATA"."CONTENTROLE" IS 'Primary:P,Secondary:S';
 
   COMMENT ON COLUMN "TC_APPLICATIONDATA"."CREATOR" IS 'ref TCC_USER';
 
   COMMENT ON COLUMN "TC_APPLICATIONDATA"."CREATETIMESTAMP" IS '建立時間';
 
   COMMENT ON COLUMN "TC_APPLICATIONDATA"."DESCRIPTION" IS '說明';
 
   COMMENT ON COLUMN "TC_APPLICATIONDATA"."FVITEM" IS 'FVITEM.ID';
 

  CREATE UNIQUE INDEX "SYS_C0012463" ON "TC_APPLICATIONDATA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE TABLE "TC_DOMAIN" 
   (	"ID" NUMBER(18,0) NOT NULL ENABLE, 
	"NAME" NVARCHAR2(600) NOT NULL ENABLE, 
	"DESCRIPTION" NVARCHAR2(100) DEFAULT NULL, 
	 CONSTRAINT "FUL_DOMAIN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "TC_DOMAIN"."ID" IS 'DOMAIN.ID';
 
   COMMENT ON COLUMN "TC_DOMAIN"."NAME" IS 'Domain name';
 
   COMMENT ON COLUMN "TC_DOMAIN"."DESCRIPTION" IS '說明';
 

  CREATE UNIQUE INDEX "SYS_C0012466" ON "TC_DOMAIN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE TABLE "TC_FVITEM" 
   (	"ID" NUMBER(18,0) NOT NULL ENABLE, 
	"NAME" NVARCHAR2(255) NOT NULL ENABLE, 
	"FILENAME" NVARCHAR2(255) NOT NULL ENABLE, 
	"FILESIZE" NUMBER(18,0) NOT NULL ENABLE, 
	"CONTENTTYPE" NVARCHAR2(255) DEFAULT NULL, 
	"DOMAIN" NUMBER(18,0) NOT NULL ENABLE, 
	"CREATOR" NUMBER(18,0) DEFAULT NULL NOT NULL ENABLE, 
	"CREATETIMESTAMP" DATE DEFAULT sysdate NOT NULL ENABLE, 
	 CONSTRAINT "FUL_FVITEM_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "TC_FVITEM_TC_DOMAIN_FK1" FOREIGN KEY ("DOMAIN")
	  REFERENCES "TC_DOMAIN" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "TC_FVITEM"."ID" IS 'FVITEM.ID';
 
   COMMENT ON COLUMN "TC_FVITEM"."NAME" IS '實體附件顯示名稱';
 
   COMMENT ON COLUMN "TC_FVITEM"."FILENAME" IS '檔名';
 
   COMMENT ON COLUMN "TC_FVITEM"."FILESIZE" IS '檔案大小';
 
   COMMENT ON COLUMN "TC_FVITEM"."CONTENTTYPE" IS 'mime type';
 
   COMMENT ON COLUMN "TC_FVITEM"."DOMAIN" IS 'ref. DOMAIN.ID';
 
   COMMENT ON COLUMN "TC_FVITEM"."CREATOR" IS '建立者(ref. TC_USER)';
 
   COMMENT ON COLUMN "TC_FVITEM"."CREATETIMESTAMP" IS '建立時間';
 

  CREATE UNIQUE INDEX "SYS_C0012542" ON "TC_FVITEM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE TABLE "TC_FVVAULT" 
   (	"ID" NUMBER(18,0) NOT NULL ENABLE, 
	"NAME" NVARCHAR2(255) DEFAULT NULL, 
	"HOSTNAME" NVARCHAR2(255) NOT NULL ENABLE, 
	"DOMAIN" NUMBER(18,0) NOT NULL ENABLE, 
	"LOCATION" NVARCHAR2(600) NOT NULL ENABLE, 
	"READONLY" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"ENABLED" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"URL" NVARCHAR2(600), 
	 CONSTRAINT "FUL_FVVAULT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "TC_FVVAULT_TC_DOMAIN_FK1" FOREIGN KEY ("DOMAIN")
	  REFERENCES "TC_DOMAIN" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "TC_FVVAULT"."ID" IS 'FVVAULT.ID';
 
   COMMENT ON COLUMN "TC_FVVAULT"."NAME" IS '實體備份目錄';
 
   COMMENT ON COLUMN "TC_FVVAULT"."HOSTNAME" IS '主機名稱';
 
   COMMENT ON COLUMN "TC_FVVAULT"."DOMAIN" IS 'DOMAIN.ID';
 
   COMMENT ON COLUMN "TC_FVVAULT"."LOCATION" IS '實體目錄';
 
   COMMENT ON COLUMN "TC_FVVAULT"."READONLY" IS '是否唯讀[0:false,1:true]';
 
   COMMENT ON COLUMN "TC_FVVAULT"."ENABLED" IS '是否開放[0:false,1,true]';
 
   COMMENT ON COLUMN "TC_FVVAULT"."URL" IS 'http url';
 

  CREATE UNIQUE INDEX "SYS_C0012480" ON "TC_FVVAULT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   CREATE SEQUENCE  "SEQ_FVITEM"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 CACHE 3 NOORDER  NOCYCLE ;
 
REM INSERTING into TC_USER
Insert into TC_USER (ID,LOGIN_ACCOUNT,LOGIN_NAME,EMP_ID,ROLE_ID,IS_VALID,UPDATE_USER) values (4,'greg.chou','周世俊','00800059',1,'Y',1);
Insert into TC_USER (ID,LOGIN_ACCOUNT,LOGIN_NAME,EMP_ID,ROLE_ID,IS_VALID,UPDATE_USER) values (2,'jimmy.lee','李振銘','800067',1,'Y',1);
Insert into TC_USER (ID,LOGIN_ACCOUNT,LOGIN_NAME,EMP_ID,ROLE_ID,IS_VALID,UPDATE_USER) values (3,'jason.yu','游永進','jason.yu',1,'Y',1);
Insert into TC_USER (ID,LOGIN_ACCOUNT,LOGIN_NAME,EMP_ID,ROLE_ID,IS_VALID,UPDATE_USER) values (1,'gilbert.lin','林振雄','00800055',1,'Y',1);
Insert into TC_USER (ID,LOGIN_ACCOUNT,LOGIN_NAME,EMP_ID,ROLE_ID,IS_VALID,UPDATE_USER) values (5,'joe.jen','任成忠','00800054',1,'Y',1);
Insert into TC_USER (ID,LOGIN_ACCOUNT,LOGIN_NAME,EMP_ID,ROLE_ID,IS_VALID,UPDATE_USER) values (6,'wayne.hu','胡憲維','00800058',1,'Y',1);
Insert into TC_USER (ID,LOGIN_ACCOUNT,LOGIN_NAME,EMP_ID,ROLE_ID,IS_VALID,UPDATE_USER) values (7,'alex.chou','周裕健','800053',1,'Y',1);
REM INSERTING into TC_GROUP
Insert into TC_GROUP (ID,GROUP_ID,GROUP_NAME,UPDATE_USER) values (1,'super-group','Super Group',1);
REM INSERTING into TC_USERGROUP
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,UPDATE_USER) values (1,1,1,1);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,UPDATE_USER) values (2,2,1,1);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,UPDATE_USER) values (3,3,1,1);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,UPDATE_USER) values (4,4,1,1);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,UPDATE_USER) values (5,5,1,1);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,UPDATE_USER) values (6,6,1,1);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,UPDATE_USER) values (7,7,1,1);
REM INSERTING into TC_DOMAIN
Insert into TC_DOMAIN (ID,NAME,DESCRIPTION) values (1,'Default','Default');
REM INSERTING into TC_FVVAULT
Insert into TC_FVVAULT (ID,NAME,HOSTNAME,DOMAIN,LOCATION,READONLY,ENABLED,URL) values (1,'Default','localhost',1,'D:\FileVault\APP\Default\',0,1,null);
Insert into TC_FVVAULT (ID,NAME,HOSTNAME,DOMAIN,LOCATION,READONLY,ENABLED,URL) values (2,'Default','remote',1,'E:\FileVault\APP\Default\',0,1,null);
