DROP INDEX TC_ROLEHOLDERROLEMAP_INDEX1;
DROP INDEX TC_WORKITEM_INDEX1;
DROP INDEX TC_VARIABLE_INDEX1;
/

DROP TABLE TC_VARIABLE;
/
DROP TABLE TC_SIGNATURE;
/
DROP TABLE TC_WORKITEM;
/
DROP TABLE TC_ACTIVITYROUTE;
/
DROP TABLE TC_ACTIVITYROUTETEMPLATE;
/
DROP TABLE TC_ACTIVITY;
/
DROP TABLE  TC_ACTIVITYTEMPLATE;
/
DROP TABLE TC_PROCESS;
/

DROP TABLE TC_PROCESSTEMPLATE;
/

DROP TABLE  TC_ROLEPRINCIPALLINK;
/
DROP TABLE  TC_ROLEHOLDERROLEMAP;
/
DROP TABLE  TC_ROLE;
/
DROP TABLE  TC_TEAM;
/
