CREATE INDEX TC_USER_IDX01 ON TC_USER( EMP_ID)
 STORAGE ( INITIAL 1m NEXT 1m PCTINCREASE 0 )
/
CREATE INDEX TC_USERGROUP_IDX01 ON TC_USERGROUP( USER_ID,GROUP_ID)
 STORAGE ( INITIAL 1m NEXT 1m PCTINCREASE 0 )
/
CREATE INDEX SK_FI_MASTER_INTERFACE_IDX01 ON SK_FI_MASTER_INTERFACE( CREATETIMESTAMP)
 STORAGE ( INITIAL 1m NEXT 1m PCTINCREASE 0 )
/
CREATE INDEX SK_FI_MASTER_INTERFACE_IDX02 ON SK_FI_MASTER_INTERFACE( STATUS)
 STORAGE ( INITIAL 1m NEXT 1m PCTINCREASE 0 )
/
CREATE INDEX SK_AR_REMIT_MASTER_IDX01 ON SK_AR_REMIT_MASTER(SAPID)
 STORAGE ( INITIAL 1m NEXT 1m PCTINCREASE 0 )
/
CREATE INDEX SK_AR_REMIT_MASTER_IDX02 ON SK_AR_REMIT_MASTER(CREATETIMESTAMP)
 STORAGE ( INITIAL 1m NEXT 1m PCTINCREASE 0 )
/
CREATE INDEX SK_AR_REMIT_MASTER_IDX03 ON SK_AR_REMIT_MASTER(REVIEW_TIMESTAMP)
 STORAGE ( INITIAL 1m NEXT 1m PCTINCREASE 0 )
/
CREATE INDEX SK_AR_REMIT_MASTER_IDX04 ON SK_AR_REMIT_MASTER(CREATOR)
 STORAGE ( INITIAL 1m NEXT 1m PCTINCREASE 0 )
/

CREATE INDEX SK_AR_REMIT_ITEM_IDX01 ON SK_AR_REMIT_ITEM(CHECK_NUMBER,PAYMENT_TYPE)
 STORAGE ( INITIAL 1m NEXT 1m PCTINCREASE 0 )
/
CREATE INDEX SK_CUSTOMER_IDX01 ON SK_CUSTOMER( SAPID)
 STORAGE ( INITIAL 1m NEXT 1m PCTINCREASE 0 )
/
CREATE INDEX SK_SALES_MEMBER_IDX01 ON SK_SALES_MEMBER( SELECTABLE)
 STORAGE ( INITIAL 1m NEXT 1m PCTINCREASE 0 )
/
CREATE INDEX SK_ACCOUNTS_RECEIVABLE_IDX01 ON SK_ACCOUNTS_RECEIVABLE( INVOICE_TIMESTAMP)
 STORAGE ( INITIAL 1m NEXT 1m PCTINCREASE 0 )
/
CREATE INDEX SK_ADVANCE_REMIT_IDX01 ON SK_ADVANCE_REMIT( REMIT_TYPE,CUSTOMER)
 STORAGE ( INITIAL 1m NEXT 1m PCTINCREASE 0 )
/
CREATE INDEX SK_SALES_DISCOUNT_LOG_IDX01 ON SK_SALES_DISCOUNT_LOG( INVOICE_NUMBER)
 STORAGE ( INITIAL 1m NEXT 1m PCTINCREASE 0 )
/
CREATE INDEX SK_SALES_DETAILS_IDX01 ON SK_SALES_DETAILS( BILLING_TYPE)
 STORAGE ( INITIAL 1m NEXT 1m PCTINCREASE 0 )
/
CREATE INDEX SK_SALES_DETAILS_IDX02 ON SK_SALES_DETAILS( invoice_timestamp)
 STORAGE ( INITIAL 1m NEXT 1m PCTINCREASE 0 )
/
CREATE INDEX SK_CHECK_MASTER_IDX01 ON SK_CHECK_MASTER( CHECK_NUMBER)
 STORAGE ( INITIAL 1m NEXT 1m PCTINCREASE 0 )
/