 --銷售通路
CREATE TABLE SK_SALES_CHANNELS
(
	ID NUMBER(18) NOT NULL ENABLE,
	CODE VARCHAR2(20 BYTE),
	NAME VARCHAR2(70 CHAR),
	PARENT NUMBER(18),
	MANAGER NUMBER(18),
	SUBSTITUTE NUMBER(1) default 0, --可否解繳下屬的單子
	CONSTRAINT SK_SALES_CHANNELS_PK PRIMARY KEY (ID),
	CONSTRAINT SK_SALES_CHANNELS_UK UNIQUE (CODE),
	CONSTRAINT SK_SALES_CHANNELS_FK1 FOREIGN KEY (PARENT) REFERENCES SK_SALES_CHANNELS(ID),
	CONSTRAINT SK_SALES_CHANNELS_FK2 FOREIGN KEY (MANAGER) REFERENCES TC_USER(ID)
)
/
--銷售群駔
CREATE TABLE SK_SALES_MEMBER
(
	ID NUMBER(18) NOT NULL ENABLE,
	CODE VARCHAR2(20 BYTE),
	NAME VARCHAR2(70 CHAR),
	MEMBER NUMBER(18),
	SELECTABLE NUMBER(1) DEFAULT 1,
	CONSTRAINT SK_SALES_MEMBER_PK PRIMARY KEY (ID),
	CONSTRAINT SK_SALES_MEMBER_UK UNIQUE (CODE),
	CONSTRAINT SK_SALES_MEMBER_FK1 FOREIGN KEY (MEMBER) REFERENCES TC_USER(ID)

)
/
CREATE TABLE SK_SALES_CHANNEL_MEMBER
(
	ID NUMBER(18) NOT NULL ENABLE,
	SALES_CHANNEL NUMBER(18),
	SALES_MEMBER NUMBER(18),
	CONSTRAINT SK_SALES_CHANNEL_MEMBER_PK PRIMARY KEY (ID),
	CONSTRAINT SK_SALES_CHANNEL_MEMBER_UK UNIQUE (SALES_CHANNEL,SALES_MEMBER),
	CONSTRAINT SK_SALES_CHANNEL_MEMBER_FK1 FOREIGN KEY (SALES_CHANNEL) REFERENCES SK_SALES_CHANNELS(ID),
	CONSTRAINT SK_SALES_CHANNEL_MEMBER_FK2 FOREIGN KEY (SALES_MEMBER) REFERENCES SK_SALES_MEMBER(ID)

)
/
--CUSTOMER TABLE, GET FROM SAP THAT BACKGROUND OR ETL TO DO MIGRATION
CREATE TABLE SK_CUSTOMER
(	
    ID NUMBER(18) NOT NULL ENABLE, --流水號
	CODE VARCHAR2(20 BYTE), --客戶代碼
	SIMPLE_CODE VARCHAR2(20 BYTE), --客戶簡易代碼
	PARENT_GROUP NUMBER(18), --企業群組	
	VAT VARCHAR2(20 BYTE), --統一編號
	NAME VARCHAR2(70 CHAR), --客戶名稱
	SALES_CHANNEL VARCHAR2(2 BYTE), --銷售通路
	SAPID VARCHAR2(8 BYTE), --銷售群組
	PAYMENT_TERM VARCHAR2(4 BYTE), --付款方式
	CURRENCY VARCHAR2(5 BYTE), --幣別
	ZIP_CODE VARCHAR2(5 BYTE),
	CITY VARCHAR2(40 CHAR),
	STREET VARCHAR2(60 CHAR),
	SHIPPING_CONDITION VARCHAR2(20 BYTE),
	TELEPHONE VARCHAR2(30 BYTE),
	DOS_CODE VARCHAR2(10 BYTE),
	HEALTH_INSURANCE_CODE VARCHAR2(32 BYTE),
	PRICING_PROGRAM VARCHAR2(1 BYTE), --客戶訂價程序 KALKS
	SALES_ALLOWANCES_PAGE VARCHAR2(30 BYTE),--列印頁數,ALL 1 2 3 4, PREVIOUS_TWO
    DISCOUNT_RATE NUMBER(2), --折讓率
	CONTROL_CODE VARCHAR2(64 BYTE),--管制證號
	KUKLA varchar2(2), --客戶分類
	CREATOR NUMBER(18), 
	CREATETIMESTAMP DATE,
	MODIFIER NUMBER(18),
	MODIFYTIMESTAMP DATE,
	CONSTRAINT SK_CUSTOMER_PK PRIMARY KEY (ID),
	CONSTRAINT SK_CUSTOMER_UK UNIQUE (CODE),
	CONSTRAINT SK_CUSTOMER_UK2 UNIQUE (SIMPLE_CODE),
	CONSTRAINT SK_CUSTOMER_FK1 FOREIGN KEY (CREATOR) REFERENCES TC_USER(ID),
	CONSTRAINT SK_CUSTOMER_FK2 FOREIGN KEY (MODIFIER) REFERENCES TC_USER(ID),
	CONSTRAINT SK_CUSTOMER_FK3 FOREIGN KEY (PARENT_GROUP) REFERENCES SK_CUSTOMER(ID)
)
/

COMMENT ON COLUMN SK_SP_USER.SK_CUSTOMER.DISCOUNT_RATE IS '折讓率';
comment on column sk_sp_user.sk_customer.KUKLA is '客戶分類';
--預收款
CREATE TABLE SK_ADVANCE_REMIT
(
	ID NUMBER(18) NOT NULL ENABLE,
	CUSTOMER NUMBER(18),
	AMOUNT NUMBER(15,2),--金額
	REMIT_TIMESTAMP DATE,--預收日期
	REMIT_TYPE VARCHAR2(30 BYTE), --預收款類別
	--CUSTOMER_NUMBER VARCHAR2(20 BYTE), -- TEMP
	--REMIT_DATE VARCHAR2(10 BYTE), -- TEMP
	CREATETIMESTAMP DATE DEFAULT SYSDATE,
	CONSTRAINT SK_ADVANCE_REMIT_PK PRIMARY KEY (ID),
	CONSTRAINT SK_ADVANCE_REMIT_FK1 FOREIGN KEY (CUSTOMER) REFERENCES SK_CUSTOMER(ID)
)
/
--銀行主檔
CREATE TABLE SK_BANK
(
	ID NUMBER(18) NOT NULL ENABLE,
	CODE VARCHAR2(16 BYTE),--銀行代號
	NAME VARCHAR2(128 CHAR),--銀行名稱
	CREATETIMESTAMP DATE default sysdate,
	CONSTRAINT SK_BANK_PK PRIMARY KEY (ID)
)
/
--SP SALES ORDER TABLE , GET FROM SAP THAT BACKGROUND OR ETL TO DO MIGRATION
--銷售主檔, 也包含議價折讓
CREATE TABLE SK_SALES_ORDER_MASTER
(
	ID NUMBER(18) NOT NULL ENABLE,
	ORDER_NUMBER VARCHAR2(20 BYTE), --訂單編號
	ORDER_TIMESTAMP DATE, --訂單日期
	INVOICE_NUMBER VARCHAR2(16 BYTE), --發票編號
	INVOICE_TIMESTAMP DATE, --發票日期
	CUSTOMER NUMBER(18), --客戶
	SHIPPING_CONDITION VARCHAR2(2 BYTE), --出貨條件
	TAX_TYPE VARCHAR2(1 BYTE),--課稅別
	SALES_GROUP VARCHAR2(2 BYTE),--配銷通路
	SAPID VARCHAR2(8 BYTE), --銷售群組	
	AMOUNT NUMBER(15,2),--發票總金額
	AMOUNT_NO_TAX NUMBER(15,2),--未稅總金額
	TAX NUMBER(15,2),--稅總額
	PREMIUM_DISCOUNT NUMBER(15,2),--總溢價折讓
	PREMIUM_DISCOUNT_TAX NUMBER(15,2),--總溢價折讓稅額
	--SALES_DISCOUNT NUMBER(15,2),--事後折讓
	--SALES_DISCOUNT_TAX NUMBER(15,2),--事後折讓稅額
	--SALES_RETURN NUMBER(15,2),--退貨金額
	TOTAL_COST NUMBER(15,2),--成本	
	--銷售淨額
	--BILLING_TYPE VARCHAR2(4 BYTE),請款類型
	CONSTRAINT SK_SALES_ORDER_MASTER_PK PRIMARY KEY (ID),
	CONSTRAINT SK_SALES_ORDER_MASTER_FK1 FOREIGN KEY (CUSTOMER) REFERENCES SK_CUSTOMER(ID)
)
/
CREATE TABLE SK_SALES_ORDER_DETAIL
(
	ID NUMBER(18) NOT NULL ENABLE,
	SALES_ORDER NUMBER(18) ,
	PRODUCT_NUMBER VARCHAR2(18 BYTE),
	PREMIUM_DISCOUNT NUMBER(15,2),--溢價折讓未稅
	PREMIUM_DISCOUNT_TAX NUMBER(13,2),--溢價折讓稅金
	QUANTITY NUMBER(13,3),--數量
	PRICE NUMBER(11,2),--數量
	CONSTRAINT SK_SALES_ORDER_DETAIL_PK PRIMARY KEY (ID),
	CONSTRAINT SK_SALES_ORDER_DETAIL_FK1 FOREIGN KEY (SALES_ORDER) REFERENCES SK_SALES_ORDER_MASTER(ID)
)
/
--銷售事後折讓主檔
CREATE TABLE SK_SALES_DISCOUNT_MASTER
(
	ID NUMBER(18) NOT NULL ENABLE,
	ORDER_NUMBER VARCHAR2(20 BYTE), --訂單編號
	ORDER_TIMESTAMP DATE, --訂單日期
	INVOICE_NUMBER VARCHAR2(16 BYTE), --發票編號
	INVOICE_TIMESTAMP DATE, --發票日期
	CUSTOMER NUMBER(18), --客戶
	SALES_GROUP VARCHAR2(2 BYTE),--配銷通路
	SAPID VARCHAR2(8 BYTE), --銷售群組	
	SALES_DISCOUNT NUMBER(15,2),--事後折讓
	SALES_DISCOUNT_TAX NUMBER(15,2),--事後折讓稅額
	--SALES_RETURN NUMBER(15,2),--退貨金額
	--BILLING_TYPE VARCHAR2(4 BYTE),請款類型
	CONSTRAINT SK_SALES_DISCOUNT_MASTER_PK PRIMARY KEY (ID),
	CONSTRAINT SK_SALES_DISCOUNT_MASTER_FK1 FOREIGN KEY (CUSTOMER) REFERENCES SK_CUSTOMER(ID)
)
/
--銷售退貨主檔
CREATE TABLE SK_SALES_RETURN_MASTER
(
	ID NUMBER(18) NOT NULL ENABLE,
	ORDER_NUMBER VARCHAR2(20 BYTE), --訂單編號
	ORDER_TIMESTAMP DATE, --訂單日期
	INVOICE_NUMBER VARCHAR2(16 BYTE), --發票編號
	INVOICE_TIMESTAMP DATE, --發票日期
	CUSTOMER NUMBER(18), --客戶
	SALES_GROUP VARCHAR2(2 BYTE),--配銷通路
	SAPID VARCHAR2(8 BYTE), --銷售群組	
	SALES_RETURN NUMBER(15,2),--退貨金額
	--BILLING_TYPE VARCHAR2(4 BYTE),請款類型
	CONSTRAINT SK_SALES_RETURN_MASTER_PK PRIMARY KEY (ID),
	CONSTRAINT SK_SALES_RETURN_MASTER_FK1 FOREIGN KEY (CUSTOMER) REFERENCES SK_CUSTOMER(ID)
)
/
--溢價折讓主檔
CREATE TABLE "SK_PREMIUM_DISCOUNT"
(
"ID"                NUMBER(18) NOT NULL ENABLE,
"ORDER_NUMBER"      VARCHAR2(30 BYTE) NOT NULL ENABLE,
"INVOICE_NUMBER"    VARCHAR2(10 BYTE) NOT NULL ENABLE,
"INVOICE_TIMESTAMP" DATE,
"CUSTOMER"          NUMBER(18) NOT NULL,
"SAPID"				VARCHAR(8),
"DISCOUNT"            NUMBER (15,2) DEFAULT 0 NOT NULL ,
"TAX"               NUMBER (15,2) DEFAULT 0 NOT NULL ,
"UPLOAD_TIMESTAMP"  DATE,
"YEAR"              VARCHAR2(4) NOT NULL,
"MONTH"             VARCHAR2(2) NOT NULL,
"CREATOR"           NUMBER(18), 
"CREATETIMESTAMP"   DATE,
"MODIFIER"          NUMBER(18) , 
"MODIFYTIMESTAMP"   DATE,
"RETURN_CODE"       VARCHAR2(255),
"ERROR_MESSAGE"     VARCHAR2(4000),
"ORDER_TIMESTAMP"	DATE,
"INTERFACE_ID" 		NUMBER(18),
CONSTRAINT "SK_PREMIUM_DISCOUNT_PK" PRIMARY KEY (ID),
CONSTRAINT "SK_PREMIUM_DISCOUNT_FK1" FOREIGN KEY (CREATOR) REFERENCES TC_USER(ID),
CONSTRAINT "SK_PREMIUM_DISCOUNT_FK2" FOREIGN KEY (MODIFIER) REFERENCES TC_USER(ID),
CONSTRAINT "SK_PREMIUM_DISCOUNT_FK3" FOREIGN KEY (CUSTOMER) REFERENCES SK_CUSTOMER(ID)
);

COMMENT ON COLUMN "SK_SP_USER"."SK_PREMIUM_DISCOUNT"."ID" IS 'PK';
COMMENT ON COLUMN "SK_SP_USER"."SK_PREMIUM_DISCOUNT"."ORDER_NUMBER" IS '訂單編號';
COMMENT ON COLUMN "SK_SP_USER"."SK_PREMIUM_DISCOUNT"."INVOICE_NUMBER" IS '發票號碼';
COMMENT ON COLUMN "SK_SP_USER"."SK_PREMIUM_DISCOUNT"."INVOICE_TIMESTAMP" IS '發票日期';
COMMENT ON COLUMN "SK_SP_USER"."SK_PREMIUM_DISCOUNT"."CUSTOMER" IS 'FK:SK_CUSTOMER.ID';
COMMENT ON COLUMN "SK_SP_USER"."SK_PREMIUM_DISCOUNT"."SAPID" IS '銷售群組';
COMMENT ON COLUMN "SK_SP_USER"."SK_PREMIUM_DISCOUNT"."DISCOUNT" IS '未稅折讓';
COMMENT ON COLUMN "SK_SP_USER"."SK_PREMIUM_DISCOUNT"."TAX" IS '折讓稅金';
COMMENT ON COLUMN "SK_SP_USER"."SK_PREMIUM_DISCOUNT"."UPLOAD_TIMESTAMP" IS '上傳時間';
COMMENT ON COLUMN "SK_SP_USER"."SK_PREMIUM_DISCOUNT"."YEAR" IS '年';
COMMENT ON COLUMN "SK_SP_USER"."SK_PREMIUM_DISCOUNT"."MONTH" IS '月';
COMMENT ON COLUMN "SK_SP_USER"."SK_PREMIUM_DISCOUNT"."CREATOR" IS 'FK:TC_USER.ID';
COMMENT ON COLUMN "SK_SP_USER"."SK_PREMIUM_DISCOUNT"."CREATETIMESTAMP" IS '建立時間';
COMMENT ON COLUMN "SK_SP_USER"."SK_PREMIUM_DISCOUNT"."MODIFIER" IS 'FK:TC_USER.ID';
COMMENT ON COLUMN "SK_SP_USER"."SK_PREMIUM_DISCOUNT"."MODIFYTIMESTAMP" IS '修改時間';
COMMENT ON COLUMN "SK_SP_USER"."SK_PREMIUM_DISCOUNT"."RETURN_CODE" IS '錯誤代碼';
COMMENT ON COLUMN "SK_SP_USER"."SK_PREMIUM_DISCOUNT"."ERROR_MESSAGE" IS '錯誤訊息';

CREATE TABLE "SK_SALES_DISCOUNT_LOG"
(
"ID" NUMBER(18) NOT NULL ENABLE,
"INVOICE_NUMBER"  VARCHAR2(16 BYTE),
"CREATOR"	NUMBER(18),
"CREATETIMESTAMP" DATE,
CONSTRAINT "SK_SALES_DISCOUNT_LOG_PK" PRIMARY KEY("ID"),
CONSTRAINT "SK_SALES_DISCOUNT_LOG_FK1" FOREIGN KEY ("CREATOR") REFERENCES TC_USER("ID")
);

COMMENT ON COLUMN "SK_SP_USER"."SK_SALES_DISCOUNT_LOG"."ID" IS 'PK';
COMMENT ON COLUMN "SK_SP_USER"."SK_SALES_DISCOUNT_LOG"."INVOICE_NUMBER" IS 'INVOICE_NUMBER';
COMMENT ON COLUMN "SK_SP_USER"."SK_SALES_DISCOUNT_LOG"."CREATOR" IS 'FK:TC_USER.ID';
COMMENT ON COLUMN "SK_SP_USER"."SK_SALES_DISCOUNT_LOG"."CREATETIMESTAMP" IS '建立時間';


--AR TABLE , GET FROM SAP THAT BACKGROUND OR ETL TO DO MIGRATION
CREATE TABLE SK_ACCOUNTS_RECEIVABLE
(
	ID NUMBER(18) NOT NULL ENABLE,
	CUSTOMER  NUMBER(18),
	ORDER_NUMBER VARCHAR2(30 BYTE),
	INVOICE_NUMBER VARCHAR2(16 BYTE),
	INVOICE_TIMESTAMP DATE,
	AMOUNT NUMBER(15,2),--應收帳款
	PREMIUM_DISCOUNT NUMBER(15,2),--溢價折讓
	SAPID VARCHAR2(10),--銷售群組
	AR_DUE_DATE DATE,--應收到期
	CREATOR NUMBER(18) , 
	CREATETIMESTAMP DATE,
	MODIFIER NUMBER(18) , 
	MODIFYTIMESTAMP DATE,
	--CUSTOMER_NUMBER VARCHAR2(20 BYTE),
	CONSTRAINT SK_ACCOUNTS_RECEIVABLE_PK PRIMARY KEY (ID),
	CONSTRAINT SK_ACCOUNTS_RECEIVABLE_UK UNIQUE (ID,ORDER_NUMBER),
	CONSTRAINT SK_ACCOUNTS_RECEIVABLE_FK1 FOREIGN KEY (CREATOR) REFERENCES TC_USER(ID),
	CONSTRAINT SK_ACCOUNTS_RECEIVABLE_FK2 FOREIGN KEY (MODIFIER) REFERENCES TC_USER(ID),
	CONSTRAINT SK_ACCOUNTS_RECEIVABLE_FK3 FOREIGN KEY (CUSTOMER) REFERENCES SK_CUSTOMER(ID)
)
/
--解繳主檔
CREATE TABLE SK_AR_REMIT_MASTER
(
	ID NUMBER(18) NOT NULL ENABLE,
	--REMIT_ID VARCHAR2(20 BYTE),
	CUSTOMER  NUMBER(18),
	SAPID VARCHAR2(10),--銷售群組
	BANK VARCHAR2(20 BYTE),--銀行	
	REMITTANCE_AMOUNT NUMBER(15,2), --現金金額
	CHECK_AMOUNT NUMBER(15,2) , --支票金額
	FINANCE_REVIEWER NUMBER(18),
	STATUS VARCHAR2(60 BYTE), --NOT YET,REVIEWED,TRANSFER_SAP,TRANSFER_OK,TRANSFER_FAILED
	REVIEW_TIMESTAMP DATE,
	CREATOR NUMBER(18) , 
	CREATETIMESTAMP DATE,
	MODIFIER NUMBER(18) , 
	MODIFYTIMESTAMP DATE,
	INTERFACE_ID NUMBER(18),
	CONSTRAINT SK_AR_REMIT_MASTER_PK PRIMARY KEY (ID),
	CONSTRAINT SK_AR_REMIT_MASTER_FK1 FOREIGN KEY (CREATOR) REFERENCES TC_USER(ID),
	CONSTRAINT SK_AR_REMIT_MASTER_FK2 FOREIGN KEY (MODIFIER) REFERENCES TC_USER(ID),
	CONSTRAINT SK_AR_REMIT_MASTER_FK3 FOREIGN KEY (CUSTOMER) REFERENCES SK_CUSTOMER(ID)
	--CONSTRAINT SK_AR_REMIT_MASTER_UK UNIQUE (REMIT_ID)
)
/
--解繳明細主檔
CREATE TABLE SK_AR_REMIT_ITEM
(
	ID NUMBER(18) NOT NULL ENABLE,
	--ACCOUNTS_RECEIVABLE  NUMBER(18),
	ORDER_NUMBER VARCHAR2(30 BYTE),
	INVOICE_NUMBER VARCHAR2(16 BYTE),
	INVOICE_TIMESTAMP DATE,
	AR_AMOUNT NUMBER(15,2),--應收帳款
	PREMIUM_DISCOUNT NUMBER(15,2) ,--溢價折讓
	AR_DUE_DATE DATE,--應收到期	
	AR_REMIT_MASTER  NUMBER(18),
	REMIT_TYPE VARCHAR2(20 BYTE),--銷貨折讓,銷貨退回,-AR,尾差/手續費,預收,現金(匯款)/支票
	SALES_DISCOUNT NUMBER(15,2), --銷貨折讓
	SALES_RETURN NUMBER(15,2), --銷貨退回
    NEGATIVE_AR NUMBER(15,2), ---AR
	DIFFERENCE_CHARGE NUMBER(3), --尾差/手續費
	ADVANCE_RECEIPTS_A NUMBER(15,2), --預收A
	ADVANCE_RECEIPTS_J NUMBER(15,2), --預收J
	PAYMENT_TYPE VARCHAR2(20 BYTE),--現金/支票(一)
	PAYMENT_TYPE2 VARCHAR2(20 BYTE),--現金/支票(二)
	CHECK_NUMBER VARCHAR2(20 BYTE),--支票號碼(一)
	CHECK_NUMBER2 VARCHAR2(20 BYTE) default 0,--支票號碼(二)
	AMOUNT NUMBER(15,2),  --沖帳金額(一)
	AMOUNT2 NUMBER(15,2), --沖帳金額(二)
	CREATOR NUMBER(18) , 
	CREATETIMESTAMP DATE default SYSDATE,
	MODIFIER NUMBER(18) , 
	MODIFYTIMESTAMP DATE,
	CONSTRAINT SK_AR_REMIT_ITEM_PK PRIMARY KEY (ID),
	CONSTRAINT SK_AR_REMIT_ITEM_FK1 FOREIGN KEY (AR_REMIT_MASTER) REFERENCES SK_AR_REMIT_MASTER(ID),
	--CONSTRAINT SK_AR_REMIT_ITEM_FK2 FOREIGN KEY (ACCOUNTS_RECEIVABLE) REFERENCES SK_ACCOUNTS_RECEIVABLE(ID),
	CONSTRAINT SK_AR_REMIT_ITEM_FK3 FOREIGN KEY (CREATOR) REFERENCES TC_USER(ID),
	CONSTRAINT SK_AR_REMIT_ITEM_FK4 FOREIGN KEY (MODIFIER) REFERENCES TC_USER(ID)
)
/
--解繳明細上傳主檔
CREATE TABLE SK_FI_MASTER_INTERFACE
(
	ID NUMBER(18) NOT NULL ENABLE,
	TRANSACTION_NO VARCHAR2(10) NOT NULL,
	REFERENCECLASSNAME VARCHAR2(180) NOT NULL , -- SK 參考類別
	REFERENCEID	NUMBER(18) NOT NULL , -- SK 參考ID
	STATUS VARCHAR2(20), -- TRANSACTION STATUS
	RETURN_CODE VARCHAR2(10), -- ERROR CODE
	RETURN_MESSAGE VARCHAR2(255 CHAR),
  UPLOADER number(18),
  UPLOAD_TIMESTAMP date,
  CREATOR number(18),
  CREATETIMESTAMP date,
	CONSTRAINT SK_FI_MASTER_INTERFACE_PK PRIMARY KEY (ID),
	CONSTRAINT SK_FI_MASTER_INTERFACE_UK1 UNIQUE (REFERENCECLASSNAME,REFERENCEID),
  CONSTRAINT SK_FI_MASTER_INTERFACE_FK1 FOREIGN KEY (UPLOADER) REFERENCES TC_USER(ID),
  CONSTRAINT SK_FI_MASTER_INTERFACE_FK2 FOREIGN KEY (CREATOR) REFERENCES TC_USER(ID)
)
/
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_MASTER_INTERFACE"."ID" IS 'PK';
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_MASTER_INTERFACE"."TRANSACTION_NO" IS 'TRNNO 交易編號';
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_MASTER_INTERFACE"."REFERENCECLASSNAME" IS 'SK 參考類別';
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_MASTER_INTERFACE"."REFERENCEID" IS 'SK 參考ID';
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_MASTER_INTERFACE"."STATUS" IS 'TRANSACTION STATUS';
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_MASTER_INTERFACE"."RETURN_CODE" IS 'ERROR CODE';
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_MASTER_INTERFACE"."UPLOADER" IS 'FK:TC_USER.ID';
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_MASTER_INTERFACE"."UPLOAD_TIMESTAMP" is '上傳時間';
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_MASTER_INTERFACE"."CREATOR" IS 'FK:TC_USER.ID';
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_MASTER_INTERFACE"."CREATETIMESTAMP" is '建立時間';

/
--解繳明細上傳檔
CREATE TABLE SK_FI_DETAIL_INTERFACE
(
	"ID" 				NUMBER(18) NOT NULL ENABLE, --TRNNO 交易編號
	MASTER NUMBER(18),
	"TRANSACTION_ITEM" 		VARCHAR2(3), --TRNITM 交易序號
	"TRANSACTION_DATE" 		DATE, --TRNDT 交易日期
	"TRANSACTION_TYPE"	VARCHAR2(4), --TRNTP 科目代碼 
	"GENERAL_LEDGER_CODE"				VARCHAR2(6),--FGLID 科目代碼
	"SUMMONS_CODE"			VARCHAR2(2),--FDBCR 借貸碼
	"CUSTOMER_NUMBER"	VARCHAR2(10), --CUSNO 客戶編號
	"INVOICE_NUMBER"				VARCHAR2(16), --INVNO 發票號碼
	"ORDER_NUMBER"			VARCHAR2(10), --SALNO 訂單號碼
	"SALES_GROUP"				VARCHAR2(4), --SALGRP 銷售群組
	"TRANSACTION_AMOUNT"		NUMBER(15,2), --TRNAMT 交易金額
	"QUANTITY"			NUMBER(8,2), --TRNQTY 數量
	"CHECK_NUMBER"			VARCHAR2(10), --CHKNO 票據號碼
	"CHECK_DUE_DATE"	DATE, --CHKDT 票據日期
	"CHECK_BANK"		VARCHAR2(10), --CHKBK 開票行
	"CHECK_ACCOUNT"		VARCHAR2(16),--CHKAC 開票帳號
	"OWNER"		VARCHAR2(16), --OWNER 作業人員
	"STATUS" VARCHAR2(2), --STFLG 檢核狀態
	"UPLOAD_TIMESTAMP"	DATE, -- UPLDT 上傳日期
	"UPLOADER"			VARCHAR2(16), --UPLBY 上傳人員
	"CREATETIMESTAMP"	DATE, -- SK 建立日期
	"CREATOR"			NUMBER(18), -- SK 建立者
	"MODIFYTIMESTAMP"	DATE, -- SK 修改者
	"MODIFIER"			NUMBER(18), -- SK 修改時間
	"REFERENCECLASSNAME" VARCHAR2(240), -- SK 參考類別
	"REFERENCEID"	NUMBER(18), -- SK 參考ID
	"RETURN_CODE" VARCHAR2(10), -- ERROR CODE
	"RETURN_MESSAGE" VARCHAR2(255 CHAR), --ERROR MESSAGE
	CONSTRAINT SK_FI_DETAIL_INTERFACE_PK PRIMARY KEY("ID"),
	CONSTRAINT SK_FI_DETAIL_INTERFACE_FK1 FOREIGN KEY (MASTER) REFERENCES SK_FI_MASTER_INTERFACE(ID),
	CONSTRAINT SK_FI_DETAIL_INTERFACE_FK2 FOREIGN KEY (CREATOR) REFERENCES TC_USER(ID),
	CONSTRAINT SK_FI_DETAIL_INTERFACE_FK3 FOREIGN KEY (MODIFIER) REFERENCES TC_USER(ID)
);
/
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_DETAIL_INTERFACE"."ID" IS 'PK';
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_DETAIL_INTERFACE"."TRANSACTION_ITEM" IS 'TRNITM 交易序號';
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_DETAIL_INTERFACE"."TRANSACTION_DATE" IS 'TRNDT 交易日期';
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_DETAIL_INTERFACE"."TRANSACTION_TYPE" IS 'TRNTP 科目代碼 ';
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_DETAIL_INTERFACE"."GENERAL_LEDGER_CODE" IS 'FGLID 科目代碼';
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_DETAIL_INTERFACE"."SUMMONS_CODE" IS 'FDBCR 借貸碼';
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_DETAIL_INTERFACE"."CUSTOMER_NUMBER" IS 'CUSNO 客戶編號';
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_DETAIL_INTERFACE"."INVOICE_NUMBER" IS 'INVNO 發票號碼';
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_DETAIL_INTERFACE"."ORDER_NUMBER" IS 'SALNO 訂單號碼';
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_DETAIL_INTERFACE"."SALES_GROUP" IS 'SALGRP 銷售群組';
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_DETAIL_INTERFACE"."TRANSACTION_AMOUNT" IS 'TRNAMT 交易金額';
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_DETAIL_INTERFACE"."QUANTITY" IS 'TRNQTY 數量';
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_DETAIL_INTERFACE"."CHECK_NUMBER" IS 'CHKNO 票據號碼';
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_DETAIL_INTERFACE"."CHECK_DUE_DATE" IS '票據日期';
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_DETAIL_INTERFACE"."CHECK_BANK" IS 'CHKBK 開票行';
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_DETAIL_INTERFACE"."CHECK_ACCOUNT" IS 'CHKAC 開票帳號';
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_DETAIL_INTERFACE"."OWNER" IS 'OWNER 作業人員';
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_DETAIL_INTERFACE"."STATUS" IS 'STFLG 檢核狀態';
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_DETAIL_INTERFACE"."UPLOAD_TIMESTAMP" IS 'UPLDT 上傳日期';
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_DETAIL_INTERFACE"."UPLOADER" IS 'UPLBY 上傳人員';
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_DETAIL_INTERFACE"."CREATETIMESTAMP" IS 'SK 建立日期';
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_DETAIL_INTERFACE"."CREATOR" IS 'SK 建立者';
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_DETAIL_INTERFACE"."MODIFYTIMESTAMP" IS 'SK 修改者';
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_DETAIL_INTERFACE"."MODIFIER" IS 'SK 修改時間';
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_DETAIL_INTERFACE"."REFERENCECLASSNAME" IS 'SK 參考類別';
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_DETAIL_INTERFACE"."REFERENCEID" IS 'SK 參考ID';
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_DETAIL_INTERFACE"."RETURN_CODE" IS 'ERROR CODE';
COMMENT ON COLUMN "SK_SP_USER"."SK_FI_DETAIL_INTERFACE"."RETURN_MESSAGE" IS 'ERROR MESSAGE';
/
--解繳明細支票號碼
--CREATE TABLE SK_AR_REMIT_ITEM_CHECK
--(
--	ID NUMBER(18) NOT NULL ENABLE,
--	AR_REMIT_ITEM  NUMBER(18),
--	CHECK_NUMBER VARCHAR2(20 BYTE),--支票號碼
--	CREATOR NUMBER(18) , 
--	CREATETIMESTAMP DATE,
--	MODIFIER NUMBER(18) , 
--	MODIFYTIMESTAMP DATE,
--	CONSTRAINT SK_AR_REMIT_ITEM_CHECK_PK PRIMARY KEY (ID),
--	CONSTRAINT SK_AR_REMIT_ITEM_CHECK_FK1 FOREIGN KEY (AR_REMIT_ITEM) REFERENCES SK_AR_REMIT_ITEM(ID),
--    CONSTRAINT SK_AR_REMIT_ITEM_CHECK_FK2 FOREIGN KEY (CREATOR) REFERENCES TC_USER(ID),
--	CONSTRAINT SK_AR_REMIT_ITEM_CHECK_FK3 FOREIGN KEY (MODIFIER) REFERENCES TC_USER(ID)
--)
--/
--解繳明細匯款銀行
--CREATE TABLE SK_AR_REMIT_ITEM_BANK
--(
--	ID NUMBER(18) NOT NULL ENABLE,
--	AR_REMIT_ITEM  NUMBER(18),
--	BANK VARCHAR2(20 BYTE),--銀行
--	CREATOR NUMBER(18) , 
--	CREATETIMESTAMP DATE,
--	MODIFIER NUMBER(18) , 
--	MODIFYTIMESTAMP DATE,
--	CONSTRAINT SK_AR_REMIT_ITEM_BANK_PK PRIMARY KEY (ID),
--	CONSTRAINT SK_AR_REMIT_ITEM_BANK_FK1 FOREIGN KEY (AR_REMIT_ITEM) REFERENCES SK_AR_REMIT_ITEM(ID),
--	CONSTRAINT SK_AR_REMIT_ITEM_BANK_FK2 FOREIGN KEY (CREATOR) REFERENCES TC_USER(ID),
--	CONSTRAINT SK_AR_REMIT_ITEM_BANK_FK3 FOREIGN KEY (MODIFIER) REFERENCES TC_USER(ID)
--)
--
--預收主檔
CREATE TABLE "SK_SP_USER"."SK_ADVANCE_PAYMENT"
(
	"ID" NUMBER(18) NOT NULL ENABLE,
  "AR_REMIT_MASTER" NUMBER(18),
	"CUSTOMER"  NUMBER(18),
	"AMOUNT" NUMBER(15,2),
	"CREATOR" NUMBER(18) , 
	"CREATETIMESTAMP" DATE,
	"MODIFIER" NUMBER(18) , 
	"MODIFYTIMESTAMP" DATE,
	INTERFACE_ID NUMBER(18),
	CONSTRAINT SK_ADVANCE_PAYMENT_PK PRIMARY KEY (ID),
  CONSTRAINT SK_ADVANCE_PAYMENT_FK1 FOREIGN KEY (AR_REMIT_MASTER) REFERENCES SK_AR_REMIT_MASTER(ID),
	CONSTRAINT SK_ADVANCE_PAYMENT_FK2 FOREIGN KEY (CREATOR) REFERENCES TC_USER(ID),
	CONSTRAINT SK_ADVANCE_PAYMENT_FK3 FOREIGN KEY (MODIFIER) REFERENCES TC_USER(ID),
	CONSTRAINT SK_ADVANCE_PAYMENT_FK4 FOREIGN KEY (CUSTOMER) REFERENCES SK_CUSTOMER(ID)
)
/
COMMENT ON COLUMN "SK_SP_USER"."SK_ADVANCE_PAYMENT"."ID" IS 'PK';
COMMENT ON COLUMN "SK_SP_USER"."SK_ADVANCE_PAYMENT"."CUSTOMER" IS 'FK:SK_CUSTOMER.ID';
--COMMENT ON COLUMN "SK_SP_USER"."SK_ADVANCE_PAYMENT"."CHECK_MASTER" IS 'FK:SK_CHECK_MASTER.ID';
COMMENT ON COLUMN "SK_SP_USER"."SK_ADVANCE_PAYMENT"."AMOUNT" IS '預收現金金額';
COMMENT ON COLUMN "SK_SP_USER"."SK_ADVANCE_PAYMENT"."CREATOR" IS '建立者';
COMMENT ON COLUMN "SK_SP_USER"."SK_ADVANCE_PAYMENT"."CREATETIMESTAMP" IS '建立時間';
COMMENT ON COLUMN "SK_SP_USER"."SK_ADVANCE_PAYMENT"."MODIFIER" IS '建立者';
COMMENT ON COLUMN "SK_SP_USER"."SK_ADVANCE_PAYMENT"."MODIFYTIMESTAMP" IS '修改時間';
/
CREATE TABLE SK_CHECK_MASTER
(
	ID NUMBER(18) NOT NULL ENABLE,
	CHECK_NUMBER VARCHAR2(10 BYTE),--支票號碼
	CUSTOMER  NUMBER(18),
	DUE_DATE DATE,
	--BILLING_BANK VARCHAR2(60 BYTE),
	BILLING_BANK NUMBER(18),
	BILLING_ACCOUNT VARCHAR2(16 BYTE),
	AMOUNT NUMBER(15,2),
  ADVANCE_PAYMENT NUMBER(18),
	CREATOR NUMBER(18) , 
	CREATETIMESTAMP DATE,
	MODIFIER NUMBER(18) , 
	MODIFYTIMESTAMP DATE,
	CONSTRAINT SK_CHECK_MASTER_PK PRIMARY KEY (ID),
	CONSTRAINT SK_CHECK_MASTER_FK1 FOREIGN KEY (CREATOR) REFERENCES TC_USER(ID),
	CONSTRAINT SK_CHECK_MASTER_FK2 FOREIGN KEY (MODIFIER) REFERENCES TC_USER(ID),
	CONSTRAINT SK_CHECK_MASTER_FK3 FOREIGN KEY (CUSTOMER) REFERENCES SK_CUSTOMER(ID),
	CONSTRAINT SK_CHECK_MASTER_FK4 FOREIGN KEY (BILLING_BANK) REFERENCES SK_BANK(ID),
  CONSTRAINT SK_CHECK_MASTER_FK5 FOREIGN KEY (ADVANCE_PAYMENT) REFERENCES SK_ADVANCE_PAYMENT(ID)
)
/
--產品主檔
CREATE TABLE SK_PRODUCT_MASTER
(
	ID NUMBER(18) NOT NULL ENABLE,
	CODE VARCHAR2(18 BYTE), --產品編號
	NAME VARCHAR2(64 CHAR), --產品名稱
	CREATOR NUMBER(18) , 
	CREATETIMESTAMP DATE,
	MODIFIER NUMBER(18) , 
	MODIFYTIMESTAMP DATE,
	CONSTRAINT SK_PRODUCT_MASTER_PK PRIMARY KEY (ID),
	CONSTRAINT SK_PRODUCT_MASTER_UK UNIQUE (CODE),
	CONSTRAINT SK_PRODUCT_MASTER_FK1 FOREIGN KEY (CREATOR) REFERENCES TC_USER(ID),
	CONSTRAINT SK_PRODUCT_MASTER_FK2 FOREIGN KEY (MODIFIER) REFERENCES TC_USER(ID)
)
/
--產品群組檔
CREATE TABLE SK_PRODUCT_CATEGORY
(
  ID NUMBER(18) NOT NULL ENABLE,
  CATEGORY VARCHAR2(10),
  DESCRIPTION VARCHAR2(30),
  REMARK VARCHAR2(15),
  CONSTRAINT SK_PRODUCT_CATEGORY_PK PRIMARY KEY (ID)
);

--逾期帳款主檔
CREATE TABLE SK_OVERDUE_AR
(
	ID NUMBER(18) NOT NULL ENABLE,
	BASELINE_TIMESTAMP DATE,--逾期帳款的時間(年,月)
	INVOICE_NUMBER VARCHAR2(16 BYTE), --發票號碼
	INVOICE_TIMESTAMP DATE, --發票日期
	INVOICE_AMOUNT NUMBER(13,2) , --發票金額
	ORDER_NUMBER VARCHAR2(16 BYTE),--訂單號碼
	SAPID VARCHAR2(4 BYTE),--銷售群組
	--CUSTOMER_NUMBER VARCHAR2(20 BYTE), --客戶編號
	--CUSTOMER_NAME VARCHAR2(70 CHAR), --客戶名稱
	CUSTOMER NUMBER(18),
	OVERDUE_DAYS_NUMBER NUMBER(6), --帳齡天數
	CREATETIMESTAMP DATE DEFAULT SYSDATE,
	CONSTRAINT SK_OVERDUE_AR_PK PRIMARY KEY (ID),
	CONSTRAINT SK_OVERDUE_AR_FK1 FOREIGN KEY (CUSTOMER) REFERENCES SK_CUSTOMER(ID)
)
/
//解繳率
CREATE TABLE SK_PAYMENT_RATE(
	ID NUMBER(18) NOT NULL ENABLE,
	BASELINE_TIMESTAMP DATE,--解繳資料的時間(年,月)
	SAPID VARCHAR2(10 BYTE), --銷售群組
	AR_AMOUNT NUMBER(13,2), --應收帳款
	PREMIUM_DISCOUNT NUMBER(13,2), --事前折讓
	SALES_RETURN NUMBER(13,2), --退貨
	SALES_DISCOUNT NUMBER(13,2),--事後折讓
	PAYMENT_AMOUNT NUMBER(13,2), --收款金額
	PAYMENT_RATE NUMBER(5,4),--解繳率
	WEIGHT NUMBER(2,1),--權值
	CREATETIMESTAMP DATE DEFAULT SYSDATE,
	CONSTRAINT SK_PAYMENT_RATE_PK PRIMARY KEY (ID)
)
/
COMMENT ON COLUMN "SK_SP_USER"."SK_PAYMENT_RATE"."ID" IS 'PK';
COMMENT ON COLUMN "SK_SP_USER"."SK_PAYMENT_RATE"."BASELINE_TIMESTAMP" IS '解繳資料的時間(年,月)';
COMMENT ON COLUMN "SK_SP_USER"."SK_PAYMENT_RATE"."SAPID" IS '銷售群組';
COMMENT ON COLUMN "SK_SP_USER"."SK_PAYMENT_RATE"."AR_AMOUNT" IS '應收帳款';
COMMENT ON COLUMN "SK_SP_USER"."SK_PAYMENT_RATE"."PREMIUM_DISCOUNT" IS '事前折讓';
COMMENT ON COLUMN "SK_SP_USER"."SK_PAYMENT_RATE"."SALES_RETURN" IS '退貨';
COMMENT ON COLUMN "SK_SP_USER"."SK_PAYMENT_RATE"."SALES_DISCOUNT" IS '事後折讓';
COMMENT ON COLUMN "SK_SP_USER"."SK_PAYMENT_RATE"."PAYMENT_AMOUNT" IS '收款金額';
COMMENT ON COLUMN "SK_SP_USER"."SK_PAYMENT_RATE"."PAYMENT_RATE" IS '解繳率';
COMMENT ON COLUMN "SK_SP_USER"."SK_PAYMENT_RATE"."WEIGHT" IS '權值';
/
CREATE TABLE SK_PAYMENT_ITEM(
	ID NUMBER(18) NOT NULL ENABLE,
	BASELINE_TIMESTAMP DATE,--解繳資料的時間(年,月)
	CUSTOMER NUMBER(18),
	ORDER_NUMBER VARCHAR2(16 BYTE),--訂單號碼
	INVOICE_NUMBER VARCHAR2(54 CHAR), --發票號碼
	SAPID VARCHAR2(10 BYTE), --銷售群組
	AR_AMOUNT NUMBER(13,2), --應收帳款
	PREMIUM_DISCOUNT NUMBER(13,2), --事前折讓
	SALES_RETURN NUMBER(13,2), --退貨
	SALES_DISCOUNT NUMBER(13,2),--事後折讓
	PAYMENT_AMOUNT NUMBER(13,2), --收款金額
	CREATETIMESTAMP DATE DEFAULT SYSDATE,
	CONSTRAINT SK_PAYMENT_ITEM_PK PRIMARY KEY (ID),
	CONSTRAINT SK_PAYMENT_ITEM_FK1 FOREIGN KEY (CUSTOMER) REFERENCES SK_CUSTOMER(ID)
)
/
COMMENT ON COLUMN "SK_SP_USER"."SK_PAYMENT_ITEM"."ID" IS 'PK';
COMMENT ON COLUMN "SK_SP_USER"."SK_PAYMENT_ITEM"."BASELINE_TIMESTAMP" IS '解繳資料的時間(年,月)';
COMMENT ON COLUMN "SK_SP_USER"."SK_PAYMENT_ITEM"."CUSTOMER" IS '客戶';
COMMENT ON COLUMN "SK_SP_USER"."SK_PAYMENT_ITEM"."ORDER_NUMBER" IS '訂單號碼';
COMMENT ON COLUMN "SK_SP_USER"."SK_PAYMENT_ITEM"."INVOICE_NUMBER" IS '發票號碼';
COMMENT ON COLUMN "SK_SP_USER"."SK_PAYMENT_ITEM"."SAPID" IS '銷售群組';
COMMENT ON COLUMN "SK_SP_USER"."SK_PAYMENT_ITEM"."AR_AMOUNT" IS '應收帳款';
COMMENT ON COLUMN "SK_SP_USER"."SK_PAYMENT_ITEM"."PREMIUM_DISCOUNT" IS '事前折讓';
COMMENT ON COLUMN "SK_SP_USER"."SK_PAYMENT_ITEM"."SALES_RETURN" IS '退貨';
COMMENT ON COLUMN "SK_SP_USER"."SK_PAYMENT_ITEM"."SALES_DISCOUNT" IS '事後折讓';
COMMENT ON COLUMN "SK_SP_USER"."SK_PAYMENT_ITEM"."PAYMENT_AMOUNT" IS '收款金額';
/
-- 銷售預算
CREATE TABLE SK_BUDGET(
	ID NUMBER(18) NOT NULL ENABLE,
	SAPID VARCHAR2(10 BYTE), --銷售群組
	BASELINE_TIMESTAMP DATE,--預算年月(年,月)
	BUDGET NUMBER(13,2), --預算
	CREATOR NUMBER(18) , 
	CREATETIMESTAMP DATE,
	MODIFIER NUMBER(18) , 
	MODIFYTIMESTAMP DATE,
	CONSTRAINT SK_BUDGET_PK PRIMARY KEY (ID),
	CONSTRAINT SK_BUDGET_UK1 UNIQUE (SAPID,BASELINE_TIMESTAMP),
	CONSTRAINT SK_BUDGET_FK1 FOREIGN KEY (CREATOR) REFERENCES TC_USER(ID),
	CONSTRAINT SK_BUDGET_FK2 FOREIGN KEY (MODIFIER) REFERENCES TC_USER(ID)	
)
/
-- 工作天數
--CREATE TABLE SK_WORKINGDAYS (
--	ID NUMBER(18) NOT NULL ENABLE,
--	BASELINE_TIMESTAMP DATE,--年月(年,月)
--	DAYS NUMBER(2) DEFAULT 0,
--	CONSTRAINT SK_WORKINGDAYS_PK PRIMARY KEY (ID)
--)
--/
-- Calendar
CREATE TABLE SK_CALENDAR (
	ID NUMBER(18) NOT NULL ENABLE,
	BASELINE_TIMESTAMP DATE,--年月日(年,月,日)
	ISWORKINGDAY NUMBER(1,0) DEFAULT 1,
	CONSTRAINT SK_CALENDAR_PK PRIMARY KEY (ID)
)
/
COMMENT ON COLUMN "SK_SP_USER"."SK_CALENDAR"."ID" IS 'PK';
COMMENT ON COLUMN "SK_SP_USER"."SK_CALENDAR"."BASELINE_TIMESTAMP" IS '年月日';
COMMENT ON COLUMN "SK_SP_USER"."SK_CALENDAR"."ISWORKINGDAY" IS '是否為工作日';
/
create table SK_SALES_DETAILS(
	ID NUMBER(18) NOT NULL ENABLE, --SKSALEID
	BILLING_TYPE varchar2(	4	BYTE	), --FKART
	BILLING_DOC varchar2(	10	BYTE	), --VBELN
	INVOICE_NUMBER varchar2(	16	BYTE	), --XBLNR
	INVOICE_TIMESTAMP date, --FKDAT
	PAYER_CUSTOMER varchar2(	10	BYTE	), --KUNRG
	BUYER_CUSTOMER varchar2(	10	BYTE	), --KUNAG
	INVOICE_AMOUNT  number(15,2), --NETWR
	SALES_ORG varchar2(4 BYTE), --VKORG
	SALES_CHANNEL varchar2(2 BYTE), --VTWEG
	SETTLEMENT_TIMESTAMP DATE,--AUGDT
	BILLING_ITEM NUMBER(6),-- POSNR
	PREVIOUS_LAYER NUMBER(6),-- UEPOS
	SAPID varchar2(3 BYTE),-- VKGRP
	PRODUCT_NUMBER varchar2(18 BYTE),-- MATNR varchar2(	18	char	)
	LOGISTIC_SITE varchar2(4 BYTE), --, LGORT varchar2(	4	char	)
	LOT_NUMBER varchar2( 10 BYTE),-- CHARG varchar2(	10	char	)
	UNIT varchar2(4 BYTE),-- VRKME varchar2(	4	char	)
	QUANTITY NUMBER(13,3),-- FKIMG number
	SELLING_PRICE NUMBER(11,2),-- KBETR number
	AMOUNT  NUMBER(15,2),-- NETWR1 number
	CATEGORY varchar2( 4 BYTE),-- PSTYV varchar2(	4	char	)
	PREMIUM_DISCOUNT  NUMBER(15,2), --NETWR2 number
	PREMIUM_DISCOUNT_TAX  number(13,2), --MWSBP number
	COST NUMBER(13,2),-- WAVWR number
	ORDER_NUMBER varchar2(16 BYTE),-- AUBEL varchar2(	16	char	)
	ORDER_ITEM NUMBER(6),-- AUPOS number
	DELIVERY_NUMBER varchar2(10 BYTE),-- VGBEL2 varchar2(	10	char	)
	DELIVERY_ITEM NUMBER(6),-- VGPOS number
	PREMIUM_DISCOUNT_NUMBER varchar2(10 BYTE),-- VBELN2 varchar2(	10	char	)
	PREMIUM_DISCOUNT_ITEM NUMBER(6),-- POSNR2 number
	ORDER_TIMESTAMP date,-- AUDAT date
	ORDER_TYPE varchar2(4 BYTE), --AUART varchar2(	4	char	)
	CONTRACT_NUMBER varchar2(10 BYTE),-- VGBEL varchar2(	10	char	)
	BUSINESS_CODE NUMBER(8),-- PERNR number
	SAP_CREATE_TIMESTAMP DATE,-- ERDAT date
	ORDER_TEXT varchar2(1024 char),-- LTEXT varchar2(	1024	char	)
	RETURN_AMOUNT NUMBER(15,2),-- NETWR3 number
	RETURN_AMOUNT_TAX NUMBER(13,2),-- MWSBP3 number
	RETURN_REASON varchar2(16 BYTE),-- AUGRU varchar2(	16	char	)
	QUOTATION_NUMBER varchar2(16 BYTE),-- VGBEL3 varchar2(	16	char	)
	QUOATION_ITEM varchar2(10 BYTE), --WKTPS varchar2(	16	char	)
	RETURN_RATE number, --RETURN_RATE number
	CHECK_DATE varchar2(	8	BYTE	),-- CHECK_DATE varchar2(	8	char	)
	CHECK_ID varchar2(	50	BYTE	), --CHECK_ID varchar2(	50	char	)
	SHIPPING_CONDITIONS varchar2( 2 BYTE), VSBED varchar2(	2	byte	), -- 出貨條件: 00: 外銷 01: 三聯式內含稅 02: 三聯式外加稅 03: 二聯式
	TAX_TYPE varchar2( 1 BYTE),-- TAXTYPE varchar2(	1	byte	) -- 課稅別:1: 應稅2: 零稅率3: 免稅
	CREATETIMESTAMP		date default sysdate, 
	INSERT_TIMESTAMP		date,
	UPDATE_TIMESTAMP		date,
	CONSTRAINT SK_SALES_DETAILS PRIMARY KEY (ID)
)
/
CREATE TABLE SK_CONTRACT(
ID NUMBER(18) NOT NULL ENABLE, --SKSALEID
CODE	VARCHAR2(16 byte)	,--合約號碼
DESCRIPTION	VARCHAR2(64 char)	,--合約說明
CONTRACT_TIMESTAMP	DATE	, --合約日期
EFFECTIVE_TIMESTAMP DATE	, --生效日期
EXPIRATION_TIMESTAMP	DATE	, --有效期限
CUSTOMER_NUMBER	VARCHAR2(16)	,--買方
SAPID	VARCHAR2(4)	,--銷售組織
SALES_CHANNEL	VARCHAR2(2)	,--配銷通路
CONTRACT_TARGET	number(13,2)	,--合約目標值
SPECIAL_RATE	number(14, 2)	,--特賣贈率
CONDITION_VALUE	number(14, 2)	,--條件值
CREATETIMESTAMP	DATE,	--建立日期
MODIFYTIMESTAMP	DATE	--異動日期
);
/
--銷售日結
CREATE TABLE SK_SALES_DAY_ACHIEVEMENT(
	ID NUMBER(18) NOT NULL ENABLE,
	BASELINE_TIMESTAMP DATE, --日期
	SAPID varchar2(3 BYTE), --銷售群組
	INVOICE_AMOUNT number(15,2), --發票金額
	PREMIUM_DISCOUNT number(15,2),--事前溢折
	SALES_DISCOUNT number(15,2),--事後折讓
	SALES_RETURN number(15,2), --退貨金額
	SALES_AMOUNT number(15,2), --銷售淨額
	COST number(15,2),--成本
	GROSS_PROFIT_RATE number(15,6),--毛利率
	BUDGET_MONTH number(15,2),--預算月額
	DAY_ACHIEVEMENT_RATE number(15,6),--預算日達成率
	MONTH_ACHIEVEMENT_RATE number(15,6),--預算月達成率
	--群組預算
	CONTRACT_AMOUNT number(15,2),--合約金額
	CONTRACT_COST number(15,2),--合約成本
	RETURN_COST number(15,2),--退貨成本
	RETURN_AMOUNT number(15,2), --退貨金額2
	CREATETIMESTAMP DATE DEFAULT SYSDATE,
	CONSTRAINT SK_SALES_DAY_ACHIEVEMENT_PK PRIMARY KEY (ID),
	CONSTRAINT SK_SALES_DAY_ACHIEVEMENT_UK UNIQUE (BASELINE_TIMESTAMP,SAPID)
);
/
--銷售月結
CREATE TABLE SK_SALES_MONTH_ACHIEVEMENT(
	ID NUMBER(18) NOT NULL ENABLE,
	BASELINE_TIMESTAMP DATE, --年月
	SAPID varchar2(3 BYTE), --銷售群組
	INVOICE_AMOUNT number(15,2), --發票金額
	PREMIUM_DISCOUNT number(15,2),--事前溢折
	SALES_DISCOUNT number(15,2),--事後折讓
	SALES_RETURN number(15,2), --退貨金額
	SALES_AMOUNT number(15,2), --銷售淨額
	COST number(15,2),--成本
	GROSS_PROFIT_RATE number(9,6),--毛利率
	BUDGET_MONTH number(15,2),--預算月額
	MONTH_ACHIEVEMENT_RATE number(9,6),--預算月達成率
	CONTRACT_AMOUNT number(15,2),--合約金額
	--特賣率
	PAYMENT_RATE NUMBER(7,4),--繳款率
	WEIGHT NUMBER(2,1),--權值
	OVERDUE_AMOUNT number(15,2),--逾期帳款
	--銷售淨額2
	CONTRACT_COST number(15,2),--合約成本
	RETURN_COST number(15,2),--退貨成本
	--應收帳款A
	--事前折讓B
	--退貨C
	--事後折讓D
	--收款金額E
	CREATETIMESTAMP DATE DEFAULT SYSDATE,
	RETURN_AMOUNT number(15,2),--退貨金額2
	CONSTRAINT SK_SALES_MONTH_ACHIEVEMENT_PK PRIMARY KEY (ID),
	CONSTRAINT SK_SALES_MONTH_ACHIEVEMENT_UK UNIQUE (BASELINE_TIMESTAMP,SAPID)
);
/
create table sk_access_log(
	ID NUMBER(18)  NOT NULL,
	action_name varchar2(20),
	user_id NUMBER(18) , 
	CREATETIMESTAMP DATE,
	PRIMARY KEY  (id),
	CONSTRAINT sk_access_log_fk1 FOREIGN KEY (user_id) REFERENCES TC_USER (ID)
);
/
CREATE TABLE SK_ZBSEGAR(
  ACTNAME VARCHAR2(12 char), --科目
  KUNNR VARCHAR2(10 BYTE),--客戶代號
  SGTXT VARCHAR2(30 BYTE),--發票號碼
  ZUONR VARCHAR2(18 BYTE),--銷貨單號
  HZUON VARCHAR2(18 BYTE),--銷售群組
  BLDAT date,--發票日期
  FDWBT NUMBER,--金額
  VSBED VARCHAR2(10 BYTE),--發票聯式
  GJAHR VARCHAR2(4 char),
  MONAT VARCHAR2(2 char),
  UPDAT date,
  FDTAG date,--應收到期
  CREATETIMESTAMP		date default sysdate
)
/
COMMENT ON COLUMN "SK_SP_USER"."SK_ZBSEGAR"."ACTNAME"
IS
  '科目';
  COMMENT ON COLUMN "SK_SP_USER"."SK_ZBSEGAR"."KUNNR"
IS
  '客戶代號';
  COMMENT ON COLUMN "SK_SP_USER"."SK_ZBSEGAR"."SGTXT"
IS
  '發票號碼';
  COMMENT ON COLUMN "SK_SP_USER"."SK_ZBSEGAR"."ZUONR"
IS
  '銷貨單號';
  COMMENT ON COLUMN "SK_SP_USER"."SK_ZBSEGAR"."HZUON"
IS
  '銷售群組';
  COMMENT ON COLUMN "SK_SP_USER"."SK_ZBSEGAR"."BLDAT"
IS
  '發票日期';
  COMMENT ON COLUMN "SK_SP_USER"."SK_ZBSEGAR"."FDWBT"
IS
  '金額';
  COMMENT ON COLUMN "SK_SP_USER"."SK_ZBSEGAR"."VSBED"
IS
  '發票聯式';
  COMMENT ON COLUMN "SK_SP_USER"."SK_ZBSEGAR"."FDTAG"
IS
  '應收到期';
/
CREATE TABLE SK_ZVBAK(
VBELN	VARCHAR2(16 byte)	,--合約號碼
KTEXT	VARCHAR2(64 char)	,--合約說明
AUDAT	DATE	, --合約日期
GUEBG	DATE	, --生效日期
GUEEN	DATE	, --有效期限
KUNNR	VARCHAR2(16)	,--買方
VKORG	VARCHAR2(4)	,--銷售組織
VTWEG	VARCHAR2(2)	,--配銷通路
ZWERT	number(13,2)	,--合約目標值
KBETR	number(14, 2)	,--特賣贈率
KWERT	number(14, 2)	,--條件值
AEDAT	DATE	,--異動日期
ERDAT	DATE	--建立日期
);

create table "SK_SP_USER"."SK_SALES_ALLOWANCES" (
"ID" NUMBER(18) NOT NULL,
"TYPE" VARCHAR2(4),
"ORG" VARCHAR2(4),
"CHANNEL" VARCHAR2(2),
"DEPT" VARCHAR2(2),
"REF_ORDER" VARCHAR2(1),
"BUYER" VARCHAR2(10),
"ORDER_NUMBER" VARCHAR2(10),
"INVOICE_NUMBER" VARCHAR2(10),
"APPLY_DATE" VARCHAR2(10),
"REASON" VARCHAR2(3),
"ITEM" VARCHAR2(6),
"BEGIN_END" VARCHAR2(2),
"PRODUCT" VARCHAR2(18),
"QUANTITY" NUMBER(16),
"UNIT" VARCHAR2(3),
"CONDITION" VARCHAR2(4),
"SALES_ALLOWANCES" NUMBER(38,6),
"PRICE_CONDITION" NUMBER(5),
"PRICE_UNIT" VARCHAR2(3),
"SAPID" VARCHAR2(3),
"RETURN_NUMBER" VARCHAR2(255),
"CREATOR" NUMBER(18),
"CREATETIMESTAMP" DATE,
"MODIFIER" NUMBER(18),
"MODIFYTIMESTAMP" DATE,
PRIMARY KEY ("ID")
);

COMMENT ON COLUMN "SK_SP_USER"."SK_SALES_ALLOWANCES"."ID" IS 'PK';
COMMENT ON COLUMN "SK_SP_USER"."SK_SALES_ALLOWANCES"."TYPE" IS '文件類型';
COMMENT ON COLUMN "SK_SP_USER"."SK_SALES_ALLOWANCES"."ORG" IS '銷售群組';
COMMENT ON COLUMN "SK_SP_USER"."SK_SALES_ALLOWANCES"."CHANNEL" IS '銷售通路';
COMMENT ON COLUMN "SK_SP_USER"."SK_SALES_ALLOWANCES"."DEPT" IS '部門';
COMMENT ON COLUMN "SK_SP_USER"."SK_SALES_ALLOWANCES"."REF_ORDER" IS '參考複製訂單(Y/N)';
COMMENT ON COLUMN "SK_SP_USER"."SK_SALES_ALLOWANCES"."BUYER" IS '買方(參考複製=N時必需輸入)';
COMMENT ON COLUMN "SK_SP_USER"."SK_SALES_ALLOWANCES"."ORDER_NUMBER" IS '訂單號碼';
COMMENT ON COLUMN "SK_SP_USER"."SK_SALES_ALLOWANCES"."INVOICE_NUMBER" IS '發票號碼';
COMMENT ON COLUMN "SK_SP_USER"."SK_SALES_ALLOWANCES"."APPLY_DATE" IS '請款日期';
COMMENT ON COLUMN "SK_SP_USER"."SK_SALES_ALLOWANCES"."REASON" IS '訂貨原因';
COMMENT ON COLUMN "SK_SP_USER"."SK_SALES_ALLOWANCES"."ITEM" IS '項目';
COMMENT ON COLUMN "SK_SP_USER"."SK_SALES_ALLOWANCES"."BEGIN_END" IS '訂單項目起訖註記(S:訂單開始,E:訂單結束)';
COMMENT ON COLUMN "SK_SP_USER"."SK_SALES_ALLOWANCES"."PRODUCT" IS '物料號碼';
COMMENT ON COLUMN "SK_SP_USER"."SK_SALES_ALLOWANCES"."QUANTITY" IS '數量';
COMMENT ON COLUMN "SK_SP_USER"."SK_SALES_ALLOWANCES"."UNIT" IS '銷售單位';
COMMENT ON COLUMN "SK_SP_USER"."SK_SALES_ALLOWANCES"."CONDITION" IS '條件類型:(ZPR1折讓含稅,ZPR0折讓未稅,PR01含稅,PR00未稅)';
COMMENT ON COLUMN "SK_SP_USER"."SK_SALES_ALLOWANCES"."SALES_ALLOWANCES" IS '折讓金額';
COMMENT ON COLUMN "SK_SP_USER"."SK_SALES_ALLOWANCES"."PRICE_CONDITION" IS '定價條件';
COMMENT ON COLUMN "SK_SP_USER"."SK_SALES_ALLOWANCES"."PRICE_UNIT" IS '定價單位';
COMMENT ON COLUMN "SK_SP_USER"."SK_SALES_ALLOWANCES"."SAPID" IS '銷售群組';
COMMENT ON COLUMN "SK_SP_USER"."SK_SALES_ALLOWANCES"."RETURN_NUMBER" IS '回傳序號';

--銷售文件批次核發記錄
CREATE TABLE "SK_SP_USER"."SD_ZTAB_EXP_RELFILENO_SD_LOG" (
"ID" NUMBER(18),
"MANDT" VARCHAR2(20 BYTE),
"BERSL" VARCHAR2(24 BYTE),
"BNAME" VARCHAR2(20 BYTE),
"VKORG" VARCHAR2(8 BYTE),
"VTWEG" VARCHAR2(4 BYTE),
"SPART" VARCHAR2(4 BYTE),
"VKGRP" VARCHAR2(6 BYTE),
"VBELN" VARCHAR2(20 BYTE),
"AUART" VARCHAR2(8 BYTE),
"AUDAT" DATE,
"POSNR" NUMBER(12),
"MATNR" VARCHAR2(36 BYTE),
"ARKTX" VARCHAR2(80 BYTE),
"KWMENG" NUMBER(25,9),
"VRKME" VARCHAR2(6 BYTE),
"UNIT_PRICE" NUMBER(14,2),
"NETWR" NUMBER(25,9),
"WAERK" VARCHAR2(10 BYTE),
"DISCOUNT" NUMBER(25,9),
"FREE" NUMBER(25,9),
"KUNNR" VARCHAR2(20 BYTE),
"NAME1" VARCHAR2(140 BYTE),
"DBRTG" VARCHAR2(10 BYTE),
"NAME" VARCHAR2(60 BYTE),
"ASP" NUMBER(14,2),
"ASP_S" NUMBER(14,2),
"VPRS" NUMBER(14,2),
"ITMPF" NUMBER(14,2),
"ITMDN" NUMBER(14,2),
"QTYDF" NUMBER(25,9),
"PRMNG" NUMBER(25,9),
"PRASP" NUMBER(14,2),
"PRASP_S" NUMBER(14,2),
"BSTZD" VARCHAR2(8 BYTE),
"BSTZD_T" VARCHAR2(40 BYTE),
"OBJNR" VARCHAR2(44 BYTE),
"STSMA" VARCHAR2(16 BYTE),
"CSTAT" VARCHAR2(10 BYTE),
"NSTAT" VARCHAR2(10 BYTE),
"REL_TEXT" VARCHAR2(120 BYTE),
"CREATE_TIME_STAMP" DATE,
"USERMODE" VARCHAR2(1),
PRIMARY KEY("ID"));

COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."ID" IS 'PK ';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."MANDT" IS '用戶端 ';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."BNAME" IS '使用者主檔記錄中的使用者名稱';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."BERSL" IS '權限碼';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."VKORG" IS '銷售組織';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."VTWEG" IS '配銷通路';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."SPART" IS '部門';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."VKGRP" IS '銷售群組';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."VBELN" IS '銷售文件號碼';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."AUART" IS '銷售文件類型';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."AUDAT" IS '文件日期';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."POSNR" IS '銷售文件項目';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."MATNR" IS '物料';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."ARKTX" IS '物料說明';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."KWMENG" IS '數量';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."VRKME" IS '銷售單位';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."UNIT_PRICE" IS '單價';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."NETWR" IS '金額';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."WAERK" IS '幣別';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."DISCOUNT" IS '溢價金額';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."FREE" IS '贈品數量';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."KUNNR" IS '客戶代碼';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."NAME1" IS '客戶名稱';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."DBRTG" IS '風險評比';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."NAME" IS '業務員';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."ASP" IS '平均單價(銷售單位)';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."ASP_S" IS '平均單價(最小單位)';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."VPRS" IS '項目成本';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."ITMPF" IS '項目毛利率';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."ITMDN" IS '單價調幅';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."QTYDF" IS '數量差異';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."PRMNG" IS '前次出貨數量';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."PRASP" IS '前次平均單價(銷售單位)';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."PRASP_S" IS '前次平均單價(最小單位)';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."BSTZD" IS '簽核層級';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."BSTZD_T" IS '簽核層級說明';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."OBJNR" IS '狀態物件號碼';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."STSMA" IS '狀態設定檔';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."CSTAT" IS '目前狀態';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."NSTAT" IS '後續狀態';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."REL_TEXT" IS '簽核備註';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."CREATE_TIME_STAMP" IS '簽核時間';
COMMENT ON COLUMN "SD_ZTAB_EXP_RELFILENO_SD_LOG"."USERMODE" IS '簽核動作';

--代理人
create table SK_PROXY (
ID number(19),
USER_ID number(19),
PROXY_ID number(19),
primary key (ID));

COMMENT ON COLUMN "SK_PROXY"."ID" IS 'PK';
COMMENT ON COLUMN "SK_PROXY"."USER_ID" IS 'FK:TC_USER.ID';
COMMENT ON COLUMN "SK_PROXY"."PROXY_ID" IS '代理人(FK:TC_USER.ID)';

CREATE TABLE SK_QUOTATION_MASTER
(
	ID NUMBER(18) NOT NULL ENABLE,
  QUOTATION_DATE DATE, --日期
	CUSTOMER NUMBER(18), --客戶
  PO_NO VARCHAR2(90), --客戶訂單號碼 (SAP的採購單號碼)
  CONSIGNEE NUMBER(18), --收貨人
	AMOUNT NUMBER(15,2) ,--總金額
	PREMIUM_DISCOUNT NUMBER(15,2) default 0,--總溢價折讓
	TOTAL_AMOUNT NUMBER(15,2),--發票總金額
  STATUS VARCHAR2(30),--狀態(OPEN: 申請, READED: 已讀, APPROVED: 核准, REJECT: 駁回, CLOSE: 結案, FAILED: 轉檔失敗)
  QUOTATION_NO VARCHAR2(30), --報價單編號
  ERROR_MESSAGE VARCHAR2(1000), --錯誤訊息
  REMARK VARCHAR2(4000),--備註
  REMARK1 VARCHAR2(255), --備註1
  REMARK2 VARCHAR2(255), --備註2
  REMARK3 VARCHAR2(255), --備註3
  NOTE VARCHAR2(4000), --悄悄話
  CREATOR NUMBER(18), --建立者
  CREATETIMESTAMP DATE, --建立時間
  MODIFIER NUMBER(18), --修改者
  MODIFYTIMESTAMP DATE, --修改時間
	CONSTRAINT SK_QUOTATION_MASTER_PK PRIMARY KEY (ID),
	CONSTRAINT SK_QUOTATION_MASTER_FK1 FOREIGN KEY (CUSTOMER) REFERENCES SK_CUSTOMER(ID),
  CONSTRAINT SK_QUOTATION_MASTER_FK2 FOREIGN KEY (CONSIGNEE) REFERENCES SK_CUSTOMER(ID),
  CONSTRAINT SK_QUOTATION_MASTER_FK3 FOREIGN KEY (CREATOR) REFERENCES TC_USER(ID),
  CONSTRAINT SK_QUOTATION_MASTER_FK4 FOREIGN KEY (MODIFIER) REFERENCES TC_USER(ID)
);

COMMENT ON COLUMN SK_QUOTATION_MASTER.ID IS 'PK';
COMMENT ON COLUMN SK_QUOTATION_MASTER."QUOTATION_DATE" IS '日期';
COMMENT ON COLUMN SK_QUOTATION_MASTER.CUSTOMER IS '客戶 (FK:SK_CUSTOMER.ID)';
COMMENT ON COLUMN SK_QUOTATION_MASTER.PO_NO IS '客戶訂單號碼 (SAP採購單號碼)';
COMMENT ON COLUMN SK_QUOTATION_MASTER.CONSIGNEE IS '收貨人 (FK:SK_CUSTOMER.ID)';
COMMENT ON COLUMN SK_QUOTATION_MASTER.CREATOR IS '建立者 (FK:TC_USER.ID)';
COMMENT ON COLUMN SK_QUOTATION_MASTER.CREATETIMESTAMP IS '建立時間';
COMMENT ON COLUMN SK_QUOTATION_MASTER.MODIFIER IS '修改者 (FK:TC_USER.ID)';
COMMENT ON COLUMN SK_QUOTATION_MASTER.MODIFYTIMESTAMP IS '修改時間';
COMMENT ON COLUMN SK_QUOTATION_MASTER.AMOUNT IS '總金額';
COMMENT ON COLUMN SK_QUOTATION_MASTER.PREMIUM_DISCOUNT IS '總溢價折讓';
COMMENT ON COLUMN SK_QUOTATION_MASTER.TOTAL_AMOUNT IS '發票總金額';
COMMENT ON COLUMN SK_QUOTATION_MASTER.STATUS IS '狀態(OPEN: 申請, READED: 已讀, APPROVED: 核准, REJECT: 駁回, CLOSE: 結案, FAILED: 轉檔失敗)';
COMMENT ON COLUMN SK_QUOTATION_MASTER."QUOTATION_NO" IS '報價單編號';
COMMENT ON COLUMN SK_QUOTATION_MASTER."ERROR_MESSAGE" IS '錯誤訊息';
COMMENT ON COLUMN SK_QUOTATION_MASTER.REMARK IS '備註';
COMMENT ON COLUMN SK_QUOTATION_MASTER.REMARK1 IS '備註1';
COMMENT ON COLUMN SK_QUOTATION_MASTER.REMARK2 IS '備註2';
COMMENT ON COLUMN SK_QUOTATION_MASTER.REMARK3 IS '備註3';
COMMENT ON COLUMN SK_QUOTATION_MASTER.NOTE IS '備註(悄悄話)';

CREATE TABLE SK_QUOTATION_DETAIL
(
	ID NUMBER(18) NOT NULL ENABLE,
	QUOTATION_MASTER NUMBER(18) ,
	PRODUCT_NUMBER VARCHAR2(18 BYTE), --產品編號
	QUANTITY NUMBER(13,3),--數量
	PRICE NUMBER(11,2),--金額
	PREMIUM_DISCOUNT NUMBER(15,2) default 0,--溢價折讓未稅
	CONSTRAINT SK_QUOTATION_DETAIL_PK PRIMARY KEY (ID),
	CONSTRAINT SK_QUOTATION_DETAIL_FK1 FOREIGN KEY (QUOTATION_MASTER) REFERENCES SK_QUOTATION_MASTER(ID)
);

COMMENT ON COLUMN SK_QUOTATION_DETAIL.ID IS 'PK';
COMMENT ON COLUMN SK_QUOTATION_DETAIL.QUOTATION_MASTER IS '訂單主檔(FK:SK_QUOTATION_MASTER.ID)';
COMMENT ON COLUMN SK_QUOTATION_DETAIL.PRODUCT_NUMBER IS '產品編號';
COMMENT ON COLUMN SK_QUOTATION_DETAIL.PRICE IS '單價';
COMMENT ON COLUMN SK_QUOTATION_DETAIL.QUANTITY IS '數量';
COMMENT ON COLUMN SK_QUOTATION_DETAIL.PREMIUM_DISCOUNT IS '溢價折讓';

CREATE TABLE SK_QUOTATION_GIFT
(
	ID NUMBER(18) NOT NULL ENABLE,
	QUOTATION_DETAIL NUMBER(18) , --報價單明細 (FK:SK_QUOTATION_DETAIL.ID)
  PRODUCT_NUMBER VARCHAR2(18 BYTE), --產品編號
  QUANTITY NUMBER(13,3), --數量
  PRICE NUMBER(11,2), --單價
  CONSTRAINT SK_QUOTATION_GIFT_PK PRIMARY KEY(ID),
  CONSTRAINT SK_QUOTATION_GIFT_FK01 FOREIGN KEY (QUOTATION_DETAIL) REFERENCES SK_QUOTATION_DETAIL(ID)
);

COMMENT ON COLUMN SK_QUOTATION_GIFT.ID IS 'PK';
COMMENT ON COLUMN SK_QUOTATION_GIFT.QUOTATION_DETAIL IS '報價單明細 (FK:SK_QUOTATION_DETAIL.ID)';
COMMENT ON COLUMN SK_QUOTATION_GIFT.PRODUCT_NUMBER IS '產品編號';
COMMENT ON COLUMN SK_QUOTATION_GIFT.QUANTITY IS '數量';
COMMENT ON COLUMN SK_QUOTATION_GIFT.PRICE IS '數量';

CREATE TABLE SK_QUOTATION_REVIEW_HISTORY
(
  ID NUMBER(18) NOT NULL,
  QUOTATION_MASTER NUMBER(18),
  REVIEWER NUMBER(18),  --審核者
  REMARK VARCHAR2(4000), --備註
  REVIEW_DATE DATE,--審核時間
  REVIEW_OPTION VARCHAR2(30),--審核選項 (READED,APPROVED,REJECT)
  CONSTRAINT SK_QUOTATION_REVIEW_HIS_PK PRIMARY KEY (ID),
  CONSTRAINT SK_QUOTATION_REVIEW_HIS_FK1 FOREIGN KEY (QUOTATION_MASTER) REFERENCES SK_QUOTATION_MASTER(ID),
  CONSTRAINT SK_QUOTATION_REVIEW_HIS_FK2 FOREIGN KEY (REVIEWER) REFERENCES TC_USER(ID)
);

COMMENT ON COLUMN SK_QUOTATION_REVIEW_HISTORY.ID IS 'PK';
COMMENT ON COLUMN SK_QUOTATION_REVIEW_HISTORY.QUOTATION_MASTER IS '訂單(FK:SK_QUOTATION_MASTER.ID)';
COMMENT ON COLUMN SK_QUOTATION_REVIEW_HISTORY.REVIEWER IS '審核者 (FK:TC_USER.ID)';
COMMENT ON COLUMN SK_QUOTATION_REVIEW_HISTORY.REMARK IS '備註';
COMMENT ON COLUMN SK_QUOTATION_REVIEW_HISTORY.REVIEW_DATE IS '審核日期';
COMMENT ON COLUMN SK_QUOTATION_REVIEW_HISTORY.REVIEW_OPTION IS '審核選項 (READED,APPROVED,REJECT)';

CREATE TABLE SK_QUOTATION_MAIL_GROUP (
ID    NUMBER(18) NOT NULL,
NAME  VARCHAR2(255) NOT NULL,
CREATOR NUMBER(18) NOT NULL,
CREATETIMESTAMP DATE,
MODIFIER NUMBER(18) not null,
MODIFYTIMESTAMP DATE,
PRIMARY KEY (ID),
FOREIGN KEY (CREATOR) REFERENCES TC_USER(ID),
FOREIGN KEY (MODIFIER) REFERENCES TC_USER(ID));

COMMENT ON COLUMN SK_QUOTATION_MAIL_GROUP.ID IS 'PK';
COMMENT ON COLUMN SK_QUOTATION_MAIL_GROUP.NAME IS '群組名稱';
COMMENT ON COLUMN SK_QUOTATION_MAIL_GROUP.CREATOR IS '建立者';
COMMENT ON COLUMN SK_QUOTATION_MAIL_GROUP.CREATETIMESTAMP IS '建立時間';
COMMENT ON COLUMN SK_QUOTATION_MAIL_GROUP.MODIFIER IS '修改者';
COMMENT ON COLUMN SK_QUOTATION_MAIL_GROUP.MODIFYTIMESTAMP IS '修改時間';

CREATE TABLE SK_QUOTATION_MAIL_GROUP_MEMBER (
ID NUMBER(18) NOT NULL, 
GROUP_ID NUMBER(18) NOT NULL,
MEMBER_ID NUMBER(18) NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (GROUP_ID) REFERENCES SK_QUOTATION_MAIL_GROUP(ID),
FOREIGN KEY (MEMBER_ID) REFERENCES SK_SALES_MEMBER(ID));

COMMENT ON COLUMN SK_QUOTATION_MAIL_GROUP_MEMBER.ID IS 'PK';
COMMENT ON COLUMN SK_QUOTATION_MAIL_GROUP_MEMBER.GROUP_ID IS 'FK:SK_QUOTATION_MAIL_GROUP.ID';
COMMENT ON COLUMN SK_QUOTATION_MAIL_GROUP_MEMBER.MEMBER_ID IS 'FK:SK_SALES_MEMBER.ID';

CREATE TABLE SK_QUOTATION_MAIL_GROUP_USER (
ID NUMBER(18) NOT NULL,
GROUP_ID NUMBER(18) NOT NULL,
USER_ID NUMBER(18) NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (GROUP_ID) REFERENCES SK_QUOTATION_MAIL_GROUP(ID),
FOREIGN KEY (USER_ID) REFERENCES TC_USER(ID));

COMMENT ON COLUMN SK_QUOTATION_MAIL_GROUP_USER.ID IS 'PK';
COMMENT ON COLUMN SK_QUOTATION_MAIL_GROUP_USER.GROUP_ID IS 'FK:SK_QUOTATION_MAIL_GROUP.ID';
COMMENT ON COLUMN SK_QUOTATION_MAIL_GROUP_USER.USER_ID IS 'FK:TC_USER.ID';

--CREATE SEQUENCE "SK_SP_USER"."SEQ_FVITEM" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 3 NOORDER NOCYCLE ;
--CREATE SEQUENCE "SK_SP_USER"."SEQ_TCC" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 3 NOORDER NOCYCLE ;
CREATE SEQUENCE "SK_SP_USER"."SEQ_TRNNO" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 3 NOORDER NOCYCLE ;
CREATE SEQUENCE SEQ_SK_SYNC INCREMENT BY 1 START WITH 1 NOMAXVALUE CACHE 3 NOORDER  NOCYCLE;
CREATE SEQUENCE SEQ_SK_ARCH_D INCREMENT BY 1 START WITH 1 NOMAXVALUE CACHE 3 NOORDER  NOCYCLE;
CREATE SEQUENCE SEQ_SK_ARCH_M INCREMENT BY 1 START WITH 1 NOMAXVALUE CACHE 3 NOORDER  NOCYCLE;
CREATE SEQUENCE "SK_SP_USER"."SEQ_WORKLIST_LOG" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 3 NOORDER NOCYCLE ;
/
Insert into TC_DOMAIN (ID,NAME,DESCRIPTION) values (1,'Default','Default');

REM INSERTING into TC_FVVAULT
Insert into TC_FVVAULT (ID,NAME,HOSTNAME,DOMAIN,LOCATION,READONLY,ENABLED,URL) values (1,'Default','localhost',1,'D:\FileVault\SKSP\',0,1,null);
Insert into TC_FVVAULT (ID,NAME,HOSTNAME,DOMAIN,LOCATION,READONLY,ENABLED,URL) values (2,'Default','remote',1,'E:\FileVault\SKSP\Default\',0,1,null);
/
REM INSERTING into TC_USER
Insert into TC_USER (ID,LOGIN_ACCOUNT,CREATOR,CREATETIMESTAMP) values (1,'administrator',1,sysdate);
Insert into TC_USER (ID,LOGIN_ACCOUNT,CREATOR,CREATETIMESTAMP) values (2,'jason.yu',1,sysdate);
Insert into TC_USER (ID,LOGIN_ACCOUNT,CREATOR,CREATETIMESTAMP) values (3,'neo.fu',1,sysdate);
Insert into TC_USER (ID,LOGIN_ACCOUNT,CREATOR,CREATETIMESTAMP) values (4,'lynn.huang',1,sysdate);
--Insert into TC_USER (ID,LOGIN_ACCOUNT,CREATOR,CREATETIMESTAMP) values (5,'edwin.ho',1,sysdate);
Insert into TC_USER (ID,LOGIN_ACCOUNT,CREATOR,CREATETIMESTAMP) values (6,'wayne.hu',1,sysdate);
Insert into TC_USER (ID,LOGIN_ACCOUNT,CREATOR,CREATETIMESTAMP) values (7,'shvon',1,sysdate);
REM INSERTING into TC_GROUP
Insert into TC_GROUP (ID,CODE,NAME,CREATOR,CREATETIMESTAMP) values (1,'ADMINISTRATORS','Administrators Group',1,sysdate);
--SK Group
Insert into TC_GROUP (ID,CODE,NAME,CREATOR,CREATETIMESTAMP) values (2,'AP-Group','AP-Group',1,sysdate);
--Insert into TC_GROUP (ID,CODE,NAME,CREATOR,CREATETIMESTAMP) values (3,'QA-Group','QA-Group',1,sysdate);
Insert into TC_GROUP (ID,CODE,NAME,CREATOR,CREATETIMESTAMP) values (4,'Sales','Sales',1,sysdate);
Insert into TC_GROUP (ID,CODE,NAME,CREATOR,CREATETIMESTAMP) values (5,'Assistant','Assistant Group',1,sysdate);
Insert into TC_GROUP (ID,CODE,NAME,CREATOR,CREATETIMESTAMP) values (6,'Finance','Finance Group',1,sysdate);
REM INSERTING into TC_USERGROUP
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (1,1,1,1,sysdate);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (2,2,1,1,sysdate);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (3,3,1,1,sysdate);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (4,4,1,1,sysdate);
--Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (5,5,1,1,sysdate);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (6,6,1,1,sysdate);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (7,7,1,1,sysdate);
commit;
/
--SK Sales Account
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (20,'0234','gn24e','gn24e@sking.com.tw','邱忠義',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (21,'0445','jeff.shay','jeff.shay@sking.com.tw','薛統旗',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (22,'0447','wade.hught','wade.hught@sking.com.tw','黃企琮',1,SYSDATE);
--INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (23,'brian.chen','brian.chen@sking.com.tw','tmp013',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (24,'0453','polly.liu','polly.liu@sking.com.tw','劉辰萱',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (25,'0424','wsp68','wsp68@sking.com.tw','王勝平',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (26,'0407','andy1516','andy1516@sking.com.tw','楊玉璽',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (27,'0485','hank.hus','hank.hus@sking.com.tw','許瀚鎮',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (28,'0441','wu.kun.ho','wu.kun.ho@sking.com.tw','吳坤和',1,SYSDATE);
--INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (29,'deby.yeh','deby.yeh@sking.com.tw','022tmp',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (30,'0460','aaron.zou','aaron.zou@sking.com.tw','鄒子健',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (31,'0318','bogi05','bogi05@sking.com.tw','劉伯禹',1,SYSDATE);
--INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (32,'evan.chen','evan.chen@sking.com.tw','025Tmp',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (33,'0488','alexhuang','alexhuang@sking.com.tw','黃學信',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (34,'0216','669588','669588@sking.com.tw','李燕青',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (35,'0372','sam516','sam516@sking.com.tw','簡榮俊',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (36,'0304','ttzu73','ttzu73@sking.com.tw','曾子行',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (37,'0263','300013','300013@sking.com.tw','黃世祿',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (38,'0415','maxlai','maxlai@sking.com.tw','賴遵仁',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (39,'0292','kenny.kang','kenny.kang@sking.com.tw','康鴻毅',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (40,'0350','507887','507887@sking.com.tw','楊雅典',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (41,'0202','kbt','kbt@sking.com.tw','張文松',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (42,'0174','mgo','mgo@sking.com.tw','劉清中',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (43,'0391','kereyhot','kereyhot@sking.com.tw','蔡銘光',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (44,'0392','tsung.chang','tsung.chang@sking.com.tw','張傳宗',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (45,'0404','vivien9920','vivien9920@sking.com.tw','羅玉琴',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (46,'0253','wu-me','wu-me@sking.com.tw','吳惠美',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (47,'0138','5600','5600@sking.com.tw','柯俊成',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (48,'0466','eric.chen','eric.chen@sking.com.tw','陳宏毅',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (49,'0409','d1216636','d1216636@sking.com.tw','董觀堅',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (50,'0451','fyfy2803','fyfy2803@sking.com.tw','蔡雅妃',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (51,'0456','pick1910','pick1910@sking.com.tw','劉宛熙',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (52,'0477','yoyo16035','yoyo16035@sking.com.tw','黃素娟',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (53,'0423','h800480','h800480@sking.com.tw','黃正裕',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (54,'0483','fb7925','fb7925@sking.com.tw','邢聖志',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (55,'0457','patrick.kuan','Patrick.Kuan@sking.com.tw','官重信',1,SYSDATE);
--INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (56,'0482','sking.311','sking.311@sking.com.tw','sking.311',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (57,'0482','s_kao','s_kao@sking.com.tw','高榮全',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (58,'0478','jeff.lee','Jeff.Lee@sking.com.tw','李英宗',1,SYSDATE);
--INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (59,'andy.jeng','andy.jeng@sking.com.tw','410tmp',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (60,'0432','alet0714','alet0714@sking.com.tw','洪錦璿',1,SYSDATE);
--INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (61,'shawn.yang','shawn.yang@sking.com.tw','412Temp',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (62,'0436','yvan','yvan@sking.com.tw','葉文斌',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (63,'0484','paddy','paddy@sking.com.tw','郭秀婷',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (64,'0479','nick0421','nick0421@sking.com.tw','白奇政',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (65,'0148','23893','23893@sking.com.tw','張德源',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (66,null,'taing.chiu','taing.chiu@sking.com.tw','邱暄棠',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (67,'0481','alan.wang','alan.wang@sking.com.tw','王朝堂',1,SYSDATE);
--INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (68,'0148','23893','23893@sking.com.tw','張德源',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (69,'0475','johnny.chang','johnny.chang@sking.com.tw','張益強',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (70,'0444','tz5168','tz5168@sking.com.tw','吳健民',1,SYSDATE);
--INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (71,'panlihu','panlihu@sking.com.tw','432tmp',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (72,'0486','emily.wang','emily.wang@sking.com.tw','王薏涵',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (73,'0422','carol','carol@sking.com.tw','林毓嫻',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (74,null,'fanny.tseng','fanny.tseng@sking.com.tw','曾芳蒂',1,SYSDATE);
--INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (74,'jia.ling','jia.ling@sking.com.tw','謝佳玲',1,SYSDATE);
--INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (75,'maggie.liou','maggie.liou@sking.com.tw','劉漢如',1,SYSDATE);
--INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (76,'emilylin','emilylin@sking.com.tw','林淑玹',1,SYSDATE);
--INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (77,'chyuan','chyuan@sking.com.tw','葉清泉',1,SYSDATE);
----INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (78,'irene','irene@sking.com.tw','謝嗣芬',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (79,'0480','kevin.hung','kevin.hung@sking.com.tw','洪啟明',1,SYSDATE);
--INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (80,'amy.tzuoo','amy.tzuoo@sking.com.tw','左小玫',1,SYSDATE);
--INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (81,'wkenny','wkenny@sking.com.tw','王家凱',1,SYSDATE);
--INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (93,'013temp','013temp@sking.com.tw','013temp',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (88,null,'rex.jeng','rex.jeng@sking.com.tw','鄭金芳',1,SYSDATE);
--SK Finance
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (82,null,'ann.chen','ann.chen@sking.com.tw','陳麗安',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (83,null,'ruby.lo','ruby.lo@sking.com.tw','羅昭宜',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (84,null,'becky','becky@sking.com.tw','林俐均',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (85,null,'jennifer.lin','jennifer.lin@sking.com.tw','林詩芸',1,SYSDATE);
--SK Assistant
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (86,null,'michelle.liu','michelle.liu@sking.com.tw','劉淑華',1,SYSDATE);
INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (87,null,'elaine','elaine@sking.com.tw','邱瓊瑩',1,SYSDATE);
--INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (91,null,'h6018','h6018@sking.com.tw','張淑惠(台中)',1,SYSDATE);
--INSERT INTO TC_USER (ID,EMP_ID,LOGIN_ACCOUNT,EMAIL,CNAME,CREATOR,CREATETIMESTAMP) VALUES (92,null,'melody.ou','melody.ou@sking.com.tw','歐惠瑜',1,SYSDATE);

--SK Sales Group
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (20,20,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (21,21,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (22,22,4,1,SYSDATE);
--Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (23,23,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (24,24,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (25,25,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (26,26,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (27,27,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (28,28,4,1,SYSDATE);
--Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (29,29,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (30,30,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (31,31,4,1,SYSDATE);
--Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (32,32,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (33,33,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (34,34,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (35,35,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (36,36,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (37,37,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (38,38,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (39,39,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (40,40,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (41,41,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (42,42,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (43,43,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (44,44,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (45,45,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (46,46,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (47,47,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (48,48,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (49,49,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (50,50,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (51,51,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (52,52,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (53,53,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (54,54,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (55,55,4,1,SYSDATE);
--Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (56,56,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (57,57,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (58,58,4,1,SYSDATE);
--Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (59,59,'andy.jeng','andy.jeng@sking.com.tw','410tmp',1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (60,60,4,1,SYSDATE);
--Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (61,61,'shawn.yang','shawn.yang@sking.com.tw','412Temp',1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (62,62,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (63,63,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (64,64,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (65,65,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (66,66,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (67,67,4,1,SYSDATE);
--Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (68,68,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (69,69,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (70,70,4,1,SYSDATE);
--Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (71,71,'panlihu','panlihu@sking.com.tw','432tmp',1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (72,72,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (73,73,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (74,74,4,1,SYSDATE);
--Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (75,75,4,1,SYSDATE);
--Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (76,76,4,1,SYSDATE);
--Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (77,77,4,1,SYSDATE);
--Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (78,78,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (79,79,4,1,SYSDATE);
--Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (80,80,4,1,SYSDATE);
--Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (81,81,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (88,88,4,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (87,87,4,1,SYSDATE);
--SK Finance Group
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (82,82,6,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (83,83,6,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (84,84,6,1,SYSDATE);
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (85,85,6,1,SYSDATE);
--SK Assistant Group
Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (86,86,5,1,SYSDATE);
--Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (91,91,5,1,SYSDATE);
--Insert into TC_USERGROUP (ID,USER_ID,GROUP_ID,CREATOR,CREATETIMESTAMP) values (92,92,5,1,SYSDATE);

--SK Channel
INSERT INTO SK_SALES_CHANNELS (ID,CODE,NAME,PARENT,MANAGER)VALUES(1,'T1','業務部&企劃部協理',null,null);
INSERT INTO SK_SALES_CHANNELS (ID,CODE,NAME,PARENT,MANAGER)VALUES(2,'T2','業務部經理',1,null);
INSERT INTO SK_SALES_CHANNELS (ID,CODE,NAME,PARENT,MANAGER)VALUES(3,'T31','北區副理310',2,55);
INSERT INTO SK_SALES_CHANNELS (ID,CODE,NAME,PARENT,MANAGER)VALUES(4,'T32','中區副理311',2,57);
INSERT INTO SK_SALES_CHANNELS (ID,CODE,NAME,PARENT,MANAGER)VALUES(5,'T33','南區副理312',2,58);
INSERT INTO SK_SALES_CHANNELS (ID,CODE,NAME,PARENT,MANAGER)VALUES(6,'T34','Key Account副理900',1,null);

INSERT INTO SK_SALES_CHANNELS (ID,CODE,NAME,PARENT,MANAGER)VALUES(21,'41','HP北區',3,null);
INSERT INTO SK_SALES_CHANNELS (ID,CODE,NAME,PARENT,MANAGER)VALUES(22,'01','GP北一區',3,20);
INSERT INTO SK_SALES_CHANNELS (ID,CODE,NAME,PARENT,MANAGER)VALUES(23,'02','GP北二區',3,null);
INSERT INTO SK_SALES_CHANNELS (ID,CODE,NAME,PARENT,MANAGER)VALUES(24,'42','HP中區',4,64);
INSERT INTO SK_SALES_CHANNELS (ID,CODE,NAME,PARENT,MANAGER)VALUES(25,'11','GP中區',4,34);
INSERT INTO SK_SALES_CHANNELS (ID,CODE,NAME,PARENT,MANAGER)VALUES(26,'43','HP南區',5,69);
INSERT INTO SK_SALES_CHANNELS (ID,CODE,NAME,PARENT,MANAGER)VALUES(27,'21','GP南一區',5,41);
INSERT INTO SK_SALES_CHANNELS (ID,CODE,NAME,PARENT,MANAGER)VALUES(28,'22','GP南二區',5,48);
INSERT INTO SK_SALES_CHANNELS (ID,CODE,NAME,PARENT,MANAGER)VALUES(29,'91','KA91北區',6,79);
--INSERT INTO SK_SALES_CHANNELS (ID,CODE,NAME,PARENT,MANAGER)VALUES(30,'92','KA92中區',6,null);
--INSERT INTO SK_SALES_CHANNELS (ID,CODE,NAME,PARENT,MANAGER)VALUES(31,'93','KA93南區',6,null);
--SK Sales Member
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(1,'010',	20, 0	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(2,'011',	21, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(3,'012',	22, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(4,'013',	null, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(5,'014',	24, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(6,'015',	25, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(7,'016',	26, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(8,'020',	27, 0	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(9,'021',	28, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(10,'022',	null, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(11,'023',	30, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(12,'024',	31, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(13,'025',	null, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(14,'026',	33, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(15,'110',	34, 0	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(16,'111',	35, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(17,'112',	36, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(18,'113',	37, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(19,'114',	38, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(20,'115',	39, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(21,'116',	40, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(22,'210',	41, 0	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(23,'211',	42, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(24,'212',	43, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(25,'213',	44, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(26,'214',	45, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(27,'215',	46, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(28,'216',	47, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(29,'220',	48, 0	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(30,'221',	49, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(31,'222',	50, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(32,'223',	51, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(33,'224',	52, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(34,'225',	53, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(35,'226',	54, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(36,'310',	55, 0	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(38,'311',	57, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(39,'312',	58, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(40,'410',	null, 0	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(41,'411',	60, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(42,'412',	null, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(43,'413',	62, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(44,'414',	63, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(45,'420',	64, 0	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(46,'421',	65, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(47,'422',	66, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(48,'423',	67, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(49,'424',	null, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(50,'430',	69, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(51,'431',	70, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(52,'432',	72, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(53,'433',	73, 1	);
--INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(54,'434',	73, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(55,'510',	null, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(56,'520',	null, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(57,'610',	null, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(58,'710',	null, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(59,'810',	null, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(60,'910',	74, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(61,'911',	79, 1	);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(62,'999',	null, 1);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(63,'811',	null, 1);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(64,'912',	null, 1);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(65,'921',	null, 1);
INSERT INTO SK_SALES_MEMBER (ID,CODE,MEMBER,SELECTABLE)VALUES(66,'931',	null, 1);

--Sales Channel Member
 --41 HP北區				
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(1,	21	,	40	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(2,	21	,	41	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(3,	21	,	42	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(4,	21	,	43	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(5,	21	,	44	);
 --22,01,GP北一區,3,20				
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(6,	22	,	1	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(7,	22	,	2	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(8,	22	,	3	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(9,	22	,	4	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(10,	22	,	5	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(11,	22	,	6	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(12,	22	,	7	);
 --23,'02','GP北二區',3,null				
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(13,	23	,	8	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(14,	23	,	9	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(15,	23	,	10	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(16,	23	,	11	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(17,	23	,	12	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(18,	23	,	13	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(19,	23	,	14	);
 --24,'42','HP中區',4,64				
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(20,	24	,	45	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(21,	24	,	46	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(22,	24	,	47	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(23,	24	,	48	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(24,	24	,	49	);
 --25,'11','GP中區',4,34				
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(25,	25	,	15	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(26,	25	,	16	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(27,	25	,	17	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(28,	25	,	18	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(29,	25	,	19	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(30,	25	,	20	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(31,	25	,	21	);
 --26,'43','HP南區',5,69				
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(32,	26	,	50	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(33,	26	,	51	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(34,	26	,	52	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(35,	26	,	53	);
--INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(36,	26	,	54	);
 --27,'21','GP南一區',5,41				
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(37,	27	,	22	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(38,	27	,	23	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(39,	27	,	24	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(40,	27	,	25	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(41,	27	,	26	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(42,	27	,	27	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(43,	27	,	28	);
 --28,'22','GP南二區',5,48				
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(44,	28	,	29	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(45,	28	,	30	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(46,	28	,	31	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(47,	28	,	32	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(48,	28	,	33	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(49,	28	,	34	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(50,	28	,	35	);
 --29,'91','KA91北區',6,79				
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(51,	29	,	60	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(52,	29	,	61	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(53,	29	,	64	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(54,	29	,	65	);
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(55,	29	,	66	);
--北區副理
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(56,	3	,	36	);
--中區副理
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(57,	4	,	38	);
--南區副理
INSERT INTO SK_SALES_CHANNEL_MEMBER(ID,SALES_CHANNEL,SALES_MEMBER)VALUES(58,	5	,	39	);

--銷售文件批次核發

--TC_GROUP
insert into tc_group values (7,'Managers','Managers',1,sysdate);

--TC_USER
INSERT INTO TC_USER VALUES (8,'shuchei','shuchei@sking.com.tw','A0283','劉淑治',0,1,SYSDATE);

--TC_USERGROUP
insert into tc_usergroup values (8,8,7,1,sysdate);
INSERT INTO TC_USERGROUP VALUES (9,88,7,1,SYSDATE);
insert into tc_usergroup values (10,85,7,1,sysdate);
--SK_PROXY
insert into sk_proxy values (1,8,85); //指定林詩芸為劉淑治的代理人.
