create table SK_ORDER_NUMBER
(
	order_number_id number(18),
	order_number VARCHAR2(30 BYTE),
	CONSTRAINT SK_ORDER_NUMBER_PK PRIMARY KEY (order_number_id),
	CONSTRAINT SK_ORDER_NUMBER_UK UNIQUE (order_number)
)
/
create table SK_INVOICE_NUMBER
(
	invoice_number_id number(18),
	invoice_number VARCHAR2(30 BYTE),
	CONSTRAINT SK_INVOICE_NUMBER_PK PRIMARY KEY (invoice_number_id),
	CONSTRAINT SK_INVOICE_NUMBER_UK UNIQUE (invoice_number)
)
/
create table SK_ORDER_DATE2
(
	ORDER_DATE_id number(18),
	YEAR NUMBER(4),
	MONTH NUMBER(2),
    MONTH_LABEL VARCHAR2(20),
	QUARTER NUMBER(1),
	QUARTER_LABEL VARCHAR2(20),
	CONSTRAINT SK_ORDER_DATE2_PK PRIMARY KEY (ORDER_DATE_id),
	CONSTRAINT SK_ORDER_DATE2_UK UNIQUE (YEAR,MONTH,QUARTER)
)
/
create table SK_SALES_MEMBER
(
	SALES_MEMBER_id number(18),
	SALES_MEMBER_CODE VARCHAR2(8 BYTE),
	CONSTRAINT SK_SALES_MEMBER_PK PRIMARY KEY (SALES_MEMBER_id),
	CONSTRAINT SK_SALES_MEMBER_UK UNIQUE (SALES_MEMBER_CODE)
)
/
create table SK_SALES_CHANNEL
(
	SALES_CHANNEL_id number(18),
	SALES_CHANNEL_CODE VARCHAR2(8 BYTE),
	CONSTRAINT SK_SALES_CHANNEL_PK PRIMARY KEY (SALES_CHANNEL_id),
	CONSTRAINT SK_SALES_CHANNEL_UK UNIQUE (SALES_CHANNEL_CODE)
)
/
create table SK_PRODUCT_MASTER
(
	PRODUCT_MASTER_id number(18),
	PRODUCT_MASTER_NUMBER VARCHAR2(18 BYTE),
	CONSTRAINT SK_PRODUCT_MASTER_PK PRIMARY KEY (PRODUCT_MASTER_id),
	CONSTRAINT SK_PRODUCT_MASTER_UK UNIQUE (PRODUCT_MASTER_NUMBER)
)
/
create table SK_PRODUCT_TYPE
(
	PRODUCT_TYPE_id number(18),
	PRODUCT_TYPE_NUMBER VARCHAR2(18 BYTE),
	CONSTRAINT SK_PRODUCT_TYPE_PK PRIMARY KEY (PRODUCT_TYPE_id),
	CONSTRAINT SK_PRODUCT_TYPE_UK UNIQUE (PRODUCT_TYPE_NUMBER)
)
/
create table SK_CUSTOMER
(
	CUSTOMER_id number(18),
	CUSTOMER_NUMBER VARCHAR2(20 BYTE),
	CONSTRAINT SK_CUSTOMER_PK PRIMARY KEY (CUSTOMER_id),
	CONSTRAINT SK_CUSTOMER_UK UNIQUE (CUSTOMER_NUMBER)
)
/
create table SK_ZVBRK_DELETE
(
	vbeln VARCHAR2(20 BYTE),
	INSERT_DATE date default sysdate
)
/
create table SK_SALES_ORDER_FACT
(
	SALES_ORDER_ID number(18),
	order_number_id number(18),
	invoice_number_id number(18),
	ORDER_DATE_id number(18),
	customer_id VARCHAR2(20 BYTE),
	SALES_MEMBER_ID number(18), --銷售群組
	SALES_CHANNEL_ID number(18), --銷售群組
	product_master_id number(18),
	product_type_id number(18),
	price number(15,2),
	quantity number(13,2),
	CONSTRAINT SK_SALES_ORDER_FACT_PK PRIMARY KEY (SALES_ORDER_ID)
)
/
