--fc-model
DROP TABLE TC
-- ODS
drop table sk_zbsegar;
drop table sk_zbsegcoll;
drop table sk_zbsegpp;
drop table sk_zkna1;
drop table sk_zmara;
drop table sk_zvbrk;

--SKSP
DROP table SK_CONTRACT;
DROP table SK_BANK;
DROP TABLE SK_BUDGET;
DROP TABLE SK_CUSTOMER_GROUP;
DROP TABLE SK_WORKINGDAYS;
--DROP TABLE SK_CONTRACT;
--DROP TABLE SK_ZVBAK;
DROP TABLE SK_ACCESS_LOG;
DROP TABLE SK_CALENDAR;
DROP TABLE SK_FI_MASTER_INTERFACE;
DROP TABLE SK_SALES_ALLOWANCES;
DROP TABLE SK_SALES_DAY_ACHIEVEMENT;
DROP TABLE SK_SALES_DAY_ARCHIEVEMENT;
DROP TABLE SK_SALES_DETAILS;
DROP TABLE SK_SALES_DISCOUNT_LOG;
DROP TABLE SK_SALES_MONTH_ACHIEVEMENT;
DROP TABLE SD_ZTAB_EXP_RELFILENO_SD_LOG;
DROP TABLE SK_ZBSEGAR;
DROP TABLE SK_AR_REMIT_ITEM;
DROP TABLE SK_AR_REMIT_MASTER;
DROP TABLE SK_ACCOUNTS_RECEIVABLE;
DROP TABLE SK_SALES_CHANNEL_MEMBER;
DROP TABLE SK_SALES_MEMBER;
DROP TABLE SK_SALES_CHANNELS;
DROP TABLE "SK_SP_USER"."SK_FI_MASTER_INTERFACE";
DROP TABLE "SK_SP_USER"."SK_FI_DETAIL_INTERFACE";
DROP TABLE SK_ADVANCE_PAYMENT;
DROP TABLE SK_PAYMENT_ITEM;
DROP TABLE SK_PREMIUM_DISCOUNT;
DROP TABLE SK_AR_REMIT_INTERFACE;
DROP TABLE SK_SALES_ALLOWANCE_LOG;
DROP TABLE SK_OVERDUE_AR;
DROP TABLE SK_PAYMENT_RATE;
DROP TABLE SK_ADVANCE_REMIT;
DROP TABLE SK_CHECK_MASTER;
DROP TABLE SK_SALES_ORDER;
DROP TABLE SK_SALES_DISCOUNT_MASTER;
DROP TABLE SK_SALES_RETURN_MASTER;
DROP TABLE SK_SALES_ORDER_DETAIL;
DROP TABLE SK_SALES_ORDER_MASTER;
DROP TABLE SK_CUSTOMER;
DROP TABLE SK_PRODUCT_MASTER;
DROP TABLE SK_QUOTATION_REVIEW_HISTORY;
DROP TABLE SK_QUOTATION_GIFT;
DROP TABLE SK_QUOTATION_DETAIL;
DROP TABLE SK_QUOTATION_MASTER;
DROP TABLE SK_QUOTATION_MAIL_GROUP_USER;
DROP TABLE SK_QUOTATION_MAIL_GROUP_MEMBER;
DROP TABLE SK_QUOTATION_MAIL_GROUP;

--SEQUENCE
DROP SEQUENCE "SK_SP_USER"."SEQ_SK_SYNC";
DROP SEQUENCE "SK_SP_USER"."SEQ_WORKLIST_LOG";
DROP SEQUENCE "SK_SP_USER"."SEQ_TRNNO";
