//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.21 at 11:37:08 AM CST 
//


package com.tcci.fc.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="processname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="processversion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}activitytemplate" maxOccurs="unbounded"/>
 *         &lt;element ref="{}activityroutetemplate" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "processname",
    "processversion",
    "activitytemplate",
    "activityroutetemplate"
})
@XmlRootElement(name = "processtemplate")
public class ProcesstemplateConverter{

    @XmlElement(required = true)
    protected String processname;
    @XmlElement(required = true)
    protected String processversion;
    @XmlElement(required = true)
    protected List<ActivitytemplateConverter> activitytemplate;
    @XmlElement(required = true)
    protected List<ActivityroutetemplateConverter> activityroutetemplate;

    /**
     * Gets the value of the processname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessname() {
        return processname;
    }

    /**
     * Sets the value of the processname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessname(String value) {
        this.processname = value;
    }

    /**
     * Gets the value of the processversion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
/*
    public String getProcessversion() {
        return processversion;
    }
*/
    /**
     * Sets the value of the processversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
/*    
    public void setProcessversion(String value) {
        this.processversion = value;
    }
*/
    /**
     * Gets the value of the activitytemplate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the activitytemplate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActivitytemplate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Activitytemplate }
     * 
     * 
     */
    public List<ActivitytemplateConverter> getActivitytemplate() {
        if (activitytemplate == null) {
            activitytemplate = new ArrayList<ActivitytemplateConverter>();
        }
        return this.activitytemplate;
    }

    public void setActivitytemplate(List<ActivitytemplateConverter> activitytemplate){
        this.activitytemplate = activitytemplate ;
    }
    /**
     * Gets the value of the activityroutetemplate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the activityroutetemplate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActivityroutetemplate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Activityroutetemplate }
     * 
     * 
     */
    public List<ActivityroutetemplateConverter> getActivityroutetemplate() {
        if (activityroutetemplate == null) {
            activityroutetemplate = new ArrayList<ActivityroutetemplateConverter>();
        }
        return this.activityroutetemplate;
    }

    public void setActivityroutetemplate(List<ActivityroutetemplateConverter> activityroutetemplate){
        this.activityroutetemplate = activityroutetemplate;
    }
}
