CREATE TABLE "TC_DOWNLOAD_LOG" 
(
"ID" BIGSERIAL PRIMARY KEY, 
"TC_APPLICATIONDATA_ID" BIGINT REFERENCES TC_APPLICATIONDATA(ID),
"TOTAL_COUNT" NUMERIC(6) default 0, 
"CREATOR" BIGINT REFERENCES TC_USER(ID) ,
"CREATETIMESTAMP" DATE,
"MODIFIER" BIGINT REFERENCES TC_USER(ID),
"MODIFYTIMESTAMP" DATE);

COMMENT ON COLUMN "TC_DOWNLOAD_LOG"."ID" IS 'PK';
COMMENT ON COLUMN "TC_DOWNLOAD_LOG"."TC_APPLICATIONDATA_ID" IS 'FK:TC_APPLICATIONDATA.ID';
COMMENT ON COLUMN "TC_DOWNLOAD_LOG"."TOTAL_COUNT" IS '總下載次數';
COMMENT ON COLUMN "TC_DOWNLOAD_LOG"."CREATOR" IS '建立者';
COMMENT ON COLUMN "TC_DOWNLOAD_LOG"."CREATETIMESTAMP" IS '建立時間';
COMMENT ON COLUMN "TC_DOWNLOAD_LOG"."MODIFIER" IS '修改者';
COMMENT ON COLUMN "TC_DOWNLOAD_LOG"."MODIFYTIMESTAMP" IS '修改時間';

CREATE TABLE "TC_DOWNLOAD_LOG_DETAIL" 
(
"ID" BIGSERIAL PRIMARY KEY,
"TC_DOWNLOAD_LOG_ID" BIGINT REFERENCES "TC_DOWNLOAD_LOG"("ID"),
"CREATOR" BIGINT REFERENCES TC_USER(ID),
"CREATETIMESTAMP" DATE
);

COMMENT ON COLUMN "TC_DOWNLOAD_LOG_DETAIL"."ID" IS 'PK';
COMMENT ON COLUMN "TC_DOWNLOAD_LOG_DETAIL"."TC_DOWNLOAD_LOG_ID" IS 'FK:TC_DOWNLOAD_LOG.ID';
COMMENT ON COLUMN "TC_DOWNLOAD_LOG_DETAIL"."CREATOR" IS '建立者';
COMMENT ON COLUMN "TC_DOWNLOAD_LOG_DETAIL"."CREATETIMESTAMP" IS '建立時間';
