CREATE TABLE FC_REPORT_TEMPLATE (
	ID bigint NOT NULL IDENTITY, 
	YEARMONTH char(6) NOT NULL,
	MODIFIER bigint NOT NULL,
	MODIFYTIMESTAMP datetime NOT NULL,
	NOTE nvarchar(1000) NULL,
	CONSTRAINT FC_REPORT_TEMPLATE_PK PRIMARY KEY (ID),
	CONSTRAINT FC_REPORT_TEMPLATE_UK UNIQUE (YEARMONTH),
	CONSTRAINT FC_REPORT_TEMPLATE_FK1 FOREIGN KEY (MODIFIER) REFERENCES TC_USER (ID)
)

CREATE TABLE FC_COMPANY (
	ID bigint NOT NULL IDENTITY,
	CODE nvarchar(6) NOT NULL,
	NAME nvarchar(50) NOT NULL,
	UPLOADER bigint,
	ACTIVE bit NOT NULL,
	CONSTRAINT FC_COMPANY_PK PRIMARY KEY (ID),
	CONSTRAINT FC_COMPANY_UK1 UNIQUE (CODE),
	CONSTRAINT FC_COMPANY_UK2 UNIQUE (NAME),
	CONSTRAINT FC_COMPANY_FK1 FOREIGN KEY (UPLOADER) REFERENCES TC_USER (ID)
)

CREATE TABLE FC_REPORT_UPLOAD (
	ID bigint NOT NULL IDENTITY, 
	YEARMONTH char(6) NOT NULL,
	COMPANY bigint  NOT NULL,
	UPLOADER bigint NOT NULL,
	MODIFYTIMESTAMP datetime NOT NULL,
	CONSTRAINT FC_REPORT_UPLOAD_PK PRIMARY KEY (ID),
	CONSTRAINT FC_REPORT_UPLOAD_UK UNIQUE (YEARMONTH, COMPANY),
	CONSTRAINT FC_REPORT_UPLOAD_FK1 FOREIGN KEY (UPLOADER) REFERENCES TC_USER (ID),
	CONSTRAINT FC_REPORT_UPLOAD_FK2 FOREIGN KEY (COMPANY) REFERENCES FC_COMPANY (ID)
)

CREATE TABLE FC_CONFIG (
	ID bigint NOT NULL IDENTITY, 
	CONFIG_KEY nvarchar(20) NOT NULL,
	CONFIG_VALUE nvarchar(50),
	CONSTRAINT FC_CONFIG_PK PRIMARY KEY (ID),
	CONSTRAINT FC_CONFIG_UK UNIQUE (CONFIG_KEY)
)

CREATE TABLE FC_REPORT_VALUE (
	ID bigint NOT NULL IDENTITY, 
	REPORT_ID bigint NOT NULL,
	SHEET nvarchar(20) NOT NULL,
	COID2 bigint NOT NULL,
	CODE nvarchar(20) NOT NULL,
	AMOUNT decimal(18,3),
	AMOUNT_ORIG decimal(18,3),
	AMOUNT_XLS decimal(18,3),
	MODIFIER bigint NOT NULL,
	MODIFYTIMESTAMP datetime NOT NULL,
	CONSTRAINT FC_REPORT_VALUE_PK PRIMARY KEY (ID),
	CONSTRAINT FC_REPORT_VALUE_FK1 FOREIGN KEY (REPORT_ID) REFERENCES FC_REPORT_UPLOAD (ID),
	CONSTRAINT FC_REPORT_VALUE_FK2 FOREIGN KEY (COID2) REFERENCES FC_COMPANY (ID),
	CONSTRAINT FC_REPORT_VALUE_FK3 FOREIGN KEY (MODIFIER) REFERENCES TC_USER (ID)
)

CREATE TABLE FC_REPORT_NOTE (
	ID bigint NOT NULL IDENTITY, 
	YEARMONTH char(6) NOT NULL,
	COID1 bigint NOT NULL,
	COID2 bigint NOT NULL,
	NOTE nvarchar(500) NULL,
	MODIFIER bigint NOT NULL,
	MODIFYTIMESTAMP datetime NOT NULL,
	CONSTRAINT FC_REPORT_NOTE_PK PRIMARY KEY (ID),
	CONSTRAINT FC_REPORT_NOTE_UK UNIQUE (YEARMONTH, COID1, COID2),
	CONSTRAINT FC_REPORT_NOTE_FK1 FOREIGN KEY (COID1) REFERENCES FC_COMPANY (ID),
	CONSTRAINT FC_REPORT_NOTE_FK2 FOREIGN KEY (COID2) REFERENCES FC_COMPANY (ID),
	CONSTRAINT FC_REPORT_NOTE_FK3 FOREIGN KEY (MODIFIER) REFERENCES TC_USER (ID),
)
