CREATE SEQUENCE "SEQ_ORG" MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 3 NOORDER NOCYCLE;

-- 公司
CREATE TABLE "ORG_COMPANY"
  (
    "ID"         NUMBER(18,0) NOT NULL ENABLE,
    "CODE"       VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "NAME"       VARCHAR2(100 CHAR) NOT NULL ENABLE,
    "ACTIVATION" NUMBER(1,0) NOT NULL ENABLE,
    CONSTRAINT "ORG_COMPANY_PK" PRIMARY KEY ("ID") ENABLE,
    CONSTRAINT "ORG_COMPANY_UK1" UNIQUE ("CODE") ENABLE
  );
COMMENT ON COLUMN "ORG_COMPANY"."ID" IS 'PK';
COMMENT ON COLUMN "ORG_COMPANY"."CODE" IS '公司代碼';
COMMENT ON COLUMN "ORG_COMPANY"."NAME" IS '公司名稱';
COMMENT ON COLUMN "ORG_COMPANY"."ACTIVATION" IS '1:啟用, 0:停用';

-- 部門
CREATE TABLE "ORG_DEPARTMENT"
  (
    "ID"         NUMBER(18,0) NOT NULL ENABLE,
    "COMPANYID"  NUMBER(18,0) NOT NULL ENABLE,
    "CODE"       VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "NAME"       VARCHAR2(100 CHAR) NOT NULL ENABLE,
    "PARENTID"   NUMBER(18,0),
    "ACTIVATION" NUMBER(1,0) NOT NULL ENABLE,
    CONSTRAINT "ORG_DEPARTMENT_PK" PRIMARY KEY ("ID") ENABLE,
    CONSTRAINT "ORG_DEPARTMENT_UK1" UNIQUE ("COMPANYID", "CODE") ENABLE,
    CONSTRAINT "ORG_DEPARTMENT_ORG_COMPAN_FK1" FOREIGN KEY ("COMPANYID") REFERENCES "ORG_COMPANY" ("ID") ENABLE,
	CONSTRAINT "ORG_DEPARTMENT_ORG_DEPART_FK1" FOREIGN KEY ("PARENTID") REFERENCES "ORG_DEPARTMENT" ("ID") ENABLE
  );
COMMENT ON COLUMN "ORG_DEPARTMENT"."ID" IS 'PK';
COMMENT ON COLUMN "ORG_DEPARTMENT"."COMPANYID" IS 'FK:ORG_COMPANY.ID';
COMMENT ON COLUMN "ORG_DEPARTMENT"."CODE" IS '部門代碼';
COMMENT ON COLUMN "ORG_DEPARTMENT"."NAME" IS '部門名稱';
COMMENT ON COLUMN "ORG_DEPARTMENT"."PARENTID" IS '上層部門';
COMMENT ON COLUMN "ORG_DEPARTMENT"."ACTIVATION" IS '1:啟用,0:停用';

-- 員工
CREATE TABLE "ORG_EMPLOYEE"
  (
    "ID"         NUMBER(18,0) NOT NULL ENABLE,
    "COMPANYID"  NUMBER(18,0) NOT NULL ENABLE,
    "DEPTID"     NUMBER(18,0) NOT NULL ENABLE,
    "CODE"       VARCHAR2(40 BYTE) NOT NULL ENABLE,
    "NAME"       VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "EMAIL"      VARCHAR2(50 BYTE),
    "ADACCOUNT"  VARCHAR2(40 BYTE),
    "ACTIVATION" NUMBER(1,0) NOT NULL ENABLE,
    CONSTRAINT "ORG_EMPLOYEE_PK" PRIMARY KEY ("ID")  ENABLE,
    CONSTRAINT "ORG_EMPLOYEE_UK1" UNIQUE ("CODE") ENABLE,
    CONSTRAINT "ORG_EMPLOYEE_ORG_COMPANY_FK1" FOREIGN KEY ("COMPANYID") REFERENCES "ORG_COMPANY" ("ID") ENABLE,
    CONSTRAINT "ORG_EMPLOYEE_ORG_DEPARTME_FK1" FOREIGN KEY ("DEPTID") REFERENCES "ORG_DEPARTMENT" ("ID") ENABLE
  );
COMMENT ON COLUMN "ORG_EMPLOYEE"."ID" IS 'PK';
COMMENT ON COLUMN "ORG_EMPLOYEE"."COMPANYID" IS 'FK:ORG_COMPANY.ID';
COMMENT ON COLUMN "ORG_EMPLOYEE"."DEPTID" IS 'FK:ORG_DEPARTMENT.ID';
COMMENT ON COLUMN "ORG_EMPLOYEE"."CODE" IS '員工編號';
COMMENT ON COLUMN "ORG_EMPLOYEE"."NAME" IS '姓名';
COMMENT ON COLUMN "ORG_EMPLOYEE"."EMAIL" IS '電子信箱';
COMMENT ON COLUMN "ORG_EMPLOYEE"."ADACCOUNT" IS 'AD帳號(小寫)';
COMMENT ON COLUMN "ORG_EMPLOYEE"."ACTIVATION" IS '1:啟用,0:停用';
