-- 排程
CREATE TABLE "TC_SCHEDULE" 
(
	"NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"EXEC_TIME" DATE, 
	"ACTIVE" NUMBER(1,0) DEFAULT 1, 
	CONSTRAINT "TC_SCHEDULE_PK" PRIMARY KEY ("NAME") ENABLE
);
COMMENT ON COLUMN "TC_SCHEDULE"."NAME" IS 'PK:排程名稱';
COMMENT ON COLUMN "TC_SCHEDULE"."EXEC_TIME" IS '前次執行時間';
COMMENT ON COLUMN "TC_SCHEDULE"."ACTIVE" IS '啟用 (1:是, 0:否)';

-- SendOverdueAccount 批次通知
INSERT INTO TC_SCHEDULE (NAME) VALUES ('SendOverdueAccount');
INSERT INTO TC_SCHEDULE (NAME) VALUES ('BatchCreateQuotation');
COMMIT;
