DROP SEQUENCE SEQ_REWARD_LOG;
DROP SEQUENCE SEQ_EC;
DROP SEQUENCE SEQ_ORDER;

DROP TABLE EC_VEHICLE_PREFERENCE;
DROP TABLE EC_LOGIN_LOG;
DROP TABLE EC_ORDER_LOG;
DROP TABLE EC_DIVISIONS_CN;
DROP TABLE EC_CLICK_LOG;
DROP TABLE EC_NOTIFY;
DROP TABLE EC_CAMPAIGN;
-- DROP TABLE EC_PRODUCT_BUY;
DROP TABLE EC_GOODS_BUY;
DROP TABLE EC_REWARD_LOG;
DROP TABLE EC_ORDER;
DROP TABLE EC_PARTNER_COMMENT;
DROP TABLE EC_FORM;

DROP TABLE EC_MEMBER_CUSTOMER;
DROP TABLE EC_MEMBER_PARTNER;
DROP TABLE EC_PLANT_PRODUCT;
DROP TABLE EC_PLANT_SALESAREA;
DROP TABLE EC_CONTRACT_PRODUCT;
DROP TABLE EC_CUSTOMER_SALES;
DROP TABLE EC_DELIVERY_PREFERENCE;
DROP TABLE EC_BANNER_PRODUCT;
-- DROP TABLE EC_PARTNER_PRODUCT;
DROP TABLE EC_PARTNER_GOODS;

DROP TABLE EC_GOODS;
DROP TABLE EC_REWARD;
DROP TABLE EC_CONTRACT;
DROP TABLE EC_PARTNER;
DROP TABLE EC_BANNER;
DROP TABLE EC_MEMBER;
DROP TABLE EC_CUSTOMER;
DROP TABLE EC_PRODUCT;
DROP TABLE EC_PLANT;
DROP TABLE EC_COMPANY;
DROP TABLE EC_SALES;
DROP TABLE EC_DELIVERY_VKORG;
DROP TABLE EC_DELIVERY_PLACE;
DROP TABLE EC_SALESAREA;

DROP TABLE TC_SCHEDULE;
DROP TABLE EC_ARTICLE;
DROP TABLE EC_BULLETIN;

