--drop TABLE EC_SERVICE;
CREATE TABLE EC_SERVICE 
(
	ID NUMBER(18,0) NOT NULL ENABLE, 
	SERVICE VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	SERVICE_URL VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(500 CHAR), 
	ACTIVE NUMBER(1,0) NOT NULL ENABLE, 
	CONSTRAINT EC_SERVICE_PK PRIMARY KEY (ID) ENABLE,
	CONSTRAINT EC_SERVICE_UK1 UNIQUE (SERVICE) ENABLE
);
COMMENT ON COLUMN EC_SERVICE.ID IS 'PK';
COMMENT ON COLUMN EC_SERVICE.SERVICE IS '服務, ex: /bulidshop/servlet';
COMMENT ON COLUMN EC_SERVICE.SERVICE_URL IS '服務網址, ex: http://192.168.203.62/bulidshop/servlet';
COMMENT ON COLUMN EC_SERVICE.DESCRIPTION IS '服務說明';
COMMENT ON COLUMN EC_SERVICE.ACTIVE IS '1:啟用, 0:停用';

INSERT INTO TC_USER (ID,LOGIN_ACCOUNT,CNAME,DISABLED,CREATOR,CREATETIMESTAMP) VALUES (1,'administrator','',0,1,SYSDATE);
INSERT INTO TC_USER (ID,LOGIN_ACCOUNT,CNAME,DISABLED,CREATOR,CREATETIMESTAMP) VALUES (2,'peter.pan','潘倫政',0,1,SYSDATE);
INSERT INTO TC_USER (ID,LOGIN_ACCOUNT,CNAME,DISABLED,CREATOR,CREATETIMESTAMP) VALUES (3,'kyle.cheng','鄭傑鳴',0,1,SYSDATE);

CREATE TABLE TC_USER 
(	
    ID NUMBER(18) NOT NULL ENABLE, 
	LOGIN_ACCOUNT VARCHAR2(60 BYTE) NOT NULL ENABLE, 
	EMAIL VARCHAR2(60 BYTE), 	
	EMP_ID VARCHAR2(20 BYTE),
	CNAME VARCHAR2(20 CHAR),
    disabled   NUMBER(1) default 0, 	
	CREATOR NUMBER(18) ,
    CREATETIMESTAMP DATE NOT NULL,	
	CONSTRAINT TC_USER_PK PRIMARY KEY (ID),
	CONSTRAINT TC_USER_UK UNIQUE (LOGIN_ACCOUNT,CREATETIMESTAMP),
	CONSTRAINT TC_USER_FK FOREIGN KEY (CREATOR) REFERENCES TC_USER(ID)
);

COMMENT ON COLUMN TC_USER.LOGIN_ACCOUNT IS '登入帳號';

CREATE TABLE TC_GROUP 
(	
    ID NUMBER(18) NOT NULL ENABLE, 
    CODE VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	NAME VARCHAR2(90 CHAR) NOT NULL ENABLE, 
	CREATOR NUMBER(18) , 
	CREATETIMESTAMP DATE,
	CONSTRAINT TC_GROUP_PK PRIMARY KEY (ID),
	CONSTRAINT TC_GROUP_UK UNIQUE (CODE),
	CONSTRAINT TC_GROUP_FK FOREIGN KEY (CREATOR) REFERENCES TC_USER(ID)
);
COMMENT ON COLUMN TC_GROUP.ID IS 'TC_GROUP.ID';
COMMENT ON COLUMN TC_GROUP.CODE IS '群組代號';
COMMENT ON COLUMN TC_GROUP.NAME IS '群組名稱';
COMMENT ON COLUMN TC_GROUP.CREATOR IS 'ref. TC_USER.ID';

CREATE TABLE TC_USERGROUP 
(	
	 ID NUMBER(18) NOT NULL ENABLE, 
	 USER_ID NUMBER(18) NOT NULL ENABLE, 
	 GROUP_ID NUMBER(18) DEFAULT 1 NOT NULL ENABLE, 
	 CREATOR NUMBER(18) , 
	 CREATETIMESTAMP DATE,
 	 CONSTRAINT TC_USERGROUP_PK PRIMARY KEY (ID),
	 CONSTRAINT TC_USERGROUP_UK1 UNIQUE (USER_ID, GROUP_ID) ENABLE,
	 CONSTRAINT TC_USERGROUP_FK1 FOREIGN KEY (GROUP_ID) REFERENCES TC_GROUP (ID),
	 CONSTRAINT TC_USERGROUP_FK2 FOREIGN KEY (USER_ID) REFERENCES TC_USER (ID),
	 CONSTRAINT TC_USERGROUP_FK3 FOREIGN KEY (CREATOR) REFERENCES TC_USER (ID)
);

COMMENT ON COLUMN TC_USERGROUP.ID IS 'PK';
COMMENT ON COLUMN TC_USERGROUP.USER_ID IS 'Group member (FK:TC_USER.ID)';
COMMENT ON COLUMN TC_USERGROUP.GROUP_ID IS 'group (FK:TC_GROUP.ID)';
COMMENT ON COLUMN TC_USERGROUP.CREATOR IS '建立者';
COMMENT ON COLUMN TC_USERGROUP.CREATETIMESTAMP IS '建立時間';

-- 會員
CREATE TABLE "EC_MEMBER"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"LOGIN_ACCOUNT" VARCHAR2(50 BYTE) NOT NULL ENABLE,
"NAME" VARCHAR2(64 CHAR) NOT NULL ENABLE,
"EMAIL" VARCHAR2(64 BYTE),
"PHONE" VARCHAR2(50 BYTE),
"PASSWORD" VARCHAR2(64 BYTE),
"ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
"CREATOR" NUMBER(18,0), 
"CREATETIME" DATE,
"MODIFIER" NUMBER(18,0), 
"MODIFYTIME" DATE,
CONSTRAINT "EC_MEMBER_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_MEMBER_UK1" UNIQUE ("LOGIN_ACCOUNT") ENABLE
);
COMMENT ON COLUMN "EC_MEMBER"."ID" IS 'PK';
COMMENT ON COLUMN "EC_MEMBER"."LOGIN_ACCOUNT" IS '登入帳號';
COMMENT ON COLUMN "EC_MEMBER"."NAME" IS '姓名';
COMMENT ON COLUMN "EC_MEMBER"."EMAIL" IS '電子信箱';
COMMENT ON COLUMN "EC_MEMBER"."PHONE" IS '電話';
COMMENT ON COLUMN "EC_MEMBER"."PASSWORD" IS '密碼(SHA256)';
COMMENT ON COLUMN "EC_MEMBER"."ACTIVE" IS '1:啟用, 0:停用';
COMMENT ON COLUMN "EC_MEMBER"."CREATOR" IS '建立人';
COMMENT ON COLUMN "EC_MEMBER"."CREATETIME" IS '建立時間';
COMMENT ON COLUMN "EC_MEMBER"."MODIFIER" IS '最近修改人';
COMMENT ON COLUMN "EC_MEMBER"."MODIFYTIME" IS '最近修改時間';

--客戶
CREATE TABLE "EC_CUSTOMER"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"MEMBER_ID" NUMBER(18,0) NOT NULL ENABLE,
"SHORTNAME" VARCHAR2(64 CHAR),
"CREATOR" NUMBER(18,0), 
"CREATETIME" DATE,
"MODIFIER" NUMBER(18,0), 
"MODIFYTIME" DATE,
CONSTRAINT "EC_CUSTOMER_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_CUSTOMER_FK1" FOREIGN KEY ("MEMBER_ID") REFERENCES "EC_MEMBER" ("ID") ENABLE,
CONSTRAINT "EC_CUSTOMER_FK2" FOREIGN KEY ("CREATOR") REFERENCES "EC_MEMBER" ("ID") ENABLE,
CONSTRAINT "EC_CUSTOMER_FK3" FOREIGN KEY ("MODIFIER") REFERENCES "EC_MEMBER" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_CUSTOMER"."ID" IS 'PK';
COMMENT ON COLUMN "EC_CUSTOMER"."MEMBER_ID" IS 'FK:EC_MEMBER.ID';
COMMENT ON COLUMN "EC_CUSTOMER"."CREATOR" IS '建立人';
COMMENT ON COLUMN "EC_CUSTOMER"."CREATETIME" IS '建立時間';
COMMENT ON COLUMN "EC_CUSTOMER"."MODIFIER" IS '最近修改人';
COMMENT ON COLUMN "EC_CUSTOMER"."MODIFYTIME" IS '最近修改時間';
--ALTER TABLE EC_CUSTOMER add SHORTNAME VARCHAR2(64 CHAR);

--客戶地址
CREATE TABLE "EC_CUS_ADDR"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"CUSTOMER_ID" NUMBER(18,0) NOT NULL ENABLE,
"RECIPIENT" VARCHAR2(40 CHAR),
"ADDRESS" VARCHAR2(80 CHAR),
"ADDRESS_2" VARCHAR2(80 CHAR),
"TYPE" VARCHAR2(10 BYTE),
"ALIAS" VARCHAR2(40 CHAR),
"COMPANY" VARCHAR2(40 CHAR),
"CITY" VARCHAR2(40 CHAR),
"STATE_REGION" VARCHAR2(40 CHAR),
"COUNTRY" VARCHAR2(40 CHAR),
"POSTAL_CODE" VARCHAR2(20 BYTE),
"FAX" VARCHAR2(20 BYTE),
"PHONE" VARCHAR2(20 BYTE),
"PHONE_EXTENSION" VARCHAR2(20 BYTE),
"PRIMARY" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
"CREATOR" NUMBER(18,0), 
"CREATETIME" DATE,
"MODIFIER" NUMBER(18,0), 
"MODIFYTIME" DATE,
CONSTRAINT "EC_CUS_ADDR_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_CUS_ADDR_FK1" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "EC_CUSTOMER" ("ID") ENABLE,
CONSTRAINT "EC_CUS_ADDR_FK2" FOREIGN KEY ("CREATOR") REFERENCES "EC_MEMBER" ("ID") ENABLE,
CONSTRAINT "EC_CUS_ADDR_FK3" FOREIGN KEY ("MODIFIER") REFERENCES "EC_MEMBER" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_CUS_ADDR"."ID" IS 'PK';
COMMENT ON COLUMN "EC_CUS_ADDR"."CUSTOMER_ID" IS 'FK:EC_CUSTOMER.ID';
COMMENT ON COLUMN "EC_CUS_ADDR"."RECIPIENT" IS '收件人姓名';
COMMENT ON COLUMN "EC_CUS_ADDR"."ADDRESS" IS '地址';
COMMENT ON COLUMN "EC_CUS_ADDR"."ADDRESS_2" IS '地址2';
COMMENT ON COLUMN "EC_CUS_ADDR"."TYPE" IS '地址類型(Bill or Ship)';
COMMENT ON COLUMN "EC_CUS_ADDR"."ALIAS" IS '別名';
COMMENT ON COLUMN "EC_CUS_ADDR"."COMPANY" IS '公司';
COMMENT ON COLUMN "EC_CUS_ADDR"."CITY" IS '城市';
COMMENT ON COLUMN "EC_CUS_ADDR"."STATE_REGION" IS '州or區';
COMMENT ON COLUMN "EC_CUS_ADDR"."COUNTRY" IS '國家';
COMMENT ON COLUMN "EC_CUS_ADDR"."POSTAL_CODE" IS '郵遞區號';
COMMENT ON COLUMN "EC_CUS_ADDR"."FAX" IS '傳真';
COMMENT ON COLUMN "EC_CUS_ADDR"."PHONE" IS '電話';
COMMENT ON COLUMN "EC_CUS_ADDR"."PHONE_EXTENSION" IS '分機';
COMMENT ON COLUMN "EC_CUS_ADDR"."PRIMARY" IS '1:主要預設';
COMMENT ON COLUMN "EC_CUS_ADDR"."CREATOR" IS '建立人';
COMMENT ON COLUMN "EC_CUS_ADDR"."CREATETIME" IS '建立時間';
COMMENT ON COLUMN "EC_CUS_ADDR"."MODIFIER" IS '最近修改人';
COMMENT ON COLUMN "EC_CUS_ADDR"."MODIFYTIME" IS '最近修改時間';

ALTER TABLE EC_CUS_ADDR add RECIPIENT VARCHAR2(40 CHAR);

--客戶交易幣別
CREATE TABLE "EC_CUS_CUR"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"CUSTOMER_ID" NUMBER(18,0) NOT NULL ENABLE,
"CURRENCY_ID" NUMBER(18,0) NOT NULL ENABLE,
"CREATOR" NUMBER(18,0), 
"CREATETIME" DATE,
"MODIFIER" NUMBER(18,0), 
"MODIFYTIME" DATE,
CONSTRAINT "EC_CUS_CUR_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_CUS_CUR_FK1" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "EC_CUSTOMER" ("ID") ENABLE,
CONSTRAINT "EC_CUS_CUR_FK2" FOREIGN KEY ("CURRENCY_ID") REFERENCES "EC_CURRENCY" ("ID") ENABLE,
CONSTRAINT "EC_CUS_CUR_FK3" FOREIGN KEY ("CREATOR") REFERENCES "EC_MEMBER" ("ID") ENABLE,
CONSTRAINT "EC_CUS_CUR_FK4" FOREIGN KEY ("MODIFIER") REFERENCES "EC_MEMBER" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_CUS_CUR"."ID" IS 'PK';
COMMENT ON COLUMN "EC_CUS_CUR"."CUSTOMER_ID" IS 'FK:EC_MEMBER.ID';
COMMENT ON COLUMN "EC_CUS_CUR"."CURRENCY_ID" IS '幣別 FK:EC_CURRENCY.ID';
COMMENT ON COLUMN "EC_CUS_CUR"."CREATOR" IS '建立人';
COMMENT ON COLUMN "EC_CUS_CUR"."CREATETIME" IS '建立時間';
COMMENT ON COLUMN "EC_CUS_CUR"."MODIFIER" IS '最近修改人';
COMMENT ON COLUMN "EC_CUS_CUR"."MODIFYTIME" IS '最近修改時間';

--EC_CUS_ATTR 客戶屬性
--EC_PRD_ATTR_VAL 客戶屬性設定值

--付款檔設定
CREATE TABLE "EC_PAYMENT"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"TITLE" VARCHAR2(80 CHAR),
"DESC" VARCHAR2(80 CHAR),
"TYPE" VARCHAR2(10 BYTE),
"ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
"CREATOR" NUMBER(18,0), 
"CREATETIME" DATE,
"MODIFIER" NUMBER(18,0), 
"MODIFYTIME" DATE,
CONSTRAINT "EC_PAYMENT_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_PAYMENT_FK1" FOREIGN KEY ("CREATOR") REFERENCES "EC_MEMBER" ("ID") ENABLE,
CONSTRAINT "EC_PAYMENT_FK2" FOREIGN KEY ("MODIFIER") REFERENCES "EC_MEMBER" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_PAYMENT"."ID" IS 'PK';
COMMENT ON COLUMN "EC_PAYMENT"."TITLE" IS '名稱';
COMMENT ON COLUMN "EC_PAYMENT"."DESC" IS '敘述';
COMMENT ON COLUMN "EC_PAYMENT"."TYPE" IS '類別(Credit Card or On Delivery)';
COMMENT ON COLUMN "EC_PAYMENT"."ACTIVE" IS '1:啟用, 0:停用';
COMMENT ON COLUMN "EC_PAYMENT"."CREATOR" IS '建立人';
COMMENT ON COLUMN "EC_PAYMENT"."CREATETIME" IS '建立時間';
COMMENT ON COLUMN "EC_PAYMENT"."MODIFIER" IS '最近修改人';
COMMENT ON COLUMN "EC_PAYMENT"."MODIFYTIME" IS '最近修改時間';

--運送方式主檔
CREATE TABLE "EC_SHIPPING"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"TITLE" VARCHAR2(80 CHAR),
"DESC" VARCHAR2(80 CHAR),
"TYPE" VARCHAR2(10 BYTE),
"ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
"CREATOR" NUMBER(18,0), 
"CREATETIME" DATE,
"MODIFIER" NUMBER(18,0), 
"MODIFYTIME" DATE,
CONSTRAINT "EC_SHIPPING_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_SHIPPING_FK1" FOREIGN KEY ("CREATOR") REFERENCES "EC_MEMBER" ("ID") ENABLE,
CONSTRAINT "EC_SHIPPING_FK2" FOREIGN KEY ("MODIFIER") REFERENCES "EC_MEMBER" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_SHIPPING"."ID" IS 'PK';
COMMENT ON COLUMN "EC_SHIPPING"."TITLE" IS '名稱';
COMMENT ON COLUMN "EC_SHIPPING"."DESC" IS '敘述';
COMMENT ON COLUMN "EC_SHIPPING"."TYPE" IS '類別';
COMMENT ON COLUMN "EC_SHIPPING"."ACTIVE" IS '1:啟用, 0:停用';
COMMENT ON COLUMN "EC_SHIPPING"."CREATOR" IS '建立人';
COMMENT ON COLUMN "EC_SHIPPING"."CREATETIME" IS '建立時間';
COMMENT ON COLUMN "EC_SHIPPING"."MODIFIER" IS '最近修改人';
COMMENT ON COLUMN "EC_SHIPPING"."MODIFYTIME" IS '最近修改時間';


--運送服務供應商
CREATE TABLE "EC_SHIPPING_PROVIDER"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"SHIPPING_ID" NUMBER(18,0) NOT NULL ENABLE,
"TITLE" VARCHAR2(80 CHAR),
"DESC" VARCHAR2(80 CHAR),
"ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
"CREATOR" NUMBER(18,0), 
"CREATETIME" DATE,
"MODIFIER" NUMBER(18,0), 
"MODIFYTIME" DATE,
CONSTRAINT "EC_SHIPPING_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_SHIPPING_FK1" FOREIGN KEY ("SHIPPING_ID") REFERENCES "EC_SHIPPING" ("ID") ENABLE,
CONSTRAINT "EC_SHIPPING_FK1" FOREIGN KEY ("CREATOR") REFERENCES "EC_MEMBER" ("ID") ENABLE,
CONSTRAINT "EC_SHIPPING_FK2" FOREIGN KEY ("MODIFIER") REFERENCES "EC_MEMBER" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_SHIPPING"."ID" IS 'PK';
COMMENT ON COLUMN "EC_SHIPPING"."SHIPPING_ID" IS 'FK:EC_SHIPPING.ID';
COMMENT ON COLUMN "EC_SHIPPING"."TITLE" IS '名稱';
COMMENT ON COLUMN "EC_SHIPPING"."DESC" IS '敘述';
COMMENT ON COLUMN "EC_SHIPPING"."ACTIVE" IS '1:啟用, 0:停用';
COMMENT ON COLUMN "EC_SHIPPING"."CREATOR" IS '建立人';
COMMENT ON COLUMN "EC_SHIPPING"."CREATETIME" IS '建立時間';
COMMENT ON COLUMN "EC_SHIPPING"."MODIFIER" IS '最近修改人';
COMMENT ON COLUMN "EC_SHIPPING"."MODIFYTIME" IS '最近修改時間';

-- 訂單
CREATE TABLE "EC_ORDER"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"ORDER_NUMBER" VARCHAR2(20 CHAR) NOT NULL ENABLE,
"CUSTOMER_ID" NUMBER(18,0) NOT NULL ENABLE,
"SELLER_ID" NUMBER(18,0),
"PAYMENT_ID" NUMBER(18,0),
"PAYMENT_TYPE" VARCHAR2(20 BYTE),
"TOTAL" NUMBER(15,2) DEFAULT 0 NOT NULL ENABLE,
"SUB_TOTAL" NUMBER(15,2) DEFAULT 0 NOT NULL ENABLE,
"SHIPPING_TOTAL" NUMBER(15,2) DEFAULT 0 NOT NULL ENABLE,
"DISCOUNT_TOTAL" NUMBER(15,2) DEFAULT 0 NOT NULL ENABLE,
"CURRENCY_ID" NUMBER(18,0) NOT NULL ENABLE,
"SHIPPING_ID" NUMBER(18,0),
"SHIPPING_DATE" VARCHAR2(8 BYTE),
"DISCOUNT_ID" NUMBER(18,0),
"COUPON_ID" NUMBER(18,0),
"BONUS"	NUMBER(5,0) DEFAULT 0 NOT NULL ENABLE,
"STATUS" VARCHAR2(20 BYTE) NOT NULL ENABLE,
"PAY_STATUS" VARCHAR2(20 BYTE),
"SHIP_STATUS" VARCHAR2(20 BYTE),
"RECIPIENT" VARCHAR2(40 CHAR),
"ADDRESS" VARCHAR2(160 CHAR),
"PHONE" VARCHAR2(20 BYTE),
"MESSAGE" VARCHAR2(255 CHAR),
"CREATOR" NUMBER(18,0), 
"CREATETIME" DATE,
"MODIFIER" NUMBER(18,0), 
"MODIFYTIME" DATE,
"APPROVETIME" DATE,
CONSTRAINT "EC_ORDER_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_ORDER_FK1" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "EC_CUSTOMER" ("ID") ENABLE,
CONSTRAINT "EC_ORDER_FK2" FOREIGN KEY ("SELLER_ID") REFERENCES "EC_SELLER" ("ID") ENABLE,
CONSTRAINT "EC_ORDER_FK3" FOREIGN KEY ("PAYMENT_ID") REFERENCES "EC_PAYMENT" ("ID") ENABLE,
CONSTRAINT "EC_ORDER_FK4" FOREIGN KEY ("CURRENCY_ID") REFERENCES "EC_CURRENCY" ("ID") ENABLE,
CONSTRAINT "EC_ORDER_FK5" FOREIGN KEY ("SHIPPING_ID") REFERENCES "EC_SHIPPING" ("ID") ENABLE,
CONSTRAINT "EC_ORDER_FK6" FOREIGN KEY ("DISCOUNT_ID") REFERENCES "EC_DISCOUNT" ("ID") ENABLE,
CONSTRAINT "EC_ORDER_FK7" FOREIGN KEY ("COUPON_ID") REFERENCES "EC_COUPON" ("ID") ENABLE,
CONSTRAINT "EC_ORDER_FK8" FOREIGN KEY ("CREATOR") REFERENCES "EC_MEMBER" ("ID") ENABLE,
CONSTRAINT "EC_ORDER_FK9" FOREIGN KEY ("MODIFIER") REFERENCES "EC_MEMBER" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_ORDER"."ID" IS 'PK';
COMMENT ON COLUMN "EC_ORDER"."ORDER_NUMBER" IS '訂單編號';
COMMENT ON COLUMN "EC_ORDER"."CUSTOMER_ID" IS 'FK:EC_CUSTOMER.ID';
COMMENT ON COLUMN "EC_ORDER"."SELLER_ID" IS 'FK:EC_SELLER.ID';
COMMENT ON COLUMN "EC_ORDER"."PAYMENT_ID" IS 'FK:EC_PAYMENT.ID';
COMMENT ON COLUMN "EC_ORDER"."PAYMENT_TYPE" IS '付款方式 (A:付款後出貨, B:貨到付款, C:分期付款)';
COMMENT ON COLUMN "EC_ORDER"."TOTAL" IS '總金額';
COMMENT ON COLUMN "EC_ORDER"."SUBTOTAL" IS '小計';
COMMENT ON COLUMN "EC_ORDER"."SHIPPING_TOTAL" IS '運費';
COMMENT ON COLUMN "EC_ORDER"."TDISCOUNT_OTAL" IS '折扣金額';
COMMENT ON COLUMN "EC_ORDER"."CURRENCY_ID" IS '幣別 FK:EC_CURRENCY.ID';
COMMENT ON COLUMN "EC_ORDER"."SHIPPING_ID" IS '運送方式 FK:EC_SHIPPING.ID';
COMMENT ON COLUMN "EC_ORDER"."SHIPPING_DATE" IS '出貨日';
COMMENT ON COLUMN "EC_ORDER"."DISCOUNT_ID" IS '折扣 FK:EC_DISCOUNT.ID';
COMMENT ON COLUMN "EC_ORDER"."COUPON_ID" IS '優惠卷 FK:EC_COUPON.ID';
COMMENT ON COLUMN "EC_ORDER"."BONUS" IS '紅利';
COMMENT ON COLUMN "EC_ORDER"."RECIPIENT" IS '收件人姓名';
COMMENT ON COLUMN "EC_ORDER"."ADDRESS" IS '收件地址';
COMMENT ON COLUMN "EC_ORDER"."PHONE" IS '收件人連絡電話';
COMMENT ON COLUMN "EC_ORDER"."MESSAGE" IS '訊息';
--COMMENT ON COLUMN "EC_ORDER"."STATUS" IS '狀態 (OPEN:未出貨, CANCEL: 取消, CLOSE:已出貨)';
--COMMENT ON COLUMN "EC_ORDER"."STATUS" IS '狀態 (Unknown:未成立(購物車), Pending:待確認, Paid:已付款, Declined:賣方拒絕, Shipped:已出貨, Authorized:已授權, Cancelled: 取消, Deleted:刪除, Returned:退回)';
COMMENT ON COLUMN "EC_ORDER"."STATUS" IS '狀態 (Unknown:未成立(購物車), Pending:待確認, Inquiry:買方詢價, quotation:賣方報價, Approve:已核准, Declined:賣方拒絕, Authorized:已授權, Cancelled: 取消, Deleted:刪除, Returned:退回)';
COMMENT ON COLUMN "EC_ORDER"."PAY_STATUS" IS '付款狀態 (A:未付款, B:已收款, C:已收到部分款項)';
COMMENT ON COLUMN "EC_ORDER"."SHIP_STATUS" IS '出貨狀態 (A:未出貨, B:已出貨, C:部分出貨, D:已到貨)';
COMMENT ON COLUMN "EC_ORDER"."CREATOR" IS '建立人';
COMMENT ON COLUMN "EC_ORDER"."CREATETIME" IS '建立時間';
COMMENT ON COLUMN "EC_ORDER"."MODIFIER" IS '最近修改人';
COMMENT ON COLUMN "EC_ORDER"."MODIFYTIME" IS '最近修改時間';
COMMENT ON COLUMN "EC_ORDER"."APPROVETIME" IS '訂單成立時間';


--Unknown, Pending, Paid, Declined, Shipped, Authorized, Cancelled, Deleted or Returned
--訂單的狀態。 可能是以下之一：未知，待定，付費，拒絕，運送，授權，取消，刪除或退回。

--ALTER TABLE EC_ORDER add RECIPIENT VARCHAR2(40 CHAR);
ALTER TABLE EC_ORDER add ADDRESS VARCHAR2(160 CHAR);
ALTER TABLE EC_ORDER add PHONE VARCHAR2(20 BYTE);


--訂單log
CREATE TABLE "EC_ORDER_LOG"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"ORDER_ID" NUMBER(18,0) NOT NULL ENABLE,
"EVENT_TYPE" VARCHAR2(10 BYTE),
"MESSAGE" VARCHAR2(120 CHAR),
"MEMBER_ID" NUMBER(18,0),
"USER_ID" NUMBER(18,0), 
"CREATETIME" DATE,
CONSTRAINT "EC_ORDER_LOG_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_ORDER_LOG_FK1" FOREIGN KEY ("ORDER_ID") REFERENCES "EC_ORDER" ("ID") ENABLE,
CONSTRAINT "EC_ORDER_LOG_FK2" FOREIGN KEY ("MEMBER_ID") REFERENCES "EC_MEMBER" ("ID") ENABLE,
CONSTRAINT "EC_ORDER_LOG_FK3" FOREIGN KEY ("USER_ID") REFERENCES "TC_USER" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_ORDER_LOG"."ID" IS 'PK';
COMMENT ON COLUMN "EC_ORDER_LOG"."ORDER_ID" IS 'FK:EC_ORDER.ID';
COMMENT ON COLUMN "EC_ORDER_LOG"."EVENT_TYPE" IS '';
COMMENT ON COLUMN "EC_ORDER_LOG"."MESSAGE" IS '訊息';
COMMENT ON COLUMN "EC_ORDER_LOG"."MEMBER_ID" IS 'FK:EC_MEMBER.ID(前台user)';
COMMENT ON COLUMN "EC_ORDER_LOG"."USER_ID" IS 'FK:TC_USER.ID(後台user)';
COMMENT ON COLUMN "EC_ORDER_LOG"."CREATETIME" IS '建立時間';
--seq
drop SEQUENCE SEQ_ORDER_LOG;
CREATE SEQUENCE SEQ_ORDER_LOG INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 3;


-- 訂單明細
CREATE TABLE "EC_ORDER_DETAIL"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"ORDER_ID" NUMBER(18,0) NOT NULL ENABLE,
"PRODUCT_ID" NUMBER(18,0) NOT NULL ENABLE,
"TOTAL" NUMBER(15,2) DEFAULT 0 NOT NULL ENABLE,
"PRICE" NUMBER(15,2) DEFAULT 0 NOT NULL ENABLE,
"QUANTITY" NUMBER(15,2) DEFAULT 0 NOT NULL ENABLE,
"SHIPPABLE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
"ON_SALE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
"CREATOR" NUMBER(18,0), 
"CREATETIME" DATE,
"MODIFIER" NUMBER(18,0), 
"MODIFYTIME" DATE,
CONSTRAINT "EC_ORDER_DETAIL_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_ORDER_DETAIL_FK1" FOREIGN KEY ("ORDER_ID") REFERENCES "EC_ORDER" ("ID") ENABLE,
CONSTRAINT "EC_ORDER_DETAIL_FK2" FOREIGN KEY ("PRODUCT_ID") REFERENCES "EC_PRODUCT" ("ID") ENABLE,
CONSTRAINT "EC_ORDER_DETAIL_FK3" FOREIGN KEY ("CREATOR") REFERENCES "EC_MEMBER" ("ID") ENABLE,
CONSTRAINT "EC_ORDER_DETAIL_FK4" FOREIGN KEY ("MODIFIER") REFERENCES "EC_MEMBER" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_ORDER_DETAIL"."ID" IS 'PK';
COMMENT ON COLUMN "EC_ORDER_DETAIL"."ORDER_ID" IS 'FK:EC_ORDER.ID';
COMMENT ON COLUMN "EC_ORDER_DETAIL"."PRODUCT_ID" IS 'FK:EC_PRODUCT.ID';
COMMENT ON COLUMN "EC_ORDER_DETAIL"."TOTAL" IS '金額';
COMMENT ON COLUMN "EC_ORDER_DETAIL"."PRICE" IS '單價';
COMMENT ON COLUMN "EC_ORDER_DETAIL"."QUANTITY" IS '數量';
COMMENT ON COLUMN "EC_ORDER_DETAIL"."SHIPPABLE" IS '1:可出貨';
COMMENT ON COLUMN "EC_ORDER_DETAIL"."ON_SALE" IS '1:銷售中';
COMMENT ON COLUMN "EC_ORDER_DETAIL"."CREATOR" IS '建立人';
COMMENT ON COLUMN "EC_ORDER_DETAIL"."CREATETIME" IS '建立時間';
COMMENT ON COLUMN "EC_ORDER_DETAIL"."MODIFIER" IS '最近修改人';
COMMENT ON COLUMN "EC_ORDER_DETAIL"."MODIFYTIME" IS '最近修改時間';

-- 訂單評價
--FK 已成立(狀態Shipped)的訂單
CREATE TABLE "EC_ORDER_RATE"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"ORDER_ID" NUMBER(18,0) NOT NULL ENABLE,
"CUSTOMER_RATE" VARCHAR2(10 BYTE),
"CUSTOMER_MESSAGE" VARCHAR2(255 CHAR),
"SELLER_RATE" VARCHAR2(10 BYTE),
"SELLER_MESSAGE" VARCHAR2(255 CHAR),
"CREATOR" NUMBER(18,0), 
"CREATETIME" DATE,
"MODIFIER" NUMBER(18,0), 
"MODIFYTIME" DATE,
CONSTRAINT "EC_ORDER_RATEL_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_ORDER_RATE_FK1" FOREIGN KEY ("ORDER_ID") REFERENCES "EC_ORDER" ("ID") ENABLE,
CONSTRAINT "EC_ORDER_RATE_FK2" FOREIGN KEY ("CREATOR") REFERENCES "EC_MEMBER" ("ID") ENABLE,
CONSTRAINT "EC_ORDER_RATE_FK3" FOREIGN KEY ("MODIFIER") REFERENCES "EC_MEMBER" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_ORDER_RATE"."ID" IS 'PK';
COMMENT ON COLUMN "EC_ORDER_RATE"."ORDER_ID" IS 'FK:EC_ORDER.ID';
COMMENT ON COLUMN "EC_ORDER_RATE"."CUSTOMER_RATE" IS '買方給評';
COMMENT ON COLUMN "EC_ORDER_RATE"."CUSTOMER_MESSAGE" IS '買方給評意見';
COMMENT ON COLUMN "EC_ORDER_RATE"."SELLER_RATE" IS '賣方給評';
COMMENT ON COLUMN "EC_ORDER_RATE"."SELLER_MESSAGE" IS '賣方給評意見';
COMMENT ON COLUMN "EC_ORDER_RATE"."CREATOR" IS '建立人';
COMMENT ON COLUMN "EC_ORDER_RATE"."CREATETIME" IS '建立時間';
COMMENT ON COLUMN "EC_ORDER_RATE"."MODIFIER" IS '最近修改人';
COMMENT ON COLUMN "EC_ORDER_RATE"."MODIFYTIME" IS '最近修改時間';

--購物車 
--FK 賣方未定 狀態Unknown 的訂單
CREATE TABLE "EC_CART_ORDER"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"ORDER_ID" NUMBER(18,0) NOT NULL ENABLE,
"CREATOR" NUMBER(18,0), 
"CREATETIME" DATE,
"MODIFIER" NUMBER(18,0), 
"MODIFYTIME" DATE,
CONSTRAINT "EC_CART_ORDER_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_CART_ORDER_FK1" FOREIGN KEY ("ORDER_ID") REFERENCES "EC_ORDER" ("ID") ENABLE,
CONSTRAINT "EC_CART_ORDER_FK2" FOREIGN KEY ("CREATOR") REFERENCES "EC_MEMBER" ("ID") ENABLE,
CONSTRAINT "EC_CART_ORDER_FK3" FOREIGN KEY ("MODIFIER") REFERENCES "EC_MEMBER" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_CART_ORDER"."ID" IS 'PK';
COMMENT ON COLUMN "EC_CART_ORDER"."ORDER_ID" IS 'FK:EC_ORDER.ID';
COMMENT ON COLUMN "EC_CART_ORDER"."CREATOR" IS '建立人';
COMMENT ON COLUMN "EC_CART_ORDER"."CREATETIME" IS '建立時間';
COMMENT ON COLUMN "EC_CART_ORDER"."MODIFIER" IS '最近修改人';
COMMENT ON COLUMN "EC_CART_ORDER"."MODIFYTIME" IS '最近修改時間';


--喜愛賣家
CREATE TABLE "EC_FAVORITE_SELLER"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"CUSTOMER_ID" NUMBER(18,0) NOT NULL ENABLE,
"SELLER_ID" NUMBER(18,0) NOT NULL ENABLE,
"CREATOR" NUMBER(18,0), 
"CREATETIME" DATE,
"MODIFIER" NUMBER(18,0), 
"MODIFYTIME" DATE,
CONSTRAINT "EC_FAVORITE_SELLER_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_FAVORITE_SELLER_FK1" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "EC_CUSTOMER" ("ID") ENABLE,
CONSTRAINT "EC_FAVORITE_SELLER_FK2" FOREIGN KEY ("SELLER_ID") REFERENCES "EC_SELLER" ("ID") ENABLE,
CONSTRAINT "EC_FAVORITE_SELLER_FK3" FOREIGN KEY ("CREATOR") REFERENCES "EC_MEMBER" ("ID") ENABLE,
CONSTRAINT "EC_FAVORITE_SELLER_FK4" FOREIGN KEY ("MODIFIER") REFERENCES "EC_MEMBER" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_FAVORITE_SELLER"."ID" IS 'PK';
COMMENT ON COLUMN "EC_FAVORITE_SELLER"."CUSTOMER_ID" IS 'FK:EC_CUSTOMER.ID';
COMMENT ON COLUMN "EC_FAVORITE_SELLER"."SELLER_ID" IS 'FK:EC_SELLER.ID';
COMMENT ON COLUMN "EC_FAVORITE_SELLER"."CREATOR" IS '建立人';
COMMENT ON COLUMN "EC_FAVORITE_SELLER"."CREATETIME" IS '建立時間';
COMMENT ON COLUMN "EC_FAVORITE_SELLER"."MODIFIER" IS '最近修改人';
COMMENT ON COLUMN "EC_FAVORITE_SELLER"."MODIFYTIME" IS '最近修改時間';
--喜愛店家
CREATE TABLE "EC_FAVORITE_STORE"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"CUSTOMER_ID" NUMBER(18,0) NOT NULL ENABLE,
"STORE_ID" NUMBER(18,0) NOT NULL ENABLE,
"CREATOR" NUMBER(18,0), 
"CREATETIME" DATE,
"MODIFIER" NUMBER(18,0), 
"MODIFYTIME" DATE,
CONSTRAINT "EC_FAVORITE_STORE_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_FAVORITE_STORE_FK1" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "EC_CUSTOMER" ("ID") ENABLE,
CONSTRAINT "EC_FAVORITE_STORE_FK2" FOREIGN KEY ("STORE_ID") REFERENCES "EC_STORE" ("ID") ENABLE,
CONSTRAINT "EC_FAVORITE_STORE_FK3" FOREIGN KEY ("CREATOR") REFERENCES "EC_MEMBER" ("ID") ENABLE,
CONSTRAINT "EC_FAVORITE_STORE_FK4" FOREIGN KEY ("MODIFIER") REFERENCES "EC_MEMBER" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_FAVORITE_STORE"."ID" IS 'PK';
COMMENT ON COLUMN "EC_FAVORITE_STORE"."CUSTOMER_ID" IS 'FK:EC_CUSTOMER.ID';
COMMENT ON COLUMN "EC_FAVORITE_STORE"."STORE_ID" IS 'FK:EC_STORE.ID';
COMMENT ON COLUMN "EC_FAVORITE_STORE"."CREATOR" IS '建立人';
COMMENT ON COLUMN "EC_FAVORITE_STORE"."CREATETIME" IS '建立時間';
COMMENT ON COLUMN "EC_FAVORITE_STORE"."MODIFIER" IS '最近修改人';
COMMENT ON COLUMN "EC_FAVORITE_STORE"."MODIFYTIME" IS '最近修改時間';

--喜愛商品
CREATE TABLE "EC_FAVORITE_PRD"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"CUSTOMER_ID" NUMBER(18,0) NOT NULL ENABLE,
"PRODUCT_ID" NUMBER(18,0) NOT NULL ENABLE,
"CREATOR" NUMBER(18,0), 
"CREATETIME" DATE,
"MODIFIER" NUMBER(18,0), 
"MODIFYTIME" DATE,
CONSTRAINT "EC_FAVORITE_PRD_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_FAVORITE_PRD_FK1" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "EC_CUSTOMER" ("ID") ENABLE,
CONSTRAINT "EC_FAVORITE_PRD_FK2" FOREIGN KEY ("PRODUCT_ID") REFERENCES "EC_PRODUCT" ("ID") ENABLE,
CONSTRAINT "EC_FAVORITE_PRD_FK3" FOREIGN KEY ("CREATOR") REFERENCES "EC_MEMBER" ("ID") ENABLE,
CONSTRAINT "EC_FAVORITE_PRD_FK4" FOREIGN KEY ("MODIFIER") REFERENCES "EC_MEMBER" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_FAVORITE_PRD"."ID" IS 'PK';
COMMENT ON COLUMN "EC_FAVORITE_PRD"."CUSTOMER_ID" IS 'FK:EC_CUSTOMER.ID';
COMMENT ON COLUMN "EC_FAVORITE_PRD"."PRODUCT_ID" IS 'FK:EC_PRODUCT.ID';
COMMENT ON COLUMN "EC_FAVORITE_PRD"."CREATOR" IS '建立人';
COMMENT ON COLUMN "EC_FAVORITE_PRD"."CREATETIME" IS '建立時間';
COMMENT ON COLUMN "EC_FAVORITE_PRD"."MODIFIER" IS '最近修改人';
COMMENT ON COLUMN "EC_FAVORITE_PRD"."MODIFYTIME" IS '最近修改時間';

--訂單留言
CREATE TABLE "EC_ORDER_MESSAGE"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"ORDER_ID" NUMBER(18,0) NOT NULL ENABLE,
"MESSAGE" VARCHAR2(120 CHAR),
"CREATOR" NUMBER(18,0), 
"CREATETIME" DATE,
CONSTRAINT "EC_ORDER_MESSAGE_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_ORDER_MESSAGE_FK1" FOREIGN KEY ("ORDER_ID") REFERENCES "EC_ORDER" ("ID") ENABLE,
CONSTRAINT "EC_ORDER_MESSAGE_FK2" FOREIGN KEY ("CREATOR") REFERENCES "EC_MEMBER" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_ORDER_MESSAGE"."ID" IS 'PK';
COMMENT ON COLUMN "EC_ORDER_MESSAGE"."ORDER_ID" IS 'FK:EC_ORDER.ID';
COMMENT ON COLUMN "EC_ORDER_MESSAGE"."MESSAGE" IS '訊息';
COMMENT ON COLUMN "EC_ORDER_MESSAGE"."CREATOR" IS '建立人';
COMMENT ON COLUMN "EC_ORDER_MESSAGE"."CREATETIME" IS '建立時間';

--PUSH_LOG
CREATE TABLE "EC_PUSH_LOG"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"CATEGORY" VARCHAR2(20 BYTE),
"PUSH_TYPE" VARCHAR2(20 BYTE),
"TITLE" VARCHAR2(200 CHAR),
"ALERT" VARCHAR2(1000 CHAR),
"AUDIENCE" VARCHAR2(1000 BYTE),
"PUSH_RESULT" VARCHAR2(1000 BYTE),
"SUCCESS" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
"CREATETIME" DATE,
CONSTRAINT "EC_PUSH_LOG_PK" PRIMARY KEY ("ID") ENABLE
);
COMMENT ON COLUMN "EC_PUSH_LOG"."ID" IS 'PK';
COMMENT ON COLUMN "EC_PUSH_LOG"."PUSH_TYPE" IS 'TAG,ALIAS';



--訂單運送資訊
CREATE TABLE "EC_ORDER_SHIP_INFO"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"ORDER_ID" NUMBER(18,0) NOT NULL ENABLE,
"SHIPPING_ID" NUMBER(18,0) NOT NULL ENABLE,
"RECIPIENT" VARCHAR2(40 CHAR),
"ADDRESS" VARCHAR2(160 CHAR),
"PHONE" VARCHAR2(20 CHAR),
"CAR_NO" VARCHAR2(20 CHAR),
"DRIVER" VARCHAR2(40 CHAR),
"CREATOR" NUMBER(18,0), 
"CREATETIME" DATE,
"MODIFIER" NUMBER(18,0), 
"MODIFYTIME" DATE,
CONSTRAINT "EC_ORDER_SHIP_INFO_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_ORDER_SHIP_INFO_FK1" FOREIGN KEY ("ORDER_ID") REFERENCES "EC_ORDER" ("ID") ENABLE,
CONSTRAINT "EC_ORDER_SHIP_INFO_FK2" FOREIGN KEY ("SHIPPING_ID") REFERENCES "EC_SHIPPING" ("ID") ENABLE,
CONSTRAINT "EC_ORDER_SHIP_INFO_FK3" FOREIGN KEY ("CREATOR") REFERENCES "EC_MEMBER" ("ID") ENABLE,
CONSTRAINT "EC_ORDER_SHIP_INFO_FK4" FOREIGN KEY ("MODIFIER") REFERENCES "EC_MEMBER" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_ORDER_SHIP_INFO"."ID" IS 'PK';
COMMENT ON COLUMN "EC_ORDER_SHIP_INFO"."ORDER_ID" IS 'FK:EC_ORDER.ID';
COMMENT ON COLUMN "EC_ORDER_SHIP_INFO"."SHIPPING_ID" IS 'FK:EC_SHIPPING.ID';
COMMENT ON COLUMN "EC_ORDER_SHIP_INFO"."RECIPIENT" IS '收件人姓名';
COMMENT ON COLUMN "EC_ORDER_SHIP_INFO"."ADDRESS" IS '收件地址';
COMMENT ON COLUMN "EC_ORDER_SHIP_INFO"."PHONE" IS '收件人連絡電話';
COMMENT ON COLUMN "EC_ORDER_SHIP_INFO"."DRIVER" IS '司機';
COMMENT ON COLUMN "EC_ORDER_SHIP_INFO"."CAR_NO" IS '車號';
COMMENT ON COLUMN "EC_ORDER_SHIP_INFO"."CREATOR" IS '建立人';
COMMENT ON COLUMN "EC_ORDER_SHIP_INFO"."CREATETIME" IS '建立時間';
COMMENT ON COLUMN "EC_ORDER_SHIP_INFO"."MODIFIER" IS '最近修改人';
COMMENT ON COLUMN "EC_ORDER_SHIP_INFO"."MODIFYTIME" IS '最近修改時間';


--SMS_LOG
CREATE TABLE "EC_SMS_LOG"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"TYPE" VARCHAR2(20 BYTE),
"TITLE" VARCHAR2(200 CHAR),
"AUDIENCE" VARCHAR2(1000 BYTE),
"SUCCESS" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
"CREATETIME" DATE,
CONSTRAINT "EC_SMS_LOG_PK" PRIMARY KEY ("ID") ENABLE
);
COMMENT ON COLUMN "EC_SMS_LOG"."ID" IS 'PK';
COMMENT ON COLUMN "EC_SMS_LOG"."TYPE" IS 'TAG,ALIAS';


CREATE TABLE EC_SMS_LOG 
(
  ID NUMBER(18) NOT NULL 
, TYPE VARCHAR2(20) 
, TITLE VARCHAR2(100) 
, AUDIENCE VARCHAR2(20) 
, SUCCESS NUMBER(1) DEFAULT 1 NOT NULL 
, CREATETIME DATE 
);

COMMENT ON COLUMN EC_SMS_LOG.ID IS 'PK';

CREATE SEQUENCE  "EC_USER"."SEQ_SMS_LOG"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;