--應收帳款檔--sap
CREATE TABLE SK_ZBSEGAR(
  ACTNAME VARCHAR2(12 char), --科目
  KUNNR VARCHAR2(10 BYTE),--客戶代號
  SGTXT VARCHAR2(50 BYTE),--發票號碼
  ZUONR VARCHAR2(18 BYTE),--銷貨單號
  HZUON VARCHAR2(18 BYTE),--銷售群組
  BLDAT date,--發票日期
  FDWBT NUMBER,--金額
  VSBED VARCHAR2(10 BYTE),--發票聯式
  GJAHR VARCHAR2(4 char),
  MONAT VARCHAR2(2 char),
  UPDAT date,
  FDTAG date,--應收到期
  CREATETIMESTAMP		date default sysdate
)
/
COMMENT ON COLUMN "WAREHOUSE"."SK_ZBSEGAR"."ACTNAME"
IS
  '科目';
  COMMENT ON COLUMN "WAREHOUSE"."SK_ZBSEGAR"."KUNNR"
IS
  '客戶代號';
  COMMENT ON COLUMN "WAREHOUSE"."SK_ZBSEGAR"."SGTXT"
IS
  '發票號碼';
  COMMENT ON COLUMN "WAREHOUSE"."SK_ZBSEGAR"."ZUONR"
IS
  '銷貨單號';
  COMMENT ON COLUMN "WAREHOUSE"."SK_ZBSEGAR"."HZUON"
IS
  '銷售群組';
  COMMENT ON COLUMN "WAREHOUSE"."SK_ZBSEGAR"."BLDAT"
IS
  '發票日期';
  COMMENT ON COLUMN "WAREHOUSE"."SK_ZBSEGAR"."FDWBT"
IS
  '金額';
  COMMENT ON COLUMN "WAREHOUSE"."SK_ZBSEGAR"."VSBED"
IS
  '發票聯式';
  COMMENT ON COLUMN "WAREHOUSE"."SK_ZBSEGAR"."FDTAG"
IS
  '應收到期';
/
--customer--sap
create table SK_ZKNA1 (							
	KUNNR		varchar2	(	10	byte	), --客戶代號
	NAME1		varchar2	(	64	 char	), --客戶名稱
	SORTL		varchar2	(	10	byte	),
	STCEG		varchar2	(	16	byte	),
	POST_CODE1		varchar2	(	10	byte	),
	CITY1		varchar2	(	64	 char	),
	STREET		varchar2	(	64	 char	),
	STR_SUPPL3		varchar2	(	64	 char	),
	NAME4		varchar2	(	64	 char	),
	TELF1		varchar2	(	16	byte	),
	KONZS		varchar2	(	10	byte	),
	BAHNE		varchar2	(	32	 char	),
	KUKLA		varchar2	(	2	byte	),
	BZIRK		varchar2	(	8	byte	),
	VKGRP		varchar2	(	4	byte	), --銷售群組
	KDGRP		varchar2	(	2	byte	),
	WAERS		varchar2	(	8	byte	),
	KALKS		varchar2	(	1	 char	),
	LPRIO		varchar2	(	2	byte	),
	VSBED		varchar2	(	2	byte	),
	ZTERM		varchar2	(	4	byte	),
	BRAN1		varchar2	(	10	byte	),
	UPDAT		date,
	ERDAT		date,
	CREATETIMESTAMP		date default sysdate
)
/
--預收檔		
create table SK_ZBSEGPP(							
	ACTNAME			varchar2(	12	char	),
	UMSKZ			varchar2(	1	byte	),
	KUNNR			varchar2(	10	byte	),
	FDWBT					number	,
	PERNR			varchar2(	10	byte	),
	HZUON			varchar2(	18	byte	),
	GJAHR			varchar2(	4	char	),
	MONAT			varchar2(	2	char	),
	UPDAT			date,
	FDTAG			date,
	CREATETIMESTAMP		date default sysdate
)
/
--Sales Order from sap
create table SK_ZVBRK(
SKSALEID number
, FKART varchar2(	4	char	)
, VBELN varchar2(	10	char	)
, XBLNR varchar2(	16	char	)
, FKDAT date
, KUNRG varchar2(	10	char	)
, KUNAG varchar2(	10	char	)
, NETWR number
, VKORG varchar2(	4	char	)
, VTWEG varchar2(	2	char	)
, AUGDT date
, POSNR number
, UEPOS number
, VKGRP varchar2(	4	char	)
, MATNR varchar2(	18	char	)
, LGORT varchar2(	4	char	)
, CHARG varchar2(	10	char	)
, VRKME varchar2(	4	char	)
, FKIMG number
, KBETR number
, NETWR1 number
, PSTYV varchar2(	4	char	)
, NETWR2 number
, MWSBP number
, WAVWR number
, AUBEL varchar2(	16	char	)
, AUPOS number
, VGBEL2 varchar2(	10	char	)
, VGPOS number
, VBELN2 varchar2(	10	char	)
, POSNR2 number
, AUDAT date
, AUART varchar2(	4	char	)
, VGBEL varchar2(	10	char	)
, PERNR number
, ERDAT date
, LTEXT varchar2(	1024	char	)
, NETWR33 number
, MWSBP33 number
, NETWR3 number
, MWSBP3 number
, AUGRU varchar2(	16	char	)
, VGBEL3 varchar2(	16	char	)
, WKTPS varchar2(	16	char	)
, RETURN_RATE number
, CHECK_DATE varchar2(	8	char	)
, CHECK_ID varchar2(	50	char	)
, VSBED varchar2(	2	byte	) -- 出貨條件: 00: 外銷 01: 三聯式內含稅 02: 三聯式外加稅 03: 二聯式
, TAXTYPE varchar2(	1	byte	) -- 課稅別:1: 應稅2: 零稅率3: 免稅
,CREATETIMESTAMP		date default sysdate 
,INSERT_TIMESTAMP		date
,UPDATE_TIMESTAMP		date
)
/
--產品主檔
CREATE TABLE SK_ZMARA
(
  MATNR VARCHAR2(18 byte)
, ARKTX VARCHAR2(64 byte)
, MAKTX VARCHAR2(64 byte)
, MEINS VARCHAR2(8 byte)
, WRKST1 VARCHAR2(64 byte)
, ZEIFO VARCHAR2(4 byte)
, WRKST2 VARCHAR2(64 byte)
, MATKL VARCHAR2(10 byte)
, SPART VARCHAR2(2 byte)
, ZEINR VARCHAR2(32 byte)
, BISMT VARCHAR2(32 byte)
, MEINH VARCHAR2(8 byte)
, UMREN NUMBER(12,2)
, LAEDA date
, ERSDA date
,CREATETIMESTAMP		date default sysdate 
)
--產品分類
create table sk_zmara_category (
CATEGORY VARCHAR2(10),
DESCRIPTION VARCHAR2(30),
REMARK  VARCHAR2(15)
);

COMMENT ON COLUMN SK_ZMARA_CATEGORY.CATEGORY IS '群組編號';
COMMENT ON COLUMN SK_ZMARA_CATEGORY.DESCRIPTION IS '群組名稱';
COMMENT ON COLUMN SK_ZMARA_CATEGORY.REMARK IS '特殊說明';


/
//解繳率
CREATE TABLE SK_ZBSEGCOLL(
  GJAHR VARCHAR2(4 byte)
, BELNR VARCHAR2(10 byte)
, KUNNR VARCHAR2(10 byte)
, ZUONR VARCHAR2(18 byte)
, SGTXT VARCHAR2(60 byte)
, HZUON VARCHAR2(18 byte)
, BUDAT VARCHAR2(10 byte)
, BLART VARCHAR2(2 byte)
, FDWBT NUMBER(13,2)
, AMT_A NUMBER(13,2)
, AMT_B NUMBER(13,2)
, AMT_C NUMBER(13,2)
, AMT_D NUMBER(13,2)
, AMT_E NUMBER(13,2)
, ZGJAHR VARCHAR2(4 byte)
, ZMONAT VARCHAR2(2 byte)
, UPDAT DATE
)
/

--銷售文件批次簽核
CREATE TABLE "SD_ZTAB_EXP_BERSL"
(
    "BNAME"    VARCHAR2(24 BYTE) NOT NULL ENABLE,
    "BERSL"    VARCHAR2(16 BYTE) NOT NULL ENABLE,
    "DISABLED" NUMBER(1,0),
    PRIMARY KEY ("BNAME", "BERSL") 
);

COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_BERSL"."BNAME"
IS
  '使用者名稱';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_BERSL"."BERSL"
IS
  '權限碼';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_BERSL"."DISABLED"
IS
  '是否失效';

CREATE TABLE "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"
(
    "ID"    NUMBER(18,0),
    "MANDT" VARCHAR2(20 BYTE),
    "BERSL" VARCHAR2(24 BYTE),
    "BNAME" VARCHAR2(20 BYTE),
    "VKORG" VARCHAR2(8 BYTE),
    "VTWEG" VARCHAR2(4 BYTE),
    "SPART" VARCHAR2(4 BYTE),
    "VKGRP" VARCHAR2(6 BYTE),
    "VBELN" VARCHAR2(20 BYTE),
    "AUART" VARCHAR2(8 BYTE),
    "AUDAT" DATE,
    "POSNR"      NUMBER(12,0),
    "MATNR"      VARCHAR2(36 BYTE),
    "ARKTX"      VARCHAR2(80 BYTE),
    "KWMENG"     NUMBER(25,9),
    "VRKME"      VARCHAR2(6 BYTE),
    "UNIT_PRICE" NUMBER(14,2),
    "NETWR"      NUMBER(25,9),
    "WAERK"      VARCHAR2(10 BYTE),
    "DISCOUNT"   NUMBER(25,9),
    "FREE"       NUMBER(25,9),
    "KUNNR"      VARCHAR2(20 BYTE),
    "NAME1"      VARCHAR2(140 BYTE),
    "DBRTG"      VARCHAR2(10 BYTE),
    "NAME"       VARCHAR2(60 BYTE),
    "ASP"        NUMBER(14,2),
    "ASP_S"      NUMBER(14,2),
    "VPRS"       NUMBER(14,2),
    "ITMPF"      NUMBER(14,2),
    "ITMDN"      NUMBER(14,2),
    "QTYDF"      NUMBER(25,9),
    "PRMNG"      NUMBER(25,9),
    "PRASP"      NUMBER(14,2),
    "PRASP_S"    NUMBER(14,2),
    "BSTZD"      VARCHAR2(8 BYTE),
    "BSTZD_T"    VARCHAR2(40 BYTE),
    "OBJNR"      VARCHAR2(44 BYTE),
    "STSMA"      VARCHAR2(16 BYTE),
    "CSTAT"      VARCHAR2(10 BYTE),
    "NSTAT"      VARCHAR2(10 BYTE),
    "REL_TEXT"   VARCHAR2(180 BYTE),
	"ALTKN"		 VARCHAR2(30),
	"PSTLZ"		 VARCHAR2(30),
	"ORT01"		 VARCHAR2(105),
    "CREATE_TIME_STAMP" DATE,
    "DELETED" NUMBER(1,0),
    PRIMARY KEY ("ID") 
);

COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."ID"
IS
  'PK ';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."MANDT"
IS
  '用戶端 ';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."BERSL"
IS
  '權限碼';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."BNAME"
IS
  '使用者主檔記錄中的使用者名稱';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."VKORG"
IS
  '銷售組織';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."VTWEG"
IS
  '配銷通路';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."SPART"
IS
  '部門';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."VKGRP"
IS
  '銷售群組';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."VBELN"
IS
  '銷售文件號碼';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."AUART"
IS
  '銷售文件類型';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."AUDAT"
IS
  '文件日期';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."POSNR"
IS
  '銷售文件項目';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."MATNR"
IS
  '物料';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."ARKTX"
IS
  '物料說明';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."KWMENG"
IS
  '數量';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."VRKME"
IS
  '銷售單位';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."UNIT_PRICE"
IS
  '單價';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."NETWR"
IS
  '金額';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."WAERK"
IS
  '幣別';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."DISCOUNT"
IS
  '溢價金額';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."FREE"
IS
  '贈品數量';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."KUNNR"
IS
  '客戶代碼';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."NAME1"
IS
  '客戶名稱';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."DBRTG"
IS
  '風險評比';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."NAME"
IS
  '業務員';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."ASP"
IS
  '平均單價(銷售單位)';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."ASP_S"
IS
  '平均單價(最小單位)';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."VPRS"
IS
  '項目成本';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."ITMPF"
IS
  '項目毛利率';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."ITMDN"
IS
  '單價調幅';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."QTYDF"
IS
  '數量差異';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."PRMNG"
IS
  '前次出貨數量';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."PRASP"
IS
  '前次平均單價(銷售單位)';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."PRASP_S"
IS
  '前次平均單價(最小單位)';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."BSTZD"
IS
  '簽核層級';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."BSTZD_T"
IS
  '簽核層級說明';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."OBJNR"
IS
  '狀態物件號碼';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."STSMA"
IS
  '狀態設定檔';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."CSTAT"
IS
  '目前狀態';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."NSTAT"
IS
  '後續狀態';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."REL_TEXT"
IS
  '簽核備註';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."ALTKN"
IS
  '異常客戶註記';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."PSTLZ"
IS
  '郵遞區號';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."ORT01"
IS
  '城市';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."CREATE_TIME_STAMP"
IS
  '建立時間';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_RELFILENO_SD"."DELETED"
IS
  '是否已註銷(待刪除)';  
  
CREATE TABLE "WAREHOUSE"."SD_ZTAB_EXP_TJ10T"
(
    "MANDT" VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "BERSL" VARCHAR2(24 BYTE) NOT NULL ENABLE,
    "SPRAS" VARCHAR2(3 BYTE),
    "TXT"   VARCHAR2(60 BYTE),
    PRIMARY KEY ("MANDT", "BERSL", "SPRAS")
);

COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_TJ10T"."MANDT"
IS
  '用戶端';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_TJ10T"."BERSL"
IS
  '權限碼';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_TJ10T"."SPRAS"
IS
  '語言代碼';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_TJ10T"."TXT"
IS
  '權限碼的內文';
  
CREATE TABLE "WAREHOUSE"."SD_ZTAB_EXP_TVKOT"
(
    "MANDT" VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "SPRAS" VARCHAR2(24 BYTE) NOT NULL ENABLE,
    "VKORG" VARCHAR2(8 BYTE),
    "VTEXT" VARCHAR2(40 BYTE),
    PRIMARY KEY ("MANDT", "SPRAS", "VKORG")
);

COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_TVKOT"."MANDT"
IS
  '用戶端';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_TVKOT"."SPRAS"
IS
  '語言代碼';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_TVKOT"."VKORG"
IS
  '銷售組織';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_TVKOT"."VTEXT"
IS
  '銷售組織名稱';
  
CREATE TABLE "WAREHOUSE"."SD_ZTAB_EXP_TVTWT"
(
    "MANDT" VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "SPRAS" VARCHAR2(24 BYTE) NOT NULL ENABLE,
    "VTWEG" VARCHAR2(4 BYTE),
    "VTEXT" VARCHAR2(40 BYTE),
    PRIMARY KEY ("MANDT", "SPRAS", "VTWEG")
);

COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_TVTWT"."MANDT"
IS
  '用戶端';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_TVTWT"."SPRAS"
IS
  '語言代碼';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_TVTWT"."VTWEG"
IS
  '配銷通路';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_TVTWT"."VTEXT"
IS
  '配銷通路名稱';  
  
CREATE TABLE "WAREHOUSE"."SD_ZTAB_EXP_VBAK"
(
    "MANDT" VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "VBELN" VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "ERDAT" DATE,
    "ERZET" DATE,
    "ERNAM" VARCHAR2(24 BYTE),
    "AUDAT" DATE,
    "VBTYP" VARCHAR2(2 BYTE),
    "AUART" VARCHAR2(8 BYTE),
    "AUGRU" VARCHAR2(6 BYTE),
    "NETWR" NUMBER(25,9),
    "WAERK" VARCHAR2(10 BYTE),
    "VKORG" VARCHAR2(8 BYTE),
    "VTWEG" VARCHAR2(4 BYTE),
    "SPART" VARCHAR2(4 BYTE),
    "VKBUR" VARCHAR2(8 BYTE),
    "VKGRP" VARCHAR2(6 BYTE),
    "VDATU" DATE,
    "KUNNR" VARCHAR2(20 BYTE),
    "AEDAT" DATE,
    "VGBEL"                       VARCHAR2(20 BYTE),
    "OBJNR"                       VARCHAR2(44 BYTE),
    "XBLNR"                       VARCHAR2(32 BYTE),
    "ZUONR"                       VARCHAR2(36 BYTE),
    "VGTYP"                       VARCHAR2(2 BYTE),
    "SD_ZTAB_EXP_RELFILENO_SD_ID" NUMBER(18,0),
    PRIMARY KEY ("MANDT", "VBELN")
);

COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAK"."MANDT"
IS
  '用戶端';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAK"."VBELN"
IS
  '銷售文件號碼';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAK"."ERDAT"
IS
  '建立日期';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAK"."ERZET"
IS
  '輸入時間';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAK"."ERNAM"
IS
  '建立物件者的姓名';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAK"."AUDAT"
IS
  '文件日期';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAK"."VBTYP"
IS
  'SD 文件種類';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAK"."AUART"
IS
  '銷售文件類型';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAK"."AUGRU"
IS
  '訂貨原因';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAK"."NETWR"
IS
  '銷售訂單淨值';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAK"."WAERK"
IS
  '文件幣別';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAK"."VKORG"
IS
  '銷售組織';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAK"."VTWEG"
IS
  '配銷通路';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAK"."SPART"
IS
  '部門';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAK"."VKBUR"
IS
  '銷售據點';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAK"."VKGRP"
IS
  '銷售群組';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAK"."VDATU"
IS
  '請求交貨日期';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAK"."KUNNR"
IS
  '買方';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAK"."AEDAT"
IS
  '更改日期';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAK"."VGBEL"
IS
  '參考文件的文件編號';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAK"."OBJNR"
IS
  '表頭層次的物件號碼';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAK"."XBLNR"
IS
  '參考文件號碼';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAK"."ZUONR"
IS
  '指派號碼';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAK"."VGTYP"
IS
  '先前 SD 文件的文件種類';

CREATE TABLE "WAREHOUSE"."SD_ZTAB_EXP_VBAP"
(
    "MANDT"  VARCHAR2(20 BYTE),
    "VBELN"  VARCHAR2(20 BYTE),
    "POSNR"  NUMBER(12,0),
    "MATNR"  VARCHAR2(36 BYTE),
    "MATKL"  VARCHAR2(18 BYTE),
    "ARKTX"  VARCHAR2(80 BYTE),
    "PSTYV"  VARCHAR2(8 BYTE),
    "UEPOS"  NUMBER(12,0),
    "NETWR"  NUMBER(25,9),
    "WAERK"  VARCHAR2(10 BYTE),
    "KWMENG" NUMBER(25,9),
    "VRKME"  NUMBER(10,0),
    "VGBEL"  VARCHAR2(20 BYTE),
    "VGPOS"  NUMBER(12,0),
    "WERKS"  VARCHAR2(8 BYTE),
    "LGORT"  VARCHAR2(8 BYTE),
    "VSTEL"  VARCHAR2(8 BYTE),
    "ERDAT" DATE,
    "ERNAM" VARCHAR2(24 BYTE),
    "ERZET" DATE,
    "NETPR" NUMBER(25,9),
    "KPEIN" VARCHAR2(10 BYTE),
    "KMEIN" NUMBER(10,0),
    "AEDAT" DATE,
    "MWSBP"                       NUMBER(25,9),
    "SD_ZTAB_EXP_RELFILENO_SD_ID" NUMBER(18,0),
    PRIMARY KEY ("MANDT", "VBELN")
);

COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAP"."MANDT"
IS
  '用戶端 ';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAP"."VBELN"
IS
  '銷售文件號碼';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAP"."POSNR"
IS
  '銷售文件項目';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAP"."MATNR"
IS
  '物料';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAP"."MATKL"
IS
  '物料群組';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAP"."ARKTX"
IS
  '銷售訂單項目短文';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAP"."PSTYV"
IS
  '銷售文件項目種類';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAP"."UEPOS"
IS
  '物料表結構中的上層項目';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAP"."NETWR"
IS
  '訂單項目淨值';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAP"."WAERK"
IS
  '幣別';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAP"."KWMENG"
IS
  '累計訂購數量';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAP"."VRKME"
IS
  '銷售單位';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAP"."VGBEL"
IS
  '參考文件的文件編號';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAP"."VGPOS"
IS
  '參考項目的項目編號';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAP"."WERKS"
IS
  '工廠';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAP"."LGORT"
IS
  '儲存地點';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAP"."VSTEL"
IS
  '出貨點/收貨點';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAP"."ERDAT"
IS
  '記錄建立的日期';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAP"."ERNAM"
IS
  '建立物件者的姓名';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAP"."ERZET"
IS
  '輸入時間';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAP"."NETPR"
IS
  '淨價';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAP"."KPEIN"
IS
  '條件定價單位';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAP"."KMEIN"
IS
  '條件單位';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAP"."AEDAT"
IS
  '更改日期';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBAP"."MWSBP"
IS
  '稅額';

CREATE TABLE "WAREHOUSE"."SD_ZTAB_EXP_VBKD"
(
    "MANDT" VARCHAR2(20 BYTE),
    "VBELN" VARCHAR2(20 BYTE),
    "POSNR" NUMBER(12,0),
    "INCO1" VARCHAR2(6 BYTE),
    "INCO2" VARCHAR2(56 BYTE),
    "ZTERM" VARCHAR2(8 BYTE),
    "KURSK" NUMBER(18,10),
    "PRSDT" DATE,
    "BSTKD"                       VARCHAR2(70 BYTE),
    "SD_ZTAB_EXP_RELFILENO_SD_ID" NUMBER(18,0),
    PRIMARY KEY ("MANDT", "VBELN")
);

COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBKD"."MANDT"
IS
  '用戶端 ';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBKD"."VBELN"
IS
  '銷售文件號碼';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBKD"."POSNR"
IS
  '銷售文件項目';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBKD"."INCO1"
IS
  '國貿條件﹝第一部份﹞';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBKD"."INCO2"
IS
  '國貿條件〈第 2 部份〉';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBKD"."ZTERM"
IS
  '付款條件碼';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBKD"."KURSK"
IS
  '價格決定的匯率';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBKD"."PRSDT"
IS
  '定價及匯率日期';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBKD"."BSTKD"
IS
  '客戶採購單號碼';

CREATE TABLE "WAREHOUSE"."SD_ZTAB_EXP_VBPA"
(
    "MANDT"                       VARCHAR2(20 BYTE),
    "VBELN"                       VARCHAR2(20 BYTE),
    "POSNR"                       NUMBER(12,0),
    "PARVW"                       VARCHAR2(4 BYTE),
    "KUNNR"                       VARCHAR2(20 BYTE),
    "LIFNR"                       VARCHAR2(20 BYTE),
    "PERNR"                       NUMBER(16,0),
    "SD_ZTAB_EXP_RELFILENO_SD_ID" NUMBER(18,0),
    PRIMARY KEY ("MANDT", "VBELN")
);

COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBPA"."MANDT"
IS
  '用戶端 ';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBPA"."VBELN"
IS
  '銷售文件號碼';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBPA"."POSNR"
IS
  '銷售文件項目';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBPA"."PARVW"
IS
  '夥伴功能';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBPA"."KUNNR"
IS
  '客戶編號 1';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBPA"."LIFNR"
IS
  '供應商或貸方的帳號';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBPA"."PERNR"
IS
  '員工號碼';

CREATE TABLE "WAREHOUSE"."SD_ZTAB_EXP_VBUK"
(
    "MANDT"                       VARCHAR2(20 BYTE),
    "VBELN"                       VARCHAR2(20 BYTE),
    "LFSTK"                       VARCHAR2(2 BYTE),
    "ABSTK"                       VARCHAR2(2 BYTE),
    "GBSTK"                       VARCHAR2(2 BYTE),
    "CMGST"                       VARCHAR2(2 BYTE),
    "SD_ZTAB_EXP_RELFILENO_SD_ID" NUMBER(18,0),
    PRIMARY KEY ("MANDT", "VBELN")
);

COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBUK"."MANDT"
IS
  '用戶端 ';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBUK"."VBELN"
IS
  '銷售文件號碼';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBUK"."LFSTK"
IS
  '交貨狀態';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBUK"."ABSTK"
IS
  '所有文件項目的總拒收狀態';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBUK"."GBSTK"
IS
  '文件的整體處理狀態';
  COMMENT ON COLUMN "WAREHOUSE"."SD_ZTAB_EXP_VBUK"."CMGST"
IS
  '信用核查的整體狀態';
  
CREATE TABLE TC_ZTAB_EXP_TVV1T
(
"MANDT" VARCHAR2(20),
"SPRAS" VARCHAR2(20),
"KVGR1" VARCHAR2(20),
"BEZEI" VARCHAR2(255),
"SYNC_TIME_STAMP" DATE,
CONSTRAINT TC_ZTAB_EXP_TVV1T_PK PRIMARY KEY ("MANDT","SPRAS","KVGR1")
);

COMMENT ON COLUMN TC_ZTAB_EXP_TVV1T.MANDT IS '用戶端';
COMMENT ON COLUMN TC_ZTAB_EXP_TVV1T.SPRAS IS '語言代碼';
COMMENT ON COLUMN TC_ZTAB_EXP_TVV1T.KVGR1 IS '客戶群組一';
COMMENT ON COLUMN TC_ZTAB_EXP_TVV1T.BEZEI IS '說明';
COMMENT ON COLUMN TC_ZTAB_EXP_TVV1T.SYNC_TIME_STAMP IS '最新更新時間';

