/*
	適用 2015/12/11 以前的 tcc-fc-model.jar, 之後的已直接加入 install_fc.sql 中.
*/

CREATE INDEX TC_FOLDERED_ACLENTRY_IDX1 ON TC_FOLDERED_ACLENTRY (ACLTARGETCLASSNAME,ACLTARGETID);

CREATE INDEX tc_FOLDERED_ACLENTRY_IDX2 ON TC_FOLDERED_ACLENTRY (ACLPRINCIPALCLASSNAME,ACLPRINCIPALID);