CREATE TABLE "TC_DOWNLOAD_LOG" 
(
"ID" INT NOT NULL IDENTITY, 
"TC_APPLICATIONDATA_ID" INT,
"TOTAL_COUNT" NUMERIC(6) default 0, 
"CREATOR" INT ,
"CREATETIMESTAMP" DATE,
"MODIFIER" INT,
"MODIFYTIMESTAMP" DATE,
CONSTRAINT "TC_DOWNLOAD_LOG_PK" PRIMARY KEY ("ID"),
CONSTRAINT "TC_DOWNLOAD_LOG_FK1" FOREIGN KEY ("CREATOR") REFERENCES "TC_USER"("ID"),
CONSTRAINT "TC_DOWNLOAD_LOG_FK2" FOREIGN KEY ("MODIFIER") REFERENCES "TC_USER"("ID")
);

CREATE TABLE "TC_DOWNLOAD_LOG_DETAIL" 
(
"ID" INT IDENTITY,
"TC_DOWNLOAD_LOG_ID" INT,
"CREATOR" INT,
"CREATETIMESTAMP" DATE,
CONSTRAINT "TC_DOWNLOAD_LOG_DETAIL_PK" PRIMARY KEY ("ID"),
CONSTRAINT "TC_DOWNLOAD_LOG_DETAIL_FK1" FOREIGN KEY ("TC_DOWNLOAD_LOG_ID") REFERENCES "TC_DOWNLOAD_LOG"("ID"),
CONSTRAINT "TC_DOWNLOAD_LOG_DETAIL_FK2" FOREIGN KEY ("CREATOR") REFERENCES "TC_USER"("ID")
);
