--
-- Table structure for table folder
--
CREATE TABLE TC_FOLDER (
  ID INT NOT NULL IDENTITY,
  NAME NVARCHAR(255) NOT NULL ,
  FOLDER INT  DEFAULT NULL,
  CREATETIMESTAMP DATETIME DEFAULT NULL,
  MODIFYTIMESTAMP DATETIME DEFAULT NULL,
  ICON NVARCHAR(300) DEFAULT NULL,
  ISREMOVED BIT DEFAULT 0, 
  MODIFIER INT  DEFAULT NULL,
  CREATOR INT  DEFAULT NULL,
  CONSTRAINT TC_FOLDER_PK PRIMARY KEY  (ID),
  CONSTRAINT TC_FOLDER_FK01 FOREIGN KEY (FOLDER) REFERENCES TC_FOLDER (ID),
  CONSTRAINT TC_FOLDER_FK03 FOREIGN KEY (MODIFIER) REFERENCES TC_USER (ID),
  CONSTRAINT TC_FOLDER_FK04 FOREIGN KEY (CREATOR) REFERENCES TC_USER (ID)
) ;


--
-- Table structure for table document master
--
CREATE TABLE TC_DOCUMENT_MASTER (
  ID INT NOT NULL IDENTITY,
  DOCNUMBER NVARCHAR(255) NOT NULL,
  NAME NVARCHAR(255) NOT NULL,
  CONSTRAINT TC_DOCUMENT_MASTER_PK PRIMARY KEY (ID)
) ;


--
-- Table structure for table document
--
CREATE TABLE  TC_DOCUMENT (
  ID INT NOT NULL IDENTITY,
  MASTER INT NOT NULL,
  VERSIONNUMBER NVARCHAR(255) NOT NULL ,
  ITERATIONNUMBER NVARCHAR(255) NOT NULL ,
  ISLATESTITERATION BIT DEFAULT 1,  
  ISLATESTVERSION BIT DEFAULT 1,  
  DOCTYPE NVARCHAR(255) DEFAULT NULL,
  DESCRIPTION NVARCHAR(4000) DEFAULT NULL,
  NAME NVARCHAR(255) DEFAULT NULL,
  FOLDER INT  NOT NULL ,
  ISREMOVED BIT DEFAULT 0, 
  CREATOR INT  DEFAULT NULL,
  MODIFIER INT  DEFAULT NULL,
  CREATETIMESTAMP DATETIME DEFAULT NULL,
  MODIFYTIMESTAMP DATETIME DEFAULT NULL,
  PRIMARY KEY  (ID),
  CONSTRAINT TC_DOCUMENT_FK01 FOREIGN KEY (FOLDER) REFERENCES TC_FOLDER (ID) ON DELETE CASCADE,
  CONSTRAINT TC_DOCUMENT_FK02 FOREIGN KEY (CREATOR) REFERENCES TC_USER (ID),
  CONSTRAINT TC_DOCUMENT_FK03 FOREIGN KEY (MODIFIER) REFERENCES TC_USER (ID),
  CONSTRAINT TC_DOCUMENT_FK04 FOREIGN KEY (MASTER) REFERENCES TC_DOCUMENT_MASTER (ID)
) ;


--
-- Table structure for table foldered aclentry
--
CREATE TABLE  TC_FOLDERED_ACLENTRY (
  ID INT NOT NULL,
  ACLTARGETCLASSNAME NVARCHAR(255) NOT NULL ,
  ACLTARGETID INT NOT NULL ,
  PERMISSIONMASK NVARCHAR(45) NOT NULL ,
  INHERITANCEMASK NVARCHAR(45) NOT NULL ,
  ACLPRINCIPALCLASSNAME NVARCHAR(255) NOT NULL ,
  ACLPRINCIPALID INT NOT NULL ,
  CREATOR INT DEFAULT NULL,
  CREATETIMESTAMP DATETIME DEFAULT NULL,
  MODIFIER INT DEFAULT NULL,
  MODIFYTIMESTAMP DATETIME DEFAULT NULL,
  CONSTRAINT TC_FOLDERED_ACLENTRY_PK PRIMARY KEY  (ID),
  CONSTRAINT TC_FOLDERED_ACLENTRY_FK01 FOREIGN KEY (CREATOR) REFERENCES TC_USER (ID),
  CONSTRAINT TC_FOLDERED_ACLENTRY_FK02 FOREIGN KEY (MODIFIER) REFERENCES TC_USER (ID)
) ;

INSERT INTO TC_FOLDER VALUES ('ROOT',NULL,getdate(),getdate(),'',0,1,1);