DROP TABLE EC_ORDER;
DROP TABLE EC_REWARD_RECORD;
DROP TABLE EC_BONUS_RECORD;
DROP TABLE EC_PARTNER_COMMENT;
DROP TABLE EC_FORM_QA;
DROP TABLE EC_FORM_BECUSTOMER;

DROP TABLE EC_MEMBER_CUSTOMER;
DROP TABLE EC_PLANT_PRODUCT;
DROP TABLE EC_PLANT_SALESAREA;
DROP TABLE EC_CONTRACT_PRODUCT;
DROP TABLE EC_CUSTOMER_SALES;
DROP TABLE EC_SALESAREA_DELIVERY;
DROP TABLE EC_SALESAREA_LOCATION;
DROP TABLE EC_BANNER_PRODUCT;
DROP TABLE EC_PARTNER_PRODUCT;

DROP TABLE EC_CONTRACT;
DROP TABLE EC_PARTNER;
DROP TABLE EC_BANNER;
DROP TABLE EC_MEMBER;
DROP TABLE EC_CUSTOMER;
DROP TABLE EC_PRODUCT;
DROP TABLE EC_PLANT;
DROP TABLE EC_SALES;
DROP TABLE EC_SALESAREA;
DROP TABLE EC_DELIVERY;
