-- 首頁廣告, 廣告及證言, 促銷訊息, 紅利兌換活動, 金幣兌換活動
CREATE TABLE "EC_BANNER"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"CATEGORY" NUMBER(2,0) NOT NULL ENABLE,
"SUBJECT" VARCHAR2(255 CHAR),
"CONTENT_URL" VARCHAR2(255 BYTE) NOT NULL ENABLE,
"LINK" VARCHAR2(255 BYTE),
"ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
CONSTRAINT "EC_BANNER_PK" PRIMARY KEY ("ID") ENABLE
);
COMMENT ON COLUMN "EC_BANNER"."ID" IS 'PK';
COMMENT ON COLUMN "EC_BANNER"."CATEGORY" IS '分類,1:首頁廣告, 2:商品廣告證言, 3:促銷訊息, 4:紅利兌換活動, 5:金幣兌換活動';
COMMENT ON COLUMN "EC_BANNER"."SUBJECT" IS '主旨';
COMMENT ON COLUMN "EC_BANNER"."CONTENT_URL" IS '圖檔網址';
COMMENT ON COLUMN "EC_BANNER"."LINK" IS 'click link';
COMMENT ON COLUMN "EC_BANNER"."ACTIVE" IS '1:啟用, 0:停用';

-- 會員
CREATE TABLE "EC_MEMBER"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"LOGIN_ACCOUNT" VARCHAR2(50 BYTE) NOT NULL ENABLE,
"NAME" VARCHAR2(64 CHAR) NOT NULL ENABLE,
"EMAIL" VARCHAR2(64 BYTE) NOT NULL ENABLE,
"PHONE" VARCHAR2(50 BYTE),
"ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
CONSTRAINT "EC_MEMBER_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_MEMBER_UK1" UNIQUE ("LOGIN_ACCOUNT") ENABLE
);
COMMENT ON COLUMN "EC_MEMBER"."ID" IS 'PK';
COMMENT ON COLUMN "EC_MEMBER"."LOGIN_ACCOUNT" IS '登入帳號';
COMMENT ON COLUMN "EC_MEMBER"."NAME" IS '姓名';
COMMENT ON COLUMN "EC_MEMBER"."EMAIL" IS '電子信箱';
COMMENT ON COLUMN "EC_MEMBER"."PHONE" IS '電話';
COMMENT ON COLUMN "EC_MEMBER"."ACTIVE" IS '1:啟用, 0:停用';

-- 客戶
CREATE TABLE "EC_CUSTOMER"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE,
"NAME" VARCHAR2(64 CHAR) NOT NULL ENABLE,
"ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
CONSTRAINT "EC_CUSTOMER_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_CUSTOMER_UK1" UNIQUE ("CODE") ENABLE
);
COMMENT ON COLUMN "EC_CUSTOMER"."ID" IS 'PK';
COMMENT ON COLUMN "EC_CUSTOMER"."CODE" IS 'SAP代碼';
COMMENT ON COLUMN "EC_CUSTOMER"."NAME" IS '客戶名稱';
COMMENT ON COLUMN "EC_CUSTOMER"."ACTIVE" IS '1:啟用, 0:停用';

-- 商品
CREATE TABLE "EC_PRODUCT"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"CODE" VARCHAR2(18 CHAR) NOT NULL ENABLE,
"NAME" VARCHAR2(80 CHAR) NOT NULL ENABLE,
"DESCRIPTION" VARCHAR2(500 CHAR),
"ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
CONSTRAINT "EC_PRODUCT_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_PRODUCT_UK1" UNIQUE ("CODE") ENABLE
);
COMMENT ON COLUMN "EC_PRODUCT"."ID" IS 'PK';
COMMENT ON COLUMN "EC_PRODUCT"."CODE" IS 'SAP料號';
COMMENT ON COLUMN "EC_PRODUCT"."NAME" IS '商品名稱';
COMMENT ON COLUMN "EC_PRODUCT"."DESCRIPTION" IS '商品介紹';
COMMENT ON COLUMN "EC_PRODUCT"."ACTIVE" IS '1:啟用, 0:停用';

-- 出貨廠
CREATE TABLE "EC_PLANT"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE,
"NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE,
"ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
CONSTRAINT "EC_PLANT_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_PLANT_UK1" UNIQUE ("CODE") ENABLE
);
COMMENT ON COLUMN "EC_PLANT"."ID" IS 'PK';
COMMENT ON COLUMN "EC_PLANT"."CODE" IS 'SAP代碼';
COMMENT ON COLUMN "EC_PLANT"."NAME" IS '廠名稱';
COMMENT ON COLUMN "EC_PLANT"."ACTIVE" IS '1:啟用, 0:停用';

-- 業務員
CREATE TABLE "EC_SALES"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"NAME" VARCHAR2(40 CHAR) NOT NULL ENABLE,
"CODE" VARCHAR2(40 BYTE) NOT NULL ENABLE,
"ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
CONSTRAINT "EC_SALES_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_SALES_UK1" UNIQUE ("CODE") ENABLE
)
;
COMMENT ON COLUMN "EC_SALES"."ID" IS 'PK';
COMMENT ON COLUMN "EC_SALES"."NAME" IS '姓名';
COMMENT ON COLUMN "EC_SALES"."CODE" IS '員工編號';
COMMENT ON COLUMN "EC_SALES"."ACTIVE" IS '1:啟用, 0:停用';

-- 銷售區
CREATE TABLE "EC_SALESAREA"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"CODE" VARCHAR2(10 BYTE) NOT NULL ENABLE,
"NAME" VARCHAR2(140 CHAR),
"ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
CONSTRAINT "EC_SALESAREA_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_SALESAREA_UK1" UNIQUE ("CODE") ENABLE
);
COMMENT ON COLUMN "EC_SALESAREA"."ID" IS 'PK';
COMMENT ON COLUMN "EC_SALESAREA"."CODE" IS '代碼';
COMMENT ON COLUMN "EC_SALESAREA"."NAME" IS '名稱';
COMMENT ON COLUMN "EC_SALESAREA"."ACTIVE" IS '1:啟用, 0:停用';

-- 送達地點
CREATE TABLE "EC_DELIVERY"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE,
"NAME" VARCHAR2(140 CHAR) NOT NULL ENABLE,
"ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
CONSTRAINT "EC_DELIVERY_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_DELIVERY_UK1" UNIQUE ("CODE") ENABLE
);
COMMENT ON COLUMN "EC_DELIVERY"."ID" IS 'PK';
COMMENT ON COLUMN "EC_DELIVERY"."CODE" IS '代碼';
COMMENT ON COLUMN "EC_DELIVERY"."NAME" IS '名稱';
COMMENT ON COLUMN "EC_DELIVERY"."ACTIVE" IS '1:啟用, 0:停用';

-- 合約
CREATE TABLE "EC_CONTRACT"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"CODE" VARCHAR2(50 CHAR) NOT NULL ENABLE,
"NAME" VARCHAR2(100 CHAR) NOT NULL ENABLE,
"PLANT_ID" NUMBER(18,0) NOT NULL ENABLE,
"CUSTOMER_ID" NUMBER(18,0) NOT NULL ENABLE,
"ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
CONSTRAINT "EC_CONTRACT_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_CONTRACT_UK1" UNIQUE ("CODE") ENABLE,
CONSTRAINT "EC_CONTRACT_FK1" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "EC_CUSTOMER" ("ID") ENABLE,
CONSTRAINT "EC_CONTRACT_FK2" FOREIGN KEY ("PLANT_ID") REFERENCES "EC_PLANT" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_CONTRACT"."ID" IS 'PK';
COMMENT ON COLUMN "EC_CONTRACT"."CODE" IS '合約號碼';
COMMENT ON COLUMN "EC_CONTRACT"."NAME" IS '合約名稱';
COMMENT ON COLUMN "EC_CONTRACT"."PLANT_ID" IS 'FK:EC_PLANT.ID';
COMMENT ON COLUMN "EC_CONTRACT"."CUSTOMER_ID" IS 'FK:EC_CUSTOMER.ID';
COMMENT ON COLUMN "EC_CONTRACT"."ACTIVE" IS '1:啟用, 0:停用';

-- 台泥伙伴
CREATE TABLE "EC_PARTNER"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"NAME" VARCHAR2(100 CHAR) NOT NULL ENABLE,
"OWNER" NUMBER(18,0) NOT NULL ENABLE,
"DESCRIPTION" VARCHAR2(500 CHAR),
"PHONE" VARCHAR2(50 BYTE),
"SOCIAL" VARCHAR2(64 BYTE),
"LATITUDE" NUMBER(10,6),
"LONGITUDE" NUMBER(10,6),
"THEME" VARCHAR2(20 BYTE),
"STATUS" NUMBER(1,0) NOT NULL ENABLE,
"CREATETIME" DATE NOT NULL ENABLE,
"ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
CONSTRAINT "EC_PARTNER_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_PARTNER_UK1" UNIQUE ("NAME") ENABLE,
CONSTRAINT "EC_PARTNER_EC_MEMBER_FK1" FOREIGN KEY ("OWNER") REFERENCES "EC_MEMBER" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_PARTNER"."ID" IS 'PK';
COMMENT ON COLUMN "EC_PARTNER"."NAME" IS '伙伴名稱';
COMMENT ON COLUMN "EC_PARTNER"."OWNER" IS '建立人, FK:EC_MEMBER.ID';
COMMENT ON COLUMN "EC_PARTNER"."DESCRIPTION" IS '位置及介紹';
COMMENT ON COLUMN "EC_PARTNER"."PHONE" IS '電話';
COMMENT ON COLUMN "EC_PARTNER"."SOCIAL" IS '社群聯絡方式';
COMMENT ON COLUMN "EC_PARTNER"."LATITUDE" IS '緯度';
COMMENT ON COLUMN "EC_PARTNER"."LONGITUDE" IS '經度';
COMMENT ON COLUMN "EC_PARTNER"."THEME" IS '版面';
COMMENT ON COLUMN "EC_PARTNER"."STATUS" IS '1:申請中 2:申請通過 3:申請駁回';
COMMENT ON COLUMN "EC_PARTNER"."CREATETIME" IS '建立時間';
COMMENT ON COLUMN "EC_PARTNER"."ACTIVE" IS '1:啟用, 0:停用';

-----------------------------------------
--  會員-客戶(ManyToMany)
CREATE TABLE "EC_MEMBER_CUSTOMER"
(
"MEMBER_ID" NUMBER(18,0) NOT NULL ENABLE,
"CUSTOMER_ID" NUMBER(18,0) NOT NULL ENABLE,
CONSTRAINT "EC_MEMBER_CUSTOMER_PK" PRIMARY KEY ("MEMBER_ID", "CUSTOMER_ID") ENABLE,
CONSTRAINT "EC_MEMBER_CUSTOMER_FK1" FOREIGN KEY ("MEMBER_ID") REFERENCES "EC_MEMBER" ("ID") ENABLE,
CONSTRAINT "EC_MEMBER_CUSTOMER_FK2" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "EC_CUSTOMER" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_MEMBER_CUSTOMER"."MEMBER_ID" IS 'FK:EC_MEMBER_ID';
COMMENT ON COLUMN "EC_MEMBER_CUSTOMER"."CUSTOMER_ID" IS 'FK:EC_CUSTOMER_ID';

-- 出貨廠-商品(ManyToMany)
CREATE TABLE "EC_PLANT_PRODUCT"
(
"PLANT_ID" NUMBER(18,0) NOT NULL ENABLE,
"PRODUCT_ID" NUMBER(18,0) NOT NULL ENABLE,
CONSTRAINT "EC_PLANT_PRODUCT_PK" PRIMARY KEY ("PLANT_ID", "PRODUCT_ID") ENABLE,
CONSTRAINT "EC_PLANT_PRODUCT_FK1" FOREIGN KEY ("PLANT_ID") REFERENCES "EC_PLANT" ("ID") ENABLE,
CONSTRAINT "EC_PLANT_PRODUCT_FK2" FOREIGN KEY ("PRODUCT_ID") REFERENCES "EC_PRODUCT" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_PLANT_PRODUCT"."PLANT_ID" IS 'FK:EC_PLANT.ID';
COMMENT ON COLUMN "EC_PLANT_PRODUCT"."PRODUCT_ID" IS 'FK:EC_PRODUCT.ID';

-- 出貨廠-銷售區
CREATE TABLE "EC_PLANT_SALESAREA"
(
"PLANT_ID" NUMBER(18,0) NOT NULL ENABLE,
"SALESAREA_ID" NUMBER(18,0) NOT NULL ENABLE,
CONSTRAINT "EC_PLANT_SALESAREA_PK" PRIMARY KEY ("PLANT_ID", "SALESAREA_ID") ENABLE,
CONSTRAINT "EC_PLANT_SALESAREA_FK1" FOREIGN KEY ("PLANT_ID") REFERENCES "EC_PLANT" ("ID") ENABLE,
CONSTRAINT "EC_PLANT_SALESAREA_FK2" FOREIGN KEY ("SALESAREA_ID") REFERENCES "EC_SALESAREA" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_PLANT_SALESAREA"."PLANT_ID" IS 'FK:EC_PLANT.ID';
COMMENT ON COLUMN "EC_PLANT_SALESAREA"."SALESAREA_ID" IS 'FK:EC_SALESAREA.ID';

-- 合約商品
CREATE TABLE "EC_CONTRACT_PRODUCT"
(
"CONTRACT_ID" NUMBER(18,0) NOT NULL ENABLE,
"PRODUCT_ID" NUMBER(18,0) NOT NULL ENABLE,
CONSTRAINT "EC_CONTRACT_PRODUCT_PK" PRIMARY KEY ("CONTRACT_ID", "PRODUCT_ID") ENABLE,
CONSTRAINT "EC_CONTRACT_PRODUCT_FK1" FOREIGN KEY ("CONTRACT_ID") REFERENCES "EC_CONTRACT" ("ID") ENABLE,
CONSTRAINT "EC_CONTRACT_PRODUCT_FK2" FOREIGN KEY ("PRODUCT_ID") REFERENCES "EC_PRODUCT" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_CONTRACT_PRODUCT"."CONTRACT_ID" IS 'FK:EC_CONTRACT.ID';
COMMENT ON COLUMN "EC_CONTRACT_PRODUCT"."PRODUCT_ID" IS 'FK:EC_PRODUCT.ID';

-- 客戶-業務員
CREATE TABLE "EC_CUSTOMER_SALES"
(
"CUSTOMER_ID" NUMBER(18,0) NOT NULL ENABLE,
"SALES_ID" NUMBER(18,0) NOT NULL ENABLE,
CONSTRAINT "EC_CUSTOMER_SALES_PK1" PRIMARY KEY ("CUSTOMER_ID", "SALES_ID") ENABLE,
CONSTRAINT "EC_CUSTOMER_SALES_FK1" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "EC_CUSTOMER" ("ID") ENABLE,
CONSTRAINT "EC_CUSTOMER_SALES_FK2" FOREIGN KEY ("SALES_ID") REFERENCES "EC_SALES" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_CUSTOMER_SALES"."CUSTOMER_ID" IS 'FK:EC_CUSTOMER.ID';
COMMENT ON COLUMN "EC_CUSTOMER_SALES"."SALES_ID" IS 'FK:EC_SALES.ID';

-- 銷售區-送達地點(ManyToMany)
CREATE TABLE "EC_SALESAREA_DELIVERY"
(
"SALESAREA_ID" NUMBER(18,0) NOT NULL ENABLE,
"DELIVERY_ID" NUMBER(18,0) NOT NULL ENABLE,
CONSTRAINT "EC_SALESAREA_DELIVERY_PK1" PRIMARY KEY ("SALESAREA_ID", "DELIVERY_ID") ENABLE,
CONSTRAINT "EC_SALESAREA_DELIVERY_FK1" FOREIGN KEY ("SALESAREA_ID") REFERENCES "EC_SALESAREA" ("ID") ENABLE,
CONSTRAINT "EC_SALESAREA_DELIVERY_FK2" FOREIGN KEY ("DELIVERY_ID") REFERENCES "EC_DELIVERY" ("ID") ENABLE
) ;
COMMENT ON COLUMN "EC_SALESAREA_DELIVERY"."SALESAREA_ID" IS 'FK:EC_SALESAREA.ID';
COMMENT ON COLUMN "EC_SALESAREA_DELIVERY"."DELIVERY_ID" IS 'FK:EC_DELIVERY.ID';

-- 銷售區-地點(省市區鎮 OneToMany) Province City District Town
CREATE TABLE "EC_SALESAREA_LOCATION"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"SALESAREA_ID" NUMBER(18,0) NOT NULL ENABLE,
"PROVINCE" VARCHAR2(20 CHAR),
"CITY" VARCHAR2(20 CHAR),
"DISTRICT" VARCHAR2(20 CHAR),
"TOWN" VARCHAR2(20 CHAR),
CONSTRAINT "EC_SALESAREA_LOCATION_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_SALESAREA_LOCATION_EC__FK1" FOREIGN KEY ("SALESAREA_ID") REFERENCES "EC_SALESAREA" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_SALESAREA_LOCATION"."ID" IS 'PK';
COMMENT ON COLUMN "EC_SALESAREA_LOCATION"."SALESAREA_ID" IS 'FK:EC_SALESAREA.ID';
COMMENT ON COLUMN "EC_SALESAREA_LOCATION"."PROVINCE" IS '省';
COMMENT ON COLUMN "EC_SALESAREA_LOCATION"."CITY" IS '市';
COMMENT ON COLUMN "EC_SALESAREA_LOCATION"."DISTRICT" IS '區';
COMMENT ON COLUMN "EC_SALESAREA_LOCATION"."TOWN" IS '鎮';

-- 訂單
CREATE TABLE "EC_ORDER"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"MEMBER_ID" NUMBER(18,0) NOT NULL ENABLE,
"CUSTOMER_ID" NUMBER(18,0) NOT NULL ENABLE,
"PRODUCT_ID" NUMBER(18,0) NOT NULL ENABLE,
"PRODUCT_CODE" VARCHAR2(18 CHAR) NOT NULL ENABLE,
"PRODUCT_NAME" VARCHAR2(80 CHAR) NOT NULL ENABLE,
"UNIT_PRICE" NUMBER(15,2) NOT NULL ENABLE,
"QUANTITY" NUMBER(9,0) NOT NULL ENABLE,
"AMOUNT" NUMBER(15,2) NOT NULL ENABLE,
"VEHICLE" VARCHAR2(40 CHAR) NOT NULL ENABLE,
"DELIVERY_DATE" VARCHAR2(8 BYTE) NOT NULL ENABLE,
"METHOD" VARCHAR2(3 BYTE) NOT NULL ENABLE,
"CONTRACT_ID" NUMBER(18,0),
"CONTRACT_CODE" VARCHAR2(50 CHAR),
"CONTRACT_NAME" VARCHAR2(100 CHAR),
"PLANT_ID" NUMBER(18,0) NOT NULL ENABLE,
"PLANT_CODE" VARCHAR2(10 CHAR) NOT NULL ENABLE,
"PLANT_NAME" VARCHAR2(70 CHAR) NOT NULL ENABLE,
"SALESAREA_ID" NUMBER(18,0) NOT NULL ENABLE,
"SALESAREA_CODE" VARCHAR2(6 CHAR) NOT NULL ENABLE,
"SALESAREA_NAME" VARCHAR2(40 CHAR) NOT NULL ENABLE,
"DELIVERY_ID" NUMBER(18,0),
"DELIVERY_CODE" VARCHAR2(20 BYTE),
"DELIVERY_NAME" VARCHAR2(140 CHAR),
"SALES_ID" NUMBER(18,0) NOT NULL ENABLE,
"SALES_CODE" VARCHAR2(8 CHAR) NOT NULL ENABLE,
"SALES_NAME" VARCHAR2(40 CHAR) NOT NULL ENABLE,
"BONUS"	NUMBER(5,0) DEFAULT 0 NOT NULL ENABLE,
"STATUS" VARCHAR2(20 BYTE) NOT NULL ENABLE,
"SAP_ORDERNUM" VARCHAR2(40 CHAR),
"CREATETIME" DATE NOT NULL ENABLE,
CONSTRAINT "EC_ORDER_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_ORDER_EC_CONTRACT_FK1" FOREIGN KEY ("CONTRACT_ID") REFERENCES "EC_CONTRACT" ("ID") ENABLE,
CONSTRAINT "EC_ORDER_EC_CUSTOMER_FK1" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "EC_CUSTOMER" ("ID") ENABLE,
CONSTRAINT "EC_ORDER_EC_DELIVERY_FK1" FOREIGN KEY ("DELIVERY_ID") REFERENCES "EC_DELIVERY" ("ID") ENABLE,
CONSTRAINT "EC_ORDER_EC_MEMBER_FK1" FOREIGN KEY ("MEMBER_ID") REFERENCES "EC_MEMBER" ("ID") ENABLE,
CONSTRAINT "EC_ORDER_EC_PLANT_FK1" FOREIGN KEY ("PLANT_ID") REFERENCES "EC_PLANT" ("ID") ENABLE,
CONSTRAINT "EC_ORDER_EC_PRODUCT_FK1" FOREIGN KEY ("PRODUCT_ID") REFERENCES "EC_PRODUCT" ("ID") ENABLE,
CONSTRAINT "EC_ORDER_EC_SALESAREA_FK1" FOREIGN KEY ("SALESAREA_ID") REFERENCES "EC_SALESAREA" ("ID") ENABLE,
CONSTRAINT "EC_ORDER_EC_SALES_FK1" FOREIGN KEY ("SALES_ID") REFERENCES "EC_SALES" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_ORDER"."ID" IS 'PK';
COMMENT ON COLUMN "EC_ORDER"."MEMBER_ID" IS 'FK:EC_MEMBER.ID';
COMMENT ON COLUMN "EC_ORDER"."CUSTOMER_ID" IS 'FK:EC_CUSTOMER.ID';
COMMENT ON COLUMN "EC_ORDER"."PRODUCT_ID" IS 'FK:EC_PRODUCT.ID';
COMMENT ON COLUMN "EC_ORDER"."PRODUCT_CODE" IS '料號';
COMMENT ON COLUMN "EC_ORDER"."PRODUCT_NAME" IS '品名';
COMMENT ON COLUMN "EC_ORDER"."UNIT_PRICE" IS '單價(RMB)';
COMMENT ON COLUMN "EC_ORDER"."QUANTITY" IS '數量';
COMMENT ON COLUMN "EC_ORDER"."AMOUNT" IS '總額';
COMMENT ON COLUMN "EC_ORDER"."VEHICLE" IS '車號';
COMMENT ON COLUMN "EC_ORDER"."DELIVERY_DATE" IS '提貨日';
COMMENT ON COLUMN "EC_ORDER"."METHOD" IS '廠交自提/工地交自提';
COMMENT ON COLUMN "EC_ORDER"."CONTRACT_ID" IS 'FK:EC_CONTRACT.ID';
COMMENT ON COLUMN "EC_ORDER"."CONTRACT_CODE" IS '合約號碼';
COMMENT ON COLUMN "EC_ORDER"."CONTRACT_NAME" IS '合約名稱';
COMMENT ON COLUMN "EC_ORDER"."PLANT_ID" IS 'FK:EC_PLANT.ID';
COMMENT ON COLUMN "EC_ORDER"."PLANT_CODE" IS '廠代碼';
COMMENT ON COLUMN "EC_ORDER"."PLANT_NAME" IS '廠名稱';
COMMENT ON COLUMN "EC_ORDER"."SALESAREA_ID" IS 'FK:EC_SALESAREA.ID';
COMMENT ON COLUMN "EC_ORDER"."SALESAREA_CODE" IS '銷售區代碼';
COMMENT ON COLUMN "EC_ORDER"."SALESAREA_NAME" IS '銷售區名稱';
COMMENT ON COLUMN "EC_ORDER"."DELIVERY_ID" IS 'FK:EC_DELIVERY.ID';
COMMENT ON COLUMN "EC_ORDER"."DELIVERY_CODE" IS '送達地點代碼';
COMMENT ON COLUMN "EC_ORDER"."DELIVERY_NAME" IS '送達地點名稱';
COMMENT ON COLUMN "EC_ORDER"."SALES_ID" IS 'FK:EC_SALES.ID';
COMMENT ON COLUMN "EC_ORDER"."SALES_CODE" IS '業務員工號';
COMMENT ON COLUMN "EC_ORDER"."SALES_NAME" IS '業務員名稱';
COMMENT ON COLUMN "EC_ORDER"."BONUS" IS '紅利';
COMMENT ON COLUMN "EC_ORDER"."SAP_ORDERNUM" IS 'SAP訂單號碼';
COMMENT ON COLUMN "EC_ORDER"."CREATETIME" IS '建立時間';

-- 金幣記錄
CREATE TABLE "EC_REWARD_RECORD"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
CONSTRAINT "EC_REWARD_RECORD_PK" PRIMARY KEY ("ID") ENABLE
);
COMMENT ON COLUMN "EC_REWARD_RECORD"."ID" IS 'PK';

-- 紅利記錄
CREATE TABLE "EC_BONUS_RECORD"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
CONSTRAINT "EC_BONUS_RECORD_PK" PRIMARY KEY ("ID") ENABLE
);
COMMENT ON COLUMN "EC_BONUS_RECORD"."ID" IS 'PK';

-- 伙伴評語
CREATE TABLE "EC_PARTNER_COMMENT"
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"PARTNER_ID" NUMBER(18,0) NOT NULL ENABLE,
"MEMBER_ID" NUMBER(18,0) NOT NULL ENABLE,
"RATE" NUMBER(2,0) NOT NULL ENABLE,
"MESSAGE" VARCHAR2(500 CHAR),
"CREATETIME" DATE NOT NULL ENABLE,
CONSTRAINT "EC_PARTNER_COMMENT_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_PARTNER_COMMENT_FK1" FOREIGN KEY ("PARTNER_ID") REFERENCES "EC_PARTNER" ("ID") ENABLE,
CONSTRAINT "EC_PARTNER_COMMENT_FK2" FOREIGN KEY ("MEMBER_ID") REFERENCES "EC_MEMBER" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_PARTNER_COMMENT"."ID" IS 'PK';
COMMENT ON COLUMN "EC_PARTNER_COMMENT"."PARTNER_ID" IS 'FK:EC_PARTNER.ID';
COMMENT ON COLUMN "EC_PARTNER_COMMENT"."MEMBER_ID" IS 'FK:EC_MEMBER.ID';
COMMENT ON COLUMN "EC_PARTNER_COMMENT"."RATE" IS '評分';
COMMENT ON COLUMN "EC_PARTNER_COMMENT"."MESSAGE" IS '評語';
COMMENT ON COLUMN "EC_PARTNER_COMMENT"."CREATETIME" IS '建立時間';

-- 伙伴商品
CREATE TABLE "EC_BANNER_PRODUCT"
(
"BANNER_ID" NUMBER(18,0) NOT NULL ENABLE,
"PRODUCT_ID" NUMBER(18,0) NOT NULL ENABLE,
CONSTRAINT "EC_BANNER_PRODUCT_PK" PRIMARY KEY ("BANNER_ID", "PRODUCT_ID") ENABLE,
CONSTRAINT "EC_BANNER_PRODUCT_FK1" FOREIGN KEY ("BANNER_ID") REFERENCES "EC_BANNER" ("ID") ENABLE,
CONSTRAINT "EC_BANNER_PRODUCT_FK2" FOREIGN KEY ("PRODUCT_ID") REFERENCES "EC_PRODUCT" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_BANNER_PRODUCT"."BANNER_ID" IS 'FK:EC_BANNER.ID';
COMMENT ON COLUMN "EC_BANNER_PRODUCT"."PRODUCT_ID" IS 'FK:EC_PRODUCT.ID';

-- 伙伴商品
CREATE TABLE "EC_PARTNER_PRODUCT"
(
"PARTNER_ID" NUMBER(18,0) NOT NULL ENABLE,
"PRODUCT_ID" NUMBER(18,0) NOT NULL ENABLE,
"UNIT_PRICE" NUMBER(18,0) NOT NULL ENABLE,
CONSTRAINT "EC_PARTNER_PRODUCT_PK" PRIMARY KEY ("PARTNER_ID", "PRODUCT_ID") ENABLE,
CONSTRAINT "EC_PARTNER_PRODUCT_FK1" FOREIGN KEY ("PARTNER_ID") REFERENCES "EC_PARTNER" ("ID") ENABLE,
CONSTRAINT "EC_PARTNER_PRODUCT_FK2" FOREIGN KEY ("PRODUCT_ID") REFERENCES "EC_PRODUCT" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_PARTNER_PRODUCT"."PARTNER_ID" IS 'FK:EC_PARTNER.ID';
COMMENT ON COLUMN "EC_PARTNER_PRODUCT"."PRODUCT_ID" IS 'FK:EC_PRODUCT.ID';
COMMENT ON COLUMN "EC_PARTNER_PRODUCT"."UNIT_PRICE" IS '單價(RMB)';

-- 申請成簽約客戶
CREATE TABLE EC_FORM_BECUSTOMER
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"MEMBER_ID" NUMBER(18,0) NOT NULL ENABLE,
"NAME" VARCHAR2(64 CHAR) NOT NULL ENABLE,
"EMAIL" VARCHAR2(64 BYTE) NOT NULL ENABLE,
"PHONE" VARCHAR2(50 BYTE),
"CREATETIME" DATE NOT NULL ENABLE,
CONSTRAINT "EC_FORM_BECUSTOMER_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_FORM_BECUSTOMER_FK1" FOREIGN KEY ("MEMBER_ID") REFERENCES "EC_MEMBER" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_FORM_BECUSTOMER"."ID" IS 'PK';
COMMENT ON COLUMN "EC_FORM_BECUSTOMER"."MEMBER_ID" IS 'FK:EC_MEMBER_ID';
COMMENT ON COLUMN "EC_FORM_BECUSTOMER"."NAME" IS '客戶名稱';
COMMENT ON COLUMN "EC_FORM_BECUSTOMER"."EMAIL" IS '電子信箱';
COMMENT ON COLUMN "EC_FORM_BECUSTOMER"."PHONE" IS '電話';
COMMENT ON COLUMN "EC_FORM_BECUSTOMER"."CREATETIME" IS '建立時間';

-- 問題留言
CREATE TABLE EC_FORM_QA
(
"ID" NUMBER(18,0) NOT NULL ENABLE,
"MEMBER_ID" NUMBER(18,0) NOT NULL ENABLE,
"MESSAGE" VARCHAR2(500 CHAR),
"CREATETIME" DATE NOT NULL ENABLE,
CONSTRAINT "EC_FORM_QA_PK" PRIMARY KEY ("ID") ENABLE,
CONSTRAINT "EC_FORM_QA_FK1" FOREIGN KEY ("MEMBER_ID") REFERENCES "EC_MEMBER" ("ID") ENABLE
);
COMMENT ON COLUMN "EC_FORM_QA"."ID" IS 'PK';
COMMENT ON COLUMN "EC_FORM_QA"."MEMBER_ID" IS 'FK:EC_MEMBER_ID';
COMMENT ON COLUMN "EC_FORM_QA"."MESSAGE" IS '留言';
COMMENT ON COLUMN "EC_FORM_QA"."CREATETIME" IS '建立時間';
