//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.21 at 11:56:28 AM CST 
//


package com.tcci.fc.jaxb;

import com.tcci.fc.entity.bpm.enumeration.ActivityTypeEnum;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="activityname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="activitytype" type="{}activityTypeEnum"/>
 *         &lt;element name="rolename" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="duration" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="expression" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "activityname",
    "activitytype",
    "rolename",
    "duration",
    "expression"
})
@XmlRootElement(name = "activitytemplate")
public class ActivitytemplateConverter {

    @XmlElement(required = true)
    protected String activityname;
    @XmlElement(required = true)
    protected ActivityTypeEnum activitytype;
    @XmlElement(required = true)
    protected String rolename;
    protected int duration;
    @XmlElement(required = true)
    protected String expression;

    /**
     * Gets the value of the activityname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivityname() {
        return activityname;
    }

    /**
     * Sets the value of the activityname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivityname(String value) {
        this.activityname = value;
    }

    /**
     * Gets the value of the activitytype property.
     * 
     * @return
     *     possible object is
     *     {@link ActivityTypeEnum }
     *     
     */
    public ActivityTypeEnum getActivitytype() {
        return activitytype;
    }

    /**
     * Sets the value of the activitytype property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActivityTypeEnum }
     *     
     */
    public void setActivitytype(ActivityTypeEnum value) {
        this.activitytype = value;
    }

    /**
     * Gets the value of the rolename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * Sets the value of the rolename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRolename(String value) {
        this.rolename = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     */
    public int getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     */
    public void setDuration(int value) {
        this.duration = value;
    }

    /**
     * Gets the value of the expression property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpression() {
        return expression;
    }

    /**
     * Sets the value of the expression property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpression(String value) {
        this.expression = value;
    }

}
