//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.21 at 11:37:08 AM CST 
//


package com.tcci.fc.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="routename" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fromactivity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="toactivity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "routename",
    "fromactivity",
    "toactivity"
})
@XmlRootElement(name = "activityroutetemplate")
public class ActivityroutetemplateConverter {

    @XmlElement(required = true)
    protected String routename;
    @XmlElement(required = true)
    protected String fromactivity;
    @XmlElement(required = true)
    protected String toactivity;

    /**
     * Gets the value of the routename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoutename() {
        return routename;
    }

    /**
     * Sets the value of the routename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoutename(String value) {
        this.routename = value;
    }

    /**
     * Gets the value of the fromactivity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromactivity() {
        return fromactivity;
    }

    /**
     * Sets the value of the fromactivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromactivity(String value) {
        this.fromactivity = value;
    }

    /**
     * Gets the value of the toactivity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToactivity() {
        return toactivity;
    }

    /**
     * Sets the value of the toactivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToactivity(String value) {
        this.toactivity = value;
    }

}
